### PR TITLE
fix(mdns): don't suspend task forever upon reading non-mDNS packet

### LINKED ISSUE #4860: Mdns `InterfaceState` never being called again after returning `Poll::Pending`
### Summary

When updating to `0.53.0`, we encountered a curious bug with Mdns.

After sending an incorrect Mdns packet, which is dropped (as expected), no packet is ever received by the peer after that, even if it is correct.

### Expected behavior

An incorrect Mdns packet should not stop the polling of an `InterfaceState`.

### Actual behavior

The polling of an `InterfaceState` is stopped after receiving an incorrect Mdns packet.

### Relevant log output

_No response_

### Possible Solution

Members of our team diagnosed the problem and managed to find the solution. It seems a dormant bug was present for a long time in the `poll` implementation of `InterfaceState` but it was only awakened with the merge of #4623. 

https://github.com/libp2p/rust-libp2p/blob/cddc306978a7cca705de5ce10ec5e16e8b732084/protocols/mdns/src/behaviour/iface.rs#L313-L325

As we can see in the above code sample, many `Poll::Ready` are handled and returned as `Poll::Pending`. However, in the [rust documentation,](https://doc.rust-lang.org/stable/std/task/enum.Poll.html#variant.Pending) we can read that "When a function returns Pending, the function *must* also ensure that the current task is scheduled to be awoken when progress can be made". When looking at the current implementation, we can safely say that, when a `Poll::Ready` is caught and converted into a `Poll::Pending`, no scheduling is done to ensure the task will be woken up.

Even if this bug has been present for a long time, it has not caused any problems up until now. Indeed, before the previously mentioned PR, all `InterfaceState` were stored in the `iface_states` `HashMap` and [were polled no matter what their previous returned value was](https://github.com/libp2p/rust-libp2p/pull/4623/files?diff=split&w=0#diff-9ec8c5fcec2242a830ffe46e2c0d7e32186d28ec335f0452af531a9025803b9fL292) (since `poll` was called in a `loop` over each `InterfaceState`). So, even if the `poll` method of `InterfaceState` had not scheduled its own awakening, it would still be called at the next iteration of the `poll` method of the mdns `Behaviour`.

However, now that each `InterfaceState` is `spawned` in its own task, nobody is calling `poll` when it returns `Poll::Pending`. That is why returning a `Poll::Pending` when internally getting a `Poll::Ready` result in the `poll` method of `InterfaceState` never being called again, causing packets to never be handled.

### Version

v0.53.0 (master)

### Would you like to work on fixing this bug ?

Yes

### PR DESCRIPTION
**Pull request by stormshield-frb**
## Description

Fixes: #4860.

## Notes & open questions

We are not completely sure if we should loop back again (ie. going through priorities `1`, `2` and `3` all over again) or if we should add another loop around priority `4`. From our understanding of the `poll` implementation, we should loop back at the top but we might be incorrect.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: protocols/mdns/src/behaviour/iface.rs [hunk 1]
```diff
@@ -319,10 +316,9 @@ where
                 Poll::Ready(Ok(Err(err))) => {
                     tracing::debug!("Parsing mdns packet failed: {:?}", err);
                 }
-                Poll::Ready(Ok(Ok(None))) | Poll::Pending => {}
+                Poll::Ready(Ok(Ok(None))) => {}
```
Comment (thomaseizinger) [inline protocols/mdns/src/behaviour/iface.rs]: I'd prefer a `continue` here and restoring the others instead of explicitly returning from the `Poll::Pending` branch.

File: protocols/mdns/src/behaviour/iface.rs [hunk 2]
```diff
@@ -319,10 +316,9 @@ where
...
+                Poll::Pending => return Poll::Pending,
```
Comment (thomaseizinger) [inline protocols/mdns/src/behaviour/iface.rs]: For consistency with other parts of the codebase, we tend to have the `return Poll::Pending` at the end of the loop and explicitly `continue` in all other branches. I find that easier to audit although it doesn't prevent us from mistakes as we can this in this PR :)

File: protocols/mdns/src/behaviour/iface.rs [hunk 3]
```diff
@@ -319,10 +316,9 @@ where
                 Poll::Ready(Ok(Err(err))) => {
                     tracing::debug!("Parsing mdns packet failed: {:?}", err);
```
Comment (thomaseizinger) [inline protocols/mdns/src/behaviour/iface.rs:322]: I think we need to `continue` here too!

Comment (thomaseizinger) [reply protocols/mdns/src/behaviour/iface.rs:322]: If we hit line `317`, the socket is broken so we should probably add `return Poll::Ready(())`. If we add a `continue`, we will run into an endless loop and in the current state, it is just a memory-leak because the task stays around without ever being `poll`-ed again.

**Review by thomaseizinger — COMMENTED** [review]
Impressive work on finding this! Thank you!

I've left a few minor comments.

File: protocols/mdns/src/behaviour/iface.rs (hunk 2 above)
Comment (stormshield-frb) [reply protocols/mdns/src/behaviour/iface.rs]: Ok will do :wink: Indeed we have to be really careful that no unwanted `Poll::Ready` hits the `return Poll::Pending` when we don't want to.

File: protocols/mdns/src/behaviour/iface.rs (hunk 3 above)
Comment (stormshield-frb) [reply protocols/mdns/src/behaviour/iface.rs:322]: Before I commit the changes about `continue`, I just want to be sure about the line where the socket is broken (because depending on if you talk about pre or post changes, line `317` is not the same :wink: )

For which pattern should I return `Poll::Ready(())` ?
- `Poll::Ready(Err(err)) if err.kind() == std::io::ErrorKind::WouldBlock`
- `Poll::Ready(Err(err))` 
First one ? Second one ? Or both ?

Comment (thomaseizinger) [reply protocols/mdns/src/behaviour/iface.rs:322]: Just the 2nd one. `WouldBlock` is what where we should return `Poll::Pending` (which happens by falling through to the end).

Comment (stormshield-frb) [reply protocols/mdns/src/behaviour/iface.rs:322]: Ok. But for `WouldBlock` it has now a `continue` to make sure the `waker` will be scheduled to wake back up again.

If we don't put a `continue` after `WouldBlock` and go straight at the end to the `Poll::Pending`, the `waker` is not scheduled anymore (since `Poll::Ready` has just been received) and `poll` will never be called again.

File: protocols/mdns/src/behaviour/iface.rs [hunk 4]
```diff
@@ -312,14 +312,18 @@ where
                 }
                 Poll::Ready(Err(err)) if err.kind() == std::io::ErrorKind::WouldBlock => {
                     // No more bytes available on the socket to read
+                    continue;
                 }
```
Comment (mxinden) [inline protocols/mdns/src/behaviour/iface.rs:316]: Given that we are setting `set_nonblocking(true)`, shouldn't this match arm never be hit?

https://github.com/libp2p/rust-libp2p/blob/e3db5a57813f6ba049ebd4eba26a3aaa2ff3568d/protocols/mdns/src/behaviour/socket.rs#L102-L105

**Review by mxinden — COMMENTED** [review]
Thank you for the debugging work!

File: protocols/mdns/src/behaviour/iface.rs (hunk 1 above)
Comment (stormshield-frb) [reply protocols/mdns/src/behaviour/iface.rs]: Should be resolved now.

File: protocols/mdns/src/behaviour/iface.rs (hunk 4 above)
Comment (thomaseizinger) [reply protocols/mdns/src/behaviour/iface.rs:316]: My understanding is the opposite: _Because_ we set `non_blocking(true)`, this error is returned if it would otherwise block. See https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.set_nonblocking.

File: protocols/mdns/src/behaviour/iface.rs (hunk 3 above)
Comment (thomaseizinger) [reply protocols/mdns/src/behaviour/iface.rs:322]: Yeah you are correct, we need the `continue` :)

File: protocols/mdns/src/behaviour/iface.rs (hunk 4 above)
Comment (thomaseizinger) [reply protocols/mdns/src/behaviour/iface.rs:316]: Normally, this should be caught by the `AsyncFd` implementation but afaik, there might still be the occasional `WouldBlock` error so the safest thing is to just poll again and register a waker.

**Review by thomaseizinger — APPROVED** [review]

File: protocols/mdns/src/behaviour/iface.rs (hunk 4 above)
Comment (stormshield-frb) [reply protocols/mdns/src/behaviour/iface.rs:316]: Is this thread resolved or are you maybe doing some research to better understand `WouldBlock` ?

Comment (mxinden) [reply protocols/mdns/src/behaviour/iface.rs:316]: Oh, my bad. Thanks for clarifying @thomaseizinger! Sorry for delaying here @stormshield-frb.

**Review by mxinden — APPROVED** [review]
:pray:

**Comment by mxinden** [comment]
[Published](https://crates.io/crates/libp2p-mdns/0.45.1) and [tagged](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-mdns-v0.45.1).

**Comment by thomaseizinger** [comment]
> [Published](https://crates.io/crates/libp2p-mdns/0.45.1) and [tagged](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-mdns-v0.45.1).

How good is it to just release from `master` whenever you want 😁

**Comment by mxinden** [comment]
:smile:  oddly satisfying! @thomaseizinger
