### PR TITLE
Fix the dialing priority system

### LINKED ISSUE #883: Nodes sometimes fail to connect
Reproduction steps:

- Open two terminals.
- Run the chat example in both. There is chance that you get a "Connection reset by peer" error in one of them.
- If you don't get the error, kill one of the chats and restart it until you get the error.

> [2019-01-22T15:20:02Z ERROR libp2p_yamux] connection error: decode error: i/o error: I/O error: Connection reset by peer (os error 104)

I initially thought that it was an error about closing the previous connection (from before we restart the chat), but this can happen on first try even when both chat examples were closed.

This can also possibly be caused by the dialing priority system not working properly.

### PR DESCRIPTION
**Pull request by tomaka**
Fixes maybe #883, I'm not sure.

Right now, when we dial a node and receive an incoming connection from that same node, we cancel the outgoing attempt.
The problem is that this outgoing attempt may have already succeeded (and we don't know yet), in which case the remote has maybe cancelled its own connection. The outcome is no connection at all.

There is a dialing priority system in place, but it applied only if we receive a new connection from a node we are already connected to.

This PR does the following:

- We no longer cancel outgoing attempts when we receiving an incoming connection. However we remove the addresses in the queue.
- Closing an open connection also cancels the outgoing connection attempt.
- We can now receive `DialError` events from nodes we are connected to. In order to clarify this, I changed the `remaining_addresses` field (indicating the number of addresses in queue) into a `new_state` field that indicates the state of the peer.

### CODE REVIEW

**Comment by tomaka** [comment]
cc https://github.com/paritytech/substrate/pull/1634

File: core/src/nodes/raw_swarm.rs [hunk 1]
```diff
@@ -1088,28 +1083,27 @@ where
...
         // Set the endpoint for this peer.
         let closed_endpoint = reach_attempts.connected_points.insert(event.peer_id().clone(), opened_endpoint.clone());
 
-        // Cancel any outgoing attempt to this peer.
-        let action = if let Some(attempt) = reach_attempts.out_reach_attempts.remove(&event.peer_id()) {
+        // We keep the current outgoing attempt because it may already have succeeded without us
+        // knowing. It is possible that the remote has already closed its ougoing attempt because
+        // it sees our outgoing attempt as a success.
+        // However we cancel any further multiaddress to attempt.
+        // TODO: cancel if we don't have dial priority? we should write tests first
```
Comment (tomaka) [inline core/src/nodes/raw_swarm.rs]: I think it is critical to do this as well; otherwise our dialing attempt will always replace the remote's connection, regardless of whether we have priority.

**Comment by tomaka** [comment]
Oh well, let's merge this.
