### PR TITLE
fix(request-response): don't keep duplicate addresses

### LINKED ISSUE #4699: AutoNAT servers added are not deduplicated
### Summary

Addresses added with [`autonat::Behaviour::add_server`](https://docs.rs/libp2p/latest/libp2p/autonat/struct.Behaviour.html#method.add_server) are not deduplicated. This is unlike [`kad::Behaviour::add_address`](https://docs.rs/libp2p/latest/libp2p/kad/struct.Behaviour.html#method.add_address).

We came across this issue as it was causing us to 'leak' memory, as we kept adding addresses that we were observing. We are adding these servers manually, because in the past we have observed AutoNAT to complain there are no AutoNAT probe servers available ([`OutboundProbeError::NoServer`](https://docs.rs/libp2p/latest/libp2p/autonat/enum.OutboundProbeError.html#variant.NoServer)). This is because by default it uses currently connected peers, but at times there might not be connections to peers causing AutoNAT to not succeed in getting our status. Waiting for our AutoNAT status caused us to further stall our node booting.

### Expected behavior

Deduplication

### Actual behavior

Duplicated servers in list

### Relevant log output

_No response_

### Possible Solution

#4700

### Version

`master`

### Would you like to work on fixing this bug ?

Yes

### PR DESCRIPTION
**Pull request by b-zee**
## Description

Resolves: #4699.

## Notes & open questions

In `kad`, there is a special `Addresses` struct that might be worth reusing for this functionality.

I will make further CHANGELOG edits etc if this fix is thought to be sensible.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by joshuef** [comment]
Nice one. This looks to have been a wee mem leak for us. We've been doing `add_server` on every `Identify` event and been leaking decent chunks of memory over time. 💪

File: protocols/request-response/src/lib.rs [hunk 1]
```diff
@@ -437,8 +437,19 @@ where
     /// by [`NetworkBehaviour::handle_pending_outbound_connection`].
     ///
     /// Addresses added in this way are only removed by `remove_address`.
-    pub fn add_address(&mut self, peer: &PeerId, address: Multiaddr) {
-        self.addresses.entry(*peer).or_default().push(address);
+    ///
+    /// Returns true if the address was added, false otherwise (i.e. if the
+    /// address is already in the list).
+    pub fn add_address(&mut self, peer: &PeerId, address: Multiaddr) -> bool {
```
Comment (joshuef) [inline protocols/request-response/src/lib.rs:443]: I wonder if its work making this take `&Multiaddr`and then only cloning if we need to add it.

It'd mean the consumer of the API doesn't have to take ownership to use it (which may involve a pointless clone, as we have atm).

**Review by mxinden — COMMENTED** [review]
How about using a `HashSet` instead?

``` diff
modified   protocols/request-response/src/lib.rs
@@ -337,7 +337,7 @@ where
     /// reachable addresses, if any.
     connected: HashMap<PeerId, SmallVec<[Connection; 2]>>,
     /// Externally managed addresses via `add_address` and `remove_address`.
-    addresses: HashMap<PeerId, SmallVec<[Multiaddr; 6]>>,
+    addresses: HashMap<PeerId, HashSet<Multiaddr>>,
     /// Requests that have not yet been sent and are waiting for a connection
     /// to be established.
     pending_outbound_requests: HashMap<PeerId, SmallVec<[RequestProtocol<TCodec>; 10]>>,
```

File: protocols/request-response/src/lib.rs (hunk 1 above)
Comment (mxinden) [reply protocols/request-response/src/lib.rs:443]: Note that `Multiaddr` is a wrapper around an `Arc<Vec<_>>`. Thus I doubt additional clones have a performance impact here.

https://github.com/multiformats/rust-multiaddr/blob/d0e9ec219645ce8bd8ae7926e4b7316a67c35f84/src/lib.rs#L40-L45

Comment (joshuef) [reply protocols/request-response/src/lib.rs:443]: Ah nice one. Good to know! 🙇

**Comment by thomaseizinger** [comment]
> How about using a `HashSet` instead?
> 
> ```diff
> modified   protocols/request-response/src/lib.rs
> @@ -337,7 +337,7 @@ where
>      /// reachable addresses, if any.
>      connected: HashMap<PeerId, SmallVec<[Connection; 2]>>,
>      /// Externally managed addresses via `add_address` and `remove_address`.
> -    addresses: HashMap<PeerId, SmallVec<[Multiaddr; 6]>>,
> +    addresses: HashMap<PeerId, HashSet<Multiaddr>>,
>      /// Requests that have not yet been sent and are waiting for a connection
>      /// to be established.
>      pending_outbound_requests: HashMap<PeerId, SmallVec<[RequestProtocol<TCodec>; 10]>>,
> ```

+1 for using a `HashSet`. Long-term, we should solve this by adding a `PeerStore` behaviour: https://github.com/libp2p/rust-libp2p/issues/4103.

**Comment by thomaseizinger** [comment]
Thanks! Can you address the clippy failure?

**Comment by b-zee** [comment]
Fixed the clippy lint.

Is v0.53.0 set to be released soon? Or, possibly, is there a patch release that this could part of soon? Thanks for all the work!

**Comment by thomaseizinger** [comment]
> Fixed the clippy lint.
> 
> Is v0.53.0 set to be released soon? Or, possibly, is there a patch release that this could part of soon? Thanks for all the work!

If you backport it to the `v0.52` branch, I can cut a patch release :)

**Review by thomaseizinger — APPROVED** [review]
