### PR TITLE
transports/quic: Add implementation based on `quinn-proto`

### LINKED ISSUE #1334: Have the `decl_storage!` macro import rstd::prelude::*
When trying to use the decl_storage macro and build to wasm, the compiler complains that the Vec type has not been declared.

For example, this minimum runtime:
```
use srml_support::{StorageValue, dispatch::Result};
pub trait Trait: system::Trait {}

decl_module! {
  pub struct Module<T: Trait> for enum Call where origin: T::Origin {
    fn set_value(_origin, value: u32) -> Result {
      <Value<T>>::put(value);
      Ok(())
    }
  }
}

decl_storage! {
  trait Store for Module<T: Trait> as RuntimeExampleStorage {
    Value: u32;
  }
}
```
will give the following error:
```
error[E0412]: cannot find type `Vec` in this scope
  --> src/runtime_example.rs:13:1
   |
13 | / decl_storage! {
14 | |   trait Store for Module<T: Trait> as RuntimeExampleStorage {
15 | |     Value: u32;
16 | |   }
17 | | }
   | |_^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use rstd::alloc::prelude::Vec;
   |
1  | use rstd::prelude::Vec;
   |
1  | use rstd::vec::Vec;
   |
1  | use srml_support::dispatch::Vec;
   |
and 1 other candidates

error: aborting due to previous error

For more information about this error, try `rustc --explain E0412`.
error: Could not compile `runtime-example-runtime`.
```

To solve this issue, you simply need to add: `use rstd::prelude::*;`

We should have the decl_storage macro automatically do this if it requires this import.

### PR DESCRIPTION
**Pull request by kpp**
<details><summary>Inital PR description</summary>
A continuation of https://github.com/libp2p/rust-libp2p/pull/2159.

Adds support for tls, removes the `UnboundedSender`s from the endpoint. The endpoint still has `UnboundedReceiver`s, but that's not different than having a `VecDeque`. The transport dial api for example doesn't allow applying backpressure.

Closes paritytech/substrate#1334

Todo: transfer unresolved comments from the previous PR

</details>

---

_Updated PR description:_

# Description

Add QUIC as transport to rust-libp2p, using the `quinn-proto` QUIC implementation.
Initially a continuation of paritytech/substrate#2159, later switched to use the code from paritytech/substrate#1334 (see 4a317df41adccb0a1dd65ad3df049683fa2ca4ea).

## Links to any relevant issues
- paritytech/substrate#2883 

## Open TODOs
- [x] Fix docs
- [x] Review / document how backpressure is enforced
- [x] Add more tests

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

## Commit message body

Add experimental QUIC implementation based on `quinn-proto`

Co-authored-by: Demi Marie Obenour <demiobenour@gmail.com>
Co-authored-by: Pierre Krieger <pierre.krieger1708@gmail.com>
Co-authored-by: Thomas Eizinger <thomas@eizinger.io>
Co-authored-by: Max Inden <mail@max-inden.de>
Co-authored-by: Marco Munizaga <marco@marcopolo.io>
Co-authored-by: Elena Frank <elena.frank@protonmail.com>

### CODE REVIEW

File: transports/quic/src/endpoint.rs [hunk 1]
```diff
@@ -0,0 +1,491 @@
...
+    }
+}
+
+struct Endpoint<C: Crypto> {
+    channel: EndpointChannel<C>,
+    endpoint: QuinnEndpoint<C::Session>,
+    socket: UdpSocket,
+    crypto_config: Arc<CryptoConfig<C>>,
+    connections: HashMap<ConnectionHandle, mpsc::Sender<ConnectionEvent>>,
+    outgoing: VecDeque<udp_socket::Transmit>,
```
Comment (kpp) [inline transports/quic/src/endpoint.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r702321209

>  DemiMarie
Is there a proof that this cannot get too large? If it does get over a certain size, would it be better to drop packets, as e.g. the kernel network stack does?
dvc94ch
These are outgoing, so you want to drop packets to prevent libp2p dos'ing itself? As far as I know this pattern is used throughout the codebase
DemiMarie
Is it possible for a peer to create a situation where libp2p tries to send a lot of data, but then is not actually able to do so? That said, I do not believe this should block merging if it is not a regression compared to the other parts of the codebase.
dvc94ch
The first packet requires a large payload before the server will answer. This restriction is lifted after the ip address was validated to prevent amplification attacks. Later on I guess that would depend on the application protocol. If you are concerned about this it might be a good idea to bandwidth limit ip's using the bandwidth wrapper.
dvc94ch
Marking this as resolved
dvc94ch
These are outgoing, so you want to drop packets to prevent libp2p dos'ing itself? As far as I know this pattern is used throughout the codebase
DemiMarie
Is it possible for a peer to create a situation where libp2p tries to send a lot of data, but then is not actually able to do so? That said, I do not believe this should block merging if it is not a regression compared to the other parts of the codebase.
dvc94ch
The first packet requires a large payload before the server will answer. This restriction is lifted after the ip address was validated to prevent amplification attacks. Later on I guess that would depend on the application protocol. If you are concerned about this it might be a good idea to bandwidth limit ip's using the bandwidth wrapper.
dvc94ch
Marking this as resolved
mxinden
How is this different to an unbounded channel? How is back-pressure to the upper layer enforced?
dvc94ch
queues are used throughout the codebase, don't know why we're making a fuss about it here
mxinden
> > queues are used throughout the codebase,

> That is correct, yes, though I would argue that those places are either (a) not relevant (e.g. libp2p-ping with little to no bandwidth usage) or (b) a deficiency introduced in the past.
That said, lower layers of libp2p do enforce backpressure today, e.g. the TCP transport (libp2p-tcp) or the Yamux implementation..

File: transports/quic/src/endpoint.rs [hunk 2]
```diff
@@ -0,0 +1,491 @@
...
+        connection_id: ConnectionHandle,
+        event: EndpointEvent,
+    },
+    /// Instruct the endpoint to transmit a packet on its UDP socket.
+    Transmit(Transmit),
+}
+
+#[derive(Debug)]
+pub struct TransportChannel<C: Crypto> {
+    tx: mpsc::UnboundedSender<ToEndpoint<C>>,
```
Comment (kpp) [inline transports/quic/src/endpoint.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r702321633

>  DemiMarie
Is there a proof that this always remains bounded?
dvc94ch
same here, this is the channel from libp2p not from the socket. other than erroring if the queue is full and trying to dial I don't see what we can do
DemiMarie
That makes sense. FYI I believe much of the complexity in my original PR was from avoiding unbounded channels at all costs, which required me to use locking instead of message-passing.
dvc94ch
Marking as resolved
mxinden 
> > same here, this is the channel from libp2p not from the socket. other than erroring if the queue is full and trying to dial I don't see what we can do

> I don't understand why the direction (libp2p -> socket) matters in regards to bounded or unbounded. Can you expand on that dvc94ch?
dvc94ch
you want a bounded channel to prevent dos attacks. you can't prevent a user from dos'ing himself, he can just exit the application.
mxinden 
> > can't prevent a user from dos'ing himself

> How does an upper layer component know whether the lower layer is able to keep up. In other words, how does the upper layer know when to add more items and when to slow down? Backpressure through bounded channels enforces just that.

File: transports/quic/src/endpoint.rs [hunk 3]
```diff
@@ -0,0 +1,491 @@
...
+
+/// Message sent to the endpoint background task.
+#[derive(Debug)]
+enum ToEndpoint<C: Crypto> {
+    /// Instructs the endpoint to start connecting to the given address.
+    Dial {
+        /// UDP address to connect to.
+        addr: SocketAddr,
+        /// The remotes public key.
+        public_key: C::PublicKey,
```
Comment (kpp) [inline transports/quic/src/endpoint.rs]: > mxinden
Do I understand correctly that one can thus not dial a remote without their PeerId?

**Comment by mxinden** [comment]
Thanks @kpp for driving this forward. I will take a look.

File: transports/quic/src/crypto.rs [hunk 4]
```diff
@@ -0,0 +1,219 @@
+// Copyright 2021 David Craven.
```
Comment (kpp) [inline transports/quic/src/crypto.rs]: > mxinden
For the sake of consistency, would you mind including license headers here?

Done

File: transports/quic/src/endpoint.rs [hunk 5]
```diff
@@ -0,0 +1,491 @@
...
+        addr: SocketAddr,
+        public_key: C::PublicKey,
+    ) -> oneshot::Receiver<Result<QuicMuxer<C>, QuicError>> {
+        let (tx, rx) = oneshot::channel();
+        let msg = ToEndpoint::Dial {
+            addr,
+            public_key,
+            tx,
+        };
+        self.tx.unbounded_send(msg).expect("endpoint has crashed");
```
Comment (kpp) [inline transports/quic/src/endpoint.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r720412870

> mxinden 
Why can one not use a bounded channel here and await both the sending and the result through the oneshot?
dvc94ch
I guess you can do that, but what's the point
mxinden
The point would be to enable backpressure throughout the system. Through backpressure an upper layer component is paused when the lower layer is overwhelmed and woken up when the lower layer is ready to receive new items.

File: transports/quic/src/endpoint.rs [hunk 6]
```diff
@@ -0,0 +1,491 @@
...
+impl<C: Crypto> EndpointChannel<C> {
+    pub fn poll_next_event(&mut self, cx: &mut Context) -> Poll<Option<ToEndpoint<C>>> {
+        Pin::new(&mut self.rx).poll_next(cx)
+    }
+
+    pub fn create_connection(
+        &self,
+        id: ConnectionHandle,
+    ) -> (ConnectionChannel<C>, mpsc::Sender<ConnectionEvent>) {
+        let (tx, rx) = mpsc::channel(12);
```
Comment (kpp) [inline transports/quic/src/endpoint.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r720414077

>  mxinden
What is the reasoning for the constant 12?
dvc94ch
empirical testing. I printlned when it was blocked and 12 seemed to work well for the test
mxinden
I wonder whether the queue is needed at all. As a rule of thumb I follow the rule of [Queues exist only to handle burstiness](https://apenwarr.ca/log/20170814). Is creating new connections a bursty task? If not, why introduce a queue?

File: transports/quic/src/endpoint.rs [hunk 7]
```diff
@@ -0,0 +1,491 @@
...
+            ty: self.socket.socket_type(),
+        };
+        let endpoint = EndpointChannel {
+            tx: tx2,
+            rx: rx1,
+            port: self.port,
+            max_datagrams: self.capabilities.max_gso_segments,
+            connection_tx: transport.tx.clone(),
+        };
+        async_global_executor::spawn(Endpoint::new(endpoint, self)).detach();
```
Comment (kpp) [inline transports/quic/src/endpoint.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r720415472

> mxinden
All of rust-libp2p is generic over the executor to be used. Before we introduce a protocol locked onto a single executor, what is the reasoning for not being generic over the executor?
dvc94ch
there is currently no api for a transport to use the swarm's executor

File: transports/quic/src/endpoint.rs [hunk 8]
```diff
@@ -0,0 +1,491 @@
...
+                    me.outgoing.drain(..n);
+                }
+                Poll::Ready(Err(err)) => tracing::error!("send_to: {}", err),
+                Poll::Pending => break,
+            }
+        }
+
+        if me.event_slot.is_none() && me.incoming_slot.is_none() {
+            let mut metas = [RecvMeta::default(); BATCH_SIZE];
+            let mut iovs = MaybeUninit::<[IoSliceMut; BATCH_SIZE]>::uninit();
```
Comment (kpp) [inline transports/quic/src/endpoint.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r720421499

> mxinden
I am assuming this is an optimization. If so, given the usage of unsafe code, what performance impact did this optimization show in benchmarks?

File: transports/quic/src/muxer.rs [hunk 9]
```diff
@@ -0,0 +1,438 @@
...
+        cx: &mut Context,
+    ) -> Poll<Result<StreamMuxerEvent<Self::Substream>, Self::Error>> {
+        let mut inner = self.inner.lock();
+        let now = Instant::now();
+
+        while let Poll::Ready(event) = inner.endpoint.poll_channel_events(cx) {
+            inner.connection.handle_event(event);
+        }
+
+        let _max_datagrams = inner.endpoint.max_datagrams();
```
Comment (kpp) [inline transports/quic/src/muxer.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r720425972

> mxinden
Does this method call have any side effects?
dvc94ch
no, this is when using quinn-proto from git which changes the api
dvc94ch
https://github.com/quinn-rs/quinn/blob/main/quinn-proto/src/connection/mod.rs#L411

File: transports/quic/src/muxer.rs [hunk 10]
```diff
@@ -0,0 +1,438 @@
...
+        while let Some(event) = inner.connection.poll_endpoint_events() {
+            inner.endpoint.send_endpoint_event(event);
+        }
+
+        while let Some(event) = inner.connection.poll() {
+            match event {
+                Event::HandshakeDataReady => {}
+                Event::Connected => {
+                    // Break here so that the noise upgrade can finish.
+                    return Poll::Pending;
```
Comment (kpp) [inline transports/quic/src/muxer.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r720427170

>  mxinden 
Can you expand on this? Why does this Future have to pause? Where is the waker of the task registered?
dvc94ch
this is so the upgrade can complete
https://github.com/libp2p/rust-libp2p/pull/2159/files#diff-b1dcda9367774dd8a742457ff79bc528d030a8cc38d6791efefc78b30f3f2e03R222

File: transports/quic/src/muxer.rs [hunk 11]
```diff
@@ -0,0 +1,438 @@
...
+                        waker.wake();
+                    }
+                    return Poll::Ready(Err(QuicMuxerError::ConnectionLost { reason }));
+                }
+                Event::Stream(StreamEvent::Opened { dir: Dir::Bi }) => {
+                    // handled at end.
+                }
+                Event::Stream(StreamEvent::Readable { id }) => {
+                    tracing::trace!("stream readable {}", id);
+                    if let Some(substream) = inner.substreams.get_mut(&id) {
```
Comment (kpp) [inline transports/quic/src/muxer.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r720428182

> Is there a scenario where one would receive a StreamEvent::Readable but not have a reference to it in inner.substreams? If not, how about an expect here to enforce this assumption?

File: transports/quic/src/tls/verifier.rs [hunk 12]
```diff
@@ -0,0 +1,244 @@
...
+    }
+
+    fn verify_tls12_signature(
+        &self,
+        _message: &[u8],
+        _cert: &Certificate,
+        _dss: &DigitallySignedStruct,
+    ) -> Result<HandshakeSignatureValid, TLSError> {
+        Err(TLSError::PeerIncompatibleError(
+            "Only TLS 1.3 certificates are supported".to_string(),
```
Comment (kpp) [inline transports/quic/src/tls/verifier.rs]: https://github.com/libp2p/rust-libp2p/pull/2159#discussion_r709586266

> DemiMarie 
I believe this is not reachable as rustls should have aborted the handshake sooner, but panicking here is not critical.

File: transports/quic/tests/smoke.rs [hunk 13]
```diff
@@ -0,0 +1,392 @@
+use anyhow::Result;
```
Comment (kpp) [inline transports/quic/tests/smoke.rs]: > DemiMarie
I recommend running the tests thousands of times in a tight loop, using netem to simulate packet loss and/or reordering. This caught bugs I was working on my version, both in my code and in quinn-proto.

**Review by kpp — COMMENTED** [review]
Linked discussions from the previous PR

File: transports/quic/src/endpoint.rs (hunk 3 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs]: You are right. One cannot dial a remote without their PeerId.

File: transports/quic/Cargo.toml [hunk 14]
```diff
@@ -0,0 +1,45 @@
+[package]
+name = "libp2p-quic"
+version = "0.6.0"
+authors = ["David Craven <david@craven.ch>", "Parity Technologies <admin@parity.io>"]
+edition = "2018"
+description = "TLS and Noise based QUIC transport implementation for libp2p"
+repository = "https://github.com/libp2p/rust-libp2p"
+license = "MIT"
+
+[features]
```
Comment (mxinden) [inline transports/quic/Cargo.toml]: If I am not mistaken, these features can not be enabled via the `libp2p` crate. Should we mirror these to the root `Cargo.toml` e.g. as `quic-tls` and `quic-noise`?

**Review by mxinden — COMMENTED** [review]
Short update: I am currently testing this pull request with https://github.com/mxinden/libp2p-perf. Still need a bit more time before I can share any results.

Small comment below.

File: transports/quic/src/endpoint.rs (hunk 3 above)
Comment (mxinden) [reply transports/quic/src/endpoint.rs]: What is the reason for this constraint @kpp?

Comment (kpp) [reply transports/quic/src/endpoint.rs]: That's the same reason as from [go-libp2p-quic-transport](https://github.com/libp2p/go-libp2p-quic-transport/blob/4d43d2d2a1c4bebe5e3cf9c863f8cb16beece0c7/cmd/client/main.go#L47):

Hence the [specs](https://github.com/libp2p/specs/blob/master/tls/tls.md#libp2p-public-key-extension):

> Clients MUST verify that the peer ID derived from the certificate matches the peer ID they intended to connect to, and MUST abort the connection if there is a mismatch.

File: transports/quic/src/transport.rs [hunk 15]
```diff
@@ -0,0 +1,405 @@
...
+    type Error = QuicError;
+    type Listener = Self;
+    type ListenerUpgrade = QuicUpgrade<C>;
+    type Dial = QuicDial<C>;
+
+    fn listen_on(self, addr: Multiaddr) -> Result<Self::Listener, TransportError<Self::Error>> {
+        multiaddr_to_socketaddr::<C>(&addr)
+            .map_err(|_| TransportError::MultiaddrNotSupported(addr))?;
+        Ok(self)
+    }
```
Comment (mxinden) [inline transports/quic/src/transport.rs]: Do I understand correctly, that `<QuicTransport as Transport>::listen_on` is a no-op apart from libp2p-core now polling QuicTransport as a listener? How does one provide multiple `Multiaddr`s to be listened on?

File: transports/quic/src/endpoint.rs (hunk 3 above)
Comment (mxinden) [reply transports/quic/src/endpoint.rs]: > Clients MUST verify that the peer ID derived from the certificate matches the peer ID they intended to connect to, and MUST abort the connection if there is a mismatch.

I read this as "[If clients intended to connect to a specific peer ID] Clients MUST verify [...]".

Under the assumption that libp2p implementations are free to implement dialing unknown peers (which rust-libp2p supports on TCP today), is there something inherent to QUIC that would block this?

//CC @marten-seemann

Comment (kpp) [reply transports/quic/src/endpoint.rs]: Let's take a look at a js example of QUIC:

```
const { createQuicSocket } = require('net');

// Create a QuicSocket associated with localhost and port 1234
const socket = createQuicSocket({ endpoint: { port: 1234 } });

const client = socket.connect({
  address: 'example.com',
  port: 4567,
  alpn: 'foo'
});
```

Since TLS1.3 is embedded into QUIC, the cert of `example.com` and it's identity can be verified via cert chain. In libp2p-tls we don't have cert chains, all certs are self-signed.
So it would require an additional handshake to verify identity in your case. That is possible but we will lose 0-RTT ability.

Comment (marten-seemann) [reply transports/quic/src/endpoint.rs]: > Under the assumption that libp2p implementations are free to implement dialing unknown peers (which rust-libp2p supports on TCP today), is there something inherent to QUIC that would block this?

No, this is completely independent from QUIC. The way we do the TLS handshake in libp2p allows this, and therefore it's possible in QUIC as well.

> Since TLS1.3 is embedded into QUIC, the cert of example.com and it's identity can be verified via cert chain. In libp2p-tls we don't have cert chains, all certs are self-signed.
> So it would require an additional handshake to verify identity in your case. That is possible but we will lose 0-RTT ability.

That is not correct. There's a cert chain, it's just ending at a CA that's trusted by the WebPKI. Please refer to https://github.com/libp2p/specs/blob/master/tls/tls.md for the details. In short: Yes, you can use the certificate chain to verify the peer's identity without any need for an additional handshake.

For 0-RTT, you could just save the peer's identity in the session ticket (encrypted, of course). That will trivially allow you restore all authentication state you had on the original connection. No additional handshake needed in this case either.

File: transports/quic/src/tls/verifier.rs (hunk 12 above)
Comment (marten-seemann) [reply transports/quic/src/tls/verifier.rs]: There's no such thing as a "TLS 1.3 certificate". Certificates are a concept that's not tied to the TLS version.

File: transports/quic/src/tls/certificate.rs [hunk 16]
```diff
@@ -0,0 +1,76 @@
...
+use super::LIBP2P_SIGNING_PREFIX_LENGTH;
+use libp2p_core::identity::Keypair;
+
+const LIBP2P_OID: &[u64] = &[1, 3, 6, 1, 4, 1, 53594, 1, 1]; // Based on libp2p TLS 1.3 specs
+const LIBP2P_SIGNATURE_ALGORITHM_PUBLIC_KEY_LENGTH: usize = 91;
+static LIBP2P_SIGNATURE_ALGORITHM: &rcgen::SignatureAlgorithm = &rcgen::PKCS_ECDSA_P256_SHA256;
+
+/// Generates a self-signed TLS certificate that includes a libp2p-specific
+/// certificate extension containing the public key of the given keypair.
+pub(crate) fn make_cert(keypair: &Keypair) -> Result<rcgen::Certificate, super::ConfigError> {
```
Comment (marten-seemann) [inline transports/quic/src/tls/certificate.rs]: Disclaimer: I'm not familiar with the structure of the Rust library _at all_.
I assume you must have some logic in your libp2p TLS implementation to do this. Would it make sense to reuse that code?
cc @mxinden

File: transports/quic/src/tls/verifier.rs [hunk 17]
```diff
@@ -0,0 +1,244 @@
...
+
+    fn verify_client_cert(
+        &self,
+        presented_certs: &[Certificate],
+        _dns_name: Option<&webpki::DNSName>,
+    ) -> Result<ClientCertVerified, rustls::TLSError> {
+        verify_presented_certs(presented_certs).map(|_| ClientCertVerified::assertion())
+    }
+
+    fn verify_tls12_signature(
```
Comment (marten-seemann) [inline transports/quic/src/tls/verifier.rs]: Why is this function needed? QUIC is only specified to work over TLS >= 1.3.

Checking that TLS >= 1.3 is negotiated should probably be part of the QUIC library.

File: transports/quic/tests/smoke.rs [hunk 18]
```diff
@@ -0,0 +1,392 @@
...
+    ProtocolName, ProtocolSupport, RequestResponse, RequestResponseCodec, RequestResponseConfig,
+    RequestResponseEvent, RequestResponseMessage,
+};
+use libp2p::swarm::{Swarm, SwarmEvent};
+use libp2p_quic::{Crypto, QuicConfig, ToLibp2p};
+use quinn_proto::crypto::Session;
+use rand::RngCore;
+use std::{io, iter};
+
+#[cfg(feature = "noise")]
```
Comment (marten-seemann) [inline transports/quic/tests/smoke.rs]: This is not needed for libp2p, is it? libp2p only uses RFC 9000.

File: transports/quic/src/tls/certificate.rs (hunk 16 above)
Comment (dvc94ch) [reply transports/quic/src/tls/certificate.rs]: rust-libp2p has no TLS implementation

File: transports/quic/src/tls/verifier.rs (hunk 17 above)
Comment (dvc94ch) [reply transports/quic/src/tls/verifier.rs]: It's required to implement the trait

File: transports/quic/tests/smoke.rs (hunk 18 above)
Comment (dvc94ch) [reply transports/quic/tests/smoke.rs]: Who says what libp2p is. PL hasn't trademarked the name and if it did I'd suggest renaming the library. The request-response protocol is also not implemented in go-libp2p

File: transports/quic/src/endpoint.rs (hunk 3 above)
Comment (dvc94ch) [reply transports/quic/src/endpoint.rs]: > For 0-RTT, you could just save the peer's identity in the session ticket (encrypted, of course). That will trivially allow you restore all authentication state you had on the original connection. No additional handshake needed in this case either.

Apart from this not being implemented it's not really 0rtt is it? You need to store some negotiated key for the next connection.

Comment (dvc94ch) [reply transports/quic/src/endpoint.rs]: > implementations are free to implement dialing unknown peers

Sure libp2p allows it over TCP. The question is if it's a good idea. An IP address and port tuple provides absolutely no authentication and can be trivially mim'd. What's the point of encrypting data at all if you're going to send it to any party. We can just remove encryption in that case as it's just wasted CPU cycles

Comment (marten-seemann) [reply transports/quic/src/endpoint.rs]: > Apart from this not being implemented it's not really 0rtt is it? You need to store some negotiated key for the next connection.

That's exactly how 0-RTT works: You store a shared key derived from the TLS master secret in the session ticket, and use that to encrypt your first flight of data.
In addition to the key that TLS stores, QUIC implementations are required to store their QUIC transport parameters in the session ticket (and the client needs to remember transport parameters along side the session ticket), see https://datatracker.ietf.org/doc/html/rfc9000#section-7.4.1 for details.
In addition to that, the application is free to store its own data in the session ticket, which in the case of libp2p one could use to store the peer's ID. Note that as this is an implementation decision, there's no need to specify the serialization format.

> Sure libp2p allows it over TCP. The question is if it's a good idea. An IP address and port tuple provides absolutely no authentication and can be trivially mim'd.

There's no risk of MITM. You still verify the certificate chain and derive the peer ID from that.

Comment (dvc94ch) [reply transports/quic/src/endpoint.rs]: > That's exactly how 0-RTT works: You store a shared key derived from the TLS master secret in the session ticket, and use that to encrypt your first flight of data.

Yes, that's how it works with tls as it is based on certificates for authentication. In a dh based authentication protocol like noise you can always have 0rtt even on the first connection.

> There's no risk of MITM. You still verify the certificate chain and derive the peer ID from that.

Sure you can. But you need to check that the peer ID you derived matches the peer ID you expected, otherwise an attacker can generate any valid self signed certificate chain and provide that. All we do here is check that it is indeed the expected peer ID.

File: transports/quic/src/transport.rs (hunk 15 above)
Comment (kpp) [reply transports/quic/src/transport.rs]: > How does one provide multiple Multiaddrs to be listened on?

If I am not mistaken, you can't `listen_on` multiple addrs on other transports too.

Comment (dvc94ch) [reply transports/quic/src/transport.rs]: > Do I understand correctly, that <QuicTransport as Transport>::listen_on is a no-op apart from libp2p-core now polling QuicTransport as a listener?

Saddly I didn't come up with a better solution, if you (@mxinden) can come up with something better that would be nice.

> If I am not mistaken, you can't listen_on multiple addrs on other transports too.

That is not accurate

> How does one provide multiple Multiaddrs to be listened on?

You need to construct multiple quic transports. altough a `listen_on("/ip4/0.0.0.0/udp/quic/0")` works for all ip4 addresses and on linux `listen_on("/ip6/:::1/udp/quic/0")` works for all ip6 & ip4 addresses.

Comment (kpp) [reply transports/quic/src/transport.rs]: > That is not accurate

Would you please provide an example except for a meta-address?

Comment (dvc94ch) [reply transports/quic/src/transport.rs]: For TCP? You can bind them individually, for quick you need to create multiple transports

File: transports/quic/src/endpoint.rs (hunk 3 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs]: > That is not correct. There's a cert chain, it's just ending at a CA that's trusted by the WebPKI. Please refer to https://github.com/libp2p/specs/blob/master/tls/tls.md for the details.

The doc states : `the host key is encoded into the libp2p Public Key Extension, which is carried in a self-signed certificate.`. So there is only one cert and it is self-signed.

File: transports/quic/tests/smoke.rs (hunk 13 above)
Comment (kpp) [reply transports/quic/tests/smoke.rs]: Done. Thanks!

File: transports/quic/src/transport.rs (hunk 15 above)
Comment (tomaka) [reply transports/quic/src/transport.rs]: In my earlier prototype, one had to pass a specific address when creating the `QuicTransport`, and `listen_on` would return an error if you try to listen on an address that isn't the one that was passed.

**Review by dvc94ch — COMMENTED** [review]
What's the point of this? @marten-seemann is not a contributor or even user of rust-libp2p, so don't know why his opinion is relevant here.

File: transports/quic/src/endpoint.rs (hunk 6 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs]: Increasing to 120 gives:

```
Interval	Transfer	Bandwidth
0 s - 10.00 s	1894 MBytes	1515.06 MBit/s
```

Which is an `x2` boost. This one should be seriously considered.

Comment (mxinden) [reply transports/quic/src/endpoint.rs]: Throughput almost always benefits from larger queue lengths, though at the expense of latency. In my eyes a good starting point on this topic is [buffer bloat](https://en.wikipedia.org/wiki/Bufferbloat). Also I found [these 4 rules](https://twitter.com/peterbourgon/status/1212800031406739456) to come in handy.

Long story short, in my eyes finding the right queue length is a lot harder than a single scenario benchmark and until we did thorough testing, I would go with a queue length of `1`, which in this case means `channel(0)` as each sender [has at least one slot reserved](https://docs.rs/futures/0.3.17/futures/channel/mpsc/fn.channel.html).

**Comment by dvc94ch** [comment]
So what's missing here? Is this one ready to merge?

**Comment by kpp** [comment]
See https://github.com/paritytech/polkadot-sdk/issues/536

**Comment by DemiMarie** [comment]
barebones-x509 author here.  What was the reason for switching to an alternate library?  I wrote barebones-x509 specifically for use in libp2p, and I would like to know what made x509-parser a better choice.

**Comment by kpp** [comment]
Sure. barebones-x509 was not tested against go implementation (and required several fixes as you remember). There could be other errors so I wrote my own and tested it.

**Comment by DemiMarie** [comment]
> Sure. barebones-x509 was not tested against go implementation (and required several fixes as you remember). There could be other errors so I wrote my own and tested it.

If I recall correctly the flaws were in the code that called barebones-x509, not barebones-x509 itself.  If you are aware of a flaw in barebones-x509, please report it as a bug.  barebones-x509 uses the same ASN.1 parser (*ring*) as WebPKI does, and does zero memory allocations internally (except in *ring*’s RSA code), so I expect it to be quite a bit more robust than der-parser or x509-parser.

**Comment by dvc94ch** [comment]
while I didn't have a preference earlier, I've recently had to parse/generate some pkcs7 and dive deep into asn1/der/ber/pem formats, [rasn](https://github.com/XAMPPRocky/rasn/) seems to be quite neat. yasna and other crates have very incomplete support afaik.

**Comment by dvc94ch** [comment]
you should be able to parse the certificate with https://github.com/XAMPPRocky/rasn/tree/main/standards/pkix

**Comment by DemiMarie** [comment]
@kpp I think one of the remaining tasks would be to get rid of the `UnboundedReceiver`s, for denial-of-service prevention.

File: transports/quic/src/endpoint.rs (hunk 5 above)
Comment (DemiMarie) [reply transports/quic/src/endpoint.rs]: In this case `dial` would need to return a `Future` that resolves when the message has been sent *and* received.  Obtaining the value from a `oneshot::Receiver` is already asynchronous so this should not be too hard.

**Comment by mxinden** [comment]
@kpp I prepared a merge of latest master and wrote a test for concurrent connections and streams. Do you want to merge it into this branch? https://github.com/kpp/rust-libp2p/pull/13

**Comment by kpp** [comment]
Yeah, the more tests we get, the better it is. I am working on on another implementation which has a highly better performance. I will push it in several days.

File: transports/quic/src/endpoint.rs (hunk 5 above)
Comment (mxinden) [reply transports/quic/src/endpoint.rs]: https://github.com/mxinden/rust-libp2p/commit/1230178cd660783a57b895d377621abaa66346e7 showcases how to remove the bounded channels. Today it builds on top of https://github.com/libp2p/rust-libp2p/pull/2529, though it would as well work without.

File: transports/quic/src/muxer.rs [hunk 19]
```diff
@@ -0,0 +1,439 @@
...
+        let mut inner = self.inner.lock();
+        let now = Instant::now();
+
+        while let Poll::Ready(event) = inner.endpoint.poll_channel_events(cx) {
+            inner.connection.handle_event(event);
+        }
+
+        let max_datagrams = inner.endpoint.max_datagrams();
+        while let Some(transmit) = inner.connection.poll_transmit(now, max_datagrams) {
+            inner.endpoint.send_transmit(transmit);
```
Comment (mxinden) [inline transports/quic/src/muxer.rs]: Note I am not 100% sure this would adhere to the API requirements of `QuinnConnection`, namely to call `send_transmit` after a `handle_event`:

https://github.com/quinn-rs/quinn/blob/7b4b4c31e5878bdbce56ab2737dd8cfbafe1c4db/quinn-proto/src/connection/mod.rs#L89-L112

Not sure whether I am interpreting these requirements too strictly. 

In case you are interested in an alternative call sequence, see https://github.com/mxinden/rust-libp2p/commit/1230178cd660783a57b895d377621abaa66346e7 more specifically:

https://github.com/mxinden/rust-libp2p/commit/1230178cd660783a57b895d377621abaa66346e7#diff-d59efbc1f8dc6ed1521dd36e906216f4ff4ade561dca9b50beea1da354240cf7R144-R305

**Review by mxinden — COMMENTED** [review]
Played around with this pull request once more over the weekend.

Outcome is basically https://github.com/mxinden/rust-libp2p/commit/1230178cd660783a57b895d377621abaa66346e7 which removes the unbounded channels.

Unfortunately I am still unable to make test in https://github.com/kpp/rust-libp2p/pull/13 succeed. Both with and without https://github.com/mxinden/rust-libp2p/commit/1230178cd660783a57b895d377621abaa66346e7.

**Comment by kpp** [comment]
So there is another implementation: https://github.com/kpp/rust-libp2p/tree/libp2p-quic-reimplementation and https://github.com/kpp/libp2p-perf/tree/quic-reimpl. The code is a bit dirty, but the swarm can connect from rust <-> go and the perf is much better:

```
$ ./run.sh 
# Start Rust and Golang servers.
Local peer id: PeerId("Qmcqq9TFaYbb94uwdER1BXyGfCFY4Bb1gKozxNyVvLvTSw")
about to listen on "/ip4/127.0.0.1/udp/9992/quic"
Listening on "/ip4/127.0.0.1/udp/9992/quic".
Listening on "/ip4/192.168.1.173/udp/9992/quic".

# Rust -> Rust

## Transport security noise
Local peer id: PeerId("12D3KooWA8UTRtRQqNi8tMyyyXmMuXxe8umQXTs4LzsuqoiXsshR")
IncomingConnection { local_addr: "/ip4/0.0.0.0/udp/9992/quic", send_back_addr: "/ip4/127.0.0.1/udp/40876/quic" }
ConnectionEstablished { peer_id: PeerId("12D3KooWA8UTRtRQqNi8tMyyyXmMuXxe8umQXTs4LzsuqoiXsshR"), endpoint: Listener { local_addr: "/ip4/0.0.0.0/udp/9992/quic", send_back_addr: "/ip4/127.0.0.1/udp/40876/quic" }, num_established: 1, concurrent_dial_errors: None }
Interval	Transfer	Bandwidth
0 s - 10.00 s	2698 MBytes	2157.97 MBit/s

# Rust -> Golang

Local peer id: PeerId("12D3KooWDxhshLBPTJcECvJafrYuYt76fcbmD3m9xdBBV1SR7HEU")
  ERROR libp2p_quic::connection: stream stopped server bidirectional stream 0
    at /home/kpp/.cargo/git/checkouts/rust-libp2p-2465c479375e5ed6/f7e52d0/transports/quic/src/connection.rs:392

Interval	Transfer	Bandwidth
0 s - 10.00 s	1932 MBytes	1545.14 MBit/s


# Golang -> Rust

## Transport security noise
2022/02/21 15:44:09 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
IncomingConnection { local_addr: "/ip4/0.0.0.0/udp/9992/quic", send_back_addr: "/ip4/127.0.0.1/udp/51067/quic" }
ConnectionEstablished { peer_id: PeerId("12D3KooWJ5kqPcjKKT9iQcQB4KVFg5xDZRM2BgSyheBqwNQRZWBq"), endpoint: Listener { local_addr: "/ip4/0.0.0.0/udp/9992/quic", send_back_addr: "/ip4/127.0.0.1/udp/51067/quic" }, num_established: 1, concurrent_dial_errors: None }
Interval 	Transfer	Bandwidth
0s - 10.00 s 	1670 MBytes	1335.96 MBit/s

# Golang -> Golang

2022/02/21 15:44:19 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Interval 	Transfer	Bandwidth
0s - 10.00 s 	1592 MBytes	1273.55 MBit/s
```

I am still playing with code, so please don't judge.


Unfortunately I am still unable to make test in https://github.com/kpp/rust-libp2p/pull/13 succeed either. I suspect there is an issue with the list of wakers in Muxer per every stream.

**Comment by dvc94ch** [comment]
can you elaborate on what the bottle neck was and what changes you made? `1545.14 MBit/s` doesn't seem like it's much of an improvement over previous code. I believe that's roughly the perf I got too.

**Comment by kpp** [comment]
You are looking into `rust -> golang` which didn't work at all. The previous result for `rust -> rust` was `288.72 MBit/s`.

**Comment by dvc94ch** [comment]
So what was the problem exactly? I'm pretty sure I'd have noticed if the code was that slow, although haven't kept up to date with all the changes that were made.

**Comment by dvc94ch** [comment]
There seems to be something fishy with these numbers anyway ## Transport security noise is the base line? It doesn't seem to have anything to do with quic

**Comment by kpp** [comment]
Don't pay attention to it: https://github.com/kpp/libp2p-perf/blob/6d6ceaead4edac8ababd3cfa5c97b96c2adf0c29/run.sh#L26.

**Comment by dvc94ch** [comment]
Well, 2.2GBit/s seems pretty good and should saturate most internet connections. Still curious as to how you achieved the x7.5 speed up.

**Comment by DemiMarie** [comment]
> Played around with this pull request once more over the weekend.
> 
> Outcome is basically [mxinden@1230178](https://github.com/mxinden/rust-libp2p/commit/1230178cd660783a57b895d377621abaa66346e7) which removes the unbounded channels.

Is it possible to avoid circumventing backpressure?

**Comment by mxinden** [comment]
> > Played around with this pull request once more over the weekend.
> > Outcome is basically [mxinden@1230178](https://github.com/mxinden/rust-libp2p/commit/1230178cd660783a57b895d377621abaa66346e7) which removes the unbounded channels.
> 
> Is it possible to avoid circumventing backpressure?

I am not sure I follow @DemiMarie. Are you asking whether it is possible for `libp2p-quic` to enforce backpressure? If I am not mistaken, given that we are using the `quinn-proto` state machine directly, yes, it seems to be possible.

**Comment by DemiMarie** [comment]
> > > Played around with this pull request once more over the weekend.
> > > Outcome is basically [mxinden@1230178](https://github.com/mxinden/rust-libp2p/commit/1230178cd660783a57b895d377621abaa66346e7) which removes the unbounded channels.
> > 
> > 
> > Is it possible to avoid circumventing backpressure?
> 
> I am not sure I follow @DemiMarie. Are you asking whether it is possible for `libp2p-quic` to enforce backpressure? If I am not mistaken, given that we are using the `quinn-proto` state machine directly, yes, it seems to be possible.

I am referring to the comment in the source code about cloning a `Sender`.

Also, have you considered switching back to https://github.com/barebones-x509/barebones-x509 for certificate parsing?  That will be much lighter than `x509-parser`, and it uses the same ASN.1 parser that `webpki` does.  The reason that it has not seen much development is simply that it is already sufficient for libp2p-quic and I have not seen much in the way of feature requests from third parties.

**Comment by dignifiedquire** [comment]
what about https://docs.rs/x509 ? it should be even more lightweight, avoiding the webpki details (haven’t checked if it supports everything required though)

**Comment by DemiMarie** [comment]
> what about https://docs.rs/x509 ? it should be even more lightweight, avoiding the webpki details (haven’t checked if it supports everything required though)

That only supports serialization, and the webpki stuff is just for error codes.

**Comment by dignifiedquire** [comment]
Ah sorry, it seems it is not published yet, https://github.com/RustCrypto/formats/tree/master/x509 is what I was referring to, which does encoding as well, as far as I understand the tests.

**Comment by DemiMarie** [comment]
@dignifiedquire that makes sense.

**Comment by elenaf9** [comment]
If I understand it correctly, the reason for using the `quinn-proto` state-machine instead of `quinn` was mostly because quinn only supports tokio as runtime [1]. There has recently been some work towards adding support to async-std for quinn [2]. Have you considered switching to use `quinn` directly? I think this could save us a lot of complexity.

Also related to this: @mxinden raised the idea in the past to remove the concept of listeners and instead implement `Stream` directly on the transport [3]. Doing this would in our case allow us to implement `Transport` directly on (a wrapper of) `quinn::Endpoint` with something like this for example:
```rust
struct Endpoint {
  inner: quinn::Endpoint
}

impl Transport for Endpoint {
   type Dial = quinn::Connecting;
   type Output = quinn::NewConnection;
   type ListenerUpgrade = quinn::Connecting;
   ...
}

impl Stream for Endpoint {
   type Item = ListenerEvent<_>
   ...
}
```
(Did not fully think this trough yet so don't focus on the specific types; it's more about the general idea).
I have been experimenting a little bit with this to see if our TCP transport implementation could be refactored according to the proposed transport trait changes. From a first draft it seems to be a doable ([4]) by pushing a lot of the listeners logic out of `swarm::connection::ListenersStream` and into `GenTcpConfig`, though I did not test the integration in the swarm yet.

What do you think about this idea in general, do you think it is worth exploring? Happy to help and work on a PoC of how `quinn::Endpoint` could be integrated with this.

- [1] https://github.com/quinn-rs/quinn/issues/502
- [2] https://github.com/quinn-rs/quinn/pull/1346
- [3] https://github.com/libp2p/rust-libp2p/discussions/2113#discussioncomment-944923, 
       https://github.com/libp2p/rust-libp2p/pull/2529#issuecomment-1087384988 
- [4] https://github.com/elenaf9/rust-libp2p/commit/0c3c45efcb2caae1a673635c5124fd600e866fd2

**Comment by kpp** [comment]
@elenaf9 I am working on the final polishing of the code. Everything works but I need to refactor it a little bit.

Still the work done by @yu-re-ka is worth looking at. Maybe I can throw away some code in the future.

File: transports/quic/src/muxer.rs [hunk 20]
```diff
@@ -0,0 +1,426 @@
...
+                poll_close_waker: None,
+                poll_event_waker: None,
+            }),
+        }
+    }
+}
+
+impl StreamMuxer for QuicMuxer {
+    type OutboundSubstream = ();
+    type Substream = quinn_proto::StreamId;
```
Comment (elenaf9) [inline transports/quic/src/muxer.rs]: With #2648 `QuicMuxer::Substream` will have to implement `AsyncRead` and `AsyncWrite`. Hence we can not just use an Id here, but instead have to implement something like quinn's `SendStream` and `RecvStream`

File: swarm/src/lib.rs [hunk 21]
```diff
@@ -1337,6 +1337,7 @@ where
             self.pool_config.or_else_with_executor(|| {
                 match ThreadPoolBuilder::new()
                     .name_prefix("libp2p-swarm-task-")
+                    .pool_size(1)
```
Comment (elenaf9) [inline swarm/src/lib.rs]: I believe this was only a temporary change, right? Is it still needed?

File: transports/quic/src/connection.rs [hunk 22]
```diff
@@ -0,0 +1,465 @@
...
+    connection_id: quinn_proto::ConnectionHandle,
+    /// `Future` that triggers at the `Instant` that `self.connection.poll_timeout()` indicates.
+    next_timeout: Option<Timer>,
+
+    /// In other to avoid race conditions where a "connected" event happens if we were not
+    /// handshaking, we cache whether the connection is handshaking and only set this to true
+    /// after a "connected" event has been received.
+    ///
+    /// In other words, this flag indicates whether a "connected" hasn't been received yet.
+    is_handshaking: bool,
```
Comment (elenaf9) [inline transports/quic/src/connection.rs]: How is this flag currently helping to avoid race conditions? I don't think it is used anywhere (apart from debug asserts).

File: transports/quic/src/connection.rs [hunk 23]
```diff
@@ -0,0 +1,465 @@
...
+                        self.next_timeout = Some(Timer::at(when));
+                    }
+                } else {
+                    break;
+                }
+            }
+
+            // The connection also needs to be able to send control messages to the endpoint. This is
+            // handled here, and we try to send them on `to_endpoint` as well.
+            if let Some(endpoint_event) = self.connection.poll_endpoint_events() {
```
Comment (elenaf9) [inline transports/quic/src/connection.rs]: Should we handle here the case of `endpoint_event.is_drained()`? Currently it is just send to the endpoint, that will then drop the sender side of `from_endpoint`, which then causes an `Error::ClosedChannel`.

File: transports/quic/src/connection.rs [hunk 24]
```diff
@@ -0,0 +1,465 @@
...
+    pub(crate) fn close(&mut self) {
+        // TODO: what if the user calls this multiple times?
+        // We send a dummy `0` error code with no message, as the API of StreamMuxer doesn't
+        // support this.
+        self.connection
+            .close(Instant::now(), From::from(0u32), Default::default());
+        self.endpoint.report_quinn_event_non_block(
+            self.connection_id,
+            quinn_proto::EndpointEvent::drained(),
+        );
```
Comment (elenaf9) [inline transports/quic/src/connection.rs]: I think `quinn_proto::Connection::close` will do a graceful shutdown and eventually emit a `EndpointEvent::drained` itself. If we already send it this event here, the Endpoint task will drop the sender side of `from_endpoint`, which will cause an `Error::ChannelClosed` (potentially before the graceful shutdown was completed).

File: transports/quic/src/connection.rs [hunk 25]
```diff
@@ -0,0 +1,465 @@
...
+    // /// If `Err(WriteError::Blocked)` is returned, then a [`ConnectionEvent::StreamWritable`] event
+    // /// will later be produced when the substream can be written to. A
+    // /// [`ConnectionEvent::StreamStopped`] event can also be emitted.
+    // pub(crate) fn write_substream(
+    //     &mut self,
+    //     id: quinn_proto::StreamId,
+    //     buf: &[u8],
+    // ) -> Result<usize, quinn_proto::WriteError> {
+    //     self.connection.write(id, buf)
+    // }
```
Comment (elenaf9) [inline transports/quic/src/connection.rs]: Is this logic superseded by `QuicMuxer::read_substream` and `QuicMuxxer::write_substream`?

File: transports/quic/src/connection.rs [hunk 26]
```diff
@@ -0,0 +1,465 @@
...
+        self.connection.send_stream(id).finish()
+    }
+
+    /// Polls the connection for an event that happend on it.
+    pub(crate) fn poll_event(&mut self, cx: &mut Context<'_>) -> Poll<ConnectionEvent> {
+        // Nothing more can be done if the connection is closed.
+        // Return `Pending` without registering the waker, essentially freezing the task forever.
+        if self.closed.is_some() {
+            return Poll::Pending;
+        }
```
Comment (elenaf9) [inline transports/quic/src/connection.rs]: I don't think we should be freezing the task. If the connection is closed (and thus we have previously returned a `ConnectionEvent::ConnectionLost`) the caller (`quic:Upgrade` / `QuicMuxer`) should make sure that the connection is cleaned up.

File: transports/quic/src/connection.rs [hunk 27]
```diff
@@ -0,0 +1,465 @@
...
+                } else if let Some(when) = self.connection.poll_timeout() {
+                    if when <= now {
+                        self.connection.handle_timeout(now);
+                    } else {
+                        //let delay = when - now;
+                        self.next_timeout = Some(Timer::at(when));
+                    }
+                } else {
+                    break;
+                }
```
Comment (elenaf9) [inline transports/quic/src/connection.rs]:
```suggestion
              if let Some(next_timeout) = &mut self.next_timeout {
                  match Future::poll(Pin::new(next_timeout), cx) {
                      Poll::Ready(when) => {
                          self.connection.handle_timeout(when);
                          self.next_timeout = None;
                      }
                      Poll::Pending => break,
                  }
              } 
              if let Some(when) = self.connection.poll_timeout() {
                  if when <= now {
                      self.connection.handle_timeout(now);
                  } else {
                      //let delay = when - now;
                      self.next_timeout = Some(Timer::at(when));
                  }
              } 
```

I think we can just write this as two sequential if statements. If I understand it correctly, we just need the loop because after calling `poll_timeout` we might set `next_timeout`. But given that we just checked that this timeout is in the future, I think polling it directly after will always return `Poll::Pending`.

File: transports/quic/Cargo.toml [hunk 28]
```diff
@@ -0,0 +1,34 @@
+[package]
+name = "libp2p-quic"
+version = "0.6.0"
```
Comment (elenaf9) [inline transports/quic/Cargo.toml]:
```suggestion
version = "0.1.0"
```

File: transports/quic/src/in_addr.rs [hunk 29]
```diff
@@ -0,0 +1,121 @@
...
+    net::IpAddr,
+    ops::DerefMut,
+    pin::Pin,
+    sync::Arc,
+    task::{Context, Poll},
+};
+
+/// Watches for interface changes.
+#[derive(Clone, Debug)]
+pub(crate) struct InAddr(Arc<Mutex<InAddrInner>>);
```
Comment (elenaf9) [inline transports/quic/src/in_addr.rs]: With #2529 `QuicTransport` does not need to be `Clone` anymore, hence I think it is also not needed for `InAddr` and we can remove the Mutex here.

File: transports/quic/src/lib.rs [hunk 30]
```diff
@@ -0,0 +1,70 @@
...
+//
+// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
+// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
+// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
+// DEALINGS IN THE SOFTWARE.
+
+#![recursion_limit = "1024"]
```
Comment (elenaf9) [inline transports/quic/src/lib.rs]: Why do we need an increased recursion limit?

File: transports/quic/src/muxer.rs [hunk 31]
```diff
@@ -0,0 +1,426 @@
...
+    /// This function behaves the same as a `Stream`.
+    ///
+    /// If `Pending` is returned, then the current task will be notified once the muxer
+    /// is ready to be polled, similar to the API of `Stream::poll()`.
+    /// Only the latest task that was used to call this method may be notified.
+    ///
+    /// It is permissible and common to use this method to perform background
+    /// work, such as processing incoming packets and polling timers.
+    ///
+    /// An error can be generated if the connection has been closed.
```
Comment (elenaf9) [inline transports/quic/src/muxer.rs]: It would be helpful if the docs would describe our implementation of the trait method, rather than just being a copy of the trait's docs :)

File: transports/quic/src/muxer.rs [hunk 32]
```diff
@@ -0,0 +1,426 @@
...
+            return Poll::Ready(Ok(0));
+        }
+
+        let mut stream = inner.connection.connection.recv_stream(id);
+        let mut chunks = match stream.read(true) {
+            Ok(chunks) => chunks,
+            Err(ReadableError::UnknownStream) => {
+                return Poll::Ready(Ok(0)); // FIXME This is a hack,
+                                           // a rust client should close substream correctly
+                                           // return Poll::Ready(Err(Self::Error::ExpiredStream))
```
Comment (elenaf9) [inline transports/quic/src/muxer.rs]: Is anything blocking this FIXME?

File: transports/quic/tests/smoke.rs [hunk 33]
```diff
@@ -0,0 +1,444 @@
...
+    let peer_id = keypair.public().to_peer_id();
+    let addr: Multiaddr = "/ip4/127.0.0.1/udp/0/quic".parse()?;
+    let config = QuicConfig::new(&keypair, addr).unwrap();
+    let endpoint = QuicEndpoint::new(config).unwrap();
+    let transport = QuicTransport::new(endpoint);
+
+    // TODO:
+    // transport
+    //     .transport
+    //     .max_idle_timeout(Some(quinn_proto::VarInt::from_u32(1_000u32).into()));
```
Comment (elenaf9) [inline transports/quic/tests/smoke.rs]: Can we add `max_idle_timeout` through `quinn_proto::ClientConfig` and `quinn_proto::ServerConfig`?

File: transports/quic/src/endpoint.rs [hunk 34]
```diff
@@ -0,0 +1,579 @@
...
+    /// Channel to the background of the endpoint.
+    /// See [`Endpoint::new_connections`] (just below) for a commentary about the mutex.
+    to_endpoint: Mutex<mpsc::Sender<ToEndpoint>>,
+
+    /// Channel where new connections are being sent.
+    /// This is protected by a futures-friendly `Mutex`, meaning that receiving a connection is
+    /// done in two steps: locking this mutex, and grabbing the next element on the `Receiver`.
+    /// The only consequence of this `Mutex` is that multiple simultaneous calls to
+    /// [`Endpoint::next_incoming`] are serialized.
+    new_connections: Mutex<mpsc::Receiver<Connection>>,
```
Comment (elenaf9) [inline transports/quic/src/endpoint.rs]: Having the receiver in a Mutex theoretically introduces a race condition when polling it. Now I know that it is only used in a single place, that is `Endpoint::poll_incoming`, which is only called in the `QuicTransport`. Nevertheless I think we should ensure on a type level that this will never be called from two different places. Hence I would propose to hold the `mpsc::Receiver<Connection>` directly in the `QuicTransport` and poll it there directly.

File: transports/quic/src/endpoint.rs [hunk 35]
```diff
@@ -0,0 +1,579 @@
...
+
+        // TODO: just for testing, do proper task spawning
+        async_global_executor::spawn(background_task(
+            config,
+            Arc::downgrade(&endpoint),
+            async_io::Async::<UdpSocket>::new(socket)?,
+            new_connections_tx,
+            to_endpoint_rx.fuse(),
+        ))
+        .detach();
```
Comment (elenaf9) [inline transports/quic/src/endpoint.rs]: Even with #2652 we have to spawn a separate task so that we don't burden the main loop. But I think we can add `Config::executor` similar to [`SwarmBuilder::executor`](https://docs.rs/libp2p/latest/libp2p/swarm/struct.SwarmBuilder.html#method.executor).

File: transports/quic/src/transport.rs [hunk 36]
```diff
@@ -0,0 +1,297 @@
...
+    IfWatcher(std::io::Error),
+}
+
+impl Transport for QuicTransport {
+    type Output = (PeerId, QuicMuxer);
+    type Error = Error;
+    // type Listener = Pin<
+    //     Box<dyn Stream<Item = Result<ListenerEvent<Upgrade, Self::Error>, Self::Error>> + Send>,
+    // >;
+    type Listener = Self;
```
Comment (elenaf9) [inline transports/quic/src/transport.rs]: With #2652 this won't be needed anymore. So I think `listen_on` can just be a noop. Eventually we might also want to allow multiple listeners / endpoints, but I think this is out of scope for this PR.

File: transports/quic/src/endpoint.rs [hunk 37]
```diff
@@ -0,0 +1,579 @@
...
+impl Endpoint {
+    /// Builds a new `Endpoint`.
+    pub fn new(config: Config) -> Result<Arc<Endpoint>, io::Error> {
+        let local_socket_addr = match crate::transport::multiaddr_to_socketaddr(&config.multiaddr) {
+            Some(a) => a,
+            None => panic!(), // TODO: Err(TransportError::MultiaddrNotSupported(multiaddr)),
+        };
+
+        // NOT blocking, as per man:bind(2), as we pass an IP address.
+        let socket = std::net::UdpSocket::bind(&local_socket_addr)?;
```
Comment (elenaf9) [inline transports/quic/src/endpoint.rs]: Could we use `quinn_udp::UdpSocket` here that quinn is also using internally?

**Review by elenaf9 — COMMENTED** [review]
Thank you for all your work on this @kpp! 
I started reviewing, but not fully through yet. 
I think #2652 will simplify the Transport implementation for us, especially because the `Listener` abstraction is removed, which I think is currently causing some difficulties.
Also note that there is a pending PR that refactors the `StreamMuxer` trait #2648. This will affect the QuicMuxer quite a lot (see below comment).  I am still wondering whether it would make more sense to switch to using the `quinn` top level crate, which would integrate well with the new StreamMuxer trait once https://github.com/quinn-rs/quinn/pull/1357 is merged.
Also with https://github.com/quinn-rs/quinn/pull/1219 the unbound channels will be removed as well as the spawning of a task for every connection, which afaik were so far the major reasons for not using `quinn` (together with the tokio runtime mentioned in my above comment).
Apart from these points, what is the reasoning for favoring `quinn_proto` over `quinn`?

File: swarm/src/lib.rs (hunk 21 above)
Comment (kpp) [reply swarm/src/lib.rs]: Oops, right!

**Comment by mxinden** [comment]
> I am still wondering whether it would make more sense to switch to using the `quinn` top level crate, which would integrate well with the new StreamMuxer trait once [quinn-rs/quinn#1357](https://github.com/quinn-rs/quinn/pull/1357) is merged.
> Also with [quinn-rs/quinn#1219](https://github.com/quinn-rs/quinn/pull/1219) the unbound channels will be removed as well as the spawning of a task for every connection, which afaik were so far the major reasons for not using `quinn` (together with the tokio runtime mentioned in my above comment).
> Apart from these points, what is the reasoning for favoring `quinn_proto` over `quinn`?

Yes, as far as I remember, and as far as I can tell (little involvement thus far) the following were the outstanding blockers:

- Usage of unbounded channels https://github.com/quinn-rs/quinn/issues?q=is%3Aissue+is%3Aopen+unbounded
- Spawning of tasks https://github.com/quinn-rs/quinn/issues/914
- Tokio only support. Though at this point, I would be open for a Tokio only `libp2p-quic` with the outlook of eventually supporting async-std. https://github.com/quinn-rs/quinn/issues/502

@elenaf9 would going with `quinn-proto` first and eventually switching to `quinn` be an option and not require to many wasted engineering hours?

File: transports/quic/Cargo.toml (hunk 28 above)
Comment (mxinden) [reply transports/quic/Cargo.toml]: `libp2p-quic` `v0.6.1` has already been released. We would either have to go with a new crate name or release `v0.7.0`.

https://crates.io/crates/libp2p-quic

File: transports/quic/src/lib.rs (hunk 30 above)
Comment (mxinden) [reply transports/quic/src/lib.rs]: I would guess some code uses the `select!` macro?

https://github.com/rust-lang/futures-rs/issues/1917

I am not saying it should stay this way.

**Comment by elenaf9** [comment]
> Yes, as far as I remember, and as far as I can tell (little involvement thus far) the following were the outstanding blockers:
> 
>  - Usage of unbounded channels https://github.com/quinn-rs/quinn/issues?q=is%3Aissue+is%3Aopen+unbounded
>  - Spawning of tasks [Reduce task-switching overhead on I/O path quinn-rs/quinn#914](https://github.com/quinn-rs/quinn/issues/914)
> - Tokio only support. Though at this point, I would be open for a Tokio only `libp2p-quic` with the outlook of eventually supporting async-std. [async_std support quinn-rs/quinn#502](https://github.com/quinn-rs/quinn/issues/502)

The first two points would be solved with https://github.com/quinn-rs/quinn/pull/1219. But to be fair I don't know how long it will take till that lands and a new quinn version is published.

> @elenaf9 would going with `quinn-proto` first and eventually switching to `quinn` be an option and not require to many wasted engineering hours?

I am not sure. We could do that, yes. But after looking at the StreamMuxer changes from paritytech/substrate#2648 I think we have to adapt the current implementation of the quic muxer anyway (see https://github.com/libp2p/rust-libp2p/pull/2289#discussion_r885718446 ). From what I can tell the quinn API would already give us the necessary types without much work needed from our side.
That being said, I am not completely opposed to sticking with `quinn_proto` for the first version. I am just wondering if finishing the current implementation is more work than switching would be. I'll leave it up to @kpp to decide 🙂

**Comment by kpp** [comment]
I don't think it's possible to switch from quinn_proto to quinn untill https://github.com/quinn-rs/quinn/pull/1219.
Would you please tell me more about merging strategy? Should I merge https://github.com/libp2p/rust-libp2p/pull/2648 and https://github.com/libp2p/rust-libp2p/pull/2652 and fix Transport/StreamMuxer API or is there another way of merging this into master?

**Comment by thomaseizinger** [comment]
> I don't think it's possible to switch from quinn_proto to quinn untill https://github.com/quinn-rs/quinn/pull/1219.
> Would you please tell me more about merging strategy? Should I merge https://github.com/libp2p/rust-libp2p/pull/2648 and https://github.com/libp2p/rust-libp2p/pull/2652 and fix Transport/StreamMuxer API or is there another way of merging this into master? 

paritytech/substrate#2648 still needs to receive in-depth reviews and we need to find consensus on the topic of mplex's performance profile with the new API. For both reasons it is marked as a draft.

Long story short: I would not block anything on these changes but I can also see how the new interface might help with the implementation of a new `StreamMuxer`.

**Comment by elenaf9** [comment]
> I don't think it's possible to switch from quinn_proto to quinn untill https://github.com/quinn-rs/quinn/pull/1219.

> https://github.com/libp2p/rust-libp2p/pull/2648 still needs to receive in-depth reviews and we need to find consensus on the topic of mplex's performance profile with the new API. For both reasons it is marked as a draft.

Okay, then let's not block on https://github.com/quinn-rs/quinn/pull/1219 or paritytech/substrate#2648 and rather continue with the current implementation using quinn-proto and the current / old StreamMuxer trait? Once a new version of quinn is published that includes the changes we can revive the discussion, but that does not have to be in the scope of this PR. 

> Would you please tell me more about merging strategy? Should I merge https://github.com/libp2p/rust-libp2p/pull/2648 and https://github.com/libp2p/rust-libp2p/pull/2652 and fix Transport/StreamMuxer API or is there another way of merging this into master?

I'll try to finish paritytech/substrate#2652 as soon as possible, however there are still some ongoing discussion about the API that I have to explore. But until those are resolved, I don't think we should merge that PR here.
That being said, that PR only affects `Transport::Listener` / `Transport::listen_on`. I think the other review comments can be resolved independently, so I hope it is not blocking you @kpp ?

File: transports/quic/src/connection.rs (hunk 25 above)
Comment (kpp) [reply transports/quic/src/connection.rs]: Yes, it is.

File: transports/quic/src/connection.rs (hunk 26 above)
Comment (kpp) [reply transports/quic/src/connection.rs]: How can I do that?

Comment (mxinden) [reply transports/quic/src/connection.rs]: I am guessing a panic is appropriate here, though I will defer to @elenaf9.

Comment (winksaville) [reply transports/quic/src/connection.rs]: > I am guessing a panic is appropriate here, though I will defer to @elenaf9.

On the face of it, It seems to me that this should `return Poll::Ready(ConnectionEvent::ConnectionLost(err))` as it does below.

Comment (kpp) [reply transports/quic/src/connection.rs]: That's quite interesting. I believe in an ideal world no one will call `poll_event` once the connection is closed. But I will check it.

Comment (winksaville) [reply transports/quic/src/connection.rs]: > That's quite interesting. I believe in an ideal world no one will call `poll_event` once the connection is closed. But I will check it.

You're right in an ideal world no one would, but this is an async world and I believe its best to assume "anything" can happen at "anytime" which means potentially in any order. So it seems perfectly possible that the connection was closed but some entity was still trying to do some other operation, such as read/write. Returning the "ConnectionLost" error seems reasonable and should be expected by any entity using the connection.

File: transports/quic/src/endpoint.rs (hunk 37 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs]: No, because `quinn_udp` still depends on `tokio`.

**Comment by thomaseizinger** [comment]
> > I don't think it's possible to switch from quinn_proto to quinn untill https://github.com/quinn-rs/quinn/pull/1219.
> > Would you please tell me more about merging strategy? Should I merge https://github.com/libp2p/rust-libp2p/pull/2648 and https://github.com/libp2p/rust-libp2p/pull/2652 and fix Transport/StreamMuxer API or is there another way of merging this into master? 
> 
> paritytech/substrate#2648 still needs to receive in-depth reviews and we need to find consensus on the topic of mplex's performance profile with the new API. For both reasons it is marked as a draft.
> 
> Long story short: I would not block anything on these changes but I can also see how the new interface might help with the implementation of a new `StreamMuxer`.

As a heads-up, I've taken paritytech/substrate#2648 apart into many individual PRs (see the description), many of which have already merged with more coming along. By far the biggest API change might land soon with paritytech/substrate#2707. Once that is merged, I'll work on removing `poll_outbound` at which point we will more or less be at the state of what paritytech/substrate#2648 is now.

File: transports/quic/src/transport.rs (hunk 36 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: I did a quick draft of how the implementation can be adapted to the transport changes: b239de6. It does not change much, but at least improves the listening logic a bit.
I thought about the listening logic a bit more and contrary to what I wrote above, I do think we already have to support multiple listeners / endpoints in the first version. 
Once #2652 is merged I am planning to work on a PR to this implementation to adapt it both, the listener changes and the StreamMuxer refactor (in particular #2707). Just to avoid duplicating work: are you currently working on this @kpp?

Comment (kpp) [reply transports/quic/src/transport.rs]: I am working on https://github.com/libp2p/rust-libp2p/pull/2707 only.

File: transports/quic/src/in_addr.rs [hunk 38]
```diff
@@ -0,0 +1,121 @@
...
+    /// The socket accepts connections on a single interface.
+    One { ip: Option<IpAddr> },
+    /// The socket accepts connections on all interfaces.
+    Any { if_watch: Box<IfWatch> },
+}
+
+enum IfWatch {
+    Pending(BoxFuture<'static, std::io::Result<IfWatcher>>),
+    Ready(Box<IfWatcher>),
+}
```
Comment (elenaf9) [inline transports/quic/src/in_addr.rs]: Referencing a discussion when `IfWatcher` was first added to tcp: https://github.com/libp2p/rust-libp2p/pull/1887#issuecomment-745233624.
`IfWatcher` used to (?) use `async_io` as reactor, which was not acceptable for some tokio users.  I believe this was changed with https://github.com/mxinden/if-watch/commit/2b8dfcb9f645ebb8502d7db598a245f927213c0a so it should not be a problem anymore. But just to be sure, could you please confirm this assumption @mxinden @dvc94ch?

Comment (elenaf9) [reply transports/quic/src/in_addr.rs]: Also: our `InAddr` logic for polling the `IfWatcher` is more or less a copy of the logic from the tcp transport (correct me if I am wrong @kpp). Admittedly it is not that much logic, but still duplicates some code. Even more if it turns out that we do need to have different implementations for `async_std` and `tokio` runtime. 
I think it would make sense to extract this to somewhere where both, the tcp transport and quic transport can use it. Either `libp2p-core`, or the `if-watch` crate directly (not familiar with the latter, so don't know if that makes sense). Wdyt @mxinden?

Comment (mxinden) [reply transports/quic/src/in_addr.rs]: > `IfWatcher` used to (?) use `async_io` as reactor, which was not acceptable for some tokio users. I believe this was changed with [mxinden/if-watch@2b8dfcb](https://github.com/mxinden/if-watch/commit/2b8dfcb9f645ebb8502d7db598a245f927213c0a) so it should not be a problem anymore.

As far as I understand this is correct. Though there is a discussion to make `if-watch` generic over the executor in-use: https://github.com/mxinden/if-watch/issues/21

Comment (mxinden) [reply transports/quic/src/in_addr.rs]: > I think it would make sense to extract this to somewhere where both, the tcp transport and quic transport can use it. Either `libp2p-core`, or the `if-watch` crate directly (not familiar with the latter, so don't know if that makes sense).

Moving this to `libp2p-core` makes sense to me. Off the top of my head, I think this is too libp2p specific in order to land in `if-watch`.

Comment (thomaseizinger) [reply transports/quic/src/in_addr.rs]: > > I think it would make sense to extract this to somewhere where both, the tcp transport and quic transport can use it. Either `libp2p-core`, or the `if-watch` crate directly (not familiar with the latter, so don't know if that makes sense).
> 
> Moving this to `libp2p-core` makes sense to me. Off the top of my head, I think this is too libp2p specific in order to land in `if-watch`.

I think we should aim for `libp2p-core` to _not_ be a catch-all for common things. If something is only used by two transports, my first suggestion would be to create a separate crate that those two transports can depend on.

**Comment by elenaf9** [comment]
For the record: @kpp and I discussed that from now on we will collaborate on this branch directly, instead of having sub-PRs for each follow-up change.

File: transports/quic/src/in_addr.rs (hunk 38 above)
Comment (elenaf9) [reply transports/quic/src/in_addr.rs]: Obsolete since with `ifwatcher-v2.0.0` the `IfWatcher` interface has simplified enough so that there is not much boilerplate code needed anymore.

File: transports/quic/src/tls/certificate.rs [hunk 39]
```diff
@@ -0,0 +1,462 @@
...
+            .verify(&msg, &self.extension.signature);
+        if !user_owns_sk {
+            return Err(Error::UnknownIssuer);
+        }
+        Ok(())
+    }
+
+    /// Return the signature scheme corresponding to [`AlgorithmIdentifier`]s
+    /// of `subject_pki` and `signature_algorithm`
+    /// according to `<https://tools.ietf.org/id/draft-ietf-tls-tls13-21.html#rfc.section.4.2.3>`.
```
Comment (thomaseizinger) [inline transports/quic/src/tls/certificate.rs]:
```suggestion
    /// according to `<https://www.rfc-editor.org/rfc/rfc8446.html#section-4.2.3>`.
```

This link is dead.

File: transports/quic/src/tls/verifier.rs [hunk 40]
```diff
@@ -0,0 +1,202 @@
...
+            // TODO SignatureScheme::ED448 is not supported by `ring` yet
+            SignatureScheme::ED25519,
+            // In particular, RSA SHOULD NOT be used unless
+            // no elliptic curve algorithms are supported.
+            SignatureScheme::RSA_PSS_SHA512,
+            SignatureScheme::RSA_PSS_SHA384,
+            SignatureScheme::RSA_PSS_SHA256,
+            SignatureScheme::RSA_PKCS1_SHA512,
+            SignatureScheme::RSA_PKCS1_SHA384,
+            SignatureScheme::RSA_PKCS1_SHA256,
```
Comment (thomaseizinger) [inline transports/quic/src/tls/verifier.rs]: Not sure if I am opening pandora's box here but why are we supporting stuff like RSA here? I understand that libp2p originally set out to support RSA keys but wouldn't it make sense to specify new authentication scheme like TLS without support for those and thus effectively phasing out support for it?

cc @marten-seemann as the author of the libp2p TLS spec.

**Review by thomaseizinger — COMMENTED** [review]
Had a closer look at the TLS module. Looks good to me.

Also pushed a couple of commits, feel free to drop them again if you disagree :)

**Comment by thomaseizinger** [comment]
Would it be worth splitting out a `libp2p-tls` crate that deals with the TLS handshake stuff similar to how we have `libp2p-noise`? What triggered this thought was this code is shared between this PR and https://github.com/libp2p/rust-libp2p/pull/2801.

Plus, the spec is actually defined completely unrelated to `libp2p-quic`.

The benefit that I am seeing is that we could actually merge `libp2p-tls` independently and thus reduce, how much we need to review here :)

**Comment by mxinden** [comment]
> Would it be worth splitting out a `libp2p-tls` crate that deals with the TLS handshake stuff similar to how we have `libp2p-noise`? What triggered this thought was this code is shared between this PR and paritytech/substrate#2801.
> 
> Plus, the spec is actually defined completely unrelated to `libp2p-quic`.
> 
> The benefit that I am seeing is that we could actually merge `libp2p-tls` independently and thus reduce, how much we need to review here :)

No opinion on the short term. In the long term we could add support for TLS on top of TCP.

**Comment by thomaseizinger** [comment]
I'd be in favor. Also happy to do the coding unless someone else is keen :)

**Comment by marten-seemann** [comment]
> Would it be worth splitting out a libp2p-tls crate that deals with the TLS handshake stuff similar to how we have libp2p-noise? 

That’s what we do in go-libp2p, the TLS code lives in a separate package, and the QUIC package just gets the certificate from there.

**Comment by elenaf9** [comment]
Yep, I initially also planned it but did not follow up on it. Would be great if you can help with this @thomaseizinger! 
For TLS + TCP we would additionally need the `Upgrade` trait implemented, but short-term I think its sufficient to just split out what we already have.

**Comment by thomaseizinger** [comment]
> Yep, I initially also planned it but did not follow up on it. Would be great if you can help with this @thomaseizinger! For TLS + TCP we would additionally need the `Upgrade` trait implemented, but short-term I think its sufficient to just split out what we already have.

I had a go at this: https://github.com/libp2p/rust-libp2p/pull/2945

**Comment by xpepermint** [comment]
Hey, let me drop some related info that might help. Sp after months working on my own implementation of QUIC/TLS13 for Rust I came across this https://github.com/aws/s2n-quic repository. The design looks pretty much identical to my own concept thus I believe they took the correct path and it's worth checking. The overall interface approache is pretty much how things should be designed in Rust.

File: transports/quic/src/endpoint.rs (hunk 7 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Added abstract runtime support in c5fc181.

File: transports/quic/src/endpoint.rs (hunk 35 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Solved with c5fc181.

File: transports/quic/Cargo.toml [hunk 41]
```diff
@@ -0,0 +1,42 @@
+[package]
+name = "libp2p-quic"
+version = "0.7.0"
+authors = ["David Craven <david@craven.ch>", "Parity Technologies <admin@parity.io>"]
```
Comment (elenaf9) [inline transports/quic/Cargo.toml]: @kpp did I see it correctly that we don't share any code with #2159 anymore, because the code was completely replaced with the code from #1334 in 4a317df41adccb0a1dd65ad3df049683fa2ca4ea?

File: transports/quic/src/endpoint.rs [hunk 42]
```diff
@@ -0,0 +1,599 @@
...
+    /// The endpoint configuration to pass to `quinn_proto`.
+    endpoint_config: Arc<quinn_proto::EndpointConfig>,
+}
+
+impl Config {
+    /// Creates a new configuration object with default values.
+    pub fn new(keypair: &libp2p_core::identity::Keypair) -> Result<Self, tls::ConfigError> {
+        let mut transport = quinn_proto::TransportConfig::default();
+        transport.max_concurrent_uni_streams(0u32.into()); // Can only panic if value is out of range.
+        transport.datagram_receive_buffer_size(None);
```
Comment (elenaf9) [inline transports/quic/src/endpoint.rs:123]: @kpp why is this set to `None`?

File: transports/quic/src/endpoint.rs [hunk 43]
```diff
@@ -0,0 +1,599 @@
...
+// wait
+/// # Shutdown
+///
+/// The background task shuts down if `endpoint_weak`, `receiver` or `new_connections` become
+/// disconnected/invalid. This corresponds to the lifetime of the associated [`quinn_proto::Endpoint`].
+///
+/// Keep in mind that we pass an `EndpointChannel` whenever we create a new connection, which
+/// guarantees that the [`EndpointDriver`], is properly kept alive for as long as any QUIC
+/// connection is open.
+///
```
Comment (elenaf9) [inline transports/quic/src/endpoint.rs]: Note: this description is outdated right now.

**Comment by elenaf9** [comment]
This is ready for a full review now (cc @mxinden, @thomaseizinger, @MarcoPolo).

Parts that especially need careful review:
- How back-pressure is propagated, e.g. if a single connection is busy. 
- The `EndpointDriver` (formerly called background_task) should be cleaned up once it is not used anymore (e.g. because the listener shut down and not connections remain)
- Finishing substreams + closing of connections

Since the TLS code will live in a separate `libp2p-tls` package (see paritytech/substrate#2945) the tls code won't need to be reviewed. We will use `libp2p-tls` once it is merged.

Note: Some parts of the docs are outdated right now, in particular the `EndpointDriver` description. I will work on fixing the docs next.

There are still TODOs in the code, namely:
- Reading / writing of ECN information from  / to datagrams
- `max_datagram`: specifies how many datagrams can be returned inside a single `quinn_proto` Transmit using GSO. Right now set to 1 since not all platforms support this.
-  Connection migration is disabled. Once it is enabled address change on a connection needs to be handled.
- Hole-punching is not supported.
- When listening on a wildcard address, the local_address on inbound connections will have an unspecified IP.
 
However those are not strictly required for a first version and thus will be tackled in follow-ups PRs. See also comments in paritytech/substrate#2883.

@kpp I did quite a bit of refactoring, both in kpp#23 and also recent commits. Would be great if you could also do a review!

File: transports/quic/Cargo.toml (hunk 41 above)
Comment (kpp) [reply transports/quic/Cargo.toml]: Yes, that's right.

File: transports/quic/src/endpoint.rs (hunk 42 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs:123]: According to docs:

```
    /// Maximum number of incoming application datagram bytes to buffer, or None to disable
    /// incoming datagrams
```

We don't deal with QUIC datagrams, we work with bistreams only.

File: transports/quic/Cargo.toml [hunk 44]
```diff
@@ -0,0 +1,42 @@
+[package]
+name = "libp2p-quic"
+version = "0.7.0"
```
Comment (mxinden) [inline transports/quic/Cargo.toml]:
```suggestion
version = "0.7.0-alpha"
```

I suggest we merge a first version as `alpha`. I think this better sets expectations while allowing folks to experiment with the new transport earlier.

What do you think?

File: transports/quic/src/endpoint.rs [hunk 45]
```diff
@@ -0,0 +1,598 @@
...
+    endpoint_config: Arc<quinn_proto::EndpointConfig>,
+}
+
+impl Config {
+    /// Creates a new configuration object with default values.
+    pub fn new(keypair: &libp2p_core::identity::Keypair) -> Result<Self, tls::ConfigError> {
+        let mut transport = quinn_proto::TransportConfig::default();
+        transport.max_concurrent_uni_streams(0u32.into()); // Can only panic if value is out of range.
+        transport.datagram_receive_buffer_size(None);
+        transport.keep_alive_interval(Some(Duration::from_millis(10)));
```
Comment (kpp) [inline transports/quic/src/endpoint.rs]: It would be nice to set max_idle_timeout (default is 10_000ms).

File: transports/quic/Cargo.toml [hunk 46]
```diff
@@ -0,0 +1,42 @@
...
+repository = "https://github.com/libp2p/rust-libp2p"
+license = "MIT"
+
+[dependencies]
+async-std-crate = { package = "async-std", version = "1.12.0", default-features = false, optional = true }
+async-trait = "0.1.50"
+futures = "0.3.15"
+futures-timer = "3.0.2"
+if-watch = "2.0.0"
+libp2p-core = { version = "0.36.0", path = "../../core" }
```
Comment (mxinden) [inline transports/quic/Cargo.toml]:
```suggestion
libp2p-core = { version = "0.36.0", path = "../../core", default-features = false }
```

At least until https://github.com/libp2p/rust-libp2p/pull/2918 is merged.

File: transports/quic/src/endpoint.rs [hunk 47]
```diff
@@ -0,0 +1,598 @@
...
+        }
+        ControlFlow::Continue(())
+    }
+
+    /// Handle datagram received on the socket.
+    /// The datagram content was written into the `socket_recv_buffer`.
+    fn handle_datagram(&mut self, bytes: Vec<u8>, packet_src: SocketAddr) -> ControlFlow<()> {
+        let packet = From::from(bytes.as_bytes());
+        let local_ip = self.channel.socket_addr.ip();
+        // TODO: ECN bits aren't handled
```
Comment (kpp) [inline transports/quic/src/endpoint.rs:481]: They are handled in the `quinn-udp` crate.

File: transports/quic/src/endpoint.rs [hunk 48]
```diff
@@ -0,0 +1,598 @@
...
+    server_config: Arc<quinn_proto::ServerConfig>,
+    /// The endpoint configuration to pass to `quinn_proto`.
+    endpoint_config: Arc<quinn_proto::EndpointConfig>,
+}
+
+impl Config {
+    /// Creates a new configuration object with default values.
+    pub fn new(keypair: &libp2p_core::identity::Keypair) -> Result<Self, tls::ConfigError> {
+        let mut transport = quinn_proto::TransportConfig::default();
+        transport.max_concurrent_uni_streams(0u32.into()); // Can only panic if value is out of range.
```
Comment (marten-seemann) [inline transports/quic/src/endpoint.rs]: What's the bidirectional stream limit?

File: transports/quic/src/endpoint.rs (hunk 45 above)
Comment (marten-seemann) [reply transports/quic/src/endpoint.rs]: That seems very short. For reference, in go-libp2p we use an idle timeout of 30s, and a keep alive interval of 15s. Obviously, rust-libp2p doesn't need to match these values.

File: transports/quic/src/endpoint.rs [hunk 49]
```diff
@@ -0,0 +1,598 @@
...
+
+    /// Handle a message sent from either the [`QuicTransport`](super::QuicTransport) or a [`Connection`].
+    fn handle_message(&mut self, to_endpoint: ToEndpoint) -> ControlFlow<()> {
+        match to_endpoint {
+            ToEndpoint::Dial { addr, result } => {
+                // This `"l"` seems necessary because an empty string is an invalid domain
+                // name. While we don't use domain names, the underlying rustls library
+                // is based upon the assumption that we do.
+                let (connection_id, connection) =
+                    match self.endpoint.connect(self.client_config.clone(), addr, "l") {
```
Comment (kpp) [inline transports/quic/src/endpoint.rs:411]: `client_config` should be with an empty peer ID if we are dialing an address without peer ID. But if we are dialing with `addr/p2p/ID`, a new client config with an appropriate peer ID should be created. See https://github.com/libp2p/rust-libp2p/pull/2947.

File: transports/quic/Cargo.toml [hunk 50]
```diff
@@ -0,0 +1,42 @@
...
+x509-parser = "0.13.0"
+yasna = "0.5.0"
+
+[features]
+default = ["async-std"]
+tokio = ["tokio-crate"]
+async-std = ["async-std-crate"]
+
+[dev-dependencies]
+anyhow = "1.0.41"
```
Comment (mxinden) [inline transports/quic/Cargo.toml]: We don't use `anyhow` anywhere else. Is the usage in tests worth the additional dependency?

File: transports/quic/src/endpoint.rs (hunk 48 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs]: 100

File: transports/quic/src/endpoint.rs (hunk 45 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs]: We have a test in which we try to dial a non-existing peer. Because right now the limit is 10s this test waits for 10s. It would be nice to have a possibility to set this limit at least for tests.

File: transports/quic/src/lib.rs [hunk 51]
```diff
@@ -0,0 +1,82 @@
...
+//!
+//! let addr = "/ip4/127.0.0.1/udp/12345/quic".parse().expect("bad address?");
+//! quic_transport.listen_on(addr).expect("listen error.");
+//! #
+//! # Ok(())
+//! # }
+//! ```
+//!
+//! The `Endpoint` struct implements the `Transport` trait of the `core` library. See the
+//! documentation of `core` and of libp2p in general to learn how to use the `Transport` trait.
```
Comment (mxinden) [inline transports/quic/src/lib.rs]:
```suggestion
//! The [`Endpoint`] struct implements the [`Transport`] trait of the [`libp2p_core`] library. See the
//! documentation of [`libp2p_core`] and of libp2p in general to learn how to use the [`Transport`] trait.
```

File: transports/quic/src/lib.rs [hunk 52]
```diff
@@ -0,0 +1,82 @@
...
+//!
+//! Note that QUIC provides transport, security, and multiplexing in a single protocol.  Therefore,
+//! QUIC connections do not need to be upgraded. You will get a compile-time error if you try.
+//! Instead, you must pass all needed configuration into the constructor.
+//!
+//! # Design Notes
+//!
+//! The entry point is the `Endpoint` struct.  It represents a single QUIC endpoint.  You
+//! should generally have one of these per process.
```
Comment (mxinden) [inline transports/quic/src/lib.rs]: I find this confusing. Is this necessary?

File: transports/quic/src/lib.rs [hunk 53]
```diff
@@ -0,0 +1,82 @@
...
+//!
+//! `Endpoint` manages a background task that processes all incoming packets.  Each
+//! `QuicConnection` also manages a background task, which handles socket output and timer polling.
+
+#![deny(unsafe_code)]
```
Comment (mxinden) [inline transports/quic/src/lib.rs]: I don't think we do this in any other crate. That is not to say that we shouldn't. Just to say that we should be consistent across all crates.

@elenaf9 @thomaseizinger do you have opinions on whether we should introduce a set of `deny` across the workspace?

File: transports/quic/src/transport.rs [hunk 54]
```diff
@@ -0,0 +1,639 @@
...
+    /// The [`EndpointDriver`](super::endpoint::EndpointDriver) has crashed.
+    #[error("Endpoint driver crashed")]
+    EndpointDriverCrashed,
+}
+
+impl<P: Provider> Transport for QuicTransport<P> {
+    type Output = (PeerId, QuicMuxer);
+    type Error = TransportError;
+    type ListenerUpgrade = Upgrade;
+    type Dial = Pin<Box<dyn Future<Output = Result<Self::Output, Self::Error>> + Send>>;
```
Comment (mxinden) [inline transports/quic/src/transport.rs]: Could as well use [`BoxFuture`](https://docs.rs/futures/latest/futures/future/type.BoxFuture.html). No strong opinion.

File: transports/quic/src/transport.rs [hunk 55]
```diff
@@ -0,0 +1,639 @@
...
+        addr: Multiaddr,
+    ) -> Result<ListenerId, CoreTransportError<Self::Error>> {
+        let socket_addr = multiaddr_to_socketaddr(&addr)
+            .ok_or(CoreTransportError::MultiaddrNotSupported(addr))?;
+        let listener_id = ListenerId::new();
+        let listener = Listener::new::<P>(listener_id, socket_addr, self.config.clone())
+            .map_err(CoreTransportError::Other)?;
+        self.listeners.push(listener);
+        // Drop reference to dialer endpoint so that the endpoint is dropped once the last
+        // connection that uses it is closed.
```
Comment (mxinden) [inline transports/quic/src/transport.rs]: I don't understand this comment. Where is the "dialer endpoint" being dropped?

File: transports/quic/src/transport.rs [hunk 56]
```diff
@@ -0,0 +1,639 @@
...
+        if let Some(listener) = self.listeners.iter_mut().find(|l| l.listener_id == id) {
+            listener.close(Ok(()));
+            true
+        } else {
+            false
+        }
+    }
+
+    fn address_translation(&self, _server: &Multiaddr, observed: &Multiaddr) -> Option<Multiaddr> {
+        Some(observed.clone())
```
Comment (mxinden) [inline transports/quic/src/transport.rs:119]: If I understand the design of `Transport::address_translation` correctly, this should only return `Some` if it is an address of this specific `Transport` implementation, i.e. here only return `Some` if `observed` contains `/quic`.

Otherwise, in combination with the `OrTransport` with `QuicTransport` being first, the second `Transport` implementation would never be asked.

https://github.com/libp2p/rust-libp2p/blob/04b07c4d14a0a6ec350fc21261a33d859fc71289/core/src/transport/choice.rs#L108-L114

File: transports/quic/src/endpoint.rs (hunk 48 above)
Comment (marten-seemann) [reply transports/quic/src/endpoint.rs]: I assume that this is only counting peer-initiated streams, right?
100 seems a bit low, we had people complain when we lowered the limit. go-libp2p is setting it to 256 now.

File: transports/quic/src/transport.rs [hunk 57]
```diff
@@ -0,0 +1,639 @@
...
+    }
+
+    fn dial(&mut self, addr: Multiaddr) -> Result<Self::Dial, CoreTransportError<Self::Error>> {
+        let socket_addr = multiaddr_to_socketaddr(&addr)
+            .ok_or_else(|| CoreTransportError::MultiaddrNotSupported(addr.clone()))?;
+        if socket_addr.port() == 0 || socket_addr.ip().is_unspecified() {
+            return Err(CoreTransportError::MultiaddrNotSupported(addr));
```
Comment (mxinden) [inline transports/quic/src/transport.rs]: Side note, I wish one could add context to a `MultiaddrNotSupported`. I think that would make debugging a lot easier.

``` rust
MultiaddrNotSupported {
  address: Multiaddr,
  reason: XXX,
}
```

File: transports/quic/src/endpoint.rs (hunk 45 above)
Comment (marten-seemann) [reply transports/quic/src/endpoint.rs]: Is there any way to set a shorter timeout for the handshake? 5s should be _plenty_ of time to complete the handshake (a QUIC handshake only takes a single RTT, or 2 RTTs if the peer does a Retry).

File: transports/quic/src/endpoint.rs [hunk 58]
```diff
@@ -0,0 +1,598 @@
...
+    /// The server configuration to pass to `quinn_proto`.
+    server_config: Arc<quinn_proto::ServerConfig>,
+    /// The endpoint configuration to pass to `quinn_proto`.
+    endpoint_config: Arc<quinn_proto::EndpointConfig>,
+}
+
+impl Config {
+    /// Creates a new configuration object with default values.
+    pub fn new(keypair: &libp2p_core::identity::Keypair) -> Result<Self, tls::ConfigError> {
+        let mut transport = quinn_proto::TransportConfig::default();
```
Comment (marten-seemann) [inline transports/quic/src/endpoint.rs:118]: Is there any config knob for stream / connection flow control (initial) window sizes? What are the defaults that quinn uses? Does quinn do auto-scaling of receive windows, where maximum values might need to be configured?

File: transports/quic/src/transport.rs [hunk 59]
```diff
@@ -0,0 +1,639 @@
...
+    // Wrapped socket for non-blocking I/O operations.
+    type Socket: Send + Sync + Unpin;
+
+    // Wrap a socket.
+    // Note: The socket must be set to non-blocking.
+    fn from_socket(socket: UdpSocket) -> io::Result<Self::Socket>;
+
+    // Receive a single datagram message.
+    // Return the number of bytes read and the address the message came from.
+    async fn recv_from(socket: &Self::Socket, buf: &mut [u8]) -> io::Result<(usize, SocketAddr)>;
```
Comment (mxinden) [inline transports/quic/src/transport.rs]: If I am not mistaken, we call `Provider::recv_from` from a poll-style function. To make sure my understanding is correct, we use an `async fn` here because `async-std`'s `UdpSocket` does not expose a poll-style `recv_from`, correct?



https://docs.rs/async-std/0.99.5/async_std/net/struct.UdpSocket.html#method.recv_from

https://docs.rs/tokio/latest/tokio/net/struct.UdpSocket.html#method.poll_recv_from

File: transports/quic/src/transport.rs [hunk 60]
```diff
@@ -0,0 +1,639 @@
...
+    Multiaddr::empty()
+        .with(socket_addr.ip().into())
+        .with(Protocol::Udp(socket_addr.port()))
+        .with(Protocol::Quic)
+}
+
+#[cfg(test)]
+#[cfg(any(feature = "async-std", feature = "tokio"))]
+mod test {
+
```
Comment (mxinden) [inline transports/quic/src/transport.rs]:
```suggestion
```

File: transports/quic/src/upgrade.rs [hunk 61]
```diff
@@ -0,0 +1,88 @@
...
+                }
+                // Other items are:
+                // - HandshakeDataReady
+                // - StreamAvailable
+                // - StreamOpened
+                // - StreamReadable
+                // - StreamWritable
+                // - StreamFinished
+                // - StreamStopped
+                _ => {}
```
Comment (mxinden) [inline transports/quic/src/upgrade.rs]: Would it make sense to exhaustively match here? In case `quinn` adds a new event, we would notice at compile time.

File: transports/quic/tests/smoke.rs [hunk 62]
```diff
@@ -0,0 +1,630 @@
...
+#[cfg(feature = "tokio")]
+use libp2p_quic::Tokio;
+#[cfg(feature = "tokio")]
+use tokio_crate as tokio;
+
+fn generate_tls_keypair() -> libp2p::identity::Keypair {
+    libp2p::identity::Keypair::generate_ed25519()
+}
+
+#[tracing::instrument]
```
Comment (mxinden) [inline transports/quic/tests/smoke.rs]: I am not familiar with the `tracing` crate. I am assuming this will be useful in the future, i.e. should be something we use across the workspace?

If not, I would prefer not using it here and thus reducing the amount of dependencies.

File: transports/quic/src/connection.rs [hunk 63]
```diff
@@ -0,0 +1,384 @@
...
+    /// Events that the endpoint will send in destination to our local [`quinn_proto::Connection`].
+    /// Passed at initialization.
+    from_endpoint: mpsc::Receiver<quinn_proto::ConnectionEvent>,
+
+    /// The QUIC state machine for this specific connection.
+    connection: quinn_proto::Connection,
+    /// Identifier for this connection according to the endpoint. Used when sending messages to
+    /// the endpoint.
+    connection_id: quinn_proto::ConnectionHandle,
+    /// `Future` that triggers at the `Instant` that `self.connection.poll_timeout()` indicates.
```
Comment (mxinden) [inline transports/quic/src/connection.rs]:
```suggestion
    /// `Future` that triggers at the [`Instant`] that `self.connection.poll_timeout()` indicates.
```

In case we ever use something else.

File: transports/quic/src/endpoint.rs [hunk 64]
```diff
@@ -0,0 +1,598 @@
...
+        client_config.transport = transport;
+        Ok(Self {
+            client_config,
+            server_config: Arc::new(server_config),
+            endpoint_config: Default::default(),
+        })
+    }
+}
+
+/// Object containing all the QUIC resources shared between all connections.
```
Comment (mxinden) [inline transports/quic/src/endpoint.rs]: Is this comment still accurate? Only owns the `Sender` and `SocketAddr`.

File: transports/quic/src/endpoint.rs [hunk 65]
```diff
@@ -0,0 +1,598 @@
...
+
+    fn new<P: Provider>(
+        config: Config,
+        socket_addr: SocketAddr,
+        new_connections: Option<mpsc::Sender<Connection>>,
+    ) -> Result<EndpointChannel, transport::TransportError> {
+        // NOT blocking, as per man:bind(2), as we pass an IP address.
+        let socket = std::net::UdpSocket::bind(&socket_addr)?;
+        socket.set_nonblocking(true)?;
+        let (to_endpoint_tx, to_endpoint_rx) = mpsc::channel(32);
```
Comment (mxinden) [inline transports/quic/src/endpoint.rs]: For future us, can you add a comment along the lines of either:

- ~"This value was chosen because of X."
- ~"This value was chosen based on intuition."

**Review by mxinden — COMMENTED** [review]
Couple of comments. Nothing big. Still need some more time to go through everything.

File: transports/quic/src/endpoint.rs (hunk 58 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs:118]: These are default values https://github.com/quinn-rs/quinn/blob/main/quinn-proto/src/config.rs#L257.

I don't know anything about auto-scaling, it would be nice to dig into it.

File: transports/quic/tests/smoke.rs (hunk 62 above)
Comment (kpp) [reply transports/quic/tests/smoke.rs]: Sorry, it's an artifact from old times when I perf'ed this crate. Seems like I forgot to remove this line.

File: transports/quic/src/endpoint.rs (hunk 58 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs:118]: Yeah there is a CUBIC(default) and New Reno congestion controllers.

Comment (marten-seemann) [reply transports/quic/src/endpoint.rs:118]: Thank you for the link, @kpp!

Looking at these values, we should probably modify:
* `allow_spin` to `false`: The spin bit exposes the end-to-end RTT to passive on-path observers. When run over a VPN or other tunneling solutions, this exposes _more_ information than a TCP connection.
* the stream receive window is set to 1.25 MB. This seems a lot as a starting value, but very little if this is the maximum value the window can ever grow to. Depends on the auto-scaling logic, if there is any.
* the connection receive window apparently is set to infinity. This is not a very good idea, since it means that the memory you're committing to the QUIC connection is the product of your stream receive window and the number of streams. With default values, that's 125 MB, making it very easy to perform a DoS against the QUIC stack.

File: transports/quic/src/endpoint.rs (hunk 47 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:481]: Yes. But integrating `quinn-udp` is quite complex and we'd more or less have to copy the code for that from `quinn`. Given that this feature isn't strictly needed in the first version I would stick with the `std` sockets for now. See https://github.com/libp2p/rust-libp2p/issues/2883#issuecomment-1259397727. We can change this later in follow-up PRs. Also, if we decide long-term to use `quinn` directly,  that would already be solved

File: transports/quic/src/endpoint.rs (hunk 49 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:411]: Will add this once #2945 is merged and we can use tls from there.

File: transports/quic/Cargo.toml (hunk 46 above)
Comment (elenaf9) [reply transports/quic/Cargo.toml]: #2918 is merged now 🙂

File: transports/quic/tests/smoke.rs (hunk 62 above)
Comment (elenaf9) [reply transports/quic/tests/smoke.rs]: Removed `tracing` from tests (916d323), and replaced it with `log` in the rest of the package (2b80d05).

File: transports/quic/src/upgrade.rs (hunk 61 above)
Comment (elenaf9) [reply transports/quic/src/upgrade.rs]: Done.

File: transports/quic/src/transport.rs (hunk 54 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: 👍 done.

File: transports/quic/Cargo.toml (hunk 50 above)
Comment (elenaf9) [reply transports/quic/Cargo.toml]: Remove with b3b8b33.

File: transports/quic/src/transport.rs (hunk 59 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Yes. I worked around the async fns in `endpoint` with the `RecvStream` and by manually polling the send future. But we could just move that logic into the `async-std` mod. Played around with it a bit. What do you think about https://github.com/elenaf9/rust-libp2p/commit/1da0bdb9636b395437b6d1e3c2d9c6c23266f0b9?

File: transports/quic/src/transport.rs (hunk 56 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs:119]: Good catch, thanks! Will fix it. Also, I believe we have the same issue for tcp. Opened #2970, lmk if I am missing something and this issue doesn't apply for the tcp transport.

File: transports/quic/src/transport.rs (hunk 59 above)
Comment (mxinden) [reply transports/quic/src/transport.rs]: I am in favor of moving the complexity down to the `async-std` module. Thanks @elenaf9.

Comment (elenaf9) [reply transports/quic/src/transport.rs]: Done in dcf6198.

File: transports/quic/src/transport.rs (hunk 57 above)
Comment (thomaseizinger) [reply transports/quic/src/transport.rs]: It might be time to go through all the transports and just see if we can add more variants that cover more specific cases.

File: Cargo.toml [hunk 66]
```diff
@@ -30,6 +30,7 @@ full = [
     "ping",
     "plaintext",
     "pnet",
+    "quic-async-std",
```
Comment (thomaseizinger) [inline Cargo.toml]: Missing the `quic-tokio` feature from `full`.

We should merge https://github.com/libp2p/rust-libp2p/pull/2963 so that my silly bash mistake is fixed and this is flagged correctly!

File: Cargo.toml [hunk 67]
```diff
@@ -118,6 +121,7 @@ smallvec = "1.6.1"
 libp2p-deflate = { version = "0.37.0", path = "transports/deflate", optional = true }
 libp2p-dns = { version = "0.37.0", path = "transports/dns", optional = true }
 libp2p-mdns = { version = "0.41.0", path = "protocols/mdns", optional = true }
+libp2p-quic = { version = "0.7.0-alpha", path = "transports/quic", default-features = false, optional = true }
```
Comment (thomaseizinger) [inline Cargo.toml]: That is a no-op now.

```suggestion
libp2p-quic = { version = "0.7.0-alpha", path = "transports/quic", optional = true }
```

File: transports/quic/Cargo.toml [hunk 68]
```diff
@@ -0,0 +1,40 @@
...
+rustls = { version = "0.20.2", default-features = false, features = ["dangerous_configuration"] }
+thiserror = "1.0.26"
+tokio-crate = { package = "tokio", version = "1.21.1", default-features = false, features = ["net", "rt"], optional = true }
+webpki = "0.22.0"
+x509-parser = "0.13.0"
+yasna = "0.5.0"
+
+[features]
+tokio = ["tokio-crate"]
+async-std = ["async-std-crate"]
```
Comment (thomaseizinger) [inline transports/quic/Cargo.toml]: Use `dep:` syntax to hide the features created by optional crates.

```suggestion
tokio = ["dep:tokio-crate"]
async-std = ["dep:async-std-crate"]
```

File: transports/quic/Cargo.toml [hunk 69]
```diff
@@ -0,0 +1,40 @@
...
+
+[dev-dependencies]
+async-std-crate = { package = "async-std", version = "1.12.0", features = ["attributes"] }
+libp2p = { version = "0.49.0", default-features = false, features = ["request-response"], path = "../.." }
```
Comment (thomaseizinger) [inline transports/quic/Cargo.toml]: We typically don't reference the version for dev-dependencies, plus, we don't have default features any more.

```suggestion
libp2p = { path = "../..", features = ["request-response"] }
```

File: transports/quic/src/lib.rs (hunk 53 above)
Comment (thomaseizinger) [reply transports/quic/src/lib.rs]: I am in favor. It might be easier to accomplish this by adjusting our `custom-clippy` command:

```diff
Index: .cargo/config.toml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.cargo/config.toml b/.cargo/config.toml
--- a/.cargo/config.toml	(revision 68f3b84e956a332b426d0563d6a0595394bce478)
+++ b/.cargo/config.toml	(date 1664861450843)
@@ -1,3 +1,3 @@
 [alias]
 # Temporary solution to have clippy config in a single place until https://github.com/rust-lang/rust-clippy/blob/master/doc/roadmap-2021.md#lintstoml-configuration is shipped.
-custom-clippy = "clippy --workspace --all-features --all-targets -- -A clippy::type_complexity -A clippy::pedantic -D warnings"
+custom-clippy = "clippy --workspace --all-features --all-targets -- -W unsafe_code -A clippy::type_complexity -A clippy::pedantic -D warnings"

```

Comment (thomaseizinger) [reply transports/quic/src/lib.rs]: We will need `warn` instead of `deny`, otherwise we cannot `allow` it in `wasm-ext` where it is necessary.

File: transports/quic/src/lib.rs [hunk 70]
```diff
@@ -0,0 +1,82 @@
...
+pub use connection::ConnectionError;
+pub use endpoint::Config;
+pub use muxer::QuicMuxer;
+pub use quinn_proto::ConnectError as DialError;
+#[cfg(feature = "async-std")]
+pub use transport::{AsyncStd, AsyncStdTransport};
+pub use transport::{Provider, QuicTransport, TransportError};
+#[cfg(feature = "tokio")]
+pub use transport::{Tokio, TokioTransport};
+pub use upgrade::Upgrade;
```
Comment (thomaseizinger) [inline transports/quic/src/lib.rs]: I'd welcome if we follow the naming conventions discussed in https://github.com/libp2p/rust-libp2p/issues/2217 right away for new code!

File: transports/quic/src/lib.rs [hunk 71]
```diff
@@ -0,0 +1,82 @@
...
+mod connection;
+mod endpoint;
+mod muxer;
+mod tls;
+mod transport;
+mod upgrade;
+
+pub use connection::ConnectionError;
+pub use endpoint::Config;
+pub use muxer::QuicMuxer;
```
Comment (thomaseizinger) [inline transports/quic/src/lib.rs]: Things work on my machine even if we don't expose this.

File: transports/quic/src/lib.rs [hunk 72]
```diff
@@ -0,0 +1,82 @@
...
+pub use quinn_proto::ConnectError as DialError;
```
Comment (thomaseizinger) [inline transports/quic/src/lib.rs]: Would it make sense to only have 1 error?

File: transports/quic/src/upgrade.rs [hunk 73]
```diff
@@ -0,0 +1,86 @@
...
+            }
+        }
+    }
+}
+
+impl fmt::Debug for Upgrade {
+    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+        fmt::Debug::fmt(&self.connection, f)
+    }
+}
```
Comment (thomaseizinger) [inline transports/quic/src/upgrade.rs]: This looks like it can be derived.

File: transports/quic/src/upgrade.rs [hunk 74]
```diff
@@ -0,0 +1,86 @@
...
+use futures::{prelude::*, ready};
+use libp2p_core::PeerId;
+use std::{
+    fmt,
+    pin::Pin,
+    task::{Context, Poll},
+};
+
+/// A QUIC connection currently being negotiated.
+pub struct Upgrade {
```
Comment (thomaseizinger) [inline transports/quic/src/upgrade.rs]:
```suggestion
pub struct Connecting {
```

File: transports/quic/src/lib.rs (hunk 70 above)
Comment (thomaseizinger) [inline transports/quic/src/lib.rs]: Things work for me even if we don't expose this.

File: transports/quic/src/muxer.rs [hunk 75]
```diff
@@ -0,0 +1,360 @@
...
+pub struct QuicMuxer {
+    inner: Arc<Mutex<Inner>>,
+}
+
+/// Mutex-protected fields of [`QuicMuxer`].
+#[derive(Debug)]
+struct Inner {
+    /// Inner connection object that yields events.
+    connection: Connection,
+    // /// State of all the substreams that the muxer reports as open.
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]:
```suggestion
    /// State of all the substreams that the muxer reports as open.
```

File: transports/quic/src/muxer.rs [hunk 76]
```diff
@@ -0,0 +1,360 @@
...
+                    }
+                }
+            }
+        }
+        inner.poll_connection_waker = Some(cx.waker().clone());
+
+        // TODO: If connection migration is enabled (currently disabled) address
+        // change on the connection needs to be handled.
+
+        Poll::Pending
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]: Putting waker + `Pending` together makes this easier to reason about IMO.

```suggestion
        // TODO: If connection migration is enabled (currently disabled) address
        // change on the connection needs to be handled.

        inner.poll_connection_waker = Some(cx.waker().clone());
        Poll::Pending
```

File: transports/quic/src/muxer.rs [hunk 77]
```diff
@@ -0,0 +1,360 @@
...
+                id
+            }
+            None => {
+                inner.poll_inbound_waker = Some(cx.waker().clone());
+                return Poll::Pending;
+            }
+        };
+        inner.substreams.insert(substream_id, Default::default());
+        let substream = Substream::new(substream_id, self.inner.clone());
+        Poll::Ready(Ok(substream))
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]: I am a fan of whitespace, YMMV :upside_down_face: 

```suggestion
        let mut inner = self.inner.lock();
        
        let substream_id = match inner.connection.accept_substream() {
            Some(id) => {
                inner.poll_outbound_waker = None;
                id
            }
            None => {
                inner.poll_inbound_waker = Some(cx.waker().clone());
                return Poll::Pending;
            }
        };
        inner.substreams.insert(substream_id, Default::default());
        let substream = Substream::new(substream_id, self.inner.clone());
        
        Poll::Ready(Ok(substream))
```

File: transports/quic/src/muxer.rs [hunk 78]
```diff
@@ -0,0 +1,360 @@
...
+        let Inner {
+            substreams,
+            connection,
+            ..
+        } = &mut *self.inner.lock();
+        if connection.is_drained() {
+            return Poll::Ready(Ok(()));
+        }
+
+        if connection.send_stream_count() != 0 {
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]:
```suggestion
        if connection.send_stream_count() > 0 {
```

Comment (thomaseizinger) [reply transports/quic/src/muxer.rs]: Isn't this condition always implied by our `substreams` hashmap?

In other words, can't we skip this `if` and just always loop through all streams that we still know about?

File: transports/quic/src/muxer.rs [hunk 79]
```diff
@@ -0,0 +1,360 @@
...
+        }
+        loop {
+            if connection.send_stream_count() == 0 && !connection.is_closed() {
+                connection.close()
+            }
+            match connection.poll_event(cx) {
+                Poll::Ready(ConnectionEvent::ConnectionLost(_)) => return Poll::Ready(Ok(())),
+                Poll::Ready(_) => {}
+                Poll::Pending => break,
+            }
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]: You should be able to use `ready!` here. That in turn will allow you to remove the `Poll::Pending` at the bottom which currently looks suspicious because it is hard to see where the waker is registered.

File: transports/quic/src/muxer.rs [hunk 80]
```diff
@@ -0,0 +1,360 @@
...
+            if let Some(waker) = muxer.poll_connection_waker.take() {
+                waker.wake();
+            }
+        }
+        if pending && bytes == 0 {
+            let substream_state = muxer
+                .substreams
+                .get_mut(&self.id)
+                .expect("known substream; qed");
+            substream_state.read_waker = Some(cx.waker().clone());
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]: This pattern is repeated a fair bit. What about:

```patch
Index: transports/quic/src/muxer.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/transports/quic/src/muxer.rs b/transports/quic/src/muxer.rs
--- a/transports/quic/src/muxer.rs	(revision dcf61986f8ed73c89b6ad49b1cf7eee728f779b1)
+++ b/transports/quic/src/muxer.rs	(date 1664863012729)
@@ -55,6 +55,14 @@
     poll_connection_waker: Option<Waker>,
 }
 
+impl Inner {
+    fn unchecked_substream_state(&mut self, id: quinn_proto::StreamId) -> &mut SubstreamState {
+        self.substreams
+            .get_mut(&id)
+            .expect("must only be called for known stream IDs")
+    }
+}
+
 /// State of a single substream.
 #[derive(Debug, Default, Clone)]
 struct SubstreamState {
@@ -279,11 +287,7 @@
             }
         }
         if pending && bytes == 0 {
-            let substream_state = muxer
-                .substreams
-                .get_mut(&self.id)
-                .expect("known substream; qed");
-            substream_state.read_waker = Some(cx.waker().clone());
+            muxer.unchecked_substream_state(self.id).read_waker = Some(cx.waker().clone());
             Poll::Pending
         } else {
             Poll::Ready(Ok(bytes))

```

File: transports/quic/src/muxer.rs [hunk 81]
```diff
@@ -0,0 +1,360 @@
...
+                Ok(None) => break,
+                Err(err @ quinn_proto::ReadError::Reset(_)) => {
+                    return Poll::Ready(Err(io::Error::new(io::ErrorKind::ConnectionReset, err)))
+                }
+                Err(quinn_proto::ReadError::Blocked) => {
+                    pending = true;
+                    break;
+                }
+            }
+        }
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]: Could use early return to visually separate happy and unhappy paths.

```suggestion
        loop {
            if buf.is_empty() {
                break;
            }
            let chunk = match chunks.next(buf.len()) {
                Ok(Some(chunk)) => chunk,
                Ok(None) => break,
                Err(err @ quinn_proto::ReadError::Reset(_)) => {
                    return Poll::Ready(Err(io::Error::new(io::ErrorKind::ConnectionReset, err)))
                }
                Err(quinn_proto::ReadError::Blocked) => {
                    pending = true;
                    break;
                }
            };

            buf.write_all(&chunk.bytes).expect("enough buffer space");
            bytes += chunk.bytes.len();
        }
```

File: transports/quic/src/muxer.rs [hunk 82]
```diff
@@ -0,0 +1,360 @@
...
+                    "Illegal ordered read can only happen if `stream.read(false)` is used."
+                );
+            }
+        };
+        let mut bytes = 0;
+        let mut pending = false;
+        loop {
+            if buf.is_empty() {
+                break;
+            }
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]: This condition being necessary seems to be extremely subtle. From reading the code, I gather that the issue is that `Chunks::next` will happily take a `max_length` or `0` in which case we will loop forever here, reading 0 sized chunks :upside_down_face:.

We should either add a comment for this or add `if !chunk.bytes.is_empty()` as a match-arm guard to the `Ok(Some)` branch.

File: transports/quic/src/muxer.rs [hunk 83]
```diff
@@ -0,0 +1,360 @@
...
+                    .get_mut(&self.id)
+                    .expect("Substream is not finished.");
+                substream_state.finished_waker = Some(cx.waker().clone());
+                Poll::Pending
+            }
+            Err(err @ quinn_proto::FinishError::Stopped(_)) => {
+                Poll::Ready(Err(io::Error::new(io::ErrorKind::ConnectionReset, err)))
+            }
+            Err(quinn_proto::FinishError::UnknownStream) => Poll::Ready(Ok(())),
+        }
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]: This is a bit hacky. We are relying on the `UnknownStream` error to figure out whether we have successfully closed the stream once this task gets woken up again because the waker has been called.

We could check for the presence of the stream in our hashmap and if it is not there, return `Poll::Ready(Ok())`?

File: transports/quic/src/transport.rs [hunk 84]
```diff
@@ -0,0 +1,641 @@
...
+use std::collections::VecDeque;
+use std::io;
+use std::marker::PhantomData;
+use std::net::{IpAddr, UdpSocket};
+use std::task::Waker;
+use std::{
+    net::SocketAddr,
+    pin::Pin,
+    task::{Context, Poll},
+};
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: I'd prefer if we merge all `use` statements into one block.

File: transports/quic/src/transport.rs [hunk 85]
```diff
@@ -0,0 +1,641 @@
...
+        }
+    }
+}
+
+/// Error that can happen on the transport.
+#[derive(Debug, thiserror::Error)]
+pub enum TransportError {
+    /// Error while trying to reach a remote.
+    #[error("{0}")]
+    Reach(quinn_proto::ConnectError),
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: Errors should not forward their `Display` impl to their inner error. See https://github.com/rust-lang/project-error-handling/issues/44.

I'd be better to use `#[source]` or `#[from]` and put `#[error(transparent)]` on this variant if there no error text that you want to add to the error chain here.

File: transports/quic/src/transport.rs [hunk 86]
```diff
@@ -0,0 +1,641 @@
...
+
+    fn listen_on(
+        &mut self,
+        addr: Multiaddr,
+    ) -> Result<ListenerId, CoreTransportError<Self::Error>> {
+        let socket_addr = multiaddr_to_socketaddr(&addr)
+            .ok_or(CoreTransportError::MultiaddrNotSupported(addr))?;
+        let listener_id = ListenerId::new();
+        let listener = Listener::new::<P>(listener_id, socket_addr, self.config.clone())
+            .map_err(CoreTransportError::Other)?;
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: Can we implement `From` instead of calling `map_err` ourselves?

File: transports/quic/src/transport.rs (hunk 55 above)
Comment (thomaseizinger) [reply transports/quic/src/transport.rs]: The `take` below clears the `Option` field but ignores the result, meaning the value will be dropped at the end of `listen_on`.

I think this might be better modeled with an explicit use of `std::mem::drop`.

File: transports/quic/src/transport.rs [hunk 87]
```diff
@@ -0,0 +1,641 @@
...
+        if socket_addr.port() == 0 || socket_addr.ip().is_unspecified() {
+            return Err(CoreTransportError::MultiaddrNotSupported(addr));
+        }
+        let mut listeners = self
+            .listeners
+            .iter_mut()
+            .filter(|l| {
+                let listen_addr = l.endpoint_channel.socket_addr();
+                listen_addr.is_ipv4() == socket_addr.is_ipv4()
+                    && listen_addr.ip().is_loopback() == socket_addr.ip().is_loopback()
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: Why are we not handling `ipv6` addresses here?

File: transports/quic/src/transport.rs [hunk 88]
```diff
@@ -0,0 +1,641 @@
...
+            })
+            .collect::<Vec<_>>();
+
+        let (tx, rx) = oneshot::channel();
+        let to_endpoint = ToEndpoint::Dial {
+            addr: socket_addr,
+            result: tx,
+        };
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: We could reduce a bit of noise here by introducing a constructor that returns a tuple on `ToEndpoint`.

File: transports/quic/src/transport.rs (hunk 57 above)
Comment (thomaseizinger) [reply transports/quic/src/transport.rs]: It might be worth splitting this `if` into two so we can add a comment that support for wildcard ports will be added eventually.

File: transports/quic/src/transport.rs [hunk 89]
```diff
@@ -0,0 +1,641 @@
...
+        if listeners.is_empty() {
+            let dialer = match socket_addr {
+                SocketAddr::V4(_) => &mut self.ipv4_dialer,
+                SocketAddr::V6(_) => &mut self.ipv6_dialer,
+            };
+            if dialer.is_none() {
+                let _ = dialer.insert(Dialer::new::<P>(
+                    self.config.clone(),
+                    socket_addr.is_ipv6(),
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: Instead of passing a flag, I think it would be easier to understand to just pass on the `SocketAddr`.

File: transports/quic/src/transport.rs [hunk 90]
```diff
@@ -0,0 +1,641 @@
...
+                )?);
+            }
+            dialer
+                .as_mut()
+                .unwrap()
+                .pending_dials
+                .push_back(to_endpoint);
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: This can be expressed a bit simpler IMO:

```suggestion
            let maybe_dialer = match socket_addr {
                SocketAddr::V4(_) => &mut self.ipv4_dialer,
                SocketAddr::V6(_) => &mut self.ipv6_dialer,
            };
            let dialer = match maybe_dialer {
                None => maybe_dialer.insert(Dialer::new::<P>(self.config.clone(), socket_addr)?),
                Some(dialer) => dialer,
            };

            dialer.pending_dials.push_back(to_endpoint);
```

File: transports/quic/src/transport.rs [hunk 91]
```diff
@@ -0,0 +1,641 @@
...
+        } else {
+            // Pick a random listener to use for dialing.
+            let n = rand::random::<usize>() % listeners.len();
+            let listener = listeners.get_mut(n).expect("Can not be out of bound.");
+            listener.pending_dials.push_back(to_endpoint);
+            if let Some(waker) = listener.waker.take() {
+                waker.wake()
+            }
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: `rand` has utilities for stuff like this:

```suggestion
            // Pick a random listener to use for dialing.
            let listener = listeners
                .choose_mut(&mut rand::thread_rng())
                .expect("Can not be out of bound.);

            listener.pending_dials.push_back(to_endpoint);
            if let Some(waker) = listener.waker.take() {
                waker.wake()
            }
```

File: transports/quic/src/transport.rs [hunk 92]
```diff
@@ -0,0 +1,641 @@
...
+    fn drive_dials(&mut self, cx: &mut Context<'_>) -> Result<(), mpsc::SendError> {
+        if let Some(to_endpoint) = self.pending_dials.pop_front() {
+            match self.endpoint_channel.try_send(to_endpoint, cx) {
+                Ok(Ok(())) => {}
+                Ok(Err(to_endpoint)) => self.pending_dials.push_front(to_endpoint),
+                Err(err) => {
+                    return Err(err);
+                }
+            }
+        }
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: Would it make sense to `loop` in here?

File: transports/quic/src/transport.rs [hunk 93]
```diff
@@ -0,0 +1,641 @@
...
+    ) -> Result<Self, CoreTransportError<TransportError>> {
+        let endpoint_channel =
+            EndpointChannel::new_dialer::<P>(config, is_ipv6).map_err(CoreTransportError::Other)?;
+        Ok(Dialer {
+            endpoint_channel,
+            pending_dials: VecDeque::new(),
+        })
+    }
+
+    fn drive_dials(&mut self, cx: &mut Context<'_>) -> Result<(), mpsc::SendError> {
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: Should this be called `poll`?

Comment (thomaseizinger) [reply transports/quic/src/transport.rs]: This would force us to return `Poll::Pending` if we don't have any `pending_dials`. This thought makes me think, shouldn't this struct contain a waker that we call when we are pushing a new pending dial?

It might make sense to move this struct into its own module so we can properly encapsulate these fields and `QuicTransport` can't just modify them at will :)

**Review by thomaseizinger — COMMENTED** [review]
Lots of comments, sorry about that :see_no_evil: 

It is mostly minor stuff, I haven't thought about back-pressure yet.

File: transports/quic/Cargo.toml (hunk 41 above)
Comment (elenaf9) [reply transports/quic/Cargo.toml]: Okay. To avoid confusion in the future, e.g. in case of questions concerning the code, I am removing David as an author here. 
@dvc94ch please let me know in case that I missed that parts of the code that are still authored by you.

File: transports/quic/src/transport.rs (hunk 55 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Done as part of 1a7b0ff92dd5aabb5e263182a0efc91fe6834b13.

File: transports/quic/src/transport.rs (hunk 57 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Could you give examples of what specific reasons/ cases you have in mind @mxinden @thomaseizinger? Did we have situations in the past where users had this error and struggled with debugging it?

> It might be worth splitting this if into two so we can add a comment that support for wildcard ports will be added eventually.

@thomaseizinger this code is part of `Transport::dial`, so we will never support dialing wildcard ports here. Am I missing something?

File: transports/quic/src/transport.rs (hunk 56 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs:119]: Fixed for quic in f2a9ebc.

File: transports/quic/src/lib.rs (hunk 71 above)
Comment (elenaf9) [reply transports/quic/src/lib.rs]: It is exposed as part of the `Transport` trait implementation, thus I prefer to export it, even if it would compile without.

Comment (elenaf9) [reply transports/quic/src/lib.rs:69]: It is exposed as part of the `Transport` trait implementation, thus I prefer to export it, even if it would compile without.

File: transports/quic/src/lib.rs (hunk 72 above)
Comment (elenaf9) [reply transports/quic/src/lib.rs]: `quinn_proto::ConnectError` is currently wrapped as a variant of `ConnectionError`. We could remove it and instead inline each variant of `quinn_proto::ConnectError` into `ConnectionError`, but I don't think its worth the effort just to avoid the re-export.

File: transports/quic/src/lib.rs (hunk 70 above)
Comment (elenaf9) [reply transports/quic/src/lib.rs]: See comment above about exposing `QuicMuxer`.

File: transports/quic/src/muxer.rs (hunk 78 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: Unfortunately not. The quinn_proto `SendStream`s are only the stream that are not finished, i.e. where we can write to. A stream could be not in `SendStream` (= no writing permitted) but still be a valid stream to read from.

File: transports/quic/src/muxer.rs (hunk 83 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: I agree that it is kinda hacky and not ideal. Problem is that a stream could be in our hashmap but still already finished. Finished streams can still be used for reading. Alternative is to explicitly set a flag `is_finished` once the connection returns a `ConnectionEvent::StreamFinished` and then return early here if this flag is set to `true`. Thinking about it again, I think this is easier to understand. Unless you have an alternative idea?

File: transports/quic/src/transport.rs (hunk 84 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Don't have a strong opinion about this. I usually group imports myself as well, but this was existing code so I did not bother to change it. I wonder if this is really something that we have to be strict about?

File: transports/quic/src/muxer.rs (hunk 79 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: Suggestion included in 6f284cc.

File: transports/quic/src/upgrade.rs (hunk 74 above)
Comment (elenaf9) [reply transports/quic/src/upgrade.rs]: Done in 49e359b.

File: transports/quic/src/upgrade.rs (hunk 73 above)
Comment (elenaf9) [reply transports/quic/src/upgrade.rs]: Suggestion included in ec21fb1.

File: transports/quic/src/lib.rs (hunk 70 above)
Comment (elenaf9) [reply transports/quic/src/lib.rs]: Done in 8e729bf.

File: Cargo.toml (hunk 66 above)
Comment (elenaf9) [reply Cargo.toml]: Done in 831383a.

File: transports/quic/src/transport.rs (hunk 85 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Suggestion included in 6f284cc.

File: transports/quic/src/transport.rs (hunk 86 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Included in 6f284cc.

File: transports/quic/src/transport.rs (hunk 57 above)
Comment (mxinden) [reply transports/quic/src/transport.rs]: > Could you give examples of what specific reasons/ cases you have in mind @mxinden @thomaseizinger? Did we have situations in the past where users had this error and struggled with debugging it?

_Just to make sure I am not creating any confusion, I think this is outside of the scope of this pull request._

I have had the problem multiple times where I pass a malformed `Multiaddr` to a hierarchy of `Transport` implementations (e.g. relayed addresses are tricky) and my `Multiaddr` is being denied via `MutliaddrNotSupported`.

Say I have the following address: `/dns6/xxx/tcp/xxx/p2p/xxx/p2p-circuit/p2p/xxx`. When I get a `MultiaddrNotSupported` I don't know whether this is due to:

- The address being malformed for `libp2p-relay`.
- The address being malformed for `libp2p-dns`.
- The addresses resolved by `libp2p-dns` being malformed for `libp2p-tcp`.

In addition to not knowing where it has been denied, I don't know what the reason for denial was.

Comment (mxinden) [reply transports/quic/src/transport.rs]: I created https://github.com/libp2p/rust-libp2p/issues/2980 to track the `MultiaddrNotSupported` suggestion. Leaving this open for the second discussion, namely:

> > It might be worth splitting this if into two so we can add a comment that support for wildcard ports will be added eventually.
> 
> @thomaseizinger this code is part of `Transport::dial`, so we will never support dialing wildcard ports here. Am I missing something?

File: transports/quic/src/transport.rs (hunk 92 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Done as part of 0b80573.

File: transports/quic/src/transport.rs (hunk 93 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: > This thought makes me think, shouldn't this struct contain a waker that we call when
 we are pushing a new pending dial?

I think I originally only added a waker for the `Listener` and not for the `Dialer` be
cause I thought that after initiating a new dial a user would continue polling the swa
rm / transport anyway. But thinking about it now there are cases were this assumption
is incorrect. Added a waker in eafa89e.

> Should this be called poll?
>
> This would force us to return Poll::Pending if we don't have any pending_dials.

Not sure if that's intuitive. `Poll::Pending` usually means "there is work to do but w
e are currently blocked", which is not the case if the `pending_dials` are empty.

File: transports/quic/src/transport.rs (hunk 87 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: We are, we are just comparing there if either both are ipv4 or both ipv6. Made it more explicit as part of 0b80573.

File: transports/quic/src/transport.rs (hunk 89 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Decided to add a `SocketFamily` enum, which was also useful in some parts of the code. Lmk what you think about 0b80573.

File: transports/quic/src/transport.rs (hunk 90 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Cleaned this code up as part of 0b80573. Thanks for the suggestion!

File: transports/quic/src/lib.rs (hunk 72 above)
Comment (thomaseizinger) [reply transports/quic/src/lib.rs]: I've had a quick (pun intended) look and this seems to be almost the only case where we have `quinn_proto` types in our public API.

Not re-exporting it would free us from having to make a major bump every time `quinn_proto` updates.

Any easy way of handling this with errors is be wrapping them in a newtype and slapping `#[error(transparent)]` on it.

File: transports/quic/src/muxer.rs (hunk 78 above)
Comment (thomaseizinger) [reply transports/quic/src/muxer.rs]: I looked at the variants of `FinishError` and then one variant seems to be what you are talking about: https://docs.rs/quinn-proto/0.8.4/quinn_proto/enum.FinishError.html#variant.Stopped

The other variant is impossible in our setup so I think we could reduce this bit of code down to looping over all our streams, ignoring the `FinishError::Stopped` if it happens and panicking or ignoring `FinishError::UnknownStream` too.

File: transports/quic/src/muxer.rs (hunk 83 above)
Comment (thomaseizinger) [reply transports/quic/src/muxer.rs]: Yeah I think I'd prefer to explicitly track this state. Something like `write_closed` maybe? So we indicate that we can still read from it.

File: transports/quic/src/transport.rs (hunk 84 above)
Comment (thomaseizinger) [reply transports/quic/src/transport.rs]: I am not too fussed. It is mostly the module declarations half-way through that confuse me :)

File: transports/quic/src/transport.rs (hunk 89 above)
Comment (thomaseizinger) [reply transports/quic/src/transport.rs]: Wonderful idea!

**Comment by thomaseizinger** [comment]
@elenaf9 I pushed two commits, hope you don't mind! Feel free to amend / drop them if you disagree :)

File: transports/quic/src/transport.rs (hunk 93 above)
Comment (thomaseizinger) [reply transports/quic/src/transport.rs]: > > Should this be called poll?
> > This would force us to return Poll::Pending if we don't have any pending_dials.
> 
> Not sure if that's intuitive. `Poll::Pending` usually means "there is work to do but w e are currently blocked", which is not the case if the `pending_dials` are empty.

I don't quite see it that way. To me `Poll::Pending` means "I cannot proceed with the task that you want me to do, unless something else makes progress". Reading from an empty queue is a legit case to register a waker IMO. It is the same thing for channels. Reading from an empty channel does not return `Ok(())` but `Poll::Pending`.

File: transports/quic/src/transport.rs (hunk 84 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: You're right, they should not be hidden in between import statements! Will fix it.

File: transports/quic/tests/smoke.rs [hunk 94]
```diff
@@ -0,0 +1,570 @@
...
+
+    match b.next().await {
+        Some(SwarmEvent::Behaviour(RequestResponseEvent::OutboundFailure { .. })) => {}
+        e => panic!("{:?}", e),
+    };
+}
+
+#[test]
+fn concurrent_connections_and_streams() {
+    use quickcheck::*;
```
Comment (MarcoPolo) [inline transports/quic/tests/smoke.rs:324]: Are you using quickcheck here? It seems like it's commented out below

File: transports/quic/src/lib.rs [hunk 95]
```diff
@@ -0,0 +1,78 @@
...
+//! use libp2p_quic as quic;
+//! use libp2p_core::{Multiaddr, Transport};
+//!
+//! let keypair = libp2p_core::identity::Keypair::generate_ed25519();
+//! let quic_config = quic::Config::new(&keypair).expect("could not make config");
+//!
+//! let mut quic_transport = quic::async_std::Transport::new(quic_config);
+//!
+//! let addr = "/ip4/127.0.0.1/udp/12345/quic".parse().expect("bad address?");
+//! quic_transport.listen_on(addr).expect("listen error.");
```
Comment (MarcoPolo) [inline transports/quic/src/lib.rs:43]: nit: this should be something like `.expect("transport should be able to listen on address")` https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style

File: transports/quic/tests/smoke.rs (hunk 94 above)
Comment (MarcoPolo) [inline transports/quic/tests/smoke.rs]: Are you using quickcheck here? It seems like it's commented out below

File: transports/quic/src/lib.rs [hunk 96]
```diff
@@ -0,0 +1,78 @@
...
+//! #
+//! use libp2p_quic as quic;
+//! use libp2p_core::{Multiaddr, Transport};
+//!
+//! let keypair = libp2p_core::identity::Keypair::generate_ed25519();
+//! let quic_config = quic::Config::new(&keypair).expect("could not make config");
+//!
+//! let mut quic_transport = quic::async_std::Transport::new(quic_config);
+//!
+//! let addr = "/ip4/127.0.0.1/udp/12345/quic".parse().expect("bad address?");
```
Comment (MarcoPolo) [inline transports/quic/src/lib.rs]: nit: 
```suggestion
//! let addr = "/ip4/127.0.0.1/udp/12345/quic".parse().expect("transport should be able to listen on address");
```

https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style

File: transports/quic/src/tls/verifier.rs (hunk 40 above)
Comment (elenaf9) [reply transports/quic/src/tls/verifier.rs]: Is this question still open or can I mark it as resolved given that tls is not part of this PR anymore?

File: transports/quic/src/lib.rs (hunk 53 above)
Comment (elenaf9) [reply transports/quic/src/lib.rs]: Doing it via `custom-clippy` make sense so it's checked for all crates. Will remove the flag here.

File: transports/quic/src/transport.rs (hunk 57 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Thanks for elaborating @mxinden. Since this is tracked in #2980 and out of scope for this PR I mark it as resolved.

File: transports/quic/src/connection.rs [hunk 97]
```diff
@@ -0,0 +1,389 @@
...
+    }
+
+    /// Returns the address of the node we're connected to.
+    pub fn remote_addr(&self) -> SocketAddr {
+        self.connection.remote_address()
+    }
+
+    /// Returns the ID of the node we're connected to.
+    pub fn remote_peer_id(&self) -> PeerId {
+        let session = self.connection.crypto_session();
```
Comment (MarcoPolo) [inline transports/quic/src/connection.rs]: Should we remember the remote peer id? Seems kind of silly to decode the certificate everytime someone asks us about the remote peer id

File: transports/quic/src/provider.rs [hunk 98]
```diff
@@ -0,0 +1,54 @@
...
+    // Note: The socket must be set to non-blocking.
+    fn from_socket(socket: std::net::UdpSocket) -> io::Result<Self>;
+
+    // Receive a single datagram message.
+    // Returns the message and the address the message came from.
+    fn poll_recv_from(&mut self, cx: &mut Context<'_>) -> Poll<io::Result<(Vec<u8>, SocketAddr)>>;
+
+    // Set sending the packet on the socket.
+    // Since only one packet may be sent at a time, this may only be called if a preceding call
+    // to [`Provider::poll_send_flush`] returned [`Poll::Ready`].
```
Comment (MarcoPolo) [inline transports/quic/src/provider.rs]: What's the benefit of having this two stage function?

Wouldn't it be simpler if this implementing something like AsyncWrite's poll_write `https://docs.rs/futures/latest/futures/io/trait.AsyncWrite.html#tymethod.poll_write`. This way it is easier to use this method, since you don't have to rely on another method being called first.

My guess is that you're mimicing the futures::Channel Sender api, where you have to check if the channel is ready before sending. But isn't this more like a Async Writer since this is wrapping a socket?

File: transports/quic/src/endpoint.rs [hunk 99]
```diff
@@ -0,0 +1,556 @@
...
+
+        let channel = EndpointChannel {
+            to_endpoint: to_endpoint_tx,
+            socket_addr: socket.local_addr()?,
+        };
+
+        let server_config = new_connections.is_some().then_some(config.server_config);
+        let socket = P::from_socket(socket)?;
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]: Small nit, feel free to disregard. I find having the same var name for different types to be confusing

File: transports/quic/src/endpoint.rs [hunk 100]
```diff
@@ -0,0 +1,556 @@
...
+            Poll::Ready(Ok(())) => {}
+            Poll::Ready(Err(err)) => return Err(err),
+            Poll::Pending => return Ok(Err(to_endpoint)),
+        };
+        self.to_endpoint.start_send(to_endpoint).map(Ok)
+    }
+
+    /// Send a message to inform the [`EndpointDriver`] about an
+    /// event caused by the owner of this [`EndpointChannel`] dropping.
+    /// This clones the sender to the endpoint to guarantee delivery.
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs:265]: To check my understanding, this is because cloning a sender effectively lets you put one more thing on to the channel. If you didn't clone, and the sender was parked you wouldn't actually be able to send the message.

Is that correct?

File: transports/quic/src/connection.rs [hunk 101]
```diff
@@ -0,0 +1,389 @@
...
+                Poll::Ready(Some(event)) => {
+                    self.connection.handle_event(event);
+                    continue;
+                }
+                Poll::Ready(None) => {
+                    if closed.is_none() {
+                        return Poll::Ready(ConnectionEvent::ConnectionLost(
+                            ConnectionError::EndpointDriverCrashed,
+                        ));
+                    }
```
Comment (MarcoPolo) [inline transports/quic/src/connection.rs]: Since we're not return in the else branch here, does this mean we could accidentally call `poll_next` again? I thought when we get back `Poll::Ready(None)` we should not call it again:

> Poll::Ready(None) means that the stream has terminated, and poll_next should not be invoked again.

from: https://docs.rs/futures-core/latest/futures_core/stream/trait.Stream.html#tymethod.poll_next

File: transports/quic/src/connection.rs [hunk 102]
```diff
@@ -0,0 +1,389 @@
...
+            }
+
+            // The maximum amount of segments which can be transmitted in a single Transmit
+            // if a platform supports Generic Send Offload (GSO).
+            // Set to 1 for now since not all platforms support GSO.
+            // TODO: Fix for platforms that support GSO.
+            let max_datagrams = 1;
+            // Poll the connection for packets to send on the UDP socket and try to send them on
+            // `to_endpoint`.
+            if let Some(transmit) = self.connection.poll_transmit(Instant::now(), max_datagrams) {
```
Comment (MarcoPolo) [inline transports/quic/src/connection.rs]: Are we polling at the right time here? Or is there a risk that we are polling too much here. The docs for poll_transmit say we should only poll when:

* the application performed some I/O on the connection
* a call was made to handle_event
* a call was made to handle_timeout

File: transports/quic/src/connection.rs [hunk 103]
```diff
@@ -0,0 +1,389 @@
...
+            if let Some(closed) = closed {
+                return Poll::Ready(ConnectionEvent::ConnectionLost(closed));
+            }
+
+            // The final step consists in handling the events related to the various substreams.
+            if let Some(ev) = self.connection.poll() {
+                match ConnectionEvent::try_from(ev) {
+                    Ok(ConnectionEvent::ConnectionLost(reason)) => {
+                        // Continue in the loop once more so that we can send a
+                        // `EndpointEvent::drained` to the endpoint before returning.
```
Comment (MarcoPolo) [inline transports/quic/src/connection.rs]: How does continuing the loop help do this? Doesn't this only happen when we drop the connection?

File: transports/quic/src/endpoint.rs [hunk 104]
```diff
@@ -0,0 +1,556 @@
...
+///
+/// Because connections are processed by the user at a rate of their choice, we cannot properly
+/// handle the situation where the channel from the background task to individual connections is
+/// full. Sleeping the task while waiting for the connection to be processed by the user could
+/// even lead to a deadlock if this processing is also sleeping waiting for some other action that
+/// itself depends on the background task (e.g. if processing the connection is waiting for a
+/// message arriving on a different connection).
+///
+/// In an ideal world, we would handle a background-task-to-connection channel being full by
+/// dropping UDP packets destined to this connection, as a way to back-pressure the remote.
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]: we could technically use flow control here to tell the sender to stop sending us packets: https://www.rfc-editor.org/rfc/rfc9000.html#name-flow-control. Then readjust when we are more capable. This probably depends on quinn integration.

File: transports/quic/src/endpoint.rs [hunk 105]
```diff
@@ -0,0 +1,556 @@
...
+/// Unfortunately, the `quinn-proto` library doesn't provide any way for us to know which
+/// connection a UDP packet is destined for before it has been turned into a `ConnectionEvent`,
+/// and because these `ConnectionEvent`s are sometimes used to synchronize the states of the
+/// endpoint and connection, it would be a logic error to silently drop them.
+///
+/// We handle this tricky situation by simply killing connections as soon as their associated
+/// channel is full.
+///
+// TODO: actually implement the killing of connections if channel is full, at the moment we just
+// wait
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]: what does wait mean? What happens when the endpoint -> connection channel is full?

File: transports/quic/src/endpoint.rs [hunk 106]
```diff
@@ -0,0 +1,556 @@
...
+            Poll::Ready(Err(err)) => return Err(err),
+            Poll::Pending => return Ok(Err(to_endpoint)),
+        };
+        self.to_endpoint.start_send(to_endpoint).map(Ok)
+    }
+
+    /// Send a message to inform the [`EndpointDriver`] about an
+    /// event caused by the owner of this [`EndpointChannel`] dropping.
+    /// This clones the sender to the endpoint to guarantee delivery.
+    /// It this should *not* be called for regular messages.
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]:
```suggestion
    /// This should *not* be called for regular messages.
```

File: transports/quic/src/endpoint.rs [hunk 107]
```diff
@@ -0,0 +1,556 @@
...
+    /// there.
+    ProcessConnectionEvent {
+        connection_id: quinn_proto::ConnectionHandle,
+        event: quinn_proto::EndpointEvent,
+    },
+    /// Instruct the endpoint to send a packet of data on its UDP socket.
+    SendUdpPacket(quinn_proto::Transmit),
+    /// The [`GenTransport`][transport::GenTransport] dialer or listener coupled to this endpoint
+    /// was dropped.
+    /// Once all pending connection closed the [`EndpointDriver`] should shut down.
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]:
```suggestion
    /// Once all pending connections are closed, the [EndpointDriver] should shut down.
```

File: transports/quic/src/endpoint.rs [hunk 108]
```diff
@@ -0,0 +1,556 @@
...
+/// are therefore in total three buffers in play: the `new_connection_tx` channel itself, the queue
+/// of elements being sent on `new_connection_tx`, and the accept buffer of the
+/// [`quinn_proto::Endpoint`].
+///
+/// ## Back-pressure on connections
+///
+/// Because connections are processed by the user at a rate of their choice, we cannot properly
+/// handle the situation where the channel from the background task to individual connections is
+/// full. Sleeping the task while waiting for the connection to be processed by the user could
+/// even lead to a deadlock if this processing is also sleeping waiting for some other action that
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]:
```suggestion
/// even lead to a deadlock if this processing is also waiting for some other action that
```

File: transports/quic/src/endpoint.rs [hunk 109]
```diff
@@ -0,0 +1,556 @@
...
+/// itself depends on the background task (e.g. if processing the connection is waiting for a
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]:
```suggestion
/// itself depends on the EndpointDriver (e.g. if processing the connection is waiting for a
```

File: transports/quic/src/endpoint.rs [hunk 110]
```diff
@@ -0,0 +1,556 @@
...
+/// message arriving on a different connection).
+///
+/// In an ideal world, we would handle a background-task-to-connection channel being full by
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]:
```suggestion
/// In an ideal world, we would handle a EndpointDriver-to-Connection channel being full by
```

File: transports/quic/src/endpoint.rs (hunk 43 above)
Comment (MarcoPolo) [reply transports/quic/src/endpoint.rs]: ah whoops. Disregard my comments if not applicable. I saw you mentioned this comment was out of date

File: transports/quic/src/endpoint.rs [hunk 111]
```diff
@@ -0,0 +1,556 @@
...
+
+                let event_back = self.endpoint.handle_event(connection_id, event);
+
+                if let Some(event_back) = event_back {
+                    debug_assert!(!is_drained_event);
+                    if let Some(sender) = self.alive_connections.get_mut(&connection_id) {
+                        // We clone the sender to guarantee that there will be at least one
+                        // free slot to send the event.
+                        // The channel can not grow out of bound because an `event_back` is
+                        // only sent if we prior received an event from the same connection.
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]:
```suggestion
                        // only sent if we previously received an event from the same connection.
```

File: transports/quic/src/endpoint.rs [hunk 112]
```diff
@@ -0,0 +1,556 @@
...
+                        Ok(()) => {}
+                        Err(err) if err.is_disconnected() => {
+                            // Connection was dropped by the user.
+                            // Inform the endpoint that this connection is drained.
+                            self.endpoint
+                                .handle_event(connec_id, quinn_proto::EndpointEvent::drained());
+                            self.alive_connections.remove(&connec_id);
+                        }
+                        Err(err) if err.is_full() => {
+                            // Connection is too busy. Drop the datagram to back-pressure the remote.
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs:509]: Is this safe? I thought the comment above said we didn't want to do this to avoid breaking the synchornization between the connection state machine and endpoint state machine.

File: transports/quic/src/endpoint.rs [hunk 113]
```diff
@@ -0,0 +1,556 @@
...
+            }
+            quinn_proto::DatagramEvent::NewConnection(connec) => {
+                // A new connection has been received. `connec_id` is a newly-allocated
+                // identifier.
+                debug_assert_eq!(connec.side(), quinn_proto::Side::Server);
+                let connection_tx = match self.new_connection_tx.as_mut() {
+                    Some(tx) => tx,
+                    None => {
+                        log::warn!(
+                            "Endpoint reported a new connection even though server capabilities are disabled."
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]: Should we just panic here? This would be an unexpected state to be in and I'm not sure how to continue (besides dropping the event).

File: transports/quic/src/endpoint.rs [hunk 114]
```diff
@@ -0,0 +1,556 @@
...
+
+impl<P: Provider> Future for EndpointDriver<P> {
+    type Output = ();
+    fn poll(mut self: std::pin::Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
+        loop {
+            match ready!(self.socket.poll_send_flush(cx)) {
+                Ok(_) => {}
+                // Errors on the socket are expected to never happen, and we handle them by simply
+                // printing a log message. The packet gets discarded in case of error, but we are
+                // robust to packet losses and it is consequently not a logic error to process with
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs]:
```suggestion
                // robust to packet losses and it is consequently not a logic error to proceed with
```

File: transports/quic/src/tls/verifier.rs (hunk 40 above)
Comment (thomaseizinger) [reply transports/quic/src/tls/verifier.rs]: Marking as resolved. Discussion now happening here: https://github.com/libp2p/rust-libp2p/pull/2945#issuecomment-1269111790

File: transports/quic/src/muxer.rs [hunk 115]
```diff
@@ -0,0 +1,359 @@
...
+    }
+}
+
+impl AsyncRead for Substream {
+    fn poll_read(
+        self: Pin<&mut Self>,
+        cx: &mut Context<'_>,
+        mut buf: &mut [u8],
+    ) -> Poll<io::Result<usize>> {
+        let mut muxer = self.muxer.lock();
```
Comment (MarcoPolo) [inline transports/quic/src/muxer.rs]: Does this mean that nothing else can do a read or write while this function holds this lock?

File: transports/quic/src/muxer.rs (hunk 82 above)
Comment (MarcoPolo) [reply transports/quic/src/muxer.rs]: I'm a bit confused. Maybe, I'm misunderstanding which line you are commenting on. When we call write_all we move the pointer up the buffer to the spot after where we've written the data to. The `buf.is_empty()` check is then checking if we still have any space left in the buffer to write to.

File: transports/quic/src/upgrade.rs [hunk 116]
```diff
@@ -0,0 +1,78 @@
...
+                    return Poll::Ready(Ok((peer_id, muxer)));
+                }
+                ConnectionEvent::ConnectionLost(err) => return Poll::Ready(Err(err.into())),
+                ConnectionEvent::HandshakeDataReady
+                | ConnectionEvent::StreamAvailable
+                | ConnectionEvent::StreamOpened
+                | ConnectionEvent::StreamReadable(_)
+                | ConnectionEvent::StreamWritable(_)
+                | ConnectionEvent::StreamFinished(_)
+                | ConnectionEvent::StreamStopped(_) => {}
```
Comment (MarcoPolo) [inline transports/quic/src/upgrade.rs]: Are these stream events even valid here? When would we see these before a connected event?

**Comment by thomaseizinger** [comment]
Whilst reviewing / working on this, I've found the terminology and file structure a bit hard to understand and inconsistent with what we use in other crates.

It might be controversial so I pushed it to my own fork for now: https://github.com/kpp/rust-libp2p/pull/25

The gist of it is:

- Rename `Connection` to `State` to showcase that it represents a state machine
- Rename `QuicMuxer` to `Connection`: For the rest of rust-libp2p, the muxer instance _is_ the connection
- Add a `connection` sub directory

File: transports/quic/src/transport.rs [hunk 117]
```diff
@@ -0,0 +1,703 @@
...
+        }
+    }
+
+    /// Poll for a next If Event.
+    fn poll_dialer(&mut self, cx: &mut Context<'_>) -> Poll<TransportError> {
+        let Self {
+            dialer_state,
+            endpoint_channel,
+            ..
+        } = &mut *self;
```
Comment (MarcoPolo) [inline transports/quic/src/transport.rs]:
```suggestion
        } = self;
```

File: transports/quic/src/endpoint.rs [hunk 118]
```diff
@@ -0,0 +1,574 @@
...
+    /// Handle datagram received on the socket.
+    /// The datagram content was written into the `socket_recv_buffer`.
+    fn handle_datagram(&mut self, packet: BytesMut, packet_src: SocketAddr) -> ControlFlow<()> {
+        let local_ip = self.channel.socket_addr.ip();
+        // TODO: ECN bits aren't handled
+        let (connec_id, event) =
+            match self
+                .endpoint
+                .handle(Instant::now(), packet_src, Some(local_ip), None, packet)
+            {
```
Comment (MarcoPolo) [inline transports/quic/src/endpoint.rs:486]: Might be nice to have a test case that hits this. My guess is this doesn't affect much, but would be good to check.

File: transports/quic/src/transport.rs [hunk 119]
```diff
@@ -0,0 +1,703 @@
...
+            .listeners
+            .iter_mut()
+            .filter(|l| {
+                let listen_addr = l.endpoint_channel.socket_addr();
+                SocketFamily::is_same(&listen_addr.ip(), &socket_addr.ip())
+                    && listen_addr.ip().is_loopback() == socket_addr.ip().is_loopback()
+            })
+            .collect::<Vec<_>>();
+
+        // Try to use pick a random listener to use for dialing.
```
Comment (MarcoPolo) [inline transports/quic/src/transport.rs]: Can we do something deterministic instead? Maybe hash the socket_addr and use that as the index for which listener.

Adding randomness introduces non-determinism which introduces a new class of possible bugs.

File: transports/quic/src/transport.rs [hunk 120]
```diff
@@ -0,0 +1,707 @@
...
+        addr: Multiaddr,
+    ) -> Result<ListenerId, CoreTransportError<Self::Error>> {
+        let socket_addr = multiaddr_to_socketaddr(&addr)
+            .ok_or(CoreTransportError::MultiaddrNotSupported(addr))?;
+        let listener_id = ListenerId::new();
+        let listener = Listener::new::<P>(listener_id, socket_addr, self.config.clone())?;
+        self.listeners.push(listener);
+
+        // Remove dialer endpoint so that the endpoint is dropped once the last
+        // connection that uses it is closed.
```
Comment (MarcoPolo) [inline transports/quic/src/transport.rs:97]: Open question (to me): Do we have a test that runs this flow? i.e. dial first, then listen_on, then make sure the dialer's endpoint is cleaned up eventually.

File: transports/quic/src/transport.rs [hunk 121]
```diff
@@ -0,0 +1,707 @@
...
+
+    fn dial_as_listener(
+        &mut self,
+        addr: Multiaddr,
+    ) -> Result<Self::Dial, CoreTransportError<Self::Error>> {
+        // TODO: As the listener of a QUIC hole punch, we need to send a random UDP packet to the
+        // `addr`. See DCUtR specification below.
+        //
+        // https://github.com/libp2p/specs/blob/master/relay/DCUtR.md#the-protocol
+        self.dial(addr)
```
Comment (MarcoPolo) [inline transports/quic/src/transport.rs]: So this isn't implemented at all then? Since this isn't having the node act as a listener. Maybe we should at least log a warning, if not return an error.

File: transports/quic/src/transport.rs [hunk 122]
```diff
@@ -0,0 +1,703 @@
...
+        let socket_addr = multiaddr_to_socketaddr(&addr)
+            .ok_or_else(|| CoreTransportError::MultiaddrNotSupported(addr.clone()))?;
+        if socket_addr.port() == 0 || socket_addr.ip().is_unspecified() {
+            return Err(CoreTransportError::MultiaddrNotSupported(addr));
+        }
+        let mut listeners = self
+            .listeners
+            .iter_mut()
+            .filter(|l| {
+                let listen_addr = l.endpoint_channel.socket_addr();
```
Comment (MarcoPolo) [inline transports/quic/src/transport.rs:136]: Do you need to check if this listener is closed?

File: transports/quic/src/transport.rs [hunk 123]
```diff
@@ -0,0 +1,703 @@
...
+        // Remove dialer endpoint so that the endpoint is dropped once the last
+        // connection that uses it is closed.
+        // New outbound connections will use a bidirectional (listener) endpoint.
+        self.dialer.remove(&socket_addr.ip().into());
+
+        Ok(listener_id)
+    }
+
+    fn remove_listener(&mut self, id: ListenerId) -> bool {
+        if let Some(listener) = self.listeners.iter_mut().find(|l| l.listener_id == id) {
```
Comment (MarcoPolo) [inline transports/quic/src/transport.rs:105]: Would it make sense to remove the listener? I'm not sure it's possible with `SelectAll`, but it's a bit confusing because we keep a closed listener forever (?).

Edit: nvm. I see from the test below that SelectAlll seems to prune completed streams (since that's what `FuturesUnordered` does). Maybe leave a comment here explaining this?

File: transports/quic/src/transport.rs [hunk 124]
```diff
@@ -0,0 +1,707 @@
...
+impl From<IpAddr> for SocketFamily {
+    fn from(ip: IpAddr) -> Self {
+        match ip {
+            IpAddr::V4(_) => SocketFamily::Ipv4,
+            IpAddr::V6(_) => SocketFamily::Ipv6,
+        }
+    }
+}
+
+/// Turn an [`IpAddr`] into a listen-address for the endpoint.
```
Comment (MarcoPolo) [inline transports/quic/src/transport.rs]: Maybe the doc comment should mention that this merged the endpoint addr port with the ip (overriding any port at the ip). Took me a bit to understand what this was doing and why.

**Review by MarcoPolo — COMMENTED** [review]
Overall this looks great! Mostly a couple minor things and questions. Thanks all!

File: transports/quic/src/provider.rs (hunk 98 above)
Comment (thomaseizinger) [reply transports/quic/src/provider.rs]: The issue is that `AsyncWrite::poll_write` will only by able to write X bytes, so you always need to get the number of written bytes from function and advance the buffer accordingly.

Doable, but not sure if necessary here?

File: transports/quic/src/muxer.rs (hunk 82 above)
Comment (thomaseizinger) [reply transports/quic/src/muxer.rs]: We only request chunks of length `buf.len()` from the quinn API (line 261), so ideally, that would just return `Ok(None)` if we request a 0-sized chunk because we don't have any more space in the buffer.

But it doesn't do that. It returns a `Chunk` of length `0` which means we will loop forever requesting new chunks and never break.

Comment (MarcoPolo) [reply transports/quic/src/muxer.rs]: Ah I see. But checking if we have space to even write into the buf seems reasonable to me. And you don't need to know anything about how things are chunked.

File: transports/quic/src/endpoint.rs (hunk 100 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:265]: Yes exactly. A newly cloned sender is  not parked [^1], which allows for at least one item to be send [^2].

[^1]: https://github.com/rust-lang/futures-rs/blob/7a98cf0bbeb397dcfaf5f020b371ab9e836d33d4/futures-channel/src/mpsc/mod.rs#L913
[^2]: https://github.com/rust-lang/futures-rs/blob/7a98cf0bbeb397dcfaf5f020b371ab9e836d33d4/futures-channel/src/mpsc/mod.rs#L497-L502

File: transports/quic/src/provider.rs (hunk 98 above)
Comment (MarcoPolo) [reply transports/quic/src/provider.rs]: gotcha. I guess what I'm wondering is if there's a reason to prefer having a poll_send_flush + start_send rather than a single method like `poll_send`

Comment (elenaf9) [reply transports/quic/src/provider.rs]: Its needed because the [`async_std::UdpSocket`](https://docs.rs/async-std/latest/async_std/net/struct.UdpSocket.html) (which we use in our async_std Provider) doesn't provide a poll-like interface for sending a message, but instead only a `async fn send_to`. So what we do is we create the future in `start_send` (and thus take ownership of the bytes to send) and then drive that future in `poll_send_flush`. With a single `poll_send(&mut self, bytes: &[u8], ...)` this would not work. Does that make sense?

File: transports/quic/src/upgrade.rs (hunk 116 above)
Comment (elenaf9) [reply transports/quic/src/upgrade.rs]: `ConnectionEvent::HandshakeDataReady` will be reported during the handshake negotiation, i.e. before the connection is reported as established. The other events I think won't happen in practice. But I don't think there is a need to explicitly enforce this here, and it's safe to just ignore them.

File: transports/quic/src/connection.rs (hunk 102 above)
Comment (elenaf9) [reply transports/quic/src/connection.rs]: I read the docs as in "at least in these cases it must be polled", not that it is **only** allowed in these cases. But I agree that we should not unnecessary poll. However, I think right now we only poll additionally:
-  Once per `Connection::poll_event` call: I think this is okay given that `Connection` is polled in its own task only when something made progress (some I/O happened).
- After `poll_transmit` returned `Some` we poll it again -> I think that make sense because there could be multiple transmits to send out
- After we sent an `EndpointEvent` to the endpoint. Looking into the code it seems like this only happens once in a while if the connection id, or the reset token changes. Also, the endpoint may return an event back where we then call `handle_event`.

Are there any other cases that I am missing / do you think any of these result in too much polling?

File: transports/quic/src/connection.rs (hunk 103 above)
Comment (elenaf9) [reply transports/quic/src/connection.rs]: `quinn-proto` may also report the connection as lost, e.g. because it timed out. In that case `quinn-proto` reports both, an `EndpointEvent::drained` and the `ConnectionEvent::ConnectionLost`. I think I originally continued here in case that the `ConnectionLost` event was reported before the `drained` event. 
But since we poll for endpoint events before polling for connection events I think this can not happen. And at the latest once the connection is dropped we also report it as drained.

Long story short: I will remove this and directly return the error.
Edit: done in 9e394b3f7e7c31df2e1db6ea19d16a80d914d885.

File: transports/quic/src/endpoint.rs (hunk 105 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: This is an outdated comment. It used to be implemented that the background task `await`ed sending events to a connection. This is not the case anymore. Also we don't kill any connections.

> What happens when the endpoint -> connection channel is full?

There are two cases in which we sent in the endpoint -> connection channel:
- To forward an incoming packet to the connection: If the connection is busy we drop the packet, thus it won't be ACK'ed and the remote will be backpressured
- When handling an event from a connection, the endpoint may return an event back to that connection. Here we clone the sender to guarantee a slot. The channel can not grow unbounded here because if the connection is too busy to read from the channel it will also not send us any events anymore, thus it can not happen that the endpoint just fills up this channel.

File: transports/quic/src/endpoint.rs (hunk 108 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: I'll rewrite the whole section since it is outdated.

File: transports/quic/src/endpoint.rs (hunk 109 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: I'll rewrite the whole section since it is outdated.

File: transports/quic/src/endpoint.rs (hunk 110 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: See above comments.

File: transports/quic/src/endpoint.rs (hunk 112 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:509]: The comment itself is outdated,  but still a valid discussion.
The concern is that after handling an udp packet, the endpoint returns here an `ConnectionEvent` for a known connection. This type has two variants:
1. `Datagram`: a forwarded datagram -> safe to drop
2. `NewIdentifiers`: new connection identifiers -> not safe to drop!

By type, the returned event may theoretically by both variants, which is why the original comment said it was not safe to drop. However, in practice only the `Datagram` variant is returned here [^1]. This is also stated in the docs on `DatagramEvent::ConnectionEvent`: " /// The datagram is redirected to its `Connection`". While it is not ideal to rely on this I am hesitant to add more complex handling for a case that can never happen in practice. 

[^1]: https://github.com/quinn-rs/quinn/blob/cd2cf756acc9e7774d2c40992e7a355d0fb51b74/quinn-proto/src/endpoint.rs#L234-L245

File: transports/quic/src/endpoint.rs (hunk 113 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: I generally prefer to not panic on external code if it can be avoided. Otherwise a bug in `quinn-proto` may cause our nodes to crash.  
Dropping is safe here since nothing changed in our state.

But not a strong opinion. At current point we do know that this code is unreachable [^1], so I am okay wiuth adding a `unreachable!` if you insist :)

[^1]: https://github.com/quinn-rs/quinn/blob/cd2cf756acc9e7774d2c40992e7a355d0fb51b74/quinn-proto/src/endpoint.rs#L251-L258

File: transports/quic/src/muxer.rs (hunk 115 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: Yes. Unfortunately there is not way around this since we need mutable access to the inner `quinn_proto::Connection`.
But none of the below code it blocking.

File: transports/quic/src/transport.rs (hunk 122 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs:136]: Good catch! Included in fdca477c381a71cd8c52be341c3f74bdc8fd0198.

File: transports/quic/src/lib.rs (hunk 96 above)
Comment (elenaf9) [reply transports/quic/src/lib.rs]: Done as part of fdca477c381a71cd8c52be341c3f74bdc8fd0198.

File: transports/quic/src/endpoint.rs (hunk 99 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Change name as part of fdca477c381a71cd8c52be341c3f74bdc8fd0198.

File: transports/quic/src/connection.rs (hunk 97 above)
Comment (elenaf9) [reply transports/quic/src/connection.rs]: This function was only called once, when the upgrade on teh connection succeeded. Moved the code so that `ConnectionEstablished` already includes the `PeerId`: 963d3dd30fac8fe54b25e7e98e3041b809918b3a

File: transports/quic/src/connection.rs (hunk 101 above)
Comment (elenaf9) [reply transports/quic/src/connection.rs]: Obsolete since the `closed` flag was removed. See https://github.com/libp2p/rust-libp2p/pull/2289#discussion_r993863056

File: transports/quic/src/endpoint.rs (hunk 107 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Included in fdca477c381a71cd8c52be341c3f74bdc8fd0198 (the suggestion also removed the backticks around `EndpointDriver`, which I'd like to keep).

File: transports/quic/src/transport.rs (hunk 117 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Included in fdca477c381a71cd8c52be341c3f74bdc8fd0198.

File: transports/quic/src/endpoint.rs (hunk 45 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Set the idle timeout to 30s (but configurable by the user) and added an additional (shorter) timeout for the inital handshake. See 2264ab83377758d0644e668caba1ae9048cc384c.

File: transports/quic/src/endpoint.rs (hunk 48 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Included 256 as default in 2264ab83377758d0644e668caba1ae9048cc384c (but configurable by the user).

File: transports/quic/src/endpoint.rs (hunk 58 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:118]: > `allow_spin` to false

Included in 2264ab83377758d0644e668caba1ae9048cc384c.

> the stream receive window is set to 1.25 MB. This seems a lot as a starting value, but very little if this is the maximum value the window can ever grow to. Depends on the auto-scaling logic, if there is any.

<s> From what I understand in the quinn-proto code it scales to that the actual stream receive window is `stream_receive_window` + bytes read thus far on the stream [^1] </s> Edit: Actually, that's not for scaling, but rather because MAX_(STREAM_)DATA is the maximum absolute byte **offset**, therefore the bytes read thus far obv need to be added. So from what I have seen quinn does not scale.

> the connection receive window apparently is set to infinity. This is not a very good idea, since it means that the memory you're committing to the QUIC connection is the product of your stream receive window and the number of streams. With default values, that's 125 MB, making it very easy to perform a DoS against the QUIC stack

What default is go-quic using? Does it scale or is it set to a fixed value?

[^1]: https://github.com/quinn-rs/quinn/blob/cd2cf756acc9e7774d2c40992e7a355d0fb51b74/quinn-proto/src/connection/streams/recv.rs#L99

File: transports/quic/src/transport.rs (hunk 93 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Resolved with 7a86e30.

File: transports/quic/src/muxer.rs (hunk 78 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: Suggestion included in 82b6a9d.

File: transports/quic/src/muxer.rs (hunk 80 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: Good idea! Included in 82b6a9d.

File: transports/quic/src/muxer.rs (hunk 83 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: Added `is_write_closed` flag in 82b6a9d.

File: transports/quic/src/muxer.rs (hunk 82 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: Included match-arm guard to check length of read bytes in 82b6a9d.

File: transports/quic/tests/smoke.rs (hunk 94 above)
Comment (elenaf9) [reply transports/quic/tests/smoke.rs]: You're right! Added quickcheck usage back in f121350b3b981b8acddd2a82aa15ee8c68cec623.

File: transports/quic/src/transport.rs (hunk 121 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Changed it in fdca477c381a71cd8c52be341c3f74bdc8fd0198 to return an error here.

File: transports/quic/src/endpoint.rs (hunk 58 above)
Comment (marten-seemann) [reply transports/quic/src/endpoint.rs:118]: quic-go, not go-quic ;)

The starting value for the connection window is 768 kB, and we scale it up if needed, up to 15 MB. ([code](https://github.com/libp2p/go-libp2p/blob/63b8803005ecca56db249a636453e19158499957/p2p/transport/quic/transport.go#L41-L52))

File: transports/quic/src/endpoint.rs (hunk 118 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:486]: Do you mean test the case where this should return `None`?
`None` is returned here if we received a packet from an unknown connection and server mode is not enabled (i.e. we are not listening on an address). This is already kinda tested in the `endpoint_reuse` test ([code](https://github.com/kpp/rust-libp2p/blob/82b6a9d078c09ae25bc4fc9bf34c8240783c5431/transports/quic/tests/smoke.rs#L486-L499)), where we check that we can not connect to an endpoint (even if we know the address) if its dial-only. 
Do you think we should still add an extra unit test here?

File: transports/quic/src/transport.rs (hunk 119 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Good idea. Done in b89ef3388a3fbf911ef35f1da9c3c0f43652359e.

File: transports/quic/src/transport.rs (hunk 123 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs:105]: Comment added in 3fa3e9ef635b991a14d49898fd72570eea612594.

File: transports/quic/src/transport.rs (hunk 124 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Doc added in 3fa3e9ef635b991a14d49898fd72570eea612594.

> overriding any port at the ip

Not sure I understand what you mean. It does not overwrite anything in the ip, but instead combines ip and port.

File: transports/quic/src/lib.rs (hunk 72 above)
Comment (elenaf9) [reply transports/quic/src/lib.rs]: Added single error type for both connection and transport, and newtypes for `quinn_proto` errors. See c0b8a55c100346c49b4428dca8642304f6238c5f. Wdyt @thomaseizinger?

File: transports/quic/src/transport.rs (hunk 124 above)
Comment (MarcoPolo) [reply transports/quic/src/transport.rs]: sorry, I must have missed that this just provides the ip address no port. Docs look good

File: transports/quic/src/endpoint.rs (hunk 112 above)
Comment (MarcoPolo) [reply transports/quic/src/endpoint.rs:509]: Dang it's a shame the variants aren't `pub` because at least we can debug assert our understanding of the code.

My worry now isn't about the behavior of quinn is today, but the behavior tomorrow. I'm afraid that this will change and we won't notice because the type didn't change, and then we'll drop critical events and be in inconsistent states that are hard to debug.

I'm not saying we should handle the `NewIdentifiers` case, but is it possible to add a check to make sure we're only dropping datagrams (even if only enabled in debug builds)

File: transports/quic/src/endpoint.rs (hunk 113 above)
Comment (MarcoPolo) [reply transports/quic/src/endpoint.rs]: what about a `debug_assert!`?

I agree we don't want to crash in production here since it's fine to keep going.

File: transports/quic/src/muxer.rs (hunk 115 above)
Comment (MarcoPolo) [reply transports/quic/src/muxer.rs]: ok, I was wondering if we could keep the lock for even shorter (maybe just around the `recv_stream` call, but it seems like even quinn keeps the lock for the whole function: https://github.com/quinn-rs/quinn/blob/main/quinn/src/recv_stream.rs#L246

File: transports/quic/src/endpoint.rs (hunk 118 above)
Comment (MarcoPolo) [reply transports/quic/src/endpoint.rs:486]: hmm I think I meant to put this comment somewhere else, because rereading this my comment doesn't make sense... Sorry for the noise!

File: transports/quic/src/transport.rs [hunk 125]
```diff
@@ -0,0 +1,704 @@
...
+                if l.is_closed {
+                    return false;
+                }
+                let listen_addr = l.endpoint_channel.socket_addr();
+                SocketFamily::is_same(&listen_addr.ip(), &socket_addr.ip())
+                    && listen_addr.ip().is_loopback() == socket_addr.ip().is_loopback()
+            })
+            .collect::<Vec<_>>();
+
+        let dialing = if !listeners.is_empty() {
```
Comment (MarcoPolo) [inline transports/quic/src/transport.rs]: Minor nit, but we may want to fast path the (probably?) common case of a single listener.

File: transports/quic/src/transport.rs (hunk 120 above)
Comment (MarcoPolo) [reply transports/quic/src/transport.rs:97]: We don't. I think this is fine for now (no test needed here) but probably something that would be nice to have in the future.

(in reference to: https://github.com/libp2p/rust-libp2p/pull/2289#discussion_r988509028)

File: transports/quic/src/connection.rs [hunk 126]
```diff
@@ -285,27 +256,67 @@ impl Connection {
...
-                    Ok(ConnectionEvent::ConnectionLost(reason)) => {
-                        // Continue in the loop once more so that we can send a
-                        // `EndpointEvent::drained` to the endpoint before returning.
-                        closed = Some(reason);
-                        continue;
-                    }
-                    Ok(event) => return Poll::Ready(event),
-                    Err(_) => unreachable!("We don't use datagrams or unidirectional streams."),
-                }
+                let event = self.parse_connection_event(ev);
```
Comment (MarcoPolo) [inline transports/quic/src/connection.rs]: minor nit: I think I had a slight preference for the `From` trait. You can still do this with tuples: https://gist.github.com/MarcoPolo/19d25b8877a35a2f87f39dd1bdd9c325. The advantage is that the from function doesn't take `self` so the arguments are more precise to what's happening.

File: transports/quic/tests/smoke.rs [hunk 127]
```diff
@@ -0,0 +1,570 @@
...
+        QuickCheck::new().quickcheck(prop::<quic::tokio::Provider> as fn(_, _) -> _);
+    }
+
+    #[cfg(feature = "async-std")]
+    QuickCheck::new().quickcheck(prop::<quic::async_std::Provider> as fn(_, _) -> _);
+}
+
+#[cfg(feature = "tokio")]
+#[tokio::test]
+async fn endpoint_reuse() {
```
Comment (MarcoPolo) [inline transports/quic/tests/smoke.rs]: Can we add a test where peer A fails to dial peer B because it uses the wrong peer id? This works, but since it relies on new codepaths (the tls stuff) we should assert that we fail to dial a wrong peer.

File: transports/quic/src/endpoint.rs (hunk 49 above)
Comment (MarcoPolo) [reply transports/quic/src/endpoint.rs:411]: Can we capture this as an issue? I think this is important to not forget.

File: transports/quic/src/muxer.rs [hunk 128]
```diff
@@ -254,12 +276,9 @@ impl AsyncRead for Substream {
         let mut bytes = 0;
         let mut pending = false;
         loop {
-            if buf.is_empty() {
-                break;
-            }
             let chunk = match chunks.next(buf.len()) {
```
Comment (MarcoPolo) [inline transports/quic/src/muxer.rs]: This means that whenever you finish filling your buffer you are always going to make another function call to chunks.next(0) just to see that there are no chunks available. 

The old code of breaking early when the buf is empty seems preferable since you are probably going to often hit this case.

cc @thomaseizinger since they suggested the match guard.

**Review by MarcoPolo — APPROVED** [review]
Mostly minor comments! Feel free to capture those into issues and tackle in a future PR. Nice work :)

File: transports/quic/src/muxer.rs (hunk 128 above)
Comment (thomaseizinger) [reply transports/quic/src/muxer.rs]: > probably going to often hit this case.

Really? Most protocols will wrap the substream in some kind of `Framed` to parse chunks of bytes as messages, which means whatever buffer they have needs to be at least large enough to hold one message, parse it and clear the buffer again.

I've not measured it but my intuition would have been that the common case will be that we are out of chunks and not that the buffer is full.

I don't really mind much which way we are coding this, if you feel strongly about the other style, I am happy with it too. IMO, we ideally upstream a change to `quinn` to return `None` instead of a zero-sized chunk.

Comment (thomaseizinger) [reply transports/quic/src/muxer.rs]: Actually, after reading the code again, I think `Ok(None)` here means that the stream is finished: https://github.com/quinn-rs/quinn/blob/3a2558258034e60989bbc199d4d8b0b7297ee269/quinn-proto/src/connection/streams/recv.rs#L239-L280

Should we handle this separately? Effectively, we will return `Ok(0)` here with how the control flow is currently set up so it may not matter.

Comment (MarcoPolo) [reply transports/quic/src/muxer.rs]: > Really? Most protocols will wrap the substream in some kind of `Framed` to parse chunks of bytes as messages, which means whatever buffer they have needs to be at least large enough to hold one message, parse it and clear the buffer again.

That's a good point! I guess it's not obvious we're often hitting this case. I made a quick hack to see how often the smoke tests hit this (it's used length prefixed data): https://gist.github.com/MarcoPolo/8b04abc59e3b0b03a1bee9490d296fb7.

Here's the result:

```
❯ cargo test --test smoke --features async-std -- --nocapture --test async_std_smoke
...
running 1 test
Found empty buf. Times: 1 out of 1. (loop run: 2)
Found empty buf. Times: 2 out of 2. (loop run: 2)
...
Found empty buf. Times: 28 out of 41. (loop run: 2)
test async_std_smoke ... ok
```

I omitted some lines, but 28 out of the 41 times we called this function ended with us seeing an empty buf. This seems surprising to me for the reason you bring up. And I haven't looked into this further, but my guess is if there is exactly N bytes left and you know you are reading N bytes and you [allocate a buf of N bytes](https://github.com/kpp/rust-libp2p/blob/master/core/src/upgrade/transfer.rs#L123), then you'll fill it up and will get an empty buf on the next loop.

If the protocol takes care of reusing buffers that are bigger than the expected bytes you need to read, you won't hit this. But it seems like in this one experiment we hit it pretty often.

Comment (thomaseizinger) [reply transports/quic/src/muxer.rs]: Nice investigation!

Happy for it to go back to the old implementation.

File: transports/quic/src/muxer.rs [hunk 129]
```diff
@@ -0,0 +1,381 @@
...
+            }
+        };
+        let mut bytes = 0;
+        let mut pending = false;
+        loop {
+            let chunk = match chunks.next(buf.len()) {
+                Ok(Some(chunk)) if !chunk.bytes.is_empty() => chunk,
+                Ok(_) => break,
+                Err(err @ quinn_proto::ReadError::Reset(_)) => {
+                    return Poll::Ready(Err(io::Error::new(io::ErrorKind::ConnectionReset, err)))
```
Comment (thomaseizinger) [inline transports/quic/src/muxer.rs]: Should we call `buf.clear()` here? Connection resets typically mean that anything we received can be considered garbage.

File: transports/quic/src/transport.rs (hunk 120 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs:97]: Added tests for this in 2eafbe6d430534ee3f0275b02209768375519ec5 and c33d17f370923f0675eee2ff9434eb28f7d35f15.

File: transports/quic/src/endpoint.rs (hunk 113 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Good idea. Added in 1f83766.

File: transports/quic/src/endpoint.rs (hunk 112 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:509]: I completely agree. I am also not happy about how it is right now, but the API currently does not give us any information about the event. Added a debug message for now, but to properly solve this long-term we could propose an method upstream `ConnectionEvent::is_datagram_event`, and `debug_assert!` that then. Will write it down to the tracking issue.

File: transports/quic/src/transport.rs (hunk 125 above)
Comment (elenaf9) [reply transports/quic/src/transport.rs]: Done in 6af111627576954b289805bf40657940305e442c. Wdyt?

File: transports/quic/src/endpoint.rs (hunk 49 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:411]: I think this PR won't be merged before #2945 is merged.

File: transports/quic/src/endpoint.rs (hunk 104 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Do you mean by shrinking the `MAX_DATA` that the remote can send us? 

(As noted on other comments, this doc is outdated anyway. We do drop UDP packets now if a connection is too busy).

File: transports/quic/tests/smoke.rs (hunk 127 above)
Comment (elenaf9) [reply transports/quic/tests/smoke.rs]: Done in 3b0bd06c9d3355cecd9078a359428fad1d216177.

File: transports/quic/src/endpoint.rs (hunk 104 above)
Comment (marten-seemann) [reply transports/quic/src/endpoint.rs]: > Do you mean by shrinking the MAX_DATA that the remote can send us?

MAX_DATA can't be taken back, once it's issued. It can only ever be increased. Also keep in mind that anything you do takes 1 RTT to take effect.

I don't understand why dropping UDP packets is not safe. In theory (not sure if quinn allows it), you can associate packets with their respective QUIC connection by just parsing the CID and doing a lookup in your connection map. 
I would expect that you don't need any general UDP packet queue here: You read UDP datagrams from the socket, parse their CID (which is _very cheap_), and put them into the queues of their respective QUIC connections. It makes sense that those queues would overflow, if a connection is particularly slow at processing these packets. This would translate into a congestion control signal for the sender, leading to a reduction in the send rate.

File: transports/quic/src/endpoint.rs (hunk 45 above)
Comment (marten-seemann) [reply transports/quic/src/endpoint.rs]: Why is the keep alive period 10ms? That would lead to a keep alive packet to be sent every 10ms. Should this be O(10s) instead? In go-libp2p, we use 15s.

File: transports/quic/src/endpoint.rs (hunk 112 above)
Comment (thomaseizinger) [reply transports/quic/src/endpoint.rs:509]: It is a bit hacky but you could `Debug` print the event and assert that it is the Datagram variant with "string contains" 😁

Comment (thomaseizinger) [reply transports/quic/src/endpoint.rs:509]: If you do it all within the `debug_assert!` macro, it won't be compiled in for production so it is zero-cost there :)

File: transports/quic/src/connection.rs (hunk 126 above)
Comment (elenaf9) [reply transports/quic/src/connection.rs]: Obsolete now since following the discussions in kpp#25 and kpp#26 `connection` and `muxer` were merged.

**Comment by elenaf9** [comment]
> Whilst reviewing / working on this, I've found the terminology and file structure a bit hard to understand and inconsistent with what we use in other crates.
> 
> It might be controversial so I pushed it to my own fork for now: [kpp#25](https://github.com/kpp/rust-libp2p/pull/25)
> 
> The gist of it is:
> 
>  -  Rename `Connection` to `State` to showcase that it represents a state machine
> 
>  - Rename `QuicMuxer` to `Connection`: For the rest of rust-libp2p, the muxer instance _is_ the connection
> 
>  - Add a `connection` sub directory

Thanks for the suggestion @thomaseizinger!
For the record: the most recent commits somewhat follow this suggestion by merging `Connection` and `QuicMuxer`, adding a shared `State`, and a `connection` subdirectory. See kpp#25 and kpp#26 for the related discussion.

File: transports/quic/src/muxer.rs (hunk 129 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: We are transparent about the connection reset, so I would leave it up to the application / caller to decide what to do with the bytes received thus far.

File: transports/quic/src/endpoint.rs (hunk 45 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: > Why is the keep alive period 10ms? That would lead to a keep alive packet to be sent every 10ms. Should this be O(10s) instead? In go-libp2p, we use 15s.

The code that this thread was started on is outdated by now. 2264ab8 included setting the keep-alive to 15s.

File: transports/quic/src/endpoint.rs (hunk 58 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:118]: Discussed out of band with @marten-seemann: 4cad0803d270bf3e93104ef723e5b94016c475f9 sets the receive window for a connection to 15MB and for streams to 10MB.

File: transports/quic/src/endpoint.rs (hunk 104 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: > > Do you mean by shrinking the MAX_DATA that the remote can send us?
>
> MAX_DATA can't be taken back, once it's issued. It can only ever be increased. Also keep in mind that anything you do takes 1 RTT to take effect.

Ah yes you are right.

---

Discussed out of band with @MarcoPolo and @marten-seemann. As mentioned before we do drop the packets if a channel to a connection is full, which is the best way to solve this issue.

File: transports/quic/src/muxer.rs (hunk 128 above)
Comment (elenaf9) [reply transports/quic/src/muxer.rs]: > Actually, after reading the code again, I think `Ok(None)` here means that the stream is finished: https://github.com/quinn-rs/quinn/blob/3a2558258034e60989bbc199d4d8b0b7297ee269/quinn-proto/src/connection/streams/recv.rs#L239-L280
> 
> Should we handle this separately? Effectively, we will return `Ok(0)` here with how the control flow is currently set up so it may not matter.

I think `Ok(None)` can also be returned after we have already iterated through the loop at least once and filled our buffer, in which case we return `Ok` with the bytes read in those previous iterations.  
Is that what you meant or did I misunderstand your point?

---

Thanks for the investigation @MarcoPolo! Went back to the old implementation and added an extra comment: a38f0e95afc3edc0e9f1ba4003dac52024911289. Edit: comment was wrong, fixed in 3725f5fbfeda813f90fc746ac624f46d7063b64e.

File: transports/quic/src/endpoint.rs (hunk 112 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs:509]: Definitely hacky :D but I am not able to come up with a better solution and it's still better than nothing. Added in 445a2a4102f38b80916d0d5667305668d282e419.

File: transports/quic/src/connection.rs [hunk 130]
```diff
@@ -257,63 +200,168 @@ impl Connection {
...
+                .connection
+                .close(Instant::now(), From::from(0u32), Default::default())
+        }
+        drop(inner);
+
+        loop {
+            match ready!(self.poll_event(cx)) {
+                Some(quinn_proto::Event::ConnectionLost { .. }) => return Poll::Ready(Ok(())),
+                None => return Poll::Ready(Err(Error::EndpointDriverCrashed)),
+                _ => {}
```
Comment (MarcoPolo) [inline transports/quic/src/connection.rs:383]: Should we put an `unreachable!` here if we never expect this case? I'm afraid that if we for some reason hit this case in the future we will eternally busy loop.

Also do we not have to worry about `Stream(_)` events?

**Review by MarcoPolo — APPROVED** [review]
One question, but otherwise this looks great! Let's chat in person to talk through the back pressure mechanics.

File: transports/quic/src/connection.rs (hunk 130 above)
Comment (MarcoPolo) [reply transports/quic/src/connection.rs:383]: I misunderstood. It's not that we don't expect this case, it's that we don't care about this case and it's safe to drop.

We don't worry about `Stream(_)` events so we drop them.

Comment (thomaseizinger) [reply transports/quic/src/connection.rs:383]: This could be made more explicit with `mem::drop` but I am not sure it is worth it :)

File: transports/quic/src/endpoint.rs (hunk 43 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Updated docs in c8b794a91531d46db5f13ba53bf735a44b8bdaf4.

File: transports/quic/src/endpoint.rs (hunk 65 above)
Comment (elenaf9) [reply transports/quic/src/endpoint.rs]: Wdyt of bbe736fe92be5561c7e0e184133671eb5c7b5aca?

**Comment by elenaf9** [comment]
Thank you for the great reviews @MarcoPolo @marten-seemann @thomaseizinger! I believe I addressed all comments, please point out in case I missed anything.

From my side this is only blocked on paritytech/substrate#2945, but otherwise ready for merge. @thomaseizinger @mxinden could I get one last review (and hopefully an approval)? 🙂

File: transports/quic/src/endpoint.rs [hunk 131]
```diff
@@ -0,0 +1,641 @@
...
+    /// TLS client config for the inner [`quinn_proto::ClientConfig`].
+    client_tls_config: Arc<rustls::ClientConfig>,
+    /// TLS server config for the inner [`quinn_proto::ServerConfig`].
+    server_tls_config: Arc<rustls::ServerConfig>,
+}
+
+impl Config {
+    /// Creates a new configuration object with default values.
+    pub fn new(keypair: &libp2p_core::identity::Keypair) -> Self {
+        let client_tls_config = Arc::new(libp2p_tls::make_client_config(keypair, None).unwrap());
```
Comment (thomaseizinger) [inline transports/quic/src/endpoint.rs:81]: Originally we added the `None` parameter here to be able to specify the expected `PeerId` and have the handshake fail instead of aborting the connection afterwards on mismatch.

The config is shared here though so we have to set it to `None`. This would require some refactoring to be able to use this feature.

**Review by thomaseizinger — APPROVED** [review]
Let's ship it!

**Comment by elenaf9** [comment]
@kpp I am assuming you don't have any objections merging here?

**Comment by kpp** [comment]
Would you please give me one more day to review and test it?

**Comment by elenaf9** [comment]
> Would you please give me one more day to review and test it?

Sure!

File: transports/quic/src/endpoint.rs (hunk 49 above)
Comment (kpp) [reply transports/quic/src/endpoint.rs:411]: This issue is important. We should mark it as TODO and file an issue to fix it ASAP.

**Review by kpp — COMMENTED** [review]
LGTM. It works, it does not fail in libp2p-perf tests.

**Comment by thomaseizinger** [comment]
I have a few more patches for this locally. Most notable, I am integrating the muxer test suite (which already discovered one bug!).

Furthermore, I think the tests for the QUIC transport should not depend on `Swarm` but test the `Transport` in isolation. For one, this avoids circular dependencies in our repository. Additionally, it raises the question why we have a `wrong_peer_id` test in here. I am in the process of rewriting these tests to only use the QUIC transport itself and this test is not possible to satisfy atm because the transport doesn't validate the `PeerId` at all.

File: transports/quic/src/connection.rs [hunk 132]
```diff
@@ -0,0 +1,423 @@
...
+    ///
+    /// This function assumes that the [`quinn_proto::Connection`] is completely fresh and none of
+    /// its methods has ever been called. Failure to comply might lead to logic errors and panics.
+    pub(crate) fn from_quinn_connection(
+        endpoint_channel: endpoint::Channel,
+        connection: quinn_proto::Connection,
+        connection_id: quinn_proto::ConnectionHandle,
+        from_endpoint: mpsc::Receiver<quinn_proto::ConnectionEvent>,
+    ) -> Self {
+        debug_assert!(!connection.is_closed());
```
Comment (dariusc93) [inline transports/quic/src/connection.rs]: I hit this point at random when doing my testing (not local test so its not easy to reproduce). Will this debug assert remain in place?

Comment (kpp) [reply transports/quic/src/connection.rs]: Oh can you provide your setup? It would be nice for us to write a test and catch this case.

**Comment by mxinden** [comment]
The IPFS exporter on https://kademlia-exporter.max-inden.de is now scraping the IPFS DHT via TCP **and** QUIC using this pull request.

image

(See yellow line at the bottom. Find graph [here](https://kademlia-exporter.max-inden.de/explore?orgId=1&left=%7B%22datasource%22:%22Prometheus%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22libp2p_swarm_connections_incoming_total%7Binstance%3D%5C%22kademlia-exporter-ipfs:8080%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-5m%22,%22to%22:%22now%22%7D%7D).)

(Multiaddr to metric conversion via @john-littlebearlabs from https://github.com/libp2p/rust-libp2p/pull/2982/.)

**Comment by thomaseizinger** [comment]
> I have a few more patches for this locally. Most notable, I am integrating the muxer test suite (which already discovered one bug!).
> 
> Furthermore, I think the tests for the QUIC transport should not depend on `Swarm` but test the `Transport` in isolation. For one, this avoids circular dependencies in our repository. Additionally, it raises the question why we have a `wrong_peer_id` test in here. I am in the process of rewriting these tests to only use the QUIC transport itself and this test is not possible to satisfy atm because the transport doesn't validate the `PeerId` at all.

I've opened a PR here: https://github.com/kpp/rust-libp2p/pull/27

@kpp @elenaf9 Please let me know what you think.

**Review by mxinden — APPROVED** [review]
Only missing pieces from my end:

- Changelog entries
- Co-author lines on squash merge commit

@elenaf9 feel free to merge once @dariusc93 and @thomaseizinger comments above are resolved.

I am excited for this to land!

File: transports/quic/src/connection.rs (hunk 132 above)
Comment (dariusc93) [reply transports/quic/src/connection.rs]: It happens at random when querying (or even bootstrapping) the DHT (either in rust-ipfs or just using libp2p itself with the bootstrap nodes). I would probably need to grab the logs from libp2p and see if that show anything useful before the assert which i can do later on today.

Comment (dariusc93) [reply transports/quic/src/connection.rs]: Sorry for the late response. I did put a small code up on https://github.com/dariusc93/libp2p-quic-test, which will produce that panic at random from that assert. Will be putting providing a log here shortly. 

cc: @kpp

**Comment by kpp** [comment]
`cargo t --features tokio` is broken:

```
error[E0433]: failed to resolve: could not find `async_std` in the crate root
   --> transports/quic/src/transport.rs:724:47
    |
724 |         let mut transport = crate::async_std::Transport::new(config);
    |                                               ^^^^^^^^^ not found in `crate::async_std`
    |
```

Is there a way to build&test CI with a matrix of tokio and async-std for the whole project?

File: transports/quic/src/connection.rs (hunk 132 above)
Comment (dariusc93) [reply transports/quic/src/connection.rs]: @kpp I uploaded the log to https://raw.githubusercontent.com/dariusc93/libp2p-quic-test/master/libp2p-quic-test.log.2022-11-05-01 . The panic seems to happen around when the connection is closed with `EndpointDriverCrashed` 

EDIT: Here is the full backtrace just in case

 ```
 thread 'tokio-runtime-worker' panicked at 'assertion failed: !connection.is_closed()', /home/darius/.cargo/git/checkouts/rust-libp2p-2465c479375e5ed6/58c3f67/transports/quic/src/connection.rs:85:9
stack backtrace:
   0:     0x55ceb2037550 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ceb2037550 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ceb2037550 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55ceb2037550 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55ceb205a00e - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x55ceb2032355 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x55ceb2038d83 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55ceb2038d83 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55ceb2038d83 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x55ceb2038a6f - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x55ceb203942a - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:     0x55ceb20392e1 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
  12:     0x55ceb20379fc - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55ceb2039042 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:     0x55ceb0d951f3 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:     0x55ceb0d950bd - core::panicking::panic::hf0565452d0d0936c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
  16:     0x55ceb12bed71 - libp2p_quic::connection::Connection::from_quinn_connection::h7cb231c41b04b9fe
                               at /home/darius/.cargo/git/checkouts/rust-libp2p-2465c479375e5ed6/58c3f67/transports/quic/src/connection.rs:85:9
  17:     0x55ceb0e9e17f - libp2p_quic::endpoint::Driver<P>::handle_datagram::h1d9e751fd1d7f2be
                               at /home/darius/.cargo/git/checkouts/rust-libp2p-2465c479375e5ed6/58c3f67/transports/quic/src/endpoint.rs:536:21
  18:     0x55ceb0ea0f0b - <libp2p_quic::endpoint::Driver<P> as core::future::future::Future>::poll::h8950de3eb59eb4d1
                               at /home/darius/.cargo/git/checkouts/rust-libp2p-2465c479375e5ed6/58c3f67/transports/quic/src/endpoint.rs:622:27
  19:     0x55ceb0d9f3e7 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h8eb5f639c7eb2830
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
  20:     0x55ceb0ed77d0 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hd912267d66a6e45e
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
  21:     0x55ceb0d9f1b7 - tokio::runtime::task::core::CoreStage<T>::poll::hd7cdf46a67f847be
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
  22:     0x55ceb0e5aef4 - tokio::runtime::task::harness::poll_future::{{closure}}::hd32c105a39396169
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
  23:     0x55ceb10b9e63 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h18d062b962cf5455
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
  24:     0x55ceb105fadd - std::panicking::try::do_call::h9f020b5dbf7ca9d7
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  25:     0x55ceb10613ab - __rust_try
  26:     0x55ceb105e4f5 - std::panicking::try::hb226b44cadf08881
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  27:     0x55ceb0f3f15a - std::panic::catch_unwind::hb5e57a2a74e7fdd6
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  28:     0x55ceb0e59a3d - tokio::runtime::task::harness::poll_future::h306a5c7ba2fc72d3
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
  29:     0x55ceb0e5b343 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h0073b1e8decc1aad
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
  30:     0x55ceb0e5ee23 - tokio::runtime::task::harness::Harness<T,S>::poll::ha5794c1a1d3b18d6
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15
  31:     0x55ceb0e75970 - tokio::runtime::task::raw::poll::ha08e626dd5fced45
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:194:5
  32:     0x55ceb1c1e76f - tokio::runtime::task::raw::RawTask::poll::had35d78cc9758431
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18
  33:     0x55ceb1c11cf2 - tokio::runtime::task::LocalNotified<S>::run::h9928713c2a8906f8
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:385:9
  34:     0x55ceb1c4033c - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h0800eef0a43c64c4
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:421:13
  35:     0x55ceb1bec1a0 - tokio::coop::with_budget::{{closure}}::h56215f3c07b8a38c
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
  36:     0x55ceb1bcbfe3 - std::thread::local::LocalKey<T>::try_with::h7430ca8068df10b6
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:445:16
  37:     0x55ceb1bcb56e - std::thread::local::LocalKey<T>::with::hb6cafa157e4b51af
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:9
  38:     0x55ceb1c40250 - tokio::coop::with_budget::h7ae836e66592bbdd
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:95:5
  39:     0x55ceb1c40250 - tokio::coop::budget::hb7b38349d994b152
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
  40:     0x55ceb1c40250 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h680c0ad819681d7e
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:420:9
  41:     0x55ceb1c3fad6 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h17f397b5df85f57d
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:387:24
  42:     0x55ceb1c3f8bd - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::he12828228d4288aa
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:372:17
  43:     0x55ceb1c58f17 - tokio::macros::scoped_tls::ScopedKey<T>::set::hf0de8d7db3fd8f1b
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/macros/scoped_tls.rs:61:9
  44:     0x55ceb1c3f7fa - tokio::runtime::scheduler::multi_thread::worker::run::h9b497f3c7b1b9b57
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:369:5
  45:     0x55ceb1c3f63b - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::h512caa19dcbabcee
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:348:45
  46:     0x55ceb1c3e513 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h6021e6254e5b92ee
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/task.rs:42:21
  47:     0x55ceb1c1110b - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::ha0c39d9cbcb2caa1
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
  48:     0x55ceb1bd1dd0 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::ha6b2f2737d1e017e
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
  49:     0x55ceb1c11018 - tokio::runtime::task::core::CoreStage<T>::poll::hea0b92624d6d3774
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
  50:     0x55ceb1bd49f8 - tokio::runtime::task::harness::poll_future::{{closure}}::h5b8f982e74c5864c
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
  51:     0x55ceb1c2ae73 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb334f9d6fd32d18d
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
  52:     0x55ceb1c5f46e - std::panicking::try::do_call::h4aac47e9b55bb4b0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  53:     0x55ceb1c6044b - __rust_try
  54:     0x55ceb1c5ef65 - std::panicking::try::hbecc55d6e43c1a8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  55:     0x55ceb1bde0fb - std::panic::catch_unwind::h97721077f867baa9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  56:     0x55ceb1bd441e - tokio::runtime::task::harness::poll_future::h3b55b0db211a1580
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
  57:     0x55ceb1bd29a0 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h8c087ee89c64526f
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
  58:     0x55ceb1bd26f4 - tokio::runtime::task::harness::Harness<T,S>::poll::h19ade99fe488a13d
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15
  59:     0x55ceb1c1e862 - tokio::runtime::task::raw::poll::h4c36bff152904a52
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:194:5
  60:     0x55ceb1c1e76f - tokio::runtime::task::raw::RawTask::poll::had35d78cc9758431
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18
  61:     0x55ceb1c11db4 - tokio::runtime::task::UnownedTask<S>::run::hf4c97c840bf29160
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:422:9
  62:     0x55ceb1c323e7 - tokio::runtime::blocking::pool::Task::run::h618833ff5348fc3c
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:111:9
  63:     0x55ceb1c34afc - tokio::runtime::blocking::pool::Inner::run::h4326ac2e57c707fc
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:346:17
  64:     0x55ceb1c33ef7 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h02568ec3cead840c
                               at /home/darius/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:321:13
  65:     0x55ceb1bcb161 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha5fc8b8a0e3cf2a6
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
  66:     0x55ceb1be6c42 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h5c268812aa9369bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/mod.rs:514:17
  67:     0x55ceb1c2ad72 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h35563faede30c7de
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
  68:     0x55ceb1c5f632 - std::panicking::try::do_call::h758ba7d1b55ac51f
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  69:     0x55ceb1c6044b - __rust_try
  70:     0x55ceb1c5e85f - std::panicking::try::h26c559f4473371ad
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  71:     0x55ceb1bddfc2 - std::panic::catch_unwind::h328f13658c5fbd19
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  72:     0x55ceb1be69ef - std::thread::Builder::spawn_unchecked_::{{closure}}::h0ea66b76d11c12ab
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/mod.rs:513:30
  73:     0x55ceb1c0697f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h31f0350d0a4cff89
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  74:     0x55ceb203c253 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f797984e2121bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  75:     0x55ceb203c253 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4f3d0ee6440e0b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  76:     0x55ceb203c253 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  77:     0x7f580f5498fd - <unknown>
  78:     0x7f580f5cba60 - <unknown>
  79:                0x0 - <unknown>
 ```

Comment (dariusc93) [reply transports/quic/src/connection.rs]: I guess my main question would be is there a point where a connection being closed would be a problem when being passed into `from_quinn_connection`? I can monitor logs with the release profile (which while running havent seen any problems so far with connecting to peers, rather that be locally or over the network), but just curious about the assert there. From what I caught so far from the logs is it happens when the endpoint crash (which happens right after an application error) with only quic, but i guess then why is it when it had a successful connection prior. I could test without relay too or maybe slim down the transport as a means of testing

Comment (kpp) [reply transports/quic/src/connection.rs]: Thank you! I think this is enough info for us to fix the bug.

**Comment by thomaseizinger** [comment]
> `cargo t --features tokio` is broken:
> 
> ```
> error[E0433]: failed to resolve: could not find `async_std` in the crate root
>    --> transports/quic/src/transport.rs:724:47
>     |
> 724 |         let mut transport = crate::async_std::Transport::new(config);
>     |                                               ^^^^^^^^^ not found in `crate::async_std`
>     |
> ```
> 
> Is there a way to build&test CI with a matrix of tokio and async-std for the whole project?

Not at the moment but either after https://github.com/libp2p/rust-libp2p/issues/2951 or together with it, we could introduce it!

**Comment by dariusc93** [comment]
Done a little bit of testing over the last couple of days but something ive noticed is memory usage increasing alot with quic. Its more noticeable while connecting with peers over DHT than with tcp, though with tcp it does happen too, but not as fast in some of my test previous testing (a separate thing imma look into since it began being noticeable since v0.49 so once i get time to check things out more closely i could determine if its my configuration or an issue in libp2p). Not exactly a blocker to this pr though but just something that ive noticed over time.

**Comment by mxinden** [comment]
> Done a little bit of testing over the last couple of days but something ive noticed is memory usage increasing alot with quic. Its more noticeable while connecting with peers over DHT than with tcp, though with tcp it does happen too, but not as fast in some of my test previous testing (a separate thing imma look into since it began being noticeable since v0.49 so once i get time to check things out more closely i could determine if its my configuration or an issue in libp2p).

@dariusc93 thanks for testing. Mind providing more numbers? The above is not very actionable. I suggest to start with number of connections correlated with consumed memory.

>  Not exactly a blocker to this pr though but just something that ive noticed over time.

Agreed. I suggest opening a new issue for it.

**Comment by mxinden** [comment]
With https://github.com/kpp/rust-libp2p/pull/27 merged, this pull request is only blocked on https://github.com/multiformats/rust-multiaddr/pull/64.

File: transports/quic/src/connection.rs (hunk 132 above)
Comment (elenaf9) [reply transports/quic/src/connection.rs]: Thank you for the detailed bug report @dariusc93! Much appreciated. 
I removed the `debug_assert!(!is_closed())` in 7770943. `quinn-proto` sets the state of a new inbound connection directly to `Drained` in some cases (depending on the frames received in the initial packet), `is_closed` is then true. Thus this is not a bug in the implementation, but the assert statement was incorrect. 

> From what I caught so far from the logs is it happens when the endpoint crash (which happens right after an application error) 

The endpoint crash is a result of the `debug_assert` failing since this causes a task (in our case the task driving the endpoint) to panic.

**Comment by elenaf9** [comment]
> Only missing pieces from my end:
> ...
> -  Co-author lines on squash merge commit

I added co-author lines to the "# Commit message body" section of this PR. 
If I understand it correctly this will add them to the squash merge commit @thomaseizinger? I might still merge manually though, but in that case those would be the co-authors that I include. Since @kpp is the author of the PR I think I don't have to add an extra line for him, right? 
Let me know in case I missed anybody!

**Comment by thomaseizinger** [comment]
> > Only missing pieces from my end:
> > ...
> > -  Co-author lines on squash merge commit
> 
> I added co-author lines to the "# Commit message body" section of this PR. 
> If I understand it correctly this will add them to the squash merge commit @thomaseizinger?

Correct. See https://github.com/libp2p/rust-libp2p/pull/3106 for a recent example and https://github.com/libp2p/rust-libp2p/commit/c32f03c3170a8123cb480ece9aa511a6f9ea6dd5 for the resulting commit!

**Comment by mxinden** [comment]
For the record https://github.com/multiformats/rust-multiaddr/pull/64 has been released with `multiaddr` `v0.16.0`. See https://github.com/multiformats/rust-multiaddr/pull/62.

**Comment by mxinden** [comment]
> > > Only missing pieces from my end:
> > > ...
> > > 
> > > * Co-author lines on squash merge commit
> > 
> > 
> > I added co-author lines to the "# Commit message body" section of this PR.
> > If I understand it correctly this will add them to the squash merge commit @thomaseizinger?
> 
> Correct. See paritytech/substrate#3106 for a recent example and [c32f03c](https://github.com/libp2p/rust-libp2p/commit/c32f03c3170a8123cb480ece9aa511a6f9ea6dd5) for the resulting commit!

Note that this is no longer the case with https://github.com/libp2p/rust-libp2p/pull/3082 merged.

**Comment by thomaseizinger** [comment]
> > > > Only missing pieces from my end:
> > > > ...
> > > > 
> > > > * Co-author lines on squash merge commit
> > > 
> > > 
> > > I added co-author lines to the "# Commit message body" section of this PR.
> > > If I understand it correctly this will add them to the squash merge commit @thomaseizinger?
> > 
> > Correct. See paritytech/substrate#3106 for a recent example and [c32f03c](https://github.com/libp2p/rust-libp2p/commit/c32f03c3170a8123cb480ece9aa511a6f9ea6dd5) for the resulting commit!
> 
> Note that this is no longer the case with https://github.com/libp2p/rust-libp2p/pull/3082 merged.

Yes, needs to be at the end of `## Description` now.

File: transports/quic/src/transport.rs [hunk 133]
```diff
@@ -0,0 +1,780 @@
...
+    let third = match iter.next() {
+        Some(p) => p,
+        None => return false,
+    };
+    let fourth = iter.next();
+    let fifth = iter.next();
+
+    matches!(first, Ip4(_) | Ip6(_) | Dns(_) | Dns4(_) | Dns6(_))
+        && matches!(second, Udp(_))
+        && matches!(third, QuicV1)
```
Comment (elenaf9) [inline transports/quic/src/transport.rs:577]: Right now we only support the new `quic-v1` codepoint. Support for `quic`/ draft-29 will be added in a follow-up PR. See https://github.com/multiformats/multiaddr/issues/145#issuecomment-1309196984 for more info. cc @marten-seemann

**Comment by elenaf9** [comment]
Unless there are any objections I will merge this PR tomorrow :tada:

**Comment by elenaf9** [comment]
:tada: We finally have a QUIC transport. 
Huge thanks to @kpp, @DemiMarie, @thomaseizinger, and everyone else that contributed to this!

**Comment by DemiMarie** [comment]
Glad that I could help @elenaf9!!!
