### PR TITLE
fix(gossipsub): gracefully disable handler on stream errors

### LINKED ISSUE #3690: First outbound stream on WebRTC connection server side times out consistently
## Summary

Using https://github.com/libp2p/universal-connectivity/pull/3, the first outbound substream always timeouts. When using libp2p-gossipsub as the first `NetworkBehaviour` that outbound substream drops the subscribe message to the remote.

```
[2023-03-27T18:00:16Z DEBUG libp2p_gossipsub::handler] Dial upgrade error: Protocol negotiation timeout.
```

## Version
Still need to write a reproducer. Posting here anyways for tracking purposes.

One can build a reproducer on top of https://github.com/libp2p/universal-connectivity/pull/3/commits/a8c18c84e5dcc6a76d22d3ec5bbd4e7af4d3a3d0.

Hacky solution for now is to retry on outbound substream dial upgrade error.

## Would you like to work on fixing this bug?

Maybe

### PR DESCRIPTION
**Pull request by vnermolaev**
## Description

Previously, we closed the entire connection upon receiving too many upgrade errors. This is unnecessarily aggressive. For example, an upgrade error may be caused by the remote dropping a stream during the initial handshake which is completely isolated from other protocols running on the same connection.

Instead of closing the connection, set `KeepAlive::No`.

Related: #3591.
Resolves: #3690.

## Notes & open questions

Few items I'd like to raise.
- Pieces of code such as 
   ```rust
   return Poll::Ready(ConnectionHandlerEvent::Close(...));
   ```
   are replaced with `self.keep_alive = KeepAlive::No` and the error report. Unfortunately, I cannot meaningfully return from the `poll` function because it returns `ConnectionHamdlerEvent` and not an `Option` thereof.
- Pieces of code such as 
   ```rust
   loop {
       ...
       return Poll::Ready(ConnectionHandlerEvent::Close(...));
       ...
   }
   ```
   are replaced with `self.keep_alive = KeepAlive::No` and the error report. Again, it is impossible to return meaningfully; I just `break`; such an approach is also observed in the `poll` function.
   - sometimes errors are reported on the `warn!` level which is inconsistent with the proposed `info!` level

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by vnermolaev** [comment]
@thomaseizinger, Will you please comment on the open questions in the first message?

File: protocols/gossipsub/src/handler.rs [hunk 1]
```diff
@@ -325,7 +325,8 @@ impl ConnectionHandler for Handler {
 
             // If there was a fatal error, close the connection.
             if let Some(error) = reported_error {
-                return Poll::Ready(ConnectionHandlerEvent::Close(error));
+                self.keep_alive = KeepAlive::No;
+                log::info!("Gossipsub error: {error}");
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: I think this indirection is confusing.

We should "handle" the error as soon as possible. Now that we are changing the error handling from returning it to logging, we can do that as soon as the error occurs instead of storing it in a variable (`upgrade_errors`) and delaying the handling.

For the specific state where the protocol is unsupported, we can store only that state and return the specific event within `poll`.

Those that make sense?

File: protocols/gossipsub/src/handler.rs [hunk 2]
```diff
@@ -475,14 +474,14 @@ impl ConnectionHandler for Handler {
                                         Some(OutboundSubstreamState::WaitingOutput(substream));
                                 }
                                 Err(e) => {
-                                    error!("Error sending message: {}", e);
-                                    return Poll::Ready(ConnectionHandlerEvent::Close(e));
+                                    error!("Error sending message: {e}");
+                                    break;
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: I need to think about this in more detail and will come back with something!

File: protocols/gossipsub/src/handler.rs (hunk 1 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: Clear. FYI there are a few places where `reported_error` is set.

Still, it bugs me that there is no return statement. Because further processing seems like extra unnecessary work. This statement applies to all places where `return` is replaced by a report.

File: protocols/gossipsub/src/handler.rs (hunk 2 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: My 5c:
- return `Poll<Option<...>>`. Breaking. Non-viable.
- return `Poll::Ready(ConnectionHandlerEvent::Custom(X))`, not clear what `X` is.
- introduce `NoOp` in `ConnectionHandlerEvent` (to mimic `Option`). Least invasive but adds a variant while another is being removed. 
- an option from a more informed person e.g., you :)

File: protocols/gossipsub/src/handler.rs (hunk 1 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: > Still, it bugs me that there is no return statement. Because further processing seems like extra unnecessary work.

Yes, we shouldn't even be doing any of this if we can just log the error in the callback where we are first encountering it.

The original reason why this variable exists is because we can't do anything in the callback where it happens.

`ConnectionHandler` is a state machine and `poll` "advances" it. Thus, if errors happen in other parts we needed to sort-of buffer them and return them on the next "tick" (i.e. `poll`).

But now that we no longer want to return them (because returning would close the connection), we can get rid of this variable and "buffering".

Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: A decision must be taken on how to return. Please see my other comment [below](https://github.com/libp2p/rust-libp2p/pull/3625#discussion_r1140067178)

**Comment by thomaseizinger** [comment]
Meta-note: Please don't force push, it makes review unnecessarily difficult.

File: protocols/gossipsub/src/handler.rs [hunk 3]
```diff
@@ -291,13 +290,17 @@ impl ConnectionHandler for Handler {
     > {
         // Handle any upgrade errors
         if let Some(error) = self.upgrade_errors.pop_front() {
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Can't we just get rid of this entire field and handle the errors within the callback where they originate?

File: protocols/gossipsub/src/handler.rs [hunk 4]
```diff
@@ -340,9 +305,8 @@ impl ConnectionHandler for Handler {
 
         if self.inbound_substreams_created > MAX_SUBSTREAM_CREATION {
             // Too many inbound substreams have been created, end the connection.
-            return Poll::Ready(ConnectionHandlerEvent::Close(
-                HandlerError::MaxInboundSubstreams,
-            ));
+            self.keep_alive = KeepAlive::No;
+            log::info!("Gossipsub error: {}", HandlerError::MaxInboundSubstreams);
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Lets simplify this to print the entire error and deprecate the variant.

File: protocols/gossipsub/src/handler.rs [hunk 5]
```diff
@@ -351,9 +315,8 @@ impl ConnectionHandler for Handler {
             && !self.outbound_substream_establishing
         {
             if self.outbound_substreams_created >= MAX_SUBSTREAM_CREATION {
-                return Poll::Ready(ConnectionHandlerEvent::Close(
-                    HandlerError::MaxOutboundSubstreams,
-                ));
+                self.keep_alive = KeepAlive::No;
+                log::info!("Gossipsub error: {}", HandlerError::MaxInboundSubstreams);
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Here too. Note that this is also the wrong variant.

File: protocols/gossipsub/src/handler.rs [hunk 6]
```diff
@@ -351,9 +315,8 @@ impl ConnectionHandler for Handler {
             && !self.outbound_substream_establishing
         {
             if self.outbound_substreams_created >= MAX_SUBSTREAM_CREATION {
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: In how many places do we increment `outbound_substreams_created`? Perhaps we can do this earlier as well?

File: protocols/gossipsub/src/handler.rs [hunk 7]
```diff
@@ -475,14 +438,14 @@ impl ConnectionHandler for Handler {
                                         Some(OutboundSubstreamState::WaitingOutput(substream));
                                 }
                                 Err(e) => {
-                                    error!("Error sending message: {}", e);
-                                    return Poll::Ready(ConnectionHandlerEvent::Close(e));
+                                    error!("Error sending message: {e}");
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: `error` is too high a level, let's log these on debug.

Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: I think we also need to set `outbound_substream` to `None` here otherwise we remain in "Poisoned".

File: protocols/gossipsub/src/handler.rs [hunk 8]
```diff
@@ -504,7 +467,8 @@ impl ConnectionHandler for Handler {
                                 Some(OutboundSubstreamState::WaitingOutput(substream))
                         }
                         Poll::Ready(Err(e)) => {
-                            return Poll::Ready(ConnectionHandlerEvent::Close(e))
+                            log::info!("NegotaitedSubstream error: {e}");
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Can we make these according to the function that failed? In this case "flushing". Like "failed to flush outbound stream".

File: protocols/gossipsub/src/handler.rs [hunk 9]
```diff
@@ -571,10 +529,37 @@ impl ConnectionHandler for Handler {
...
+            ConnectionEvent::DialUpgradeError(DialUpgradeError { error, .. }) => {
                 self.outbound_substream_establishing = false;
-                warn!("Dial upgrade error {:?}", e);
-                self.upgrade_errors.push_back(e);
+
+                match error {
+                    // Timeout errors get mapped to NegotiationTimeout and we close the connection.
+                    ConnectionHandlerUpgrErr::Timeout | ConnectionHandlerUpgrErr::Timer => {
+                        self.keep_alive = KeepAlive::No;
+                        log::info!("Dial upgrade error: {}", HandlerError::NegotiationTimeout);
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Here too, no need for the `HandlerError` indirection if we can just log it directly.

File: protocols/gossipsub/src/handler.rs [hunk 10]
```diff
@@ -571,10 +529,37 @@ impl ConnectionHandler for Handler {
...
+                    }
+                    // There was an error post negotiation, close the connection.
+                    ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Apply(e)) => {
+                        self.keep_alive = KeepAlive::No;
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: This isn't fatal, lets not set `keep_alive` here but just log the error.

File: protocols/gossipsub/src/handler.rs [hunk 11]
```diff
@@ -571,10 +529,37 @@ impl ConnectionHandler for Handler {
...
+                    }
+                    ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Select(negotiation_error)) => {
+                        match negotiation_error {
+                            NegotiationError::Failed => {
+                                // The protocol is not supported
+                                self.protocol_unsupported = true;
+                                log::info!("Dial upgrade error: {}", NegotiationError::Failed);
+                            }
+                            NegotiationError::ProtocolError(e) => {
+                                self.keep_alive = KeepAlive::No;
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Same here, lets not set this `No`.

File: protocols/gossipsub/src/handler.rs (hunk 9 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: I think we can deprecate the entire `HandlerError` type.

**Review by thomaseizinger — COMMENTED** [review]
Nice, we are making progress in the right direction here.

File: protocols/gossipsub/src/handler.rs [hunk 12]
```diff
@@ -340,9 +305,8 @@ impl ConnectionHandler for Handler {
 
         if self.inbound_substreams_created > MAX_SUBSTREAM_CREATION {
```
Comment (vnermolaev) [inline protocols/gossipsub/src/handler.rs]: Conditions for inbound and outbound streams vary, i.e.,
`self.inbound_substreams_created > MAX_SUBSTREAM_CREATION` vs
`self.outbound_substreams_created >= MAX_SUBSTREAM_CREATION`.
I am sticking to the latter option.

File: protocols/gossipsub/src/handler.rs (hunk 4 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: addressed

File: protocols/gossipsub/src/handler.rs (hunk 5 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: addressed

File: protocols/gossipsub/src/handler.rs (hunk 7 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: this level has been set before I started working on this PR. So I am not sure which `error`s must be converted to `debug`s. I am doing it for this one.

Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: We can end up with a `Poisoned` stream in multiple places which I have not modified. Just look for the `error`-level logs, `self.outbound_stream` is not set to `None` there.
E.g.
```rust
Poll::Ready(Err(e)) => {
    error!("Outbound substream error while sending output: {e:?}");
    break;
}
```                       
 Do you think I should also update it there?

File: protocols/gossipsub/src/handler.rs (hunk 8 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: addressed

File: protocols/gossipsub/src/handler.rs (hunk 10 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: addressed

File: protocols/gossipsub/src/handler.rs (hunk 11 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: addressed

File: protocols/gossipsub/src/handler.rs (hunk 12 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: I am almost certain this is an oversight so I am in favor of harmonizing.

cc @AgeManning.

File: protocols/gossipsub/src/handler.rs (hunk 9 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: Unfortunately, no. Variants `MaxTransmissionSize` and `Codec` are used when implementing, e.g., `impl<TSocket> InboundUpgrade<TSocket> for ProtocolConfig`.
I have removed other variants.

File: protocols/gossipsub/src/error_priv.rs [hunk 13]
```diff
@@ -89,16 +88,8 @@ impl From<SigningError> for PublishError {
...
-    #[error("The maximum number of inbound substreams created has been exceeded.")]
-    MaxInboundSubstreams,
-    #[error("The maximum number of outbound substreams created has been exceeded.")]
-    MaxOutboundSubstreams,
     #[error("The message exceeds the maximum transmission size.")]
     MaxTransmissionSize,
-    #[error("Protocol negotiation timeout.")]
-    NegotiationTimeout,
-    #[error("Protocol negotiation failed.")]
-    NegotiationProtocolError(ProtocolError),
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/error_priv.rs]: Can we keep these but mark as `deprecated` with a note that it will no longer be emitted? That would allow us to ship it as a patch-release instead of a breaking change.

File: protocols/gossipsub/src/handler.rs [hunk 14]
```diff
@@ -536,11 +545,10 @@ impl ConnectionHandler for Handler {
                     // Timeout errors get mapped to NegotiationTimeout and we close the connection.
                     ConnectionHandlerUpgrErr::Timeout | ConnectionHandlerUpgrErr::Timer => {
                         self.keep_alive = KeepAlive::No;
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: One timeout is not fatal, let's remove this line please.

File: protocols/gossipsub/src/handler.rs [hunk 15]
```diff
@@ -181,6 +181,13 @@ impl Handler {
             <Self as ConnectionHandler>::InboundOpenInfo,
         >,
     ) {
+        if self.inbound_substreams_created == MAX_SUBSTREAM_CREATION {
+            // Too many inbound substreams have been created, end the connection.
+            self.keep_alive = KeepAlive::No;
+            log::info!("Gossipsub error: The maximum number of inbound substreams created has been exceeded.");
+            return;
+        }
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Say we continuously fail to establish inbound streams. This function is only called upon successfully establishing an inbound stream. Thus, we would never set `keep_alive` to `No`, correct?

I think this check (and the one below) needs to be in `on_connection_event`. For `on_fully_negotiated_inbound` and `listen_error` we check the `inbound_substream_created` variable and the equivalent for the other.

Thoughts?

File: protocols/gossipsub/src/handler.rs [hunk 16]
```diff
@@ -181,6 +181,13 @@ impl Handler {
             <Self as ConnectionHandler>::InboundOpenInfo,
         >,
     ) {
+        if self.inbound_substreams_created == MAX_SUBSTREAM_CREATION {
+            // Too many inbound substreams have been created, end the connection.
+            self.keep_alive = KeepAlive::No;
+            log::info!("Gossipsub error: The maximum number of inbound substreams created has been exceeded.");
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]:
```suggestion
            log::info!("The maximum number of inbound substreams created has been exceeded.");
```

Nit: This is already part of the module that is inferred from where we use the macro.

File: protocols/gossipsub/src/handler.rs [hunk 17]
```diff
@@ -571,10 +538,32 @@ impl ConnectionHandler for Handler {
...
+                        match negotiation_error {
+                            NegotiationError::Failed => {
+                                // The protocol is not supported
+                                self.protocol_unsupported = true;
+                                log::info!("Dial upgrade error: {}", NegotiationError::Failed);
+                            }
+                            NegotiationError::ProtocolError(e) => {
+                                log::info!("Gossipsub error: Protocol negotiation failed. {e}");
+                            }
+                        }
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: You can merge this match statement into the outer one and thus reduce one level of indentation.

**Review by thomaseizinger — COMMENTED** [review]
Thanks!

Some more thoughts.

File: protocols/gossipsub/src/error_priv.rs (hunk 13 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/error_priv.rs]: addressed

File: protocols/gossipsub/src/handler.rs (hunk 15 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: Functionally speaking, it only makes a little difference if you look at the code.
However, semantically, these checks are better placed in `on_connection even` indeed.
Moved.

Also, I did not manage to find a place where the counter is _de_ cremented.

File: protocols/gossipsub/src/handler.rs (hunk 17 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: done

File: protocols/gossipsub/src/handler.rs (hunk 14 above)
Comment (vnermolaev) [reply protocols/gossipsub/src/handler.rs]: done

File: protocols/gossipsub/src/handler.rs [hunk 18]
```diff
@@ -475,14 +431,17 @@ impl ConnectionHandler for Handler {
...
+                                    );
+                                    self.outbound_substream = None;
+                                    break;
                                 }
                             }
                         }
                         Poll::Ready(Err(e)) => {
-                            error!("Outbound substream error while sending output: {:?}", e);
-                            return Poll::Ready(ConnectionHandlerEvent::Close(e));
+                            error!("Outbound substream error while sending output: {e:?}");
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Minor consistency alignment.

```suggestion
                            log::debug!("Outbound substream error while sending output: {e}");
```

File: protocols/gossipsub/src/handler.rs [hunk 19]
```diff
@@ -525,14 +485,8 @@ impl ConnectionHandler for Handler {
...
                         Poll::Ready(Err(e)) => {
-                            warn!("Outbound substream error while closing: {:?}", e);
-                            return Poll::Ready(ConnectionHandlerEvent::Close(
-                                io::Error::new(
-                                    io::ErrorKind::BrokenPipe,
-                                    "Failed to close outbound substream",
-                                )
-                                .into(),
-                            ));
+                            warn!("Outbound substream error while closing: {e:?}");
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Same here.

```suggestion
                            log::debug!("Outbound substream error while closing: {e}");
```

File: protocols/gossipsub/src/handler.rs (hunk 7 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: Previously, we returned `ConnectionHandlerEvent::Close` which meant we would never call `poll` again on this handler. This is changing now so we need to update the code accordingly so those state machines are never in poisoned.

File: protocols/gossipsub/src/handler.rs (hunk 15 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: > Functionally speaking, it only makes a little difference if you look at the code.

I don't think I agree. Perhaps the name could be improved but if I understand correctly, the idea here was that we at most _try to create_ `MAX_SUBSTREAM_CREATION` substream. Thus we should check the counter against this upper bound for every successful **and** failed creation of a substream. See the doc comment on the constant.

File: protocols/gossipsub/src/handler.rs [hunk 20]
```diff
@@ -566,15 +520,51 @@ impl ConnectionHandler for Handler {
...
-            ConnectionEvent::DialUpgradeError(DialUpgradeError { error: e, .. }) => {
+            ConnectionEvent::DialUpgradeError(DialUpgradeError { error, .. }) => {
                 self.outbound_substream_establishing = false;
-                warn!("Dial upgrade error {:?}", e);
-                self.upgrade_errors.push_back(e);
+
+                match error {
+                    // Timeout errors get mapped to NegotiationTimeout and we close the connection.
+                    ConnectionHandlerUpgrErr::Timeout | ConnectionHandlerUpgrErr::Timer => {
+                        log::info!("Dial upgrade error: Protocol negotiation timeout.");
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]:
```suggestion
                        log::debug!("Dial upgrade error: Protocol negotiation timeout.");
```

File: protocols/gossipsub/src/handler.rs [hunk 21]
```diff
@@ -566,15 +520,51 @@ impl ConnectionHandler for Handler {
...
+                    }
+                    // There was an error post negotiation, close the connection.
+                    ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Apply(e)) => {
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: This `e` is a `HandlerError` but effectively, the `InboundUpgrade` and `OutboundUpgrade` functions never fail. Can we replace these with `Void` please and use `void::unreachable(e)` here please?

File: protocols/gossipsub/src/handler.rs [hunk 22]
```diff
@@ -566,15 +520,51 @@ impl ConnectionHandler for Handler {
...
+                    ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Select(
+                        NegotiationError::Failed,
+                    )) => {
+                        // The protocol is not supported
+                        self.protocol_unsupported = true;
+                        log::info!("Dial upgrade error: {}", NegotiationError::Failed);
+                    }
+                    ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Select(
+                        NegotiationError::ProtocolError(e),
+                    )) => log::info!("Protocol negotiation failed. {e}"),
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]:
```suggestion
                    )) => log::debug!("Protocol negotiation failed: {e}"),
```

File: protocols/gossipsub/src/handler.rs [hunk 23]
```diff
@@ -566,15 +520,51 @@ impl ConnectionHandler for Handler {
...
+                    // There was an error post negotiation, close the connection.
+                    ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Apply(e)) => {
+                        log::info!("Dial upgrade error: {e}");
+                    }
+                    ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Select(
+                        NegotiationError::Failed,
+                    )) => {
+                        // The protocol is not supported
+                        self.protocol_unsupported = true;
+                        log::info!("Dial upgrade error: {}", NegotiationError::Failed);
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]:
```suggestion
                        log::debug!("The remote peer does not support gossipsub on this connection");
```

File: protocols/gossipsub/src/error_priv.rs [hunk 24]
```diff
@@ -89,14 +89,18 @@ impl From<SigningError> for PublishError {
 /// Errors that can occur in the protocols handler.
 #[derive(Debug, Error)]
 pub enum HandlerError {
+    #[deprecated(note = "This error will not be emitted")]
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/error_priv.rs]:
```suggestion
    #[deprecated(note = "This error will no longer be emitted")]
```

**Review by thomaseizinger — COMMENTED** [review]
Thanks for pushing this forward!

**Comment by vnermolaev** [comment]
I did not expect to make harmonization changes. So in the first commits, I kept the surface as minimal as possible.

**Comment by thomaseizinger** [comment]
> I did not expect to make harmonization changes. So in the first commits, I kept the surface as minimal as possible.

I figured while we are at it, might as well tidy up the code a bit :)

**Review by thomaseizinger — APPROVED** [review]
This is good from my end. I would like @mxinden to also have a look.

File: protocols/gossipsub/src/handler.rs (hunk 12 above)
Comment (AgeManning) [reply protocols/gossipsub/src/handler.rs]: Yeah, looks like an oversight to me

File: protocols/gossipsub/CHANGELOG.md [hunk 25]
```diff
@@ -2,8 +2,11 @@
 
 - Signed messages now use sequential integers in the sequence number field.
   See [PR 3551].
+- Gracefully disable handler on stream errors. Deprecate a few variants of `HandlerError`.
+  See [PR 3625].
 
-[PR 3551]: https://github.com/libp2p/rust-libp2p/pull/3551
+[PR 3551]: https://github.com/libp2p/rust-libp2p/pull/3551git pull
```
Comment (thomaseizinger) [inline protocols/gossipsub/CHANGELOG.md]:
```suggestion
[PR 3551]: https://github.com/libp2p/rust-libp2p/pull/3551
```

File: protocols/gossipsub/src/handler.rs [hunk 26]
```diff
@@ -564,17 +517,65 @@ impl ConnectionHandler for Handler {
...
                 self.on_fully_negotiated_outbound(fully_negotiated_outbound)
             }
-            ConnectionEvent::DialUpgradeError(DialUpgradeError { error: e, .. }) => {
+            ConnectionEvent::DialUpgradeError(DialUpgradeError { error, .. }) => {
                 self.outbound_substream_establishing = false;
-                warn!("Dial upgrade error {:?}", e);
-                self.upgrade_errors.push_back(e);
+
+                match error {
+                    // Timeout errors get mapped to NegotiationTimeout and we close the connection.
```
Comment (mxinden) [inline protocols/gossipsub/src/handler.rs]: Is this still true?

File: protocols/gossipsub/src/handler.rs [hunk 27]
```diff
@@ -564,17 +517,65 @@ impl ConnectionHandler for Handler {
...
+                    ConnectionHandlerUpgrErr::Timeout | ConnectionHandlerUpgrErr::Timer => {
+                        log::debug!("Dial upgrade error: Protocol negotiation timeout.");
+                    }
+                    // There was an error post negotiation, close the connection.
```
Comment (mxinden) [inline protocols/gossipsub/src/handler.rs]: Is this still true?

**Review by mxinden — COMMENTED** [review]
Overall change looks good to me. Thanks for the work.

//CC @divagant-martian and @AgeManning to make sure this does not break any assumptions in lighthouse.

File: protocols/gossipsub/src/handler.rs (hunk 26 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: Seems outdated, nice catch!

File: protocols/gossipsub/src/handler.rs (hunk 27 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: Seems outdated, nice catch!

**Comment by mxinden** [comment]
@p-shahi and @2color this pull request should fix the issue of `libp2p-gossipsub` closing the connection due to an outbound stream upgrade timing out. Note that it does not fix the root cause, namely the outbound stream upgrade timing out. It will only prevent the closing of the connection.

https://github.com/libp2p/universal-connectivity/pull/3

**Comment by thomaseizinger** [comment]
Whoops, fat finger sorry.

@mxinden I addressed your comments and did a few more minor cleanups. Would appreciate if you could have another look. Also, https://github.com/libp2p/universal-connectivity/pull/3 is a good validation that this is the right direction.

File: protocols/gossipsub/CHANGELOG.md (hunk 25 above)
Comment (vnermolaev) [reply protocols/gossipsub/CHANGELOG.md]: yes, this was an accidental focus switch :(

**Review by mxinden — APPROVED** [review]
Great. Thanks for the follow-ups.

Let's give the sigma prime folks a bit more time to comment.

File: protocols/gossipsub/src/handler.rs [hunk 28]
```diff
@@ -470,19 +424,22 @@ impl ConnectionHandler for Handler {
...
+                                    self.outbound_substream = None;
+                                    break;
                                 }
                             }
                         }
                         Poll::Ready(Err(e)) => {
-                            error!("Outbound substream error while sending output: {:?}", e);
-                            return Poll::Ready(ConnectionHandlerEvent::Close(e));
+                            log::debug!("Outbound substream error while sending output: {e}");
+                            break;
```
Comment (AgeManning) [inline protocols/gossipsub/src/handler.rs:352]: I think this leaves the Substream state in the Poisoned state, which is going to cause gossipsub to panic on line 502

File: protocols/gossipsub/src/handler.rs [hunk 29]
```diff
@@ -504,7 +461,8 @@ impl ConnectionHandler for Handler {
                                 Some(OutboundSubstreamState::WaitingOutput(substream))
                         }
                         Poll::Ready(Err(e)) => {
-                            return Poll::Ready(ConnectionHandlerEvent::Close(e))
+                            log::debug!("Outbound substream error while flushing output: {e}");
+                            break;
```
Comment (AgeManning) [inline protocols/gossipsub/src/handler.rs]: Similarly here.

File: protocols/gossipsub/src/handler.rs [hunk 30]
```diff
@@ -525,14 +483,8 @@ impl ConnectionHandler for Handler {
...
-                            warn!("Outbound substream error while closing: {:?}", e);
-                            return Poll::Ready(ConnectionHandlerEvent::Close(
-                                io::Error::new(
-                                    io::ErrorKind::BrokenPipe,
-                                    "Failed to close outbound substream",
-                                )
-                                .into(),
-                            ));
+                            log::debug!("Outbound substream error while closing: {e}");
+                            break;
```
Comment (AgeManning) [inline protocols/gossipsub/src/handler.rs:371]: And here

File: protocols/gossipsub/src/handler.rs [hunk 31]
```diff
@@ -564,17 +516,58 @@ impl ConnectionHandler for Handler {
...
         >,
     ) {
+        if event.is_outbound() {
+            self.outbound_substream_establishing = false;
+        }
+
+        if event.is_inbound() && self.inbound_substreams_created == MAX_SUBSTREAM_CREATION {
+            // Too many inbound substreams have been created, disable the handler.
+            self.keep_alive = KeepAlive::No;
+            log::info!("The maximum number of inbound substreams created has been exceeded.");
```
Comment (AgeManning) [inline protocols/gossipsub/src/handler.rs]: Maybe this should be a warn, error or a crit. In principle this should never happen and we don't want the connection to just end silently

File: protocols/gossipsub/src/handler.rs [hunk 32]
```diff
@@ -564,17 +516,58 @@ impl ConnectionHandler for Handler {
...
             }
-            ConnectionEvent::DialUpgradeError(DialUpgradeError { error: e, .. }) => {
-                self.outbound_substream_establishing = false;
-                warn!("Dial upgrade error {:?}", e);
-                self.upgrade_errors.push_back(e);
+            ConnectionEvent::DialUpgradeError(DialUpgradeError {
+                error: ConnectionHandlerUpgrErr::Timeout | ConnectionHandlerUpgrErr::Timer,
+                ..
+            }) => {
+                log::debug!("Dial upgrade error: Protocol negotiation timeout.");
```
Comment (AgeManning) [inline protocols/gossipsub/src/handler.rs]: We only do the negotiation once to create long-lived substreams. If the negotiation times out, I rarely find it useful to continually re-connect and retry the negotiations, which is why I previously opted to just close the connection. 

If I understand these changes, every message we want to send, we are going to continually try and re-negotiate?

File: protocols/gossipsub/src/handler.rs [hunk 33]
```diff
@@ -564,17 +516,58 @@ impl ConnectionHandler for Handler {
...
+            }
+            ConnectionEvent::DialUpgradeError(DialUpgradeError {
+                error: ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Apply(e)),
+                ..
+            }) => void::unreachable(e),
```
Comment (AgeManning) [inline protocols/gossipsub/src/handler.rs]: Is this for sure unreachable?

File: protocols/gossipsub/src/handler.rs [hunk 34]
```diff
@@ -564,17 +516,58 @@ impl ConnectionHandler for Handler {
             Self::OutboundOpenInfo,
         >,
     ) {
+        if event.is_outbound() {
+            self.outbound_substream_establishing = false;
+        }
+
+        if event.is_inbound() && self.inbound_substreams_created == MAX_SUBSTREAM_CREATION {
```
Comment (AgeManning) [inline protocols/gossipsub/src/handler.rs]: I typically prefer to use `>=` than an `==`. 
Although it shouldn't matter in this current instance, it can be more robust against modifications in the future, for example, someone incrementing inbound_substreams_created in the `poll()`, which causes us to exceed the limit.

File: protocols/gossipsub/src/handler.rs [hunk 35]
```diff
@@ -564,17 +516,58 @@ impl ConnectionHandler for Handler {
...
+            // Too many inbound substreams have been created, disable the handler.
+            self.keep_alive = KeepAlive::No;
+            log::info!("The maximum number of inbound substreams created has been exceeded.");
+            return;
+        }
+
+        if event.is_outbound() && self.outbound_substreams_created == MAX_SUBSTREAM_CREATION {
+            // Too many outbound substreams have been created, disable the handler.
+            self.keep_alive = KeepAlive::No;
+            log::info!("The maximum number of outbound substreams created has been exceeded.");
```
Comment (AgeManning) [inline protocols/gossipsub/src/handler.rs]: Similarly here, I think this should be a warn, error, or crit.

File: protocols/gossipsub/src/handler.rs [hunk 36]
```diff
@@ -564,17 +516,58 @@ impl ConnectionHandler for Handler {
...
+                log::debug!("The remote peer does not support gossipsub on this connection");
+            }
+            ConnectionEvent::DialUpgradeError(DialUpgradeError {
+                error:
+                    ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Select(
+                        NegotiationError::ProtocolError(e),
+                    )),
+                ..
+            }) => {
+                log::debug!("Protocol negotiation failed: {e}")
```
Comment (AgeManning) [inline protocols/gossipsub/src/handler.rs]: Similarly here. ARe we going to constantly try and re-negotiate? I think we should either drop the connection of set KeepAlive to No.

**Review by AgeManning — CHANGES_REQUESTED** [review]
I think we need to be careful when changing the handler, because it can be pretty hard to debug problems we may introduce and can run into panics fairly easily. 

I think this should be tested pretty thoroughly before putting it into a release. 

I haven't really thought through all the intermediate states we could get in when things go wrong but we leave the connection alive. 

It looks like at a first glance some things are missed which currently will cause the code to panic.

**Comment by thomaseizinger** [comment]
Thanks for the review @AgeManning! I'll give the state machines another in-depth look tomorrow.

**Comment by AgeManning** [comment]
All good. Had some more general questions around the approach of KeepAlive vs dropping connections: https://github.com/libp2p/rust-libp2p/issues/3591#issuecomment-1480318632

**Comment by thomaseizinger** [comment]
@vnermolaev Would you be up to auditing those state machines? I might get to it later today but I'd appreciate if you could take a look.

File: protocols/gossipsub/src/handler.rs (hunk 33 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: Yes, proven by the type-system because e is `Void`.

File: protocols/gossipsub/src/handler.rs (hunk 32 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: We can also consider this a "hard error" for gossipsub and immediately disable the handler.

File: protocols/gossipsub/src/handler.rs (hunk 36 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: Up to `MAX_SUBSTREAM_CREATION` times only, then the handler will be set to `KeepAlive::No`.

File: protocols/gossipsub/src/handler.rs (hunk 31 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: The thinking was that `info!` is typically used for a state change (we are disabling the handler). I don't want to wake an ops person at 3am because we are emitting `warn` or `error` here :)

Happy to be convinced otherwise.

File: protocols/gossipsub/src/handler.rs (hunk 32 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: Currently, we'd try `MAX_SUBSTREAM_CREATION` times and then disable the handler.

**Comment by DougAnderson444** [comment]
@thomaseizinger I've patched in this branch as you suggested, but I'm still seeing issues when publishing messages.

Peers can successfully:
- connect
- ping and pong, and 
- subscribe to the dialed server's topic

But when they publish the messages, they generally aren't arriving at the browser peers. The only messages that seem to publish and arrive are those sent from the server to the browser about 140 seconds later.

I'm seeing a lot of substreams dropping, wondering if that has something to do with all the dropped message
```
[INFO libp2p_webrtc::tokio::substream::drop_listener] 
Substream 14 dropped without graceful close, sending Reset     
```

**Comment by thomaseizinger** [comment]
> The only messages that seem to publish and arrive are those sent from the server to the browser about 140 seconds later.

That almost sounds like we are not flushing messages correctly somewhere.

Generally, this branch should primarily fix entire connections being closed which is what I think you saw before right?

**Comment by thomaseizinger** [comment]
Which JS implementation are you using? It is a wild theory but perhaps the two implementations fail to agree on which stream they should be using (gossipsub has a single, long-lived stream), hence they keep establishing new streams but dropping them again after?

**Comment by DougAnderson444** [comment]
> Which JS implementation are you using? 

Using [@libp2p/webrtc@1.0.4](https://www.npmjs.com/package/@libp2p/webrtc/v/1.0.4) over [here](https://github.com/DougAnderson444/rdy2serve/blob/94beaeefbbeea728974118faf08e613c9bd20a05/clients/sveltekit/src/lib/chat/Chat.svelte#L9) using ["/meshsub/1.1.0"](https://github.com/DougAnderson444/rdy2serve/blob/94beaeefbbeea728974118faf08e613c9bd20a05/clients/sveltekit/src/lib/chat/Chat.svelte#L160)

> It is a wild theory but perhaps the two implementations fail to agree on which stream they should be using (gossipsub has a single, long-lived stream), hence they keep establishing new streams but dropping them again after?

Quite possible, I haven't been at this issue long enough to trace both sides line by line.  

The strange thing is, some of the time is works, and when it works... it works pretty well. I'm trying to narrow down the circumstances of when it works, but it's been a moving target for sure.

**Comment by DougAnderson444** [comment]
and the [@chainsafe/libp2p-gossipsub@6.2.0](https://www.npmjs.com/package/@chainsafe/libp2p-gossipsub)

**Comment by DougAnderson444** [comment]
>  establishing new streams but dropping them again after?

Is there a way to identify the streams that is common in both implementations?

Edit: Nevermind, this is definitely happening within rust-gossipsub, somewhere between add subscriber and the upgrade failing due to timeout, see #3665 (sorry to clutter up this pull request, but I know something is still just not right even with the fixes you added)

File: protocols/gossipsub/src/handler.rs (hunk 31 above)
Comment (AgeManning) [reply protocols/gossipsub/src/handler.rs]: Yeah, I'm not all that concerned. I;d be curious to know when to use a warn then. I'd typically use a warn if something has not behaved as it should and is worth notifying a user. 
In this case, we pretty much should never see this log, unless something is pretty broken. I find it handy to grep warn/error etc to find things that are broken. This fits into that classification imo. 

But if other parts of libp2p are not doing it, happy to leave as an info.

File: protocols/gossipsub/src/handler.rs (hunk 32 above)
Comment (AgeManning) [reply protocols/gossipsub/src/handler.rs]: Yep, that seems like reasonable logic. 

If there were another behaviour that had a keepalive::Yes. It would continue to try and reconnect tho right?

**Review by AgeManning — DISMISSED** [review]
Look ok to me now. I think @divagant-martian may be having a look over too soon.

File: protocols/gossipsub/src/handler.rs (hunk 32 above)
Comment (mxinden) [reply protocols/gossipsub/src/handler.rs]: > Currently, we'd try `MAX_SUBSTREAM_CREATION` times and then disable the handler.

I don't think this is correct. We increase `outbound_substream_established` only on successful substream negotiation (i.e. in `on_fully_negotiated_outbound`). The above failure does not increase the counter and thus the limit `MAX_SUBSTREAM_CREATION` is never hit.

File: protocols/gossipsub/src/handler.rs [hunk 37]
```diff
@@ -564,17 +505,58 @@ impl ConnectionHandler for Handler {
...
             }
             ConnectionEvent::FullyNegotiatedOutbound(fully_negotiated_outbound) => {
                 self.on_fully_negotiated_outbound(fully_negotiated_outbound)
             }
-            ConnectionEvent::DialUpgradeError(DialUpgradeError { error: e, .. }) => {
-                self.outbound_substream_establishing = false;
-                warn!("Dial upgrade error {:?}", e);
-                self.upgrade_errors.push_back(e);
+            ConnectionEvent::DialUpgradeError(DialUpgradeError {
+                error: ConnectionHandlerUpgrErr::Timeout | ConnectionHandlerUpgrErr::Timer,
```
Comment (mxinden) [inline protocols/gossipsub/src/handler.rs]: In case we stick with retrying after an outbound substream failed.

```suggestion
                error: ConnectionHandlerUpgrErr::Timeout | ConnectionHandlerUpgrErr::Timer,
                info,
```

I suggest requeuing the RPC into the front of `self.send_queue.push_front(info)`. Otherwise the remote may receive a `GRAFT` before a `SUBSCRIBE`. Related to https://github.com/libp2p/rust-libp2p/issues/3690.

File: protocols/gossipsub/src/handler.rs (hunk 31 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: Why would we never see this log? We would see this if we connect to a node that doesn't support the gossipsub protocol right? Nothing is inherently broken if that happens so I am not sure a `warn` is appropriate.

File: protocols/gossipsub/src/handler.rs (hunk 32 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: > > Currently, we'd try `MAX_SUBSTREAM_CREATION` times and then disable the handler.
> 
> I don't think this is correct. We increase `outbound_substream_established` only on successful substream negotiation (i.e. in `on_fully_negotiated_outbound`). The above failure does not increase the counter and thus the limit `MAX_SUBSTREAM_CREATION` is never hit.

You are totally right, not sure how I missed that. Do we agree that the logic I described is what we want to have?

Comment (mxinden) [reply protocols/gossipsub/src/handler.rs]: > Do we agree that the logic I described is what we want to have?

Agreed in case it includes the re-enqueuing of the RPC of the failed outbound stream. See https://github.com/libp2p/rust-libp2p/pull/3625#discussion_r1150749684.

**Comment by mxinden** [comment]
@thomaseizinger do you have time to work on this pull request today? If not, I will try to apply the above discussed changes to unblock https://github.com/libp2p/universal-connectivity/pull/3.

File: protocols/gossipsub/src/handler.rs (hunk 32 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: Yep I think that makes sense.

**Comment by thomaseizinger** [comment]
> @thomaseizinger do you have time to work on this pull request today? If not, I will try to apply the above discussed changes to unblock [libp2p/universal-connectivity#3](https://github.com/libp2p/universal-connectivity/pull/3).

Please go ahead. I have limited time this week, just trying to catch-up and make sure nobody is blocked.

File: protocols/gossipsub/src/handler.rs (hunk 32 above)
Comment (mxinden) [reply protocols/gossipsub/src/handler.rs]: Tracking the number of requested outbound streams instead of the number of successfully upgraded outbound streams is done with https://github.com/libp2p/rust-libp2p/pull/3625/commits/0507493a1e5232047c8495319e82b00bd80303eb.

File: protocols/gossipsub/src/handler.rs (hunk 37 above)
Comment (mxinden) [reply protocols/gossipsub/src/handler.rs]: Re-enqueuing is done with https://github.com/libp2p/rust-libp2p/pull/3625/commits/b5728952464f570c5636f5e6a4fa2448e28f3cbe.

File: protocols/gossipsub/src/handler.rs (hunk 31 above)
Comment (mxinden) [reply protocols/gossipsub/src/handler.rs]: Agreed that this should rather be a `warn` instead of a `info`.

> Why would we never see this log?

By default `env-logger` does not log on `info` level. I would argue that users should see this by default, thus it should be a level higher than `info` which is `warn`.

> In this case, we pretty much should never see this log, unless something is pretty broken. I find it handy to grep warn/error etc to find things that are broken. This fits into that classification imo.

Agreed.

> We would see this if we connect to a node that doesn't support the gossipsub protocol right?

As far as I can tell a `UpgradeError::Select(NegotiationError::Failed)` would lead to `self.protocol_unsupported = true` and thus a direct disabling (i.e. `self.keep_alive = KeepAlive::No`) in the next `ConnectionHandler::poll` invocation. Thus we would never request another outbound stream and thus the log line above is never printed. Am I missing something @thomaseizinger?

Just to avoid confusion, I am in favor of the above behavior. I don't think there is value in directly requesting another stream in case the remote signaled that it does not support the protocol on the previous stream. Objections?

**Comment by mxinden** [comment]
@DougAnderson444 do you mind testing with the latest two commits? Do you still see the above failures? Note that re-enqueuing is happening after failure only, thus there is a timeout delay of 10s between retries.

**Comment by mxinden** [comment]
This now resolves https://github.com/libp2p/rust-libp2p/issues/3690. Note that https://github.com/libp2p/rust-libp2p/issues/3690 is most likely rooted in `libp2p-webrtc`, though the last commit here makes `libp2p-gossipsub` resilient against the spurious failures.

**Comment by thomaseizinger** [comment]
@mxinden I think I found an even simpler version that doesn't need re-queuing. Let me know what you think. It follows the ideas in https://github.com/libp2p/rust-libp2p/issues/3268.

**Comment by DougAnderson444** [comment]
> @DougAnderson444 do you mind testing with the latest two commits? Do you still see the above failures? Note that re-enqueuing is happening after failure only, thus there is a timeout delay of 10s between retries.

### Versions

Happy to do so! I'm patching using these branches:

```toml
[patch.crates-io]
libp2p = { git = "https://github.com/vnermolaev/rust-libp2p.git", branch = "deprecate/gossipsub-close-event", version = "0.51.2" } # debugging https://github.com/libp2p/rust-libp2p/pull/3625
```

and

```json
"dependencies": {
        "@chainsafe/libp2p-gossipsub": "github:maschad/js-libp2p-gossipsub#fix/add-mesh-peers-to-sub"  
```

### Result

1. ✔️Server and Browser both connect, and Ping fine
2. ✔️Browser seems to be getting the messages published by the serve
3. ❌The server does not get the messages published by the browser. (Although I did get the chat to work **_once_**, it is still usually failing) 

<details><summary>Rust Server Log</summary>

```
[2023-03-29T20:58:05Z DEBUG rdy2serve] > Spawning task for server!
[2023-03-29T20:58:05Z DEBUG rdy2serve] > Send message!
[2023-03-29T20:58:05Z DEBUG libp2p_gossipsub::behaviour] Subscribing to topic: chat
[2023-03-29T20:58:05Z DEBUG libp2p_gossipsub::behaviour] Running JOIN for topic: TopicHash { hash: "chat" }
[2023-03-29T20:58:05Z DEBUG libp2p_gossipsub::behaviour] RANDOM PEERS: Got 0 peers
[2023-03-29T20:58:05Z DEBUG libp2p_gossipsub::behaviour] JOIN: Inserting 0 random peers into the mesh
[2023-03-29T20:58:05Z DEBUG libp2p_gossipsub::behaviour] Completed JOIN for topic: TopicHash { hash: "chat" }
[2023-03-29T20:58:05Z DEBUG libp2p_gossipsub::behaviour] Subscribed to topic: chat
[2023-03-29T20:58:05Z DEBUG rtc_server] Listening on "/ip6/::/udp/0/webrtc-direct"
[2023-03-29T20:58:05Z DEBUG libp2p_swarm] Listener ListenerId(3977904630604207785); New address: "/ip6/2607:fea8:fec0:7337::a129/udp/61239/webrtc-direct/certhash/uEiAIaK1rtpcOhftKv3hePFRsrxQfwgJdL08Rwg0FpN2smQ"
[2023-03-29T20:58:05Z INFO  rtc_server] Listening on /ip6/2607:fea8:fec0:7337::a129/udp/61239/webrtc-direct/certhash/uEiAIaK1rtpcOhftKv3hePFRsrxQfwgJdL08Rwg0FpN2smQ
[2023-03-29T20:58:05Z DEBUG libp2p_swarm] Listener ListenerId(3977904630604207785); New address: "/ip6/2607:fea8:fec0:7337:6b21:9df6:d46e:29d3/udp/61239/webrtc-direct/certhash/uEiAIaK1rtpcOhftKv3hePFRsrxQfwgJdL08Rwg0FpN2smQ"
[2023-03-29T20:58:05Z DEBUG rtc_server] >>>> Setting ADDRESS
[2023-03-29T20:58:05Z DEBUG libp2p_swarm] Listener ListenerId(3977904630604207785); New address: "/ip6/2607:fea8:fec0:7337:d582:cd72:2d27:ddcf/udp/61239/webrtc-direct/certhash/uEiAIaK1rtpcOhftKv3hePFRsrxQfwgJdL08Rwg0FpN2smQ"
[2023-03-29T20:58:05Z DEBUG libp2p_swarm] Listener ListenerId(3977904630604207785); New address: "/ip6/::1/udp/61239/webrtc-direct/certhash/uEiAIaK1rtpcOhftKv3hePFRsrxQfwgJdL08Rwg0FpN2smQ"
[2023-03-29T20:58:05Z INFO  rtc_server] Listening on /ip6/::1/udp/61239/webrtc-direct/certhash/uEiAIaK1rtpcOhftKv3hePFRsrxQfwgJdL08Rwg0FpN2smQ
[2023-03-29T20:58:05Z DEBUG rtc_server] Reply listener spawned
Connect with:
/ip6/2607:fea8:fec0:7337:6b21:9df6:d46e:29d3/udp/61239/webrtc-direct/certhash/uEiAIaK1rtpcOhftKv3hePFRsrxQfwgJdL08Rwg0FpN2smQ/p2p/12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy

*** To Shutdown, use Ctrl + C ***

➡️  Incoming Connection on "/ip6/2607:fea8:fec0:7337:6b21:9df6:d46e:29d3/udp/54724/webrtc-direct"
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] Data channel 0 open
[2023-03-29T20:58:13Z DEBUG libp2p_swarm] Connection established: PeerId("12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw") Listener { local_addr: "/ip6/::/udp/61239/webrtc-direct/certhash/uEiAIaK1rtpcOhftKv3hePFRsrxQfwgJdL08Rwg0FpN2smQ", send_back_addr: "/ip6/2607:fea8:fec0:7337:6b21:9df6:d46e:29d3/udp/54724/webrtc-direct" }; Total (peer): 1.
[2023-03-29T20:58:13Z DEBUG libp2p_gossipsub::behaviour] New peer connected: 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw
✔️  Connection Established to 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw in 274.0693ms on /ip6/2607:fea8:fec0:7337:
6b21:9df6:d46e:29d3/udp/54724/webrtc-direct
[2023-03-29T20:58:13Z DEBUG libp2p_gossipsub::behaviour] Adding explicit peer 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] Data channel 1 open
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] Data channel 3 open
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] Incoming data channel 0
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] Data channel 0 open
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] Incoming data channel 0
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] Data channel 0 open
[2023-03-29T20:58:13Z DEBUG libp2p_gossipsub::behaviour] New peer type found: Gossipsub v1.1 for peer: 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] Incoming data channel 0
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] Data channel 0 open
[2023-03-29T20:58:13Z INFO  libp2p_webrtc::tokio::substream::drop_listener] Substream 4 dropped without graceful close, sending Reset
[2023-03-29T20:58:13Z DEBUG libp2p_webrtc::tokio::connection] a DropListener failed: Stream closed
[2023-03-29T20:58:13Z INFO  libp2p_webrtc::tokio::substream::drop_listener] Substream 2 dropped without graceful close, sending Reset
[2023-03-29T20:58:13Z DEBUG libp2p_gossipsub::behaviour] Handling subscriptions: [Subscription { action: Subscribe, topic_hash: TopicHash { hash: "chat" } }], from source: 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw
[2023-03-29T20:58:13Z DEBUG libp2p_gossipsub::behaviour] SUBSCRIPTION: Adding gossip peer: 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw to topic: TopicHash { hash: "chat" }
💨💨💨  TopicHash { hash: "chat" } Subscriber: 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw
[2023-03-29T20:58:13Z DEBUG rtc_server] ### Number peers: 0 ###
[2023-03-29T20:58:13Z DEBUG libp2p_gossipsub::behaviour] Adding explicit peer 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw
[2023-03-29T20:58:23Z DEBUG libp2p_gossipsub::handler] Dial upgrade error: Protocol negotiation timeout.
[2023-03-29T20:58:23Z INFO  libp2p_webrtc::tokio::substream::drop_listener] Substream 3 dropped without graceful close, sending Reset
[2023-03-29T20:58:23Z DEBUG libp2p_webrtc::tokio::connection] Data channel 5 open
[2023-03-29T20:58:33Z INFO  libp2p_webrtc::tokio::substream::drop_listener] Substream 1 dropped without graceful close, sending Reset
[2023-03-29T20:58:33Z DEBUG libp2p_webrtc::tokio::connection] Data channel 7 open
🏐 Pinged 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw (3.5391ms)
[2023-03-29T20:58:35Z DEBUG libp2p_gossipsub::behaviour] Starting heartbeat
[2023-03-29T20:58:35Z DEBUG libp2p_gossipsub::behaviour] HEARTBEAT: Mesh low. Topic: chat Contains: 0 needs: 2
[2023-03-29T20:58:35Z DEBUG libp2p_gossipsub::behaviour] RANDOM PEERS: Got 0 peers
[2023-03-29T20:58:35Z DEBUG libp2p_gossipsub::behaviour] Updating mesh, new mesh: {}
[2023-03-29T20:58:35Z DEBUG libp2p_gossipsub::behaviour] Completed Heartbeat
[2023-03-29T20:58:43Z DEBUG libp2p_webrtc::tokio::connection] Incoming data channel 0
[2023-03-29T20:58:43Z DEBUG libp2p_webrtc::tokio::connection] Data channel 0 open
🏓 Ponged by 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw
[2023-03-29T20:58:43Z DEBUG libp2p_gossipsub::behaviour] Published message: MessageId(33393432313634353835363635383739333231)[2023-03-29T20:58:43Z INFO  libp2p_webrtc::tokio::substream::drop_listener] Substream 8 dropped without graceful close, sending Reset
[2023-03-29T20:58:43Z DEBUG libp2p_webrtc::tokio::connection] a DropListener failed: Stream closed
🏐 Pinged 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw (3.7088ms)
[2023-03-29T20:59:13Z DEBUG libp2p_webrtc::tokio::connection] Incoming data channel 0
[2023-03-29T20:59:13Z DEBUG libp2p_webrtc::tokio::connection] Data channel 0 open
🏓 Ponged by 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw
[2023-03-29T20:59:13Z DEBUG libp2p_gossipsub::behaviour] Published message: MessageId(31323636313839373139333630393332313336)[2023-03-29T20:59:13Z INFO  libp2p_webrtc::tokio::substream::drop_listener] Substream 10 dropped without graceful close, sending Reset
[2023-03-29T20:59:13Z DEBUG libp2p_webrtc::tokio::connection] a DropListener failed: Stream closed
🏐 Pinged 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw (3.8357ms)
[2023-03-29T20:59:35Z DEBUG libp2p_gossipsub::behaviour] Starting heartbeat
[2023-03-29T20:59:35Z DEBUG libp2p_gossipsub::behaviour] HEARTBEAT: Mesh low. Topic: chat Contains: 0 needs: 2
[2023-03-29T20:59:35Z DEBUG libp2p_gossipsub::behaviour] RANDOM PEERS: Got 0 peers
[2023-03-29T20:59:35Z DEBUG libp2p_gossipsub::behaviour] Updating mesh, new mesh: {}
[2023-03-29T20:59:35Z DEBUG libp2p_gossipsub::behaviour] RANDOM PEERS: Got 0 peers
[2023-03-29T20:59:35Z DEBUG libp2p_gossipsub::behaviour] Gossiping IHAVE to 0 peers.
[2023-03-29T20:59:35Z DEBUG libp2p_gossipsub::behaviour] Completed Heartbeat

```

</details>


<details><summary>Javascript Browser Client Log</summary>

```js
client.ts:19 [vite] connecting...
client.ts:134 [vite] connected.
common.js:113 libp2p:gossipsub starting +0ms
common.js:113 libp2p:gossipsub started +25ms
common.js:113 libp2p:gossipsub JOIN chat +5ms
common.js:113 libp2p:dialer storing multiaddrs 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy +0ms DefaultMultiaddr {bytes: Uint8Array(101), Symbol(@multiformats/js-multiaddr/multiaddr): true}
common.js:113 libp2p:dialer creating dial target for 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy +6ms
common.js:113 libp2p:dialer 1 tokens request, returning 1, 99 remaining +13ms
common.js:113 libp2p:webrtc:transport dialing address - /ip6/2607:fea8:fec0:7337:6b21:9df6:d46e:29d3/udp/61239/webrtc-direct/certhash/uEiAIaK1rtpcOhftKv3hePFRsrxQfwgJdL08Rwg0FpN2smQ/p2p/12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy +0ms
common.js:113 libp2p:dialer token 0 released +376ms
common.js:113 libp2p:dialer dial succeeded to 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy +2ms
common.js:113 libp2p:gossipsub new peer 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy +39s
common.js:113 libp2p:gossipsub create outbound stream 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy +25ms
common.js:113 libp2p:gossipsub send subscriptions to +1ms 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy
common.js:113 libp2p:gossipsub create inbound stream 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy +10s
common.js:113 libp2p:gossipsub rpc.from 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy subscriptions 1 messages 0 ihave 0 iwant 0 graft 0 prune 0 +7ms
common.js:113 libp2p:gossipsub subscription update from 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy topic chat +1ms
Chat.svelte:78 {latency: 30}
common.js:113 libp2p:gossipsub rpc.from 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy subscriptions 0 messages 1 ihave 0 iwant 0 graft 0 prune 0 +20s
Chat.svelte:140 {evt: CustomEvent}
Chat.svelte:144 *** Gossipsub received: 1680123523270317600 Subscriber 12D3KooWBBDBGLKLL66aYRbUcEmUxPwyzGYwFevg331TxXhqhbEw on topic chat, sending replies
Chat.svelte:78 {latency: 21}
common.js:113 libp2p:gossipsub rpc.from 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy subscriptions 0 messages 1 ihave 0 iwant 0 graft 0 prune 0 +30s
Chat.svelte:78 {latency: 22}
common.js:113 libp2p:gossipsub rpc.from 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy subscriptions 0 messages 1 ihave 0 iwant 0 graft 0 prune 0 +30s
Chat.svelte:78 {latency: 24}
common.js:113 libp2p:gossipsub rpc.from 12D3KooWRNJmBsMxfZ3VbbFVyf9VS2yzzuYzMqkMQsAvNE9ucxcy subscriptions 0 messages 1 ihave 0 iwant 0 graft 0 prune 0 +31s

```
</details>

I'm going to hack around the browser side again to see if there is a sequence issue I am missing.  This is getting so close, I can _feel_ the progress.

File: protocols/gossipsub/src/handler.rs (hunk 31 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: Makes sense!

File: swarm/src/handler.rs [hunk 38]
```diff
@@ -212,6 +212,31 @@ pub enum ConnectionEvent<'a, IP: InboundUpgradeSend, OP: OutboundUpgradeSend, IO
...
+        )
+    }
+
+    /// Whether the event concerns an inbound stream.
+    pub fn is_inbound(&self) -> bool {
+        // Note: This will get simpler with https://github.com/libp2p/rust-libp2p/pull/3605.
+        matches!(
+            self,
+            Self::FullyNegotiatedInbound(_)
+                | Self::DialUpgradeError(DialUpgradeError {
```
Comment (thomaseizinger) [inline swarm/src/handler.rs]: Whoops, this needs to be `ListenUpgradeError`!

**Review by thomaseizinger — COMMENTED** [review]
Found one bug at least.

**Comment by mxinden** [comment]
> @mxinden I think I found an even simpler version that doesn't need re-queuing. Let me know what you think. It follows the ideas in #3268.

Neat. The two commits look good to me.

**Comment by DougAnderson444** [comment]
### Result: REAL SUCCESS!

I tried out these latest commits:

✔️ Direct peer chat browser-to-server and back! Round trip.
✔️ Instead of failing 90% of the time, looks like it's `pubsub`'ing 60 - 80% of the time! It definitely works much better now =) 

⚠️ **Note**: Even with these fixes so far, Gossipsub is still a bit buggy (sometimes some of the peers can't receive / publish messages amongst peers) but it's definitely better than before as there usually seems to be at least `1 of n` peers who can connect and publish to the other peers. When this happens, the non-publisher browsers receive the single browser's message through the rust-server, but browsers can't seem to to publish as easily through the same server.  But only _some_ of the time.

Thank you for finding those bugs!

image

**Comment by thomaseizinger** [comment]
@DougAnderson444 I am surprised the last two commits make a difference, they should be functionally identical but good to hear that it is working better now!

File: protocols/gossipsub/CHANGELOG.md [hunk 39]
```diff
@@ -2,8 +2,11 @@
 
 - Signed messages now use sequential integers in the sequence number field.
   See [PR 3551].
+- Gracefully disable handler on stream errors. Deprecate a few variants of `HandlerError`.
+  See [PR 3625].
```
Comment (mxinden) [inline protocols/gossipsub/CHANGELOG.md:6]: Note for ourselves that this needs to move to a new `v0.44.3` section.

Comment (thomaseizinger) [reply protocols/gossipsub/CHANGELOG.md:6]: Done.

File: protocols/gossipsub/src/handler.rs [hunk 40]
```diff
@@ -469,20 +406,19 @@ impl ConnectionHandler for Handler {
...
                                 }
-                                Err(HandlerError::MaxTransmissionSize) => {
-                                    error!("Message exceeded the maximum transmission size and was not sent.");
-                                    self.outbound_substream =
-                                        Some(OutboundSubstreamState::WaitingOutput(substream));
-                                }
                                 Err(e) => {
-                                    error!("Error sending message: {}", e);
-                                    return Poll::Ready(ConnectionHandlerEvent::Close(e));
+                                    log::debug!(
```
Comment (divagant-martian) [inline protocols/gossipsub/src/handler.rs]: The logs for errors on outbound substreams have all been downgraded to `debug` while the inbound ones are kept as `warn`. I would expect the `pub` part of gossipsub to be as important (if not more) as the `sub` part to keep these all as `warn` at least

File: swarm/src/handler.rs [hunk 41]
```diff
@@ -212,6 +212,31 @@ pub enum ConnectionEvent<'a, IP: InboundUpgradeSend, OP: OutboundUpgradeSend, IO
...
+        // Note: This will get simpler with https://github.com/libp2p/rust-libp2p/pull/3605.
+        matches!(
+            self,
+            Self::FullyNegotiatedInbound(_)
+                | Self::ListenUpgradeError(ListenUpgradeError {
+                    error: ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Select(_)), // Only `Select` is relevant, the others may be for other handlers too.
+                    ..
+                })
+        )
+    }
```
Comment (divagant-martian) [inline swarm/src/handler.rs]: Just a minor note here. While `ConnectionEvent` probably has changes not too often, this will be easily missed to be updated if a new variant is added. Personal preference would be to include something closer to a full match

Comment (thomaseizinger) [reply swarm/src/handler.rs]: Fair!

File: protocols/gossipsub/src/handler.rs (hunk 40 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs]: To me, a `warn` always means "Should I wake an ops person at 3am because of this"? Connections can die at any time because somebody e.g. closes their laptop. That is not a reason to wake an ops person IMO, hence I am gonna downgrade the inbound streams to debug instead upgrading the outbound ones to warn.

File: protocols/gossipsub/src/handler.rs [hunk 42]
```diff
@@ -338,28 +295,17 @@ impl ConnectionHandler for Handler {
             }
         }
 
-        if self.inbound_substreams_created > MAX_SUBSTREAM_CREATION {
-            // Too many inbound substreams have been created, end the connection.
-            return Poll::Ready(ConnectionHandlerEvent::Close(
-                HandlerError::MaxInboundSubstreams,
-            ));
-        }
+        // Invariant: `self.inbound_substreams_created < MAX_SUBSTREAM_CREATION`.
```
Comment (mxinden) [inline protocols/gossipsub/src/handler.rs]: How about adding an `assert!` or `debug_assert!` (preference for the former) here?

File: protocols/gossipsub/src/handler.rs [hunk 43]
```diff
@@ -381,25 +327,16 @@ impl ConnectionHandler for Handler {
...
-                                    // peer is still around, they will re-establish their
-                                    // connection
-                                    self.inbound_substream =
-                                        Some(InboundSubstreamState::Closing(substream));
-                                }
-                            }
+                            log::debug!("Failed to read from inbound stream: {error}");
+                            // Close this side of the stream. If the
+                            // peer is still around, they will re-establish their
+                            // connection
```
Comment (mxinden) [inline protocols/gossipsub/src/handler.rs]:
```suggestion
                            // peer is still around, they will re-establish their
                            // outbound stream i.e. our inbound stream.
```

It is not a connection that they reestablish, but a stream, right?

File: swarm/src/handler.rs [hunk 44]
```diff
@@ -212,6 +212,38 @@ pub enum ConnectionEvent<'a, IP: InboundUpgradeSend, OP: OutboundUpgradeSend, IO
     ListenUpgradeError(ListenUpgradeError<IOI, IP>),
 }
 
+impl<'a, IP: InboundUpgradeSend, OP: OutboundUpgradeSend, IOI, OOI>
```
Comment (mxinden) [inline swarm/src/handler.rs:215]: Note that this needs a `libp2p-swarm` version bump and a bump of the `libp2p-swarm` dependency in the `libp2p-gossipsub` `Cargo.toml`.

**Review by mxinden — APPROVED** [review]
3 more comments. Otherwise looks good to me.

File: swarm/src/handler.rs (hunk 44 above)
Comment (thomaseizinger) [reply swarm/src/handler.rs:215]: Right, because we released since we started this :)

File: protocols/gossipsub/src/handler.rs (hunk 42 above)
Comment (mxinden) [reply protocols/gossipsub/src/handler.rs]: Taking a closer look, I don't think this invariant actually holds.

In `on_connection_event` we drop new inbound requests on `==`:

``` rust
        if event.is_inbound() && self.inbound_substreams_created == MAX_SUBSTREAM_CREATION {
            // Too many inbound substreams have been created, disable the handler.
            self.keep_alive = KeepAlive::No;
            log::warn!("The maximum number of inbound substreams created has been exceeded");
            return;
        }
```

Thus `self.inbound_substreams` may never be `>` but it could be `==` and thus the invariant of `<` does not hold.

@thomaseizinger am I missing something?

File: swarm/src/handler.rs (hunk 44 above)
Comment (mxinden) [reply swarm/src/handler.rs:215]: Done in bbdf8f5fb.

File: protocols/gossipsub/src/handler.rs [hunk 45]
```diff
@@ -564,17 +495,58 @@ impl ConnectionHandler for Handler {
...
+            log::warn!("The maximum number of inbound substreams created has been exceeded");
+            return;
+        }
+
+        if event.is_outbound() && self.outbound_substreams_requested == MAX_SUBSTREAM_CREATION {
+            // Too many outbound substreams have been created, disable the handler.
+            self.keep_alive = KeepAlive::No;
+            log::warn!("The maximum number of outbound substreams created has been exceeded");
+            return;
+        }
```
Comment (mxinden) [inline protocols/gossipsub/src/handler.rs]: As far as I can tell there are still multiple issues with this code.

- In case the remote node joins the local nodes mesh (`HandlerIn::JoinedMesh`), `self.keep_alive = KeepAlive::No` will be replaced by `KeepAlive::Yes`, see `on_behaviour_event`. Also in case the remote node leaves the local nodes mesh, `KeepAlive::Until` is set. Though the `ConnectionHandler` will still not be able to establish an outbound stream as `MAX_SUBSTREAM_CREATION` is hit.
- We may still emit `OutboundSubstreamRequest` in `ConnectionHandler::poll` as it does not check `self.outbound_substreams_requested <= MAX_SUBSTREAM_CREATION` first. That leads to wasted stream upgrades as that stream will then be dropped here.

I will have to think about this with a clear mind, i.e. tomorrow. Maybe we should go @thomaseizinger suggested route of modelling all of these states (keep alive, disabling, not supported, ...) as a combined `enum` to reduce the amount of possible state variants at compile time.

**Review by mxinden — DISMISSED** [review]

**Comment by mxinden** [comment]
https://github.com/libp2p/rust-libp2p/pull/3625/commits/f999f3e489ed33d0d13ff612ca853a85df727d99 splits the `Handler` into an `EnabledHandler` and a `DisabledHandler` making many invalid states impossible at compile time. In my eyes this makes it significantly easier to reason about the state of the handler and removes multiple edge cases. E.g. without this patch `send_queue` could have been growing unbounded in case the handler reached `MAX_SUBSTREAM_CREATION` but the gossipsub `NetworkBehaviour` continued pushing messages to the handler.

I know this is yet another large change to this already large pull request. To value everyone's time, @thomaseizinger would you mind taking a look first? Once this looks good to you we can ask for another larger round of reviews from other folks.

File: protocols/gossipsub/src/handler.rs (hunk 45 above)
Comment (mxinden) [reply protocols/gossipsub/src/handler.rs]: See https://github.com/libp2p/rust-libp2p/pull/3625#issuecomment-1498924751 for a potential solution.

File: protocols/gossipsub/src/handler.rs [hunk 46]
```diff
@@ -485,6 +390,90 @@ impl ConnectionHandler for Handler {
...
+            Handler::Enabled(handler) => match message {
+                HandlerIn::Message(m) => handler.send_queue.push(m),
+                HandlerIn::JoinedMesh => {
+                    handler.in_mesh = true;
+                }
+                HandlerIn::LeftMesh => {
+                    handler.in_mesh = false;
+                }
+            },
+            Handler::Disabled(_) => {}
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: Log a `debug` here that we are dropping the message?

File: protocols/gossipsub/src/handler.rs [hunk 47]
```diff
@@ -495,60 +484,83 @@ impl ConnectionHandler for Handler {
...
-            }
-            ConnectionEvent::DialUpgradeError(DialUpgradeError {
-                error:
-                    ConnectionHandlerUpgrErr::Upgrade(UpgradeError::Select(
-                        NegotiationError::ProtocolError(e),
-                    )),
-                ..
-            }) => {
-                log::debug!("Protocol negotiation failed: {e}")
+                match event {
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs:516]: We started adding `transpose` functions to this event such that you can split it directly into an `Either` and can combine things like `Handler::Disabled` and the `unreachable` into one match arm. Might be worth doing here as well.

File: swarm/CHANGELOG.md [hunk 48]
```diff
@@ -1,3 +1,9 @@
+## 0.42.2 - unreleased
+
+- Add `ConnectionEvent::` `is_outbound` and `is_inbound`. See [PR 3625].
```
Comment (thomaseizinger) [inline swarm/CHANGELOG.md]:
```suggestion
- Add `ConnectionEvent::{is_outbound,is_inbound}`. See [PR 3625].
```

File: protocols/gossipsub/src/handler.rs [hunk 49]
```diff
@@ -564,19 +486,81 @@ impl ConnectionHandler for Handler {
...
+
+                if event.is_outbound()
+                    && handler.outbound_substreams_requested == MAX_SUBSTREAM_CREATION
+                {
+                    log::warn!(
+                        "The maximum number of outbound substreams created has been exceeded"
+                    );
+                    *self = Handler::Disabled(DisabledHandler::MaxStreamCreation);
+                    return;
+                }
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: If I understand correctly, than these counters are incremented elsewhere right?

For listening we likely increment them upon successful stream creations, for outbound, we increment them when we request the outbound stream. Two questions:

1. Should we account for failed inbound streams as well?
2. If yes to (1), should we increment these counters here as part of checking `is_inbound` and `is_outbound`?

**Review by thomaseizinger — COMMENTED** [review]
Thank you Max!

**Comment by thomaseizinger** [comment]
> [f999f3e](https://github.com/libp2p/rust-libp2p/commit/f999f3e489ed33d0d13ff612ca853a85df727d99) splits the `Handler` into an `EnabledHandler` and a `DisabledHandler` making many invalid states impossible at compile time. In my eyes this makes it significantly easier to reason about the state of the handler and removes multiple edge cases. E.g. without this patch `send_queue` could have been growing unbounded in case the handler reached `MAX_SUBSTREAM_CREATION` but the gossipsub `NetworkBehaviour` continued pushing messages to the handler.
> 
> I know this is yet another large change to this already large pull request. To value everyone's time, @thomaseizinger would you mind taking a look first? Once this looks good to you we can ask for another larger round of reviews from other folks.

Yes, thank you for doing this. I think this makes a lot of sense. I am liking the direction this is going. Eventually, we might be able to add first-class support for "disabling" a handler to the swarm.

File: protocols/gossipsub/src/handler.rs (hunk 47 above)
Comment (mxinden) [reply protocols/gossipsub/src/handler.rs:516]: Neat! But if I am not mistaken the `transpose` methods are `pub(crate)`. Was that a deliberate choice? If not, mind pushing a commit to this branch @thomaseizinger?

File: protocols/gossipsub/src/handler.rs (hunk 49 above)
Comment (mxinden) [reply protocols/gossipsub/src/handler.rs]: Good idea. Done with 552cb0891.

File: protocols/gossipsub/src/handler.rs (hunk 46 above)
Comment (mxinden) [reply protocols/gossipsub/src/handler.rs]: :+1: b01e86f59

File: protocols/gossipsub/src/handler.rs (hunk 47 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs:516]: Ah interesting. I don't see a reason why they couldn't be public as well. Feel free to make them public.

Comment (mxinden) [reply protocols/gossipsub/src/handler.rs:516]: `libp2p-swarm` implements `transpose` for `    FullyNegotiatedInbound<Either<_, _>>, Either<_, _>>`. Note the second `Either`. In this case both `ProtocolConfig` and `DeniedUpgrade` use a `()` for the `InboundUpgradeInfo`, thus the `libp2p-swarm` `transpose` does not apply.

@thomaseizinger I suggest we proceed here without this change. Fine by you?

Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs:516]: Yep, fine by me.

**Comment by mxinden** [comment]
@thomaseizinger can you give this pull request another review?

File: protocols/gossipsub/src/handler.rs [hunk 50]
```diff
@@ -564,19 +485,83 @@ impl ConnectionHandler for Handler {
...
+                            "The maximum number of inbound substreams attempts has been exceeded"
+                        );
+                        *self = Handler::Disabled(DisabledHandler::MaxSubstreamAttempts);
+                        return;
+                    }
+                }
+
+                if event.is_outbound() {
+                    handler.outbound_substream_establishing = false;
+
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs:504]:
```suggestion
```

File: protocols/gossipsub/src/handler.rs [hunk 51]
```diff
@@ -564,19 +485,83 @@ impl ConnectionHandler for Handler {
...
+                        *self = Handler::Disabled(DisabledHandler::MaxSubstreamAttempts);
+                        return;
+                    }
+                }
+
+                match event {
+                    ConnectionEvent::FullyNegotiatedInbound(FullyNegotiatedInbound {
+                        protocol,
+                        ..
+                    }) => match protocol {
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs:520]: Could flatten this `match` into the outer one.

**Review by thomaseizinger — DISMISSED** [review]
LGTM. Should we extract the changes around `void` and `ConnectionEvent` into separate PRs?

**Comment by thomaseizinger** [comment]
@vnermolaev I am sorry that we hijacked your PR like this :see_no_evil: 

I hope you don't mind. We discovered several issues around handler errors with gossipsub and this PR helped us uncover those. Thanks for kicking it off and I hope it doesn't scare you back from contributing in the future :)

File: protocols/gossipsub/src/handler.rs [hunk 52]
```diff
@@ -554,6 +389,92 @@ impl ConnectionHandler for Handler {
...
+                    OutboundSubstreamState::PendingSend(_, _)
+                    | OutboundSubstreamState::PendingFlush(_),
+                ) = handler.outbound_substream
+                {
+                    return KeepAlive::Yes;
+                }
+
+                KeepAlive::Until(handler.last_io_activity + handler.idle_timeout)
+            }
+            Handler::Disabled(_) => KeepAlive::No,
```
Comment (divagant-martian) [inline protocols/gossipsub/src/handler.rs:448]: I think this way it's possible we don't send the `PeerKind::UnsupportedProtocol` "on time" unless there is some kind of guarantee that poll will be called first **(?)**.  This event is important since we might want to get rid of (ban, or otherwise prevent connections to) this peer if it doesn't support what we need

Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs:448]: A handler is always completed drained of its events first before we even ask whether or not it should be shut down.

Comment (thomaseizinger) [reply protocols/gossipsub/src/handler.rs:448]: See https://github.com/libp2p/rust-libp2p/blob/06ea8cef7ef6d8527fa9fdb9fc23dec88abe2a7b/swarm/src/connection.rs#L216-L303.

Comment (mxinden) [reply protocols/gossipsub/src/handler.rs:448]: Adding to the above, we first "drain" (i.e. `poll`) the `ConnectionHandler` till it returns `Poll::Pending`:

https://github.com/libp2p/rust-libp2p/blob/06ea8cef7ef6d8527fa9fdb9fc23dec88abe2a7b/swarm/src/connection.rs#L231-L247

Only then do we check the `connection_keep_alive` statsu:

https://github.com/libp2p/rust-libp2p/blob/06ea8cef7ef6d8527fa9fdb9fc23dec88abe2a7b/swarm/src/connection.rs#L284-L303

**Comment by mxinden** [comment]
@divagant-martian @AgeManning does either of you mind giving this another review?

**Comment by mxinden** [comment]
@p-shahi with https://github.com/libp2p/rust-libp2p/pull/3765 and https://github.com/libp2p/rust-libp2p/pull/3767 merged into `master` and `master` merged into this pull request, this pull request again should fix all the issues that you are facing on https://github.com/libp2p/universal-connectivity/ with rust-libp2p. Mind updating your fork of rust-libp2p to the latest commit on this branch?

**Review by divagant-martian — APPROVED** [review]
LGTM, management of handler state as an enum seems like a great code quality improvement on top, ty @mxinden

**Comment by mxinden** [comment]
@Mergifyio refresh

**Review by mxinden — APPROVED** [review]

**Comment by dariusc93** [comment]
@mxinden The changelog from this PR may have to get updated since libp2p-gossipsub 0.44.3 didnt include this change before 0.51.3 patch release.
