### PR TITLE
fix: swarm panic while metric collection

### LINKED ISSUE #6153: Metric collection for swarm event panics
### Summary

Calling `record(&SwarmEvent)` panics with the following message:
```
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libp2p-metrics-0.16.0/src/swarm.rs:236:26:
closed connection to previously be established
```

I'm calling `record` on each event I'm getting from `swarm.select_next_some()`.

### Expected behavior

Metrics collection should never panic

### Actual behavior

Panics [here](https://github.com/libp2p/rust-libp2p/blob/1755bca475928ad0e603c42b98c29107c88816cb/misc/metrics/src/swarm.rs#L236): `closed connection to previously be established`

### Relevant log output

<details>
<summary>Logs</summary>

```shell
2025-08-26T09:30:21.043590169Z Swarm event: NewListenAddr { listener_id: ListenerId(1), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.043604165Z Swarm event: NewListenAddr { listener_id: ListenerId(1), address: /ip4/10.233.127.195/udp/12345/quic-v1 }
2025-08-26T09:30:21.044143360Z Swarm event: Behaviour(LogListeners { listeners: [] })
2025-08-26T09:30:21.064841051Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWSRvKpvNbsrGbLXGFZV7GYdcrYNh4W2nipwHHMYikzV58"), connection_id: ConnectionId(1), endpoint: Dialer { address: /dns4/testnet.subsquid.io/udp/22445/quic-v1/p2p/12D3KooWSRvKpvNbsrGbLXGFZV7GYdcrYNh4W2nipwHHMYikzV58, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 21.581685ms }
2025-08-26T09:30:21.066446903Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB"), connection_id: ConnectionId(2), endpoint: Dialer { address: /dns4/testnet.subsquid.io/udp/22446/quic-v1/p2p/12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 23.202546ms }
2025-08-26T09:30:21.079487420Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWSRvKpvNbsrGbLXGFZV7GYdcrYNh4W2nipwHHMYikzV58"), address: /ip4/127.0.0.1/udp/22445/quic-v1 }
2025-08-26T09:30:21.079534649Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWSRvKpvNbsrGbLXGFZV7GYdcrYNh4W2nipwHHMYikzV58"), address: /ip4/10.6.3.21/udp/22445/quic-v1 }
2025-08-26T09:30:21.079552863Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/2489/quic-v1 }
2025-08-26T09:30:21.079922409Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB"), address: /ip4/127.0.0.1/udp/22445/quic-v1 }
2025-08-26T09:30:21.079963176Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB"), address: /ip4/10.6.4.8/udp/22445/quic-v1 }
2025-08-26T09:30:21.079999825Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/65224/quic-v1 }
2025-08-26T09:30:21.604794161Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWQMT5EsPowQHoPaDmCxDnUgnkFGu16DFYgp6xzpj5e3pS")), connection_id: ConnectionId(3) }
2025-08-26T09:30:21.604832092Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWNJUY4VMSmbD8xPwhJn19CB9hHQjJmEhXcEZBWsYuf6DB")), connection_id: ConnectionId(4) }
2025-08-26T09:30:21.606099658Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWEJmVk686ksUCCr6dEKTX6ezSkMZqjLy1ZWasArNM1nbk")), connection_id: ConnectionId(5) }
2025-08-26T09:30:21.630548510Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWNJUY4VMSmbD8xPwhJn19CB9hHQjJmEhXcEZBWsYuf6DB"), connection_id: ConnectionId(4), endpoint: Dialer { address: /ip4/147.78.211.212/udp/12345/quic-v1/p2p/12D3KooWNJUY4VMSmbD8xPwhJn19CB9hHQjJmEhXcEZBWsYuf6DB, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 25.608654ms }
2025-08-26T09:30:21.635188594Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWQMT5EsPowQHoPaDmCxDnUgnkFGu16DFYgp6xzpj5e3pS"), connection_id: ConnectionId(3), endpoint: Dialer { address: /ip4/95.216.66.187/udp/12345/quic-v1/p2p/12D3KooWQMT5EsPowQHoPaDmCxDnUgnkFGu16DFYgp6xzpj5e3pS, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 30.332336ms }
2025-08-26T09:30:21.635782011Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWEJmVk686ksUCCr6dEKTX6ezSkMZqjLy1ZWasArNM1nbk"), connection_id: ConnectionId(5), endpoint: Dialer { address: /ip4/65.108.121.153/udp/12345/quic-v1/p2p/12D3KooWEJmVk686ksUCCr6dEKTX6ezSkMZqjLy1ZWasArNM1nbk, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 29.62815ms }
2025-08-26T09:30:21.656992166Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWNJUY4VMSmbD8xPwhJn19CB9hHQjJmEhXcEZBWsYuf6DB"), address: /ip4/147.78.211.212/udp/12345/quic-v1/p2p/12D3KooWNJUY4VMSmbD8xPwhJn19CB9hHQjJmEhXcEZBWsYuf6DB }
2025-08-26T09:30:21.657036680Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWNJUY4VMSmbD8xPwhJn19CB9hHQjJmEhXcEZBWsYuf6DB"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.657065514Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWNJUY4VMSmbD8xPwhJn19CB9hHQjJmEhXcEZBWsYuf6DB"), address: /ip4/10.171.2.22/udp/12345/quic-v1 }
2025-08-26T09:30:21.657101051Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/13862/quic-v1 }
2025-08-26T09:30:21.665580342Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWEJmVk686ksUCCr6dEKTX6ezSkMZqjLy1ZWasArNM1nbk"), address: /ip4/65.108.121.153/udp/12345/quic-v1 }
2025-08-26T09:30:21.665602444Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWEJmVk686ksUCCr6dEKTX6ezSkMZqjLy1ZWasArNM1nbk"), address: /ip4/172.18.0.2/udp/12345/quic-v1 }
2025-08-26T09:30:21.665636097Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWEJmVk686ksUCCr6dEKTX6ezSkMZqjLy1ZWasArNM1nbk"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.665649602Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/26848/quic-v1 }
2025-08-26T09:30:21.668145350Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQMT5EsPowQHoPaDmCxDnUgnkFGu16DFYgp6xzpj5e3pS"), address: /ip4/95.216.66.187/udp/12345/quic-v1 }
2025-08-26T09:30:21.668190996Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQMT5EsPowQHoPaDmCxDnUgnkFGu16DFYgp6xzpj5e3pS"), address: /ip4/172.23.0.2/udp/12345/quic-v1 }
2025-08-26T09:30:21.668231472Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQMT5EsPowQHoPaDmCxDnUgnkFGu16DFYgp6xzpj5e3pS"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.668269514Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/40996/quic-v1 }
2025-08-26T09:30:21.681174595Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWHKBBGyYU83Jx3eCPCTPbysPe7e6bbVhYtvvHsP6QELfD")), connection_id: ConnectionId(6) }
2025-08-26T09:30:21.694287208Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWM33BK2xQ5XYcdV8gduPXZJHCjkYQmcjZnSbJBkYxuCW2")), connection_id: ConnectionId(7) }
2025-08-26T09:30:21.697273389Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWHKvqRmBizZPwyznsHE7yRaQK1YK9qsDQszGruxK5EXoG")), connection_id: ConnectionId(8) }
2025-08-26T09:30:21.697334374Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooW9yQws9oxjj6aAAKov8zb69ZVj5UEBzFh6sD4srTNfQFb")), connection_id: ConnectionId(9) }
2025-08-26T09:30:21.697396311Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWQvLUZvHZaJow5VorSsGUoCFMyrdCWRJGgEJiy9m1qSnh")), connection_id: ConnectionId(10) }
2025-08-26T09:30:21.697458698Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWEYbv2PZnrjc2dWMwiH7zRP3AWCZLHQETNRtAUbBeh7rt")), connection_id: ConnectionId(11) }
2025-08-26T09:30:21.697518190Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWDYkXwAXTcnbTk9KKsBoNEoiZfEPbM9pAD1EJBHxA54Yg")), connection_id: ConnectionId(12) }
2025-08-26T09:30:21.697571871Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWM5cax5Xom2j2xg4fgatGNKkHndgTvffgC95rHpXLLogs")), connection_id: ConnectionId(13) }
2025-08-26T09:30:21.697630281Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWFfZdwF6Gq3w4K9DBp5iAhpf82R2Wmb1RPP5gDF8HnhfD")), connection_id: ConnectionId(14) }
2025-08-26T09:30:21.697663814Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWG9qAyDQCiLAt5d7faoquE1bWhtCKGDxLnKtBaNPNNF4M")), connection_id: ConnectionId(15) }
2025-08-26T09:30:21.697706605Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWLoJTLWH5FPnLuFMCJE9Ryf3zxivvbhs71jwKp7aER3yg")), connection_id: ConnectionId(16) }
2025-08-26T09:30:21.697757560Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWKwhKrYJMav2JrndFhNWXMDg6bFUXKPxZGAswWE2A55rA")), connection_id: ConnectionId(17) }
2025-08-26T09:30:21.697796414Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWL2K3BrbdwhAFYXe5jD3um6PzGQDr5PBZ8KqfpkWMgFRU")), connection_id: ConnectionId(18) }
2025-08-26T09:30:21.697829726Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWFzpwx3mu75ZWE9kEsn6uiAV7sdAs3p9rYn4nNdHnNDsC")), connection_id: ConnectionId(19) }
2025-08-26T09:30:21.697862939Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWNzVwL5hNfodCWYesNYgfrzq3rFFhZTuquDi2EZvd1Sjy")), connection_id: ConnectionId(20) }
2025-08-26T09:30:21.697906040Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWG6gBg52bNt9Qu1932Nvo2YgT5SPwzyFr94FB55swqBJT")), connection_id: ConnectionId(21) }
2025-08-26T09:30:21.697951536Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWQ6Gcit7HkWxRgMGbdcPGSB1YKFhtPaQHXkSf8ZeGwrP4")), connection_id: ConnectionId(22) }
2025-08-26T09:30:21.698001560Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWR52HYG69STueKjb15rvNodWkP7oVKMhgRbCUCZ9Hw5Hh")), connection_id: ConnectionId(23) }
2025-08-26T09:30:21.698051253Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWCf3NM6WcLya3izvzsMLVT2k2y6Mv1BPNXbwz7xDtZ2xq")), connection_id: ConnectionId(24) }
2025-08-26T09:30:21.698092631Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWLHXNmCkoVLrXwUGVQruSMe779oeo6w4ANVUjx3ygdrjs")), connection_id: ConnectionId(25) }
2025-08-26T09:30:21.711036236Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWHKBBGyYU83Jx3eCPCTPbysPe7e6bbVhYtvvHsP6QELfD"), connection_id: ConnectionId(6), endpoint: Dialer { address: /ip4/65.108.121.153/udp/12349/quic-v1/p2p/12D3KooWHKBBGyYU83Jx3eCPCTPbysPe7e6bbVhYtvvHsP6QELfD, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 29.762554ms }
2025-08-26T09:30:21.711495600Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWM5cax5Xom2j2xg4fgatGNKkHndgTvffgC95rHpXLLogs"), connection_id: ConnectionId(13), endpoint: Dialer { address: /dns4/testnet.subsquid.io/udp/42445/quic-v1/p2p/12D3KooWM5cax5Xom2j2xg4fgatGNKkHndgTvffgC95rHpXLLogs, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 13.855231ms }
2025-08-26T09:30:21.712597174Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWHKvqRmBizZPwyznsHE7yRaQK1YK9qsDQszGruxK5EXoG"), connection_id: ConnectionId(8), endpoint: Dialer { address: /ip4/194.163.153.166/udp/12345/quic-v1/p2p/12D3KooWHKvqRmBizZPwyznsHE7yRaQK1YK9qsDQszGruxK5EXoG, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 15.235679ms }
2025-08-26T09:30:21.712931002Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWCf3NM6WcLya3izvzsMLVT2k2y6Mv1BPNXbwz7xDtZ2xq"), connection_id: ConnectionId(24), endpoint: Dialer { address: /ip4/178.63.105.179/udp/12345/quic-v1/p2p/12D3KooWCf3NM6WcLya3izvzsMLVT2k2y6Mv1BPNXbwz7xDtZ2xq, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 14.83203ms }
2025-08-26T09:30:21.712965417Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWQ6Gcit7HkWxRgMGbdcPGSB1YKFhtPaQHXkSf8ZeGwrP4"), connection_id: ConnectionId(22), endpoint: Dialer { address: /ip4/167.235.114.83/udp/12349/quic-v1/p2p/12D3KooWQ6Gcit7HkWxRgMGbdcPGSB1YKFhtPaQHXkSf8ZeGwrP4, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 14.990708ms }
2025-08-26T09:30:21.723992073Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWR52HYG69STueKjb15rvNodWkP7oVKMhgRbCUCZ9Hw5Hh"), connection_id: ConnectionId(23), endpoint: Dialer { address: /ip4/147.78.211.217/udp/12345/quic-v1/p2p/12D3KooWR52HYG69STueKjb15rvNodWkP7oVKMhgRbCUCZ9Hw5Hh, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 25.925821ms }
2025-08-26T09:30:21.724331903Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWM5cax5Xom2j2xg4fgatGNKkHndgTvffgC95rHpXLLogs"), address: /ip4/10.6.4.7/udp/42445/quic-v1 }
2025-08-26T09:30:21.724359675Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWM5cax5Xom2j2xg4fgatGNKkHndgTvffgC95rHpXLLogs"), address: /dns4/testnet.subsquid.io/udp/42445/quic-v1 }
2025-08-26T09:30:21.724385694Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWM5cax5Xom2j2xg4fgatGNKkHndgTvffgC95rHpXLLogs"), address: /ip4/127.0.0.1/udp/42445/quic-v1 }
2025-08-26T09:30:21.724404680Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/30737/quic-v1 }
2025-08-26T09:30:21.724470984Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWNzVwL5hNfodCWYesNYgfrzq3rFFhZTuquDi2EZvd1Sjy"), connection_id: ConnectionId(20), endpoint: Dialer { address: /ip4/147.78.211.219/udp/12345/quic-v1/p2p/12D3KooWNzVwL5hNfodCWYesNYgfrzq3rFFhZTuquDi2EZvd1Sjy, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 26.56776ms }
2025-08-26T09:30:21.725199025Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWG6gBg52bNt9Qu1932Nvo2YgT5SPwzyFr94FB55swqBJT"), connection_id: ConnectionId(21), endpoint: Dialer { address: /ip4/147.78.211.203/udp/12345/quic-v1/p2p/12D3KooWG6gBg52bNt9Qu1932Nvo2YgT5SPwzyFr94FB55swqBJT, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 27.244343ms }
2025-08-26T09:30:21.725937375Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWLHXNmCkoVLrXwUGVQruSMe779oeo6w4ANVUjx3ygdrjs"), connection_id: ConnectionId(25), endpoint: Dialer { address: /ip4/147.78.211.205/udp/12345/quic-v1/p2p/12D3KooWLHXNmCkoVLrXwUGVQruSMe779oeo6w4ANVUjx3ygdrjs, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 27.792254ms }
2025-08-26T09:30:21.726562301Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWFfZdwF6Gq3w4K9DBp5iAhpf82R2Wmb1RPP5gDF8HnhfD"), connection_id: ConnectionId(14), endpoint: Dialer { address: /ip4/194.163.167.132/udp/12345/quic-v1/p2p/12D3KooWFfZdwF6Gq3w4K9DBp5iAhpf82R2Wmb1RPP5gDF8HnhfD, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 28.853653ms }
2025-08-26T09:30:21.726592167Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWM33BK2xQ5XYcdV8gduPXZJHCjkYQmcjZnSbJBkYxuCW2"), connection_id: ConnectionId(7), endpoint: Dialer { address: /ip4/147.78.211.225/udp/12345/quic-v1/p2p/12D3KooWM33BK2xQ5XYcdV8gduPXZJHCjkYQmcjZnSbJBkYxuCW2, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 32.27879ms }
2025-08-26T09:30:21.727086127Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQ6Gcit7HkWxRgMGbdcPGSB1YKFhtPaQHXkSf8ZeGwrP4"), address: /ip4/172.19.0.2/udp/12349/quic-v1 }
2025-08-26T09:30:21.727092659Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQ6Gcit7HkWxRgMGbdcPGSB1YKFhtPaQHXkSf8ZeGwrP4"), address: /ip4/127.0.0.1/udp/12349/quic-v1 }
2025-08-26T09:30:21.727103219Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQ6Gcit7HkWxRgMGbdcPGSB1YKFhtPaQHXkSf8ZeGwrP4"), address: /ip4/167.235.114.83/udp/12349/quic-v1/p2p/12D3KooWQ6Gcit7HkWxRgMGbdcPGSB1YKFhtPaQHXkSf8ZeGwrP4 }
2025-08-26T09:30:21.727113268Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQ6Gcit7HkWxRgMGbdcPGSB1YKFhtPaQHXkSf8ZeGwrP4"), address:  }
2025-08-26T09:30:21.727120311Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/40921/quic-v1 }
2025-08-26T09:30:21.727167500Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWDYkXwAXTcnbTk9KKsBoNEoiZfEPbM9pAD1EJBHxA54Yg"), connection_id: ConnectionId(12), endpoint: Dialer { address: /ip4/65.108.15.47/udp/12345/quic-v1/p2p/12D3KooWDYkXwAXTcnbTk9KKsBoNEoiZfEPbM9pAD1EJBHxA54Yg, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 29.579138ms }
2025-08-26T09:30:21.727282406Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWCf3NM6WcLya3izvzsMLVT2k2y6Mv1BPNXbwz7xDtZ2xq"), address:  }
2025-08-26T09:30:21.727302184Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWCf3NM6WcLya3izvzsMLVT2k2y6Mv1BPNXbwz7xDtZ2xq"), address: /ip4/172.18.0.2/udp/12345/quic-v1 }
2025-08-26T09:30:21.727323343Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWCf3NM6WcLya3izvzsMLVT2k2y6Mv1BPNXbwz7xDtZ2xq"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.727357468Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWCf3NM6WcLya3izvzsMLVT2k2y6Mv1BPNXbwz7xDtZ2xq"), address: /ip4/178.63.105.179/udp/12345/quic-v1/p2p/12D3KooWCf3NM6WcLya3izvzsMLVT2k2y6Mv1BPNXbwz7xDtZ2xq }
2025-08-26T09:30:21.727371364Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/56876/quic-v1 }
2025-08-26T09:30:21.727423732Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWL2K3BrbdwhAFYXe5jD3um6PzGQDr5PBZ8KqfpkWMgFRU"), connection_id: ConnectionId(18), endpoint: Dialer { address: /ip4/65.108.73.124/udp/12345/quic-v1/p2p/12D3KooWL2K3BrbdwhAFYXe5jD3um6PzGQDr5PBZ8KqfpkWMgFRU, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 29.589848ms }
2025-08-26T09:30:21.728718820Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooW9yQws9oxjj6aAAKov8zb69ZVj5UEBzFh6sD4srTNfQFb"), connection_id: ConnectionId(9), endpoint: Dialer { address: /ip4/147.78.211.221/udp/12345/quic-v1/p2p/12D3KooW9yQws9oxjj6aAAKov8zb69ZVj5UEBzFh6sD4srTNfQFb, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 31.350312ms }
2025-08-26T09:30:21.729144101Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWEYbv2PZnrjc2dWMwiH7zRP3AWCZLHQETNRtAUbBeh7rt"), connection_id: ConnectionId(11), endpoint: Dialer { address: /ip4/147.78.211.210/udp/12345/quic-v1/p2p/12D3KooWEYbv2PZnrjc2dWMwiH7zRP3AWCZLHQETNRtAUbBeh7rt, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 31.63059ms }
2025-08-26T09:30:21.730007106Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWHKvqRmBizZPwyznsHE7yRaQK1YK9qsDQszGruxK5EXoG"), address: /ip4/194.163.153.166/udp/12345/quic-v1 }
2025-08-26T09:30:21.730031742Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWHKvqRmBizZPwyznsHE7yRaQK1YK9qsDQszGruxK5EXoG"), address: /ip4/172.20.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.730073731Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWHKvqRmBizZPwyznsHE7yRaQK1YK9qsDQszGruxK5EXoG"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.730110550Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWHKvqRmBizZPwyznsHE7yRaQK1YK9qsDQszGruxK5EXoG"), address: /ip4/172.17.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.730143913Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWHKvqRmBizZPwyznsHE7yRaQK1YK9qsDQszGruxK5EXoG"), address: /ip4/172.18.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.730161015Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/46472/quic-v1 }
2025-08-26T09:30:21.730315496Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWKwhKrYJMav2JrndFhNWXMDg6bFUXKPxZGAswWE2A55rA"), connection_id: ConnectionId(17), endpoint: Dialer { address: /ip4/147.78.211.204/udp/12345/quic-v1/p2p/12D3KooWKwhKrYJMav2JrndFhNWXMDg6bFUXKPxZGAswWE2A55rA, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 32.513492ms }
2025-08-26T09:30:21.736019172Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWQhZopTFgysUgzpEW1eTj9UPEc9mK2NbEsUQSivbMCLoF")), connection_id: ConnectionId(26) }
2025-08-26T09:30:21.739929643Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWQtAGvDDgxkGmYzHBjofbtBRVP3zu18jJZ711E3YYnoUD")), connection_id: ConnectionId(27) }
2025-08-26T09:30:21.740197918Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWR52LhKYkcK5iDQyXBfnZ3bsUB6q9L8pcsDGxa4faLx7c")), connection_id: ConnectionId(28) }
2025-08-26T09:30:21.740907554Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWHKBBGyYU83Jx3eCPCTPbysPe7e6bbVhYtvvHsP6QELfD"), address: /ip4/172.22.0.2/udp/12349/quic-v1 }
2025-08-26T09:30:21.740932771Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWHKBBGyYU83Jx3eCPCTPbysPe7e6bbVhYtvvHsP6QELfD"), address: /ip4/127.0.0.1/udp/12349/quic-v1 }
2025-08-26T09:30:21.740955594Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWHKBBGyYU83Jx3eCPCTPbysPe7e6bbVhYtvvHsP6QELfD"), address: /ip4/65.108.121.153/udp/12349/quic-v1 }
2025-08-26T09:30:21.740971474Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/9712/quic-v1 }
2025-08-26T09:30:21.744542456Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWLubdDzVZ3UFuTFJVvmwtNwDbeGZC15n6H1FCedtpLPik")), connection_id: ConnectionId(29) }
2025-08-26T09:30:21.747159332Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWG9qAyDQCiLAt5d7faoquE1bWhtCKGDxLnKtBaNPNNF4M"), connection_id: ConnectionId(15), endpoint: Dialer { address: /ip4/62.205.223.79/udp/12346/quic-v1/p2p/12D3KooWG9qAyDQCiLAt5d7faoquE1bWhtCKGDxLnKtBaNPNNF4M, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 49.454992ms }
2025-08-26T09:30:21.747863337Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWFfZdwF6Gq3w4K9DBp5iAhpf82R2Wmb1RPP5gDF8HnhfD"), address:  }
2025-08-26T09:30:21.747905737Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWFfZdwF6Gq3w4K9DBp5iAhpf82R2Wmb1RPP5gDF8HnhfD"), address: /ip4/194.163.167.132/udp/12345/quic-v1/p2p/12D3KooWFfZdwF6Gq3w4K9DBp5iAhpf82R2Wmb1RPP5gDF8HnhfD }
2025-08-26T09:30:21.747928209Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWFfZdwF6Gq3w4K9DBp5iAhpf82R2Wmb1RPP5gDF8HnhfD"), address: /ip4/172.24.0.2/udp/12345/quic-v1 }
2025-08-26T09:30:21.747966100Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWFfZdwF6Gq3w4K9DBp5iAhpf82R2Wmb1RPP5gDF8HnhfD"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.747981930Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/18112/quic-v1 }
2025-08-26T09:30:21.748803396Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWQhZopTFgysUgzpEW1eTj9UPEc9mK2NbEsUQSivbMCLoF"), connection_id: ConnectionId(26), endpoint: Dialer { address: /dns4/testnet.subsquid.io/udp/52445/quic-v1/p2p/12D3KooWQhZopTFgysUgzpEW1eTj9UPEc9mK2NbEsUQSivbMCLoF, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 12.752404ms }
2025-08-26T09:30:21.749980202Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWR52HYG69STueKjb15rvNodWkP7oVKMhgRbCUCZ9Hw5Hh"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.750020177Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWR52HYG69STueKjb15rvNodWkP7oVKMhgRbCUCZ9Hw5Hh"), address: /ip4/147.78.211.217/udp/12345/quic-v1 }
2025-08-26T09:30:21.750068508Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWR52HYG69STueKjb15rvNodWkP7oVKMhgRbCUCZ9Hw5Hh"), address: /ip4/10.171.2.27/udp/12345/quic-v1 }
2025-08-26T09:30:21.750106379Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/54523/quic-v1 }
2025-08-26T09:30:21.751030429Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWNzVwL5hNfodCWYesNYgfrzq3rFFhZTuquDi2EZvd1Sjy"), address: /ip4/147.78.211.219/udp/12345/quic-v1 }
2025-08-26T09:30:21.751064473Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWNzVwL5hNfodCWYesNYgfrzq3rFFhZTuquDi2EZvd1Sjy"), address: /ip4/10.171.2.29/udp/12345/quic-v1 }
2025-08-26T09:30:21.751096954Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWNzVwL5hNfodCWYesNYgfrzq3rFFhZTuquDi2EZvd1Sjy"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.751113395Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/12017/quic-v1 }
2025-08-26T09:30:21.753129891Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWG6gBg52bNt9Qu1932Nvo2YgT5SPwzyFr94FB55swqBJT"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.753147865Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWG6gBg52bNt9Qu1932Nvo2YgT5SPwzyFr94FB55swqBJT"), address: /ip4/147.78.211.203/udp/12345/quic-v1 }
2025-08-26T09:30:21.753187750Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWG6gBg52bNt9Qu1932Nvo2YgT5SPwzyFr94FB55swqBJT"), address: /ip4/10.171.2.13/udp/12345/quic-v1 }
2025-08-26T09:30:21.753203660Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/10130/quic-v1 }
2025-08-26T09:30:21.753475612Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWLHXNmCkoVLrXwUGVQruSMe779oeo6w4ANVUjx3ygdrjs"), address: /ip4/147.78.211.205/udp/12345/quic-v1/p2p/12D3KooWLHXNmCkoVLrXwUGVQruSMe779oeo6w4ANVUjx3ygdrjs }
2025-08-26T09:30:21.753497994Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWLHXNmCkoVLrXwUGVQruSMe779oeo6w4ANVUjx3ygdrjs"), address: /ip4/10.171.2.15/udp/12345/quic-v1 }
2025-08-26T09:30:21.753548920Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWLHXNmCkoVLrXwUGVQruSMe779oeo6w4ANVUjx3ygdrjs"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.753570490Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/44662/quic-v1 }
2025-08-26T09:30:21.756199338Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWDYkXwAXTcnbTk9KKsBoNEoiZfEPbM9pAD1EJBHxA54Yg"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.756222712Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWDYkXwAXTcnbTk9KKsBoNEoiZfEPbM9pAD1EJBHxA54Yg"), address: /ip4/65.108.15.47/udp/12345/quic-v1 }
2025-08-26T09:30:21.756250645Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWDYkXwAXTcnbTk9KKsBoNEoiZfEPbM9pAD1EJBHxA54Yg"), address: /ip4/192.168.128.2/udp/12345/quic-v1 }
2025-08-26T09:30:21.756269801Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/32673/quic-v1 }
2025-08-26T09:30:21.756488262Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWL2K3BrbdwhAFYXe5jD3um6PzGQDr5PBZ8KqfpkWMgFRU"), address: /ip4/192.168.208.2/udp/12345/quic-v1 }
2025-08-26T09:30:21.756526074Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWL2K3BrbdwhAFYXe5jD3um6PzGQDr5PBZ8KqfpkWMgFRU"), address:  }
2025-08-26T09:30:21.756551622Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWL2K3BrbdwhAFYXe5jD3um6PzGQDr5PBZ8KqfpkWMgFRU"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.756578783Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/9869/quic-v1 }
2025-08-26T09:30:21.760092707Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWM33BK2xQ5XYcdV8gduPXZJHCjkYQmcjZnSbJBkYxuCW2"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.760134335Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWM33BK2xQ5XYcdV8gduPXZJHCjkYQmcjZnSbJBkYxuCW2"), address: /ip4/10.171.2.35/udp/12345/quic-v1 }
2025-08-26T09:30:21.760173058Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWM33BK2xQ5XYcdV8gduPXZJHCjkYQmcjZnSbJBkYxuCW2"), address: /ip4/147.78.211.225/udp/12345/quic-v1/p2p/12D3KooWM33BK2xQ5XYcdV8gduPXZJHCjkYQmcjZnSbJBkYxuCW2 }
2025-08-26T09:30:21.760195931Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/1198/quic-v1 }
2025-08-26T09:30:21.761300861Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooW9yQws9oxjj6aAAKov8zb69ZVj5UEBzFh6sD4srTNfQFb"), address: /ip4/147.78.211.221/udp/12345/quic-v1 }
2025-08-26T09:30:21.761323053Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooW9yQws9oxjj6aAAKov8zb69ZVj5UEBzFh6sD4srTNfQFb"), address: /ip4/10.171.2.31/udp/12345/quic-v1 }
2025-08-26T09:30:21.761353641Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooW9yQws9oxjj6aAAKov8zb69ZVj5UEBzFh6sD4srTNfQFb"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.761367046Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/53214/quic-v1 }
2025-08-26T09:30:21.761603Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWEYbv2PZnrjc2dWMwiH7zRP3AWCZLHQETNRtAUbBeh7rt"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.761624761Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWEYbv2PZnrjc2dWMwiH7zRP3AWCZLHQETNRtAUbBeh7rt"), address: /ip4/147.78.211.210/udp/12345/quic-v1/p2p/12D3KooWEYbv2PZnrjc2dWMwiH7zRP3AWCZLHQETNRtAUbBeh7rt }
2025-08-26T09:30:21.761652553Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWEYbv2PZnrjc2dWMwiH7zRP3AWCZLHQETNRtAUbBeh7rt"), address: /ip4/10.171.2.20/udp/12345/quic-v1 }
2025-08-26T09:30:21.761675506Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/6552/quic-v1 }
2025-08-26T09:30:21.761745809Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQhZopTFgysUgzpEW1eTj9UPEc9mK2NbEsUQSivbMCLoF"), address: /ip4/10.6.2.7/udp/52445/quic-v1 }
2025-08-26T09:30:21.761773110Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQhZopTFgysUgzpEW1eTj9UPEc9mK2NbEsUQSivbMCLoF"), address: /dns4/testnet.subsquid.io/udp/52445/quic-v1 }
2025-08-26T09:30:21.761805531Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQhZopTFgysUgzpEW1eTj9UPEc9mK2NbEsUQSivbMCLoF"), address: /ip4/127.0.0.1/udp/52445/quic-v1 }
2025-08-26T09:30:21.761820059Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/20369/quic-v1 }
2025-08-26T09:30:21.763446991Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWKwhKrYJMav2JrndFhNWXMDg6bFUXKPxZGAswWE2A55rA"), address: /ip4/147.78.211.204/udp/12345/quic-v1 }
2025-08-26T09:30:21.763466087Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWKwhKrYJMav2JrndFhNWXMDg6bFUXKPxZGAswWE2A55rA"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.763488669Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWKwhKrYJMav2JrndFhNWXMDg6bFUXKPxZGAswWE2A55rA"), address: /ip4/10.171.2.14/udp/12345/quic-v1 }
2025-08-26T09:30:21.763518866Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/53571/quic-v1 }
2025-08-26T09:30:21.766235400Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWQtAGvDDgxkGmYzHBjofbtBRVP3zu18jJZ711E3YYnoUD"), connection_id: ConnectionId(27), endpoint: Dialer { address: /ip4/147.78.211.216/udp/12345/quic-v1/p2p/12D3KooWQtAGvDDgxkGmYzHBjofbtBRVP3zu18jJZ711E3YYnoUD, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 26.241265ms }
2025-08-26T09:30:21.787678002Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWQvLUZvHZaJow5VorSsGUoCFMyrdCWRJGgEJiy9m1qSnh"), connection_id: ConnectionId(10), endpoint: Dialer { address: /ip4/38.102.124.208/udp/12345/quic-v1/p2p/12D3KooWQvLUZvHZaJow5VorSsGUoCFMyrdCWRJGgEJiy9m1qSnh, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 90.231156ms }
2025-08-26T09:30:21.793510821Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQtAGvDDgxkGmYzHBjofbtBRVP3zu18jJZ711E3YYnoUD"), address: /ip4/147.78.211.216/udp/12345/quic-v1 }
2025-08-26T09:30:21.793540938Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQtAGvDDgxkGmYzHBjofbtBRVP3zu18jJZ711E3YYnoUD"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.793562859Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQtAGvDDgxkGmYzHBjofbtBRVP3zu18jJZ711E3YYnoUD"), address: /ip4/10.171.2.26/udp/12345/quic-v1 }
2025-08-26T09:30:21.793583248Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/60366/quic-v1 }
2025-08-26T09:30:21.796084967Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWG9qAyDQCiLAt5d7faoquE1bWhtCKGDxLnKtBaNPNNF4M"), address: /ip4/127.0.0.1/udp/12346/quic-v1 }
2025-08-26T09:30:21.796105035Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWG9qAyDQCiLAt5d7faoquE1bWhtCKGDxLnKtBaNPNNF4M"), address: /ip4/172.18.0.2/udp/12346/quic-v1 }
2025-08-26T09:30:21.796132827Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWG9qAyDQCiLAt5d7faoquE1bWhtCKGDxLnKtBaNPNNF4M"), address: /ip4/62.205.223.79/udp/12346/quic-v1 }
2025-08-26T09:30:21.796146874Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/25755/quic-v1 }
2025-08-26T09:30:21.861782062Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWR52LhKYkcK5iDQyXBfnZ3bsUB6q9L8pcsDGxa4faLx7c"), connection_id: ConnectionId(28), endpoint: Dialer { address: /ip4/64.137.176.138/udp/12346/quic-v1/p2p/12D3KooWR52LhKYkcK5iDQyXBfnZ3bsUB6q9L8pcsDGxa4faLx7c, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 121.521566ms }
2025-08-26T09:30:21.880821190Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQvLUZvHZaJow5VorSsGUoCFMyrdCWRJGgEJiy9m1qSnh"), address:  }
2025-08-26T09:30:21.880852800Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQvLUZvHZaJow5VorSsGUoCFMyrdCWRJGgEJiy9m1qSnh"), address: /ip4/172.18.0.2/udp/12345/quic-v1 }
2025-08-26T09:30:21.880882836Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQvLUZvHZaJow5VorSsGUoCFMyrdCWRJGgEJiy9m1qSnh"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:21.880908945Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWQvLUZvHZaJow5VorSsGUoCFMyrdCWRJGgEJiy9m1qSnh"), address: /ip4/38.102.124.208/udp/12345/quic-v1/p2p/12D3KooWQvLUZvHZaJow5VorSsGUoCFMyrdCWRJGgEJiy9m1qSnh }
2025-08-26T09:30:21.880936507Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/5648/quic-v1 }
2025-08-26T09:30:21.952968617Z Swarm event: ConnectionEstablished { peer_id: PeerId("12D3KooWLoJTLWH5FPnLuFMCJE9Ryf3zxivvbhs71jwKp7aER3yg"), connection_id: ConnectionId(16), endpoint: Dialer { address: /ip4/1.229.241.143/udp/12345/quic-v1/p2p/12D3KooWLoJTLWH5FPnLuFMCJE9Ryf3zxivvbhs71jwKp7aER3yg, role_override: Dialer, port_use: Reuse }, num_established: 1, concurrent_dial_errors: Some([]), established_in: 255.174718ms }
2025-08-26T09:30:21.985233681Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWR52LhKYkcK5iDQyXBfnZ3bsUB6q9L8pcsDGxa4faLx7c"), address: /ip4/172.18.0.2/udp/12346/quic-v1 }
2025-08-26T09:30:21.985280719Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWR52LhKYkcK5iDQyXBfnZ3bsUB6q9L8pcsDGxa4faLx7c"), address: /ip4/64.137.176.138/udp/12346/quic-v1/p2p/12D3KooWR52LhKYkcK5iDQyXBfnZ3bsUB6q9L8pcsDGxa4faLx7c }
2025-08-26T09:30:21.985297441Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWR52LhKYkcK5iDQyXBfnZ3bsUB6q9L8pcsDGxa4faLx7c"), address:  }
2025-08-26T09:30:21.985326766Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWR52LhKYkcK5iDQyXBfnZ3bsUB6q9L8pcsDGxa4faLx7c"), address: /ip4/127.0.0.1/udp/12346/quic-v1 }
2025-08-26T09:30:21.985360139Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/57815/quic-v1 }
2025-08-26T09:30:22.205491092Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWLoJTLWH5FPnLuFMCJE9Ryf3zxivvbhs71jwKp7aER3yg"), address: /ip4/172.18.0.2/udp/12345/quic-v1 }
2025-08-26T09:30:22.205536557Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWLoJTLWH5FPnLuFMCJE9Ryf3zxivvbhs71jwKp7aER3yg"), address: /ip4/127.0.0.1/udp/12345/quic-v1 }
2025-08-26T09:30:22.205571253Z Swarm event: NewExternalAddrOfPeer { peer_id: PeerId("12D3KooWLoJTLWH5FPnLuFMCJE9Ryf3zxivvbhs71jwKp7aER3yg"), address: /ip4/1.229.241.143/udp/12345/quic-v1 }
2025-08-26T09:30:22.205584938Z Swarm event: NewExternalAddrCandidate { address: /ip4/162.19.121.18/udp/52607/quic-v1 }
2025-08-26T09:30:26.699070518Z Swarm event: OutgoingConnectionError { connection_id: ConnectionId(19), peer_id: Some(PeerId("12D3KooWFzpwx3mu75ZWE9kEsn6uiAV7sdAs3p9rYn4nNdHnNDsC")), error: Transport([(/ip4/65.108.238.53/udp/12375/quic-v1/p2p/12D3KooWFzpwx3mu75ZWE9kEsn6uiAV7sdAs3p9rYn4nNdHnNDsC, Other(Custom { kind: Other, error: Other(Transport(Right(HandshakeTimedOut))) }))]) }
2025-08-26T09:30:26.744826908Z Swarm event: OutgoingConnectionError { connection_id: ConnectionId(29), peer_id: Some(PeerId("12D3KooWLubdDzVZ3UFuTFJVvmwtNwDbeGZC15n6H1FCedtpLPik")), error: Transport([(/ip4/65.108.238.53/udp/12365/quic-v1/p2p/12D3KooWLubdDzVZ3UFuTFJVvmwtNwDbeGZC15n6H1FCedtpLPik, Other(Custom { kind: Other, error: Other(Transport(Right(HandshakeTimedOut))) }))]) }
2025-08-26T09:30:26.785643389Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWFzpwx3mu75ZWE9kEsn6uiAV7sdAs3p9rYn4nNdHnNDsC")), connection_id: ConnectionId(30) }
2025-08-26T09:30:26.785784454Z Swarm event: Dialing { peer_id: Some(PeerId("12D3KooWLubdDzVZ3UFuTFJVvmwtNwDbeGZC15n6H1FCedtpLPik")), connection_id: ConnectionId(31) }
2025-08-26T09:30:31.604886708Z Swarm event: ConnectionClosed { peer_id: PeerId("12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB"), connection_id: ConnectionId(2), endpoint: Dialer { address: /dns4/testnet.subsquid.io/udp/22446/quic-v1/p2p/12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB, role_override: Dialer, port_use: Reuse }, num_established: 0, cause: Some(KeepAliveTimeout) }
2025-08-26T09:30:31.604936211Z thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libp2p-metrics-0.16.0/src/swarm.rs:236:26:
closed connection to previously be established
```

</details>

### Possible Solution

_No response_

### Version

v0.55.0

### Would you like to work on fixing this bug?

Yes

### PR DESCRIPTION
**Pull request by kamuik16**
## Description

Fixes #6153 

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: misc/metrics/src/swarm.rs [hunk 1]
```diff
@@ -453,3 +458,90 @@ impl From<&libp2p_swarm::ListenError> for IncomingConnectionError {
         }
     }
 }
+
+#[cfg(test)]
+mod tests {
```
Comment (elenaf9) [inline misc/metrics/src/swarm.rs:463]: :pray:

**Review by elenaf9 — APPROVED** [review]
LGTM. Thanks!

**Comment by elenaf9** [comment]
Changelog entry and patch version bump are missing.

**Comment by kamuik16** [comment]
> Changelog entry and patch version bump are missing.

Which version should I bump to?

**Comment by elenaf9** [comment]
> > Changelog entry and patch version bump are missing.
> 
> Which version should I bump to?

`0.17.1` please.

**Comment by kamuik16** [comment]
> > > Changelog entry and patch version bump are missing.
> > 
> > 
> > Which version should I bump to?
> 
> `0.17.1` please.

Done.

**Comment by kamuik16** [comment]
cargo-deny is also complaining, nothing related with my changes.

**Comment by kamuik16** [comment]
> cargo-deny is also complaining, nothing related with my changes.

Would you like me to address that in this PR as well? @elenaf9

**Comment by elenaf9** [comment]
> cargo-deny is also complaining, nothing related with my changes.

Doesn't need to be solved in this PR.

**Review by elenaf9 — APPROVED** [review]
