### PR TITLE
fix(swarm-derive): allow mixing of ignored fields

### LINKED ISSUE #2569: swarm-derive/: Don't fail when ignored fields are first
The `NetworkBehaviour` derive macro seems to fail when the `#[behaviour(ignore)]` fields are not the very last fields.

E.g. while the first here fails, the second succeeds:

``` rust
/// Behaviour type.
#[derive(libp2p::NetworkBehaviour)]
#[behaviour(out_event = "BehaviourEvent", event_process = true)]
pub struct Behaviour<Types: IpfsTypes> {
    #[behaviour(ignore)]
    repo: Arc<Repo<Types>>,
    // mdns: Toggle<TokioMdns>,
    kademlia: Kademlia<MemoryStore>,
    #[behaviour(ignore)]
    kad_subscriptions: SubscriptionRegistry<KadResult, String>,
    bitswap: Bitswap,
    ping: Ping,
    identify: Identify,
    pubsub: Pubsub,
    pub swarm: SwarmApi,
}
```

``` rust
/// Behaviour type.
#[derive(libp2p::NetworkBehaviour)]
#[behaviour(event_process = true)]
pub struct Behaviour<Types: IpfsTypes> {
    // mdns: Toggle<TokioMdns>,
    kademlia: Kademlia<MemoryStore>,
    bitswap: Bitswap,
    ping: Ping,
    identify: Identify,
    pubsub: Pubsub,
    pub swarm: SwarmApi,
    #[behaviour(ignore)]
    repo: Arc<Repo<Types>>,
    #[behaviour(ignore)]
    kad_subscriptions: SubscriptionRegistry<KadResult, String>,
}
```

See https://github.com/rs-ipfs/rust-ipfs/pull/499#discussion_r826401633 for a failure in the wild.

### PR DESCRIPTION
**Pull request by rand0m-cloud**
Fixes #2569 and adds a test to cover the previous failure.

### CODE REVIEW

File: swarm-derive/src/lib.rs [hunk 1]
```diff
@@ -92,6 +92,13 @@ fn build_struct(ast: &DeriveInput, data_struct: &DataStruct) -> TokenStream {
         event_process
     };
 
+    // The fields of the struct we are interested in (no ignored fields)
```
Comment (mxinden) [inline swarm-derive/src/lib.rs]:
```suggestion
    // The fields of the struct we are interested in (no ignored fields).
```

**Review by mxinden — APPROVED** [review]
Thanks for the fix, the clean-up and the test. Solid work! :pray:

**Comment by mxinden** [comment]
[Tagged](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-swarm-derive-0.27.1) and [published](https://crates.io/crates/libp2p-swarm-derive/0.27.1). //CC @rand0m-cloud
