### PR TITLE
fix(relay): export `RateLimiter` type

### LINKED ISSUE #3741: Publicly export `libp2p_relay::behaviour::rate_limiter`
## Description

Publicly export module `libp2p_relay::behaviour::rate_limiter` 

## Motivation

This is needed to be able to provide changes to `libp2p_relay::Config::circuit_src_rate_limiters` and `libp2p_relay::Config::reservation_rate_limiters` .

## Are you planning to do it yourself in a pull request?

Yes

### PR DESCRIPTION
**Pull request by dariusc93**
## Description

The `rate-limiter` module  was not made publicly available. This change exports the `RateLimiter` trait defined within that module which allows users to define their own rate limiters. To make common usecases easy, we also provide a set of constructor functions for common rate limiters.

Resolves #3741.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Thanks for the patch! I am wondering how we can best follow the conventions laid out in https://github.com/libp2p/rust-libp2p/issues/2217 with this.

Currently, all the the fields on `relay::Config` are public (they should probably be private so we don't expose such a large API).

I am thinking, instead of just exposing the `rate_limiter` module, why don't we:

- Export the `RateLimiter` trait on the crate root (https://github.com/libp2p/rust-libp2p/pull/3735 would have enforced that)
- Add functions on `Config` to create the two predefined rate limiters (`per_peer` and `per_ip`).
- As parameters to the above functions, I'd recommend that we _don't_ expose `GenericRateLimiterConfig` but just the two parameters required. That is one less type in our API.

This way, we don't have to expose the entire module but still allow users to use the existing configs and build their own.

Does that work for your usecase?

**Comment by dariusc93** [comment]
Sounds good to me @thomaseizinger

**Comment by mxinden** [comment]
Sorry for the trouble @dariusc93. I am assuming that this was my mistake back from https://github.com/libp2p/rust-libp2p/pull/2059.

Agreed with the suggestions above by @thomaseizinger. Thanks!

@dariusc93 do you want to tackle these suggestions?

**Comment by thomaseizinger** [comment]
> Thanks for the patch! I am wondering how we can best follow the conventions laid out in #2217 with this.
> 
> Currently, all the the fields on `relay::Config` are public (they should probably be private so we don't expose such a large API).
> 
> I am thinking, instead of just exposing the `rate_limiter` module, why don't we:
> 
>     * Export the `RateLimiter` trait on the crate root ([chore: enforce `unreachable_pub` lint #3735](https://github.com/libp2p/rust-libp2p/pull/3735) would have enforced that)
> 
>     * Add functions on `Config` to create the two predefined rate limiters (`per_peer` and `per_ip`).
> 
>     * As parameters to the above functions, I'd recommend that we _don't_ expose `GenericRateLimiterConfig` but just the two parameters required. That is one less type in our API.
> 
> 
> This way, we don't have to expose the entire module but still allow users to use the existing configs and build their own.
> 
> Does that work for your usecase?

@dariusc93 In case you missed this message, I am currently waiting on a response if the above suggestion would work for you.

**Comment by dariusc93** [comment]
> @dariusc93 In case you missed this message, I am currently waiting on a response if the above suggestion would work for you.

Yes it does work for me, just havent had the time to implement the suggestions myself (meant to do it this past weekend though but been busy).

**Comment by thomaseizinger** [comment]
> > @dariusc93 In case you missed this message, I am currently waiting on a response if the above suggestion would work for you.
> 
> Yes it does work for me, just havent had the time to implement the suggestions myself (meant to do it this past weekend though but been busy).

No worries (and rush) at all :)
Just wanted to make sure there isn't a misunderstanding!

File: protocols/relay/src/behaviour.rs [hunk 1]
```diff
@@ -61,6 +61,32 @@ pub struct Config {
     pub circuit_src_rate_limiters: Vec<Box<dyn rate_limiter::RateLimiter>>,
 }
 
+impl Config {
+    pub fn per_peer(mut self, limit: NonZeroU32, interval: Duration) -> Self {
```
Comment (dariusc93) [inline protocols/relay/src/behaviour.rs]: Do we want these function to be per `reservation_rate_limiters` and `circuit_src_rate_limiters` or do we want to have it so we populate both vectors per function?

Comment (mxinden) [reply protocols/relay/src/behaviour.rs]: I am not 100% sure I follow the question. I would expect a user to want to set a different limit for reservations than for circuits, with the rational that a reservation is less expensive than a circuit. Does that make sense? I am not sure though whether we really need to support this use-case via the easy-path, instead of deferring the user to the `rate-limiter` primitives directly.

Comment (thomaseizinger) [reply protocols/relay/src/behaviour.rs]: @mxinden see https://github.com/libp2p/rust-libp2p/pull/3742#issuecomment-1498853088.

I think splitting as better as per @mxinden's reasoning. We only provide these functions to be able to hide more details from the public API. The user should still be able to make fine-grained configuration changes otherwise there is no point in providing them I think.

File: protocols/relay/CHANGELOG.md [hunk 2]
```diff
@@ -19,12 +19,15 @@
 
 ## 0.15.2
 
+- Export `rate-limiter` module. See [PR 3742].
```
Comment (thomaseizinger) [inline protocols/relay/CHANGELOG.md]: This needs to move to a new section now.

**Comment by thomaseizinger** [comment]
@dariusc93 Let me know when this is ready for another review or you have any questions.

**Comment by dariusc93** [comment]
> @dariusc93 Let me know when this is ready for another review or you have any questions.

Will do! I havent forgotten about this PR and look to tackle this before this week is over.

**Comment by dariusc93** [comment]
Sorry for the delay @thomaseizinger. I did push changes to split it for both `reservation_rate_limiters` and `circuit_src_rate_limiters`, though im not sure on the naming itself but should satisfy using `GenericRateLimiterConfig` internally while still giving those who implement `RateLimiter` the option to push into those fields, although I am wondering if we should make the `Config` fields private and have functions to set the value to the respected fields. Thoughts? We could just mark the fields as deprecated pointing users to use the corresponding functions instead if it is done.

**Review by thomaseizinger — COMMENTED** [review]
Nice, thank you for the changes!

I think this design makes sense:

- Easy things are easy: Users can call one of the pre-defined constructor functions on `Config` to create several rate limiters
- Hard things are possible: Users can implement their own `RateLimiter` and push it to the field directly
- The design is open: Users can access all values of the config.
- The API surface is minimal: `GenericRateLimiterConfig` is an implementation detail

There might be an argument to _not_ making the fields public and instead provide getter functions. Those would give us slightly more options in case we ever want to change these fields. For the moment, I am not too worried about that though.

File: protocols/relay/CHANGELOG.md [hunk 3]
```diff
@@ -1,8 +1,12 @@
 ## 0.16.1 - unreleased
 
+- Export `rate-limiter` module.
```
Comment (thomaseizinger) [inline protocols/relay/CHANGELOG.md]:
```suggestion
- Export `RateLimiter` type. 
```

**Review by thomaseizinger — APPROVED** [review]
