### PR TITLE
.github/workflows: Deny cargo doc warnings in CI

### LINKED ISSUE #2914: Fix warnings produced by `cargo doc --workspace`
## Description

Currently, `cargo doc` is emitting a number of warnings. We should fix those and amend the CI configuration to fail as soon as any warnings are emitted.

## Motivation

Warnings are (often) no good.

## Are you planning to do it yourself in a pull request?

Maybe.

### PR DESCRIPTION
**Pull request by ddimaria**
# Description

- [x] Update CI to fail on warnings
- [x] Fix all warnings

## Links to any relevant issues

Fixes https://github.com/libp2p/rust-libp2p/issues/2914

## Open Questions

I'm assuming that it's OK to document private items as it was already specified in the `RUSTDOCFLAGS` `--document-private-items` directive.  Warnings are still generated with this turned on.  To turn off the warnings (in `swarm`), I added `#![allow(rustdoc::private_intra_doc_links)]` to `lib.rs`.

```shell
warning: public documentation for `max_negotiating_inbound_streams` links to private item `PoolConfig::with_max_negotiating_inbound_streams`
    --> swarm/src/lib.rs:1373:15
     |
1373 |     /// See [`PoolConfig::with_max_negotiating_inbound_streams`].
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this item is private
     |
     = note: this link will resolve properly if you pass `--document-private-items`
```

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: swarm/src/lib.rs [hunk 1]
```diff
@@ -51,7 +51,7 @@
 //! The [`ConnectionHandler`] trait defines how each active connection to a
 //! remote should behave: how to handle incoming substreams, which protocols
 //! are supported, when to open a new outbound substream, etc.
-//!
+#![allow(rustdoc::private_intra_doc_links)]
```
Comment (thomaseizinger) [inline swarm/src/lib.rs]: I am not sure if it makes sense to allow this. Do the offending links work on `docs.rs`? Because if not, then there isn't really much of a point I think.

I'd be in favor of rewriting the docs instead.

@mxinden Thoughts?

**Review by thomaseizinger — COMMENTED** [review]
Thanks for working on this!

One question.

File: swarm/src/lib.rs (hunk 1 above)
Comment (mxinden) [reply swarm/src/lib.rs]: > I'd be in favor of rewriting the docs instead.

I would be in favor of this as well.

**Review by mxinden — COMMENTED** [review]
Thanks @ddimaria for the help here.

File: swarm/src/lib.rs (hunk 1 above)
Comment (ddimaria) [reply swarm/src/lib.rs]: The links show up in `docs.rs`, though the links do not work because the `connection` and `connection/pool` modules are private, so completely agree on the doc rewrite (assuming making `connection` and `connection/pool` public isn't a good option).  Links to the offending documentation:

* https://github.com/libp2p/rust-libp2p/blob/master/swarm/src/dial_opts.rs#L124-L129
* https://github.com/libp2p/rust-libp2p/blob/master/swarm/src/dial_opts.rs#L198-L203
* https://github.com/libp2p/rust-libp2p/blob/master/swarm/src/lib.rs#L1371-L1377

I can lift the doc comments from the referenced functions and replace the private links with them, though this is not DRY, so it adds to the doc-update burden.  Thoughts @thomaseizinger ?

Comment (thomaseizinger) [reply swarm/src/lib.rs]: I'd suggest we simply remove the docs from the non-public items and put them on the public ones. In other words, inline the documentation we are currently referring to and deleting it from there!

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -111,7 +111,7 @@ jobs:
     - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8 # v2.0.0
 
     - name: Check rustdoc links
-      run: RUSTDOCFLAGS="--deny broken_intra_doc_links" cargo doc --verbose --workspace --no-deps --document-private-items --all-features
+      run: RUSTDOCFLAGS="--deny rustdoc::broken_intra_doc_links --deny warnings" cargo doc --verbose --workspace --no-deps --all-features
```
Comment (ddimaria) [inline .github/workflows/ci.yml:114]: Removed `--document-private-items` as we don't want references to non-public items.

File: swarm/src/lib.rs (hunk 1 above)
Comment (ddimaria) [reply swarm/src/lib.rs]: This is done, though I left the documentation in the private functions alone as it looked out of place with the other items documented.  It may be out of scope for this PR, but it's worth considering changing `///` to `//` documentation in private items.

**Review by thomaseizinger — APPROVED** [review]
Awesome, thank you!

**Comment by ddimaria** [comment]
> Awesome, thank you!

Thank you @thomaseizinger! Do you need to approve the workflow (first time contributor)?

> First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) 9 expected checks
