### PR TITLE
fix: gossipsub-batch-subscription

### LINKED ISSUE #6271: Gossipsub Hello RPC not spec compliant
### Summary

I'm currently extending [Nebula](https://github.com/dennis-tra/nebula) to also track the GossipSub topics that the remote peer is subscribed to. To do that I'm waiting for the remote peer to open a GossipSub stream and send the hello RPC which contains the list of subscribed topics.

I noticed that for Lighthouse peers the list only contained a single entry. Turns out that each topic subscription is sent as an individual messaage:

https://github.com/libp2p/rust-libp2p/blob/21d2c46e3cffe62e33c4817e950028c671cbb986/protocols/gossipsub/src/behaviour.rs#L2955-L2957

This is, I guess, not a big issue when it comes to interoperability but it's not [spec compliant](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.0.md#dependencies):

> Whenever a new peer is connected, the gossipsub implementation checks to see if the peer implements floodsub and/or gossipsub, and if so, it sends it a hello packet that announces the topics that it is currently subscribing to.

### Expected behavior

I would expect that the initial RPC packet contains all topics that a peer is subscribed to.

### Actual behavior

The topics that a peer is subscribed to are split across multiple RPCs.

### Relevant log output

```shell

```

### Possible Solution

_No response_

### Version

_No response_

### Would you like to work on fixing this bug?

Maybe

cc @cortze

### PR DESCRIPTION
**Pull request by Shashwat-Nautiyal**
## Description

Previously, when a new peer connected, the GossipSub behaviour sent one RpcOut::Subscribe message per subscribed topic. This  meant N separate protobuf frames were written to the wire for N topics.

This PR introduces ```RpcOut::SubscribeMany```, a batched variant that carries all subscriptions as a ```Vec<(TopicHash, bool, bool)>```, and updates ```on_connection_established``` to use it. The result is a single ```proto::RPC```with multiple SubOpts entries on the wire, which is both spec-compliant and more efficient.

The receiving side was already correct as ```handle_received_subscriptions``` already iterates a ```Vec<proto::SubOpts>```, so no changes are needed there and backward compatibility is fully preserved.

Fixes #6271

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: protocols/gossipsub/src/behaviour/tests/subscription.rs [hunk 1]
```diff
@@ -54,13 +54,17 @@ fn test_subscribe() {
         "Subscribe should add a new entry to the mesh[topic] hashmap"
     );
 
-    // collect all the subscriptions
+    // collect all the subscriptions (hello RPC on connection is now a single SubscribeMany)
```
Comment (jxs) [inline protocols/gossipsub/src/behaviour/tests/subscription.rs]:
```suggestion
    // collect all the subscriptions
```

File: protocols/gossipsub/src/behaviour/tests/subscription.rs [hunk 2]
```diff
@@ -114,19 +118,23 @@ fn test_unsubscribe() {
         "should be able to unsubscribe successfully from each topic",
     );
 
-    // collect all the subscriptions
+    // collect all the subscriptions (hello RPC on connection is now a single SubscribeMany)
```
Comment (jxs) [inline protocols/gossipsub/src/behaviour/tests/subscription.rs]:
```suggestion
    // collect all the subscriptions
```

**Review by jxs — DISMISSED** [review]
Thanks! LGTM!

**Review by jxs — APPROVED** [review]
