### PR TITLE
fix(swarm): prevent overflow in keep-alive computation

### LINKED ISSUE #4641: `.with_idle_connection_timeout(Duration::from_secs(u64::MAX))` still a bug.
### Summary

Simply set idle timeout connection for swarm to `Duration::from_secs(u64)` or `Duration::MAX` still cause `overflow when adding duration to instant`.

### Expected behavior

As the examples, I want to keep connections forever.

### Actual behavior

```bash
thread 'tokio-runtime-worker' panicked at library/std/src/time.rs:419:33:
overflow when adding duration to instant
```

### Relevant log output

```shell
[2023-10-13T07:28:54Z INFO  libp2p_mdns::behaviour::iface] creating instance on iface 192.168.1.14
[2023-10-13T07:28:54Z INFO  p2p_actor_sdk::node] Listening on /ip4/127.0.0.1/udp/64103/quic-v1
[2023-10-13T07:28:54Z INFO  p2p_actor_sdk::node] Listening on /ip4/192.168.1.14/udp/64103/quic-v1
[2023-10-13T07:28:55Z INFO  p2p_actor_sdk::behaviours::gossip_bhv] Subscribing `test`..
[2023-10-13T07:28:56Z INFO  libp2p_mdns::behaviour] discovered: 12D3KooWPCA2Nf518t7TN3sQn5Wf4fKjTxEchX841DcJgwnvBCGU /ip4/192.168.1.14/udp/64356/quic-v1
thread 'tokio-runtime-worker' panicked at library/std/src/time.rs:419:33:
overflow when adding duration to instant
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/panicking.rs:178:5
   3: core::panicking::panic_str
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/panicking.rs:152:5
   4: core::option::expect_failed
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/option.rs:1978:5
   5: core::option::Option<T>::expect
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/option.rs:888:21
   6: <std::time::Instant as core::ops::arith::Add<core::time::Duration>>::add
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/time.rs:419:33
   7: futures_timer::native::delay::Delay::_reset
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-timer-3.0.2/src/native/delay.rs:95:46
   8: futures_timer::native::delay::Delay::reset
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-timer-3.0.2/src/native/delay.rs:72:12
   9: libp2p_swarm::connection::Connection<THandler>::poll
             at /Users/zrus/.cargo/git/checkouts/rust-libp2p-98135dbcf5b63918/d6351ee/swarm/src/connection.rs:358:29
  10: libp2p_swarm::connection::pool::task::new_for_established_connection::{{closure}}::{{closure}}
             at /Users/zrus/.cargo/git/checkouts/rust-libp2p-98135dbcf5b63918/d6351ee/swarm/src/connection/pool/task.rs:182:26
  11: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/poll_fn.rs:56:9
  12: futures_util::future::future::FutureExt::poll_unpin
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/mod.rs:562:9
  13: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/select.rs:118:35
  14: libp2p_swarm::connection::pool::task::new_for_established_connection::{{closure}}
             at /Users/zrus/.cargo/git/checkouts/rust-libp2p-98135dbcf5b63918/d6351ee/swarm/src/connection/pool/task.rs:184:10
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/future/future.rs:125:9
  16: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/core.rs:328:17
  17: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/loom/std/unsafe_cell.rs:16:9
  18: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/core.rs:317:13
  19: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/harness.rs:485:19
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/panic/unwind_safe.rs:271:9
  21: std::panicking::try::do_call
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/panicking.rs:504:40
  22: ___rust_try
  23: std::panicking::try
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/panicking.rs:468:19
  24: std::panic::catch_unwind
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/panic.rs:142:14
  25: tokio::runtime::task::harness::poll_future
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/harness.rs:473:18
  26: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/harness.rs:208:27
  27: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/harness.rs:153:15
  28: tokio::runtime::task::raw::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/raw.rs:276:5
  29: tokio::runtime::task::raw::RawTask::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/raw.rs:200:18
  30: tokio::runtime::task::LocalNotified<S>::run
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/mod.rs:408:9
  31: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/multi_thread/worker.rs:639:17
  32: tokio::runtime::coop::with_budget
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/coop.rs:107:5
  33: tokio::runtime::coop::budget
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/coop.rs:73:5
  34: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  35: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  36: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  37: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context/scoped.rs:40:9
  38: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context.rs:176:26
  39: std::thread::local::LocalKey<T>::try_with
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/thread/local.rs:270:16
  40: std::thread::local::LocalKey<T>::with
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/thread/local.rs:246:9
  41: tokio::runtime::context::set_scheduler
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context.rs:176:9
  42: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  43: tokio::runtime::context::runtime::enter_runtime
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/context/runtime.rs:65:16
  44: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  45: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  46: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/blocking/task.rs:42:21
  47: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/core.rs:328:17
  48: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/loom/std/unsafe_cell.rs:16:9
  49: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/core.rs:317:13
  50: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/harness.rs:485:19
  51: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/core/src/panic/unwind_safe.rs:271:9
  52: std::panicking::try::do_call
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/panicking.rs:504:40
  53: ___rust_try
  54: std::panicking::try
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/panicking.rs:468:19
  55: std::panic::catch_unwind
             at /rustc/d627cf07ce46d230a93732a4714d16f00df9466b/library/std/src/panic.rs:142:14
  56: tokio::runtime::task::harness::poll_future
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/harness.rs:473:18
  57: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/harness.rs:208:27
  58: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/harness.rs:153:15
  59: tokio::runtime::task::raw::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/raw.rs:276:5
  60: tokio::runtime::task::raw::RawTask::poll
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/raw.rs:200:18
  61: tokio::runtime::task::UnownedTask<S>::run
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/task/mod.rs:445:9
  62: tokio::runtime::blocking::pool::Task::run
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/blocking/pool.rs:159:9
  63: tokio::runtime::blocking::pool::Inner::run
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/blocking/pool.rs:513:17
  64: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/zrus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Possible Solution

_No response_

### Version

Directly from github on branch `master`

### Would you like to work on fixing this bug ?

No

### PR DESCRIPTION
**Pull request by ghost**
## Description

Add safe check to prevent `Delay::reset()` panic when duration overflow.

Fixes: #4641.

## Attributions

Co-authored-by: Leonz <bellerophon00530@gmail.com>
Co-authored-by: Max Inden <mail@max-inden.de>

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: swarm/src/connection.rs [hunk 1]
```diff
@@ -354,8 +354,11 @@ where
                         if let Some(new_duration) = deadline.checked_duration_since(Instant::now())
                         {
                             let effective_keep_alive = max(new_duration, *idle_timeout);
-
-                            timer.reset(effective_keep_alive)
+                            
+                            let now = Instant::now();
+                            let safe_effective_keep_alive = checked_add_fraction(now, effective_keep_alive);
+                            
+                            timer.reset(safe_effective_keep_alive)
```
Comment (mxinden) [inline swarm/src/connection.rs]: How about the following, computing `now` once and adding a comment.

``` rust
                    if *deadline != t {
                        *deadline = t;
                        let now = Instant::now();
                        if let Some(new_duration) = deadline.checked_duration_since(now) {
                            let effective_keep_alive = max(new_duration, *idle_timeout);

                            // `Delay::reset` panics if `now + effective_keep_alive` is `> u64::MAX`.
                            let safe_effective_keep_alive = checked_add_fraction(now, effective_keep_alive);
                            timer.reset(safe_effective_keep_alive)
```

**Review by mxinden — COMMENTED** [review]
Thank you for the fast turnaround time. Overall looks good to me.

@thomaseizinger mind taking a look given that this is quite subtle?

@zrus can you add an entry to `swarm/CHANGELOG.md`?

File: swarm/src/connection.rs (hunk 1 above)
Comment (ghost) [reply swarm/src/connection.rs]: Looks good to me. And I will update the `CHANGELOG.md` then.

File: swarm/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,8 @@
+## 0.43.7 - unreleased
+
+- Fix overflow in `KeepAlive` computation that could occur panic at `Delay::reset` if `SwarmBuilder::idle_connection_timeout` is configured too large.
+  See [PR 4644](https://github.com/libp2p/rust-libp2p/pull/4644).
+
 ## 0.43.6 - unreleased
```
Comment (mxinden) [inline swarm/CHANGELOG.md]:
```suggestion
## 0.43.6 - unreleased

- Fix overflow in connection keep alive computation that could panic at `Delay::reset` with a large `SwarmBuilder::idle_connection_timeout`.
  See [PR 4644](https://github.com/libp2p/rust-libp2p/pull/4644).
```

`0.43.6` is not yet released. Thus we can include it in there already.

**Review by mxinden — APPROVED** [review]
Thank you for the follow-up. Again, let's give Thomas a chance to review. The more eyes on this subtle code path, the better.

File: swarm/CHANGELOG.md (hunk 2 above)
Comment (ghost) [reply swarm/CHANGELOG.md]: Oh, my mistake. Sorry about that.

**Review by thomaseizinger — COMMENTED** [review]
Thanks! Embarrassing that we didn't catch this in the first patch.

I'd like to test this better. In https://github.com/libp2p/rust-libp2p/pull/4595, we are extracting this big code block into a function. Would you be up for copying that to this PR and writing some prop-tests using `quickcheck` for it?

**Comment by ghost** [comment]
> I'd like to test this better. In #4595, we are extracting this big code block into a function. Would you be up for copying that to this PR and writing some prop-tests using `quickcheck` for it?

I have done it. But I have not added any tests yet.  Please help me on this.

File: swarm/src/connection.rs [hunk 3]
```diff
@@ -157,6 +161,8 @@ where
     local_supported_protocols: HashSet<StreamProtocol>,
     remote_supported_protocols: HashSet<StreamProtocol>,
     idle_timeout: Duration,
+    /// The counter of active streams
+    stream_counter: ActiveStreamCounter,
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]: This is unrelated, please remove this bit!

**Review by thomaseizinger — COMMENTED** [review]
Thanks!

Regarding tests, are you familiar with quickcheck? https://github.com/BurntSushi/quickcheck

File: swarm/src/connection.rs (hunk 3 above)
Comment (ghost) [reply swarm/src/connection.rs]: Done. Please review it.

**Comment by ghost** [comment]
> Regarding tests, are you familiar with quickcheck? https://github.com/BurntSushi/quickcheck

I have not used it before. Could you guide me?

**Comment by thomaseizinger** [comment]
> > Regarding tests, are you familiar with quickcheck? [BurntSushi/quickcheck](https://github.com/BurntSushi/quickcheck)
> 
> I have not used it before. Could you guide me?

Sure! You'll like this :)

The idea of `quickcheck` is to _property-based_ testing by generate test-cases automatically asserting no the code having certain _properties_. We can use that for this code to check that regardless of which inputs we generate, the code never pancis but always yields a valid `Shutdown` value.

You can find an example test in the `connection.rs` file: `max_negotiating_inbound_streams`.

To write your own test, you need to create a `prop` function (name doesn't matter) that takes the inputs you want `quickcheck` to permute. The function needs to call `compute_new_shutdown`. To start with, we don't need to make any further assertions, simply not panicking is good already!

We'll need a couple of things:

1. Add an implementation of `quickcheck::Arbitrary` to `KeepAlive`. The implementation should be gated by `#[cfg(test)]`.
2. Generalize the `KeepAliveUntilConnectionHandler` to take an entire `KeepAlive` and not just an `Instant`.
3. Write a quickcheck-test with a `prop` function that takes a `KeepAlive` and a `Duration`:
	- The test should make a new `KeepAliveUntilConnectionHandler` with the passed in `KeepAlive`
	- Call `compute_new_shutdown` with `Shutdown::None`, the handler and the provided `Duration` as `idle_timeout`

That should get us started. We can then think about whether we want to permute the existing `Shutdown` as well which is a bit trickier.

**Comment by thomaseizinger** [comment]
Tagging @leonzchang for visibility of related effort. We cherry-picked some of your code to make testing this easier :)

I added you as a co-author to the PR description to correctly attribute your contribution!

**Comment by mxinden** [comment]
In order to unblock https://github.com/libp2p/rust-libp2p/pull/4625, I am looking into the quickcheck test right now.

**Review by mxinden — DISMISSED** [review]
Thank you for your work!

File: swarm/src/connection.rs [hunk 4]
```diff
@@ -1008,6 +1004,88 @@ mod tests {
...
+                    ),
+                    _ => unreachable!(),
+                };
+
+                Self(shutdown)
+            }
+        }
+
+        #[derive(Clone, Debug)]
+        struct ArbitraryDuration(Duration);
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]: I think `Duration` already implements `Arbitrary`.

File: swarm/src/connection.rs [hunk 5]
```diff
@@ -1008,6 +1004,88 @@ mod tests {
...
     }
 
+    #[test]
+    fn compute_new_shutdown_does_not_panic() {
+        let _ = env_logger::try_init();
+
+        #[derive(Clone, Debug)]
+        struct ArbitraryKeepAlive(KeepAlive);
+
+        impl Arbitrary for ArbitraryKeepAlive {
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]: Couldn't we just implement this on `KeepAlive` directly?

File: swarm/src/connection.rs [hunk 6]
```diff
@@ -1008,6 +1004,88 @@ mod tests {
...
+                        Delay::new(Duration::from_secs(1)),
+                        instant.clone(),
+                    ),
+                };
+
+                ArbitraryShutdown(shutdown)
+            }
+        }
+
+        impl Arbitrary for ArbitraryShutdown {
```
Comment (thomaseizinger) [inline swarm/src/connection.rs:1032]: Same here.

**Review by thomaseizinger — DISMISSED** [review]
Thanks @mxinden !

Added some ideas that we can tackle in a follow-up :)

**Comment by thomaseizinger** [comment]
@mxinden There are merge conflicts unfortunately.

File: swarm/src/connection.rs (hunk 5 above)
Comment (mxinden) [reply swarm/src/connection.rs]: The `Arbitrary` implementation and thus `quickcheck` would thus be part of our public API surface, no?

Comment (thomaseizinger) [reply swarm/src/connection.rs]: Not if we have it within a `cfg(test)` module.

File: swarm/src/connection.rs (hunk 6 above)
Comment (mxinden) [reply swarm/src/connection.rs:1032]: `Arbitrary` requires `Clone`. `Shutdown` does not implement `Clone` because `Delay` does not implement `Clone`. Thus we need the wrapper type here.

Comment (thomaseizinger) [reply swarm/src/connection.rs:1032]: Oh interesting, thanks for clarifying!

Comment (thomaseizinger) [reply swarm/src/connection.rs:1032]: Can we panic on the delay cloning instead?

Comment (mxinden) [reply swarm/src/connection.rs:1032]: `quickcheck` uses `Clone` to run through the various permutations, e.g. change one parameter but not another. For the latter it needs `Clone`. Thus a panic in a `Clone` implementation would not work.

File: swarm/src/handler.rs [hunk 7]
```diff
@@ -765,6 +765,26 @@ impl Ord for KeepAlive {
     }
 }
 
+#[cfg(test)]
+impl quickcheck::Arbitrary for KeepAlive {
```
Comment (mxinden) [inline swarm/src/handler.rs:769]: @thomaseizinger I am assuming that this is fine too?

Comment (thomaseizinger) [reply swarm/src/handler.rs:769]: Yes!

**Review by mxinden — DISMISSED** [review]
@thomaseizinger assuming that with all comments addressed, you are fine with me merging here.

**Review by mxinden — APPROVED** [review]

**Comment by ghost** [comment]
I apologize for disappearing suddenly from last conversation about the test. I was too busy last week. And thank both of you, @thomaseizinger, @mxinden, for the great work and being patient with me.

**Comment by thomaseizinger** [comment]
> I apologize for disappearing suddenly from last conversation about the test. I was too busy last week. And thank both of you, @thomaseizinger, @mxinden, for the great work and being patient with me.

No worries at all! Normally nothing is super urgent but we wanted to start the next breaking release and this felt important enough to be patched before that :)
