### PR TITLE
fix(gossipsub): fixed incorrect default values in ConfigBuilder

### LINKED ISSUE #6111: Typo in default value in doc string in gossipsub config
### Summary

There is a lie in the docs:
```rust
/// The maximum byte size for each gossip (default is 2048 bytes).
pub fn max_transmit_size(&mut self, max_transmit_size: usize) -> &mut Self {
    self.config.protocol.max_transmit_size = max_transmit_size;
    self
}
```

### Expected behavior

```rust
/// The maximum byte size for each gossip (default is 65536 bytes).
```

### Actual behavior

N.A

### Relevant log output

```shell

```

### Possible Solution

_No response_

### Version

_No response_

### Would you like to work on fixing this bug?

No

### PR DESCRIPTION
**Pull request by sirandreww-starkware**
## Description

Fixed minor doc issue in ConfigBuilder
Fixes https://github.com/libp2p/rust-libp2p/issues/6111

## Notes & open questions

None

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: protocols/gossipsub/src/config.rs [hunk 1]
```diff
@@ -768,13 +768,19 @@ impl ConfigBuilder {
...
+    /// let mut config = ConfigBuilder::default();
+    /// assert_eq!(config.build().unwrap().max_transmit_size(), 65536);
+    /// ```
     pub fn max_transmit_size(&mut self, max_transmit_size: usize) -> &mut Self {
         self.config.protocol.default_max_transmit_size = max_transmit_size;
         self
     }
 
-    /// The maximum byte size for each gossip for a given topic. (default is 2048 bytes).
+    /// The maximum byte size for each gossip for a given topic. (default is 65536 bytes).
```
Comment (elenaf9) [inline protocols/gossipsub/src/config.rs]:
```suggestion
    /// The maximum byte size for each gossip for a given topic. (default is [`max_transmit_size`]).
```

Comment (sirandreww-starkware) [reply protocols/gossipsub/src/config.rs]: The constants are not defined as consts so I'm not sure this will work, where is `max_transmit_size` defined?

Comment (elenaf9) [reply protocols/gossipsub/src/config.rs]: `max_transmit_size` is the function just above. If there is no individual value configured for a topic it will fall back to whatever was set as default value there.

Comment (sirandreww-starkware) [reply protocols/gossipsub/src/config.rs]: oh shoot how did I miss that, alrighty thank you

**Comment by sirandreww-starkware** [comment]
Is this merged? I don't see it on master and the PR is still open...

**Comment by sirandreww-starkware** [comment]
Not sure why CI is not passing

File: protocols/gossipsub/src/config.rs [hunk 2]
```diff
@@ -761,13 +761,20 @@ impl ConfigBuilder {
...
     }
 
-    /// The maximum byte size for each gossip (default is 2048 bytes).
+    /// The maximum byte size for each gossip (default is 65536 bytes).
+    ///
+    /// ```
+    /// use libp2p_gossipsub::ConfigBuilder;
+    /// let mut config = ConfigBuilder::default();
+    /// assert_eq!(config.build().unwrap().max_transmit_size(), 65536);
+    /// ```
```
Comment (elenaf9) [inline protocols/gossipsub/src/config.rs]: I appreciate the additional code example, but not sure if it is really helpful? It just duplicates what is already written above.

If we add a code example, I'd rather have one that shows how to use the method.

Comment (sirandreww-starkware) [reply protocols/gossipsub/src/config.rs]: I added it as kind of a test, this way in the future such a case where the stated value is incorrect can never happen (even if the default changes, one would have to change the docs for tests to pass). I'm happy to add to this example if this rule still applies. I can add another two lines after the assert, one that changes the value and the other checks it again?

**Review by elenaf9 — APPROVED** [review]

File: protocols/gossipsub/CHANGELOG.md [hunk 3]
```diff
@@ -24,6 +24,9 @@
 - Fix mesh not being constructed even when not adding any peer.
   See [PR 6100](https://github.com/libp2p/rust-libp2p/pull/6100)
 
+- Fix incorrect default values in ConfigBuilder
+  See [PR 6113](https://github.com/libp2p/rust-libp2p/pull/6113)
+
```
Comment (elenaf9) [inline protocols/gossipsub/CHANGELOG.md]: Please move this up to the `## 0.50.0` section.

File: protocols/gossipsub/src/config.rs (hunk 2 above)
Comment (jxs) [reply protocols/gossipsub/src/config.rs]: yeah I'd rather leave this out as it makes the code less readable
