### PR TITLE
fix(ping): Fix panic in WASM caused by retrying on dial upgrade errors

### LINKED ISSUE #5442: libp2p-ping sometimes panics in WASM
### Summary

While researching our https://github.com/eigerco/lumina/issues/256 bug we found one of the causes were bacause libp2p-ping was panicking.

This was due to inconsistent behavior in `futures-timer` when it was used in WASM.

### Expected behavior

Not to panic

### Actual behavior

Panics

### Relevant log output

_No response_

### Possible Solution

We fixed the issue with https://github.com/async-rs/futures-timer/pull/74 PR and we are waiting to be reviewed and get merged.

If `futures-timer` rejects or do not merge our fix, then another fix can be applied directly in `libp2p-ping`.

### Version

_No response_

### Would you like to work on fixing this bug ?

Yes

### PR DESCRIPTION
**Pull request by oblique**
## Description

This PR workarounds async-rs/futures-timer#74 issue.

Fixes #5442

## Notes & open questions

It is hard to create a reproduction as a unit test, however I created a [reproduction repository](https://github.com/oblique/libp2p-issue-5442). Please read `README.md` for more info.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: protocols/ping/src/handler.rs [hunk 1]
```diff
@@ -183,6 +183,7 @@ impl Handler {
         >,
     ) {
         self.outbound = None; // Request a new substream on the next `poll`.
+        self.interval.reset(Duration::new(0, 0));
```
Comment (dariusc93) [inline protocols/ping/src/handler.rs:197]: Might be worth to document why we are resetting it upon an error.

Comment (oblique) [reply protocols/ping/src/handler.rs:197]: Done

File: protocols/ping/CHANGELOG.md [hunk 2]
```diff
@@ -1,12 +1,17 @@
-## 0.44.1 - unreleased
+## 0.44.2
+
+- Use `web-time` instead of `instant`.
+  See [PR 5347](https://github.com/libp2p/rust-libp2p/pull/5347).
+
+- Fixes panic in WASM caused by retrying on dail errors.
```
Comment (jxs) [inline protocols/ping/CHANGELOG.md]:
```suggestion
- Fix panic in WASM caused by retrying on dail errors.
```

File: protocols/ping/src/handler.rs [hunk 3]
```diff
@@ -184,6 +184,18 @@ impl Handler {
     ) {
         self.outbound = None; // Request a new substream on the next `poll`.
 
+        // Timer is already polled and expired before substream request is initiated
+        // and will be polled again later on in our `poll` because we reset `self.outbound`.
+        //
+        // `futures-timer` allows an expired timer to be polled again and returns
+        // immidietly a `Poll::Ready`. However in its WASM implementation there is
```
Comment (jxs) [inline protocols/ping/src/handler.rs]:
```suggestion
        // immediately `Poll::Ready`. However in its WASM implementation there is
```

File: protocols/ping/src/handler.rs [hunk 4]
```diff
@@ -184,6 +184,18 @@ impl Handler {
...
+        // a bug that causes the expired timer to panic.
+        //
+        // This is a workaround until a proper fix is merged and released.
+        //
+        // See async-rs/futures-timer#74 and libp2p/rust-libp2p#5447 for more info.
+        self.interval.reset(Duration::new(0, 0));
```
Comment (jxs) [inline protocols/ping/src/handler.rs:197]: in the two instances that I see `self.outbound` be set to `None`, here (line `185`) and on `Handler::new`  `self.interval` is `reset` with `Duration::new(0, 0)`, which means that we don't care about `self.interval` when `self.outbound` is `None` right? If so, it makes more sense to just skip polling `self.interval` here:
https://github.com/libp2p/rust-libp2p/blob/3b61e57d0e72d371ccdfc134bd71cb3aa20addee/protocols/ping/src/handler.rs#L310-L318

**Review by jxs — COMMENTED** [review]
Thanks for working on this Yianis, left a comment

File: protocols/ping/src/handler.rs (hunk 4 above)
Comment (oblique) [reply protocols/ping/src/handler.rs:197]: You missed one case: [Line 289](https://github.com/oblique/rust-libp2p/blob/2ea753ceafdd289e7934394fc044165912e9d4e6/protocols/ping/src/handler.rs?#L289-L306) also sets `outbound`  to `None` and in the case of a `OutboundState::Ping` and later on `Poll::Ready(Err(_))` the timer is set to the ping interval.

The question is: Since the retry of this case is delayed, should the dial error follow the same way and delay its retry?

File: protocols/ping/CHANGELOG.md [hunk 5]
```diff
@@ -3,6 +3,9 @@
 - Use `web-time` instead of `instant`.
   See [PR 5347](https://github.com/libp2p/rust-libp2p/pull/5347).
 
+- Fix panic in WASM caused by retrying on dail errors.
```
Comment (jxs) [inline protocols/ping/CHANGELOG.md]:
```suggestion
- Fix panic in WASM caused by retrying on dial upgrade errors.
```

File: protocols/ping/src/handler.rs [hunk 6]
```diff
@@ -184,6 +184,18 @@ impl Handler {
...
+        // Timer is already polled and expired before substream request is initiated
+        // and will be polled again later on in our `poll` because we reset `self.outbound`.
+        //
+        // `futures-timer` allows an expired timer to be polled again and returns
+        // immediately `Poll::Ready`. However in its WASM implementation there is
+        // a bug that causes the expired timer to panic.
+        //
+        // This is a workaround until a proper fix is merged and released.
+        //
+        // See async-rs/futures-timer#74 and libp2p/rust-libp2p#5447 for more info.
```
Comment (jxs) [inline protocols/ping/src/handler.rs]:
```suggestion
        // This is a workaround until a proper fix is merged and released.
        // See libp2p/rust-libp2p#5447 for more info.
        //
        // TODO: remove when async-rs/futures-timer#74 gets merged.
```

**Review by jxs — APPROVED** [review]

File: protocols/ping/src/handler.rs (hunk 4 above)
Comment (jxs) [reply protocols/ping/src/handler.rs:197]: Thanks for expanding Yianis, I don't think the dial upgrade error should follow, as you stated it wasn't the previous behaviour.
