### PR TITLE
Properly handle protocol negotiation errors

### LINKED ISSUE #71: Server stops with an error if a client doesn't support any of the protocols of the server
This problem is easy to fix, however it becomes much harder to fix if we want to report failing clients to the user of the library so that they can for example perform logging.

### PR DESCRIPTION
**Pull request by tomaka**
Fix #71 

The `listen_on` method no longer produces a `impl Stream<Item = (impl AsyncRead + AsyncWrite, Multiaddr>`, but instead a `impl Stream<Item = (Result<impl AsyncRead + AsyncWrite, IoError>, Multiaddr)>`.

This means that we can produce an `Ok(Err(...))` when a client started connecting but failed for some reason. Possible reasons include for example an error in the websocket protocol, no protocol supported has been found, or an invalid public key has been sent during secio handshake.
Right now these errors would entirely stop the server.

### CODE REVIEW

File: libp2p-swarm/src/transport.rs [hunk 1]
```diff
@@ -664,22 +664,37 @@ impl<'a, T, C> UpgradedNode<T, C>
...
-			})
-			.and_then(|(upgrade_id, connection, upgrade, client_addr)| {
-				upgrade.upgrade(connection, upgrade_id, Endpoint::Listener)
-					.map(|s| (s, client_addr))
+				// Turn the `Result<impl AsyncRead + AsyncWrite, IoError>` into
+				// a `Result<impl Future<Item = impl AsyncRead + AsyncWrite, Error = IoError>, IoError>`
+				let connection = connection.map(|connection| {
+					let upgrade = upgrade.clone();
+					#[inline]
+					fn iter_map<T>((n, t): (Bytes, T)) -> (Bytes, fn(&Bytes,&Bytes)->bool, T) {
```
Comment (Vurich) [inline libp2p-swarm/src/transport.rs]: Why can't this be a closure? Even if you've got to manually hint the types you can do `|n: Bytes, t| -> (_, fn(&_, &_) -> bool, _) (n, <Bytes as PartialEq>::eq, t)`?

File: libp2p-tcp-transport/src/lib.rs [hunk 2]
```diff
@@ -237,7 +237,7 @@ mod tests {
             let listener = tcp.listen_on(addr).unwrap().0.for_each(|(sock, _)| {
                 // Define what to do with the socket that just connected to us
                 // Which in this case is read 3 bytes
-                let handle_conn = tokio_io::io::read_exact(sock, [0; 3])
+                let handle_conn = tokio_io::io::read_exact(sock.unwrap(), [0; 3])
```
Comment (Vurich) [inline libp2p-tcp-transport/src/lib.rs]: Ideally this would be an `expect`, since if this fails we'll just turn it into an `expect` in order to find out what failed anyway.

**Review by eira-fransham — CHANGES_REQUESTED** [review]
Nothing major, mostly looks great.

File: example/examples/echo-server.rs [hunk 3]
```diff
@@ -71,34 +71,56 @@ fn main() {
...
-            let client_finished = loop_fn(socket, |socket| {
+            let client_finished = loop_fn(socket, move |socket| {
+                let client_addr = client_addr.clone();
                 socket.into_future()
                     .map_err(|(err, _)| err)
-                    .and_then(|(msg, rest)| {
+                    .and_then(move |(msg, rest)| {
                         if let Some(msg) = msg {
                             // One message has been received. We send it back to the client.
+                            println!("Received a message from {}: {:?}\n => Sending back \
```
[the remark this answers is not in the document]
Comment (tomaka) [reply example/examples/echo-server.rs]: Yes, it's on purpose!

File: libp2p-swarm/src/transport.rs (hunk 1 above)
Comment (tomaka) [reply libp2p-swarm/src/transport.rs]: The `listener_select_proto` function requires the iterator to be clonable. Rust closures are unfortunately not clonable, so doing `.map(<closure>)` would make the whole iterator non-clonable.

File: libp2p-tcp-transport/src/lib.rs (hunk 2 above)
Comment (tomaka) [reply libp2p-tcp-transport/src/lib.rs]: I didn't put an `expect` because we're in a test and `Err` is actually never produced at all. I can put one if needed, but that seems unnecessary.

Comment (rphmeier) [reply libp2p-tcp-transport/src/lib.rs]: expect would be better, but given that tests are run in debug mode (w/ backtraces) I think it's fine.

Any non-test code should expect instead of unwrap, since debuginfo won't be available.

File: libp2p-swarm/src/transport.rs (hunk 1 above)
Comment (Vurich) [reply libp2p-swarm/src/transport.rs]: [You can coerce a closure to a pointer](https://play.rust-lang.org/?gist=d7e606ca16ae08de329b90c2e72c1e55&version=stable)

**Comment by tomaka** [comment]
Ping? Both concerns turned out to be fine!

**Comment by tomaka** [comment]
Actually let's wait for #48 first.

**Comment by tomaka** [comment]
Ping review!

File: example/examples/echo-server.rs [hunk 4]
```diff
@@ -71,34 +71,56 @@ fn main() {
...
             });
 
             // We absorb errors from the `client_finished` future so that an error while processing
-            // a client doesn't propagate and stop the entire server.
+            // a client (eg. if the client unexpectedly disconnects) doesn't propagate and stop the
+            // entire server.
             client_finished.then(move |res| {
                 if let Err(err) = res {
-                    println!("error while processing client {}: {:?}", client_addr, err);
+                    println!("Error while processing client {}: {:?}", client_addr2, err);
```
Comment (Vurich) [inline example/examples/echo-server.rs]: I don't like `client_addrN` for the clones, I'd prefer `let client_addr = client_addr.clone()` in the scopes that need it.

File: libp2p-swarm/src/connection_reuse.rs [hunk 5]
```diff
@@ -159,27 +164,32 @@ where
 /// Implementation of `Stream<Item = (impl AsyncRead + AsyncWrite, Multiaddr)` for the
 /// `ConnectionReuse` struct.
 pub struct ConnectionReuseListener<S, M>
-where
-	S: Stream<Item = (M, Multiaddr), Error = IoError>,
-	M: StreamMuxer,
+where S: Stream<Item = (Result<M, IoError>, Multiaddr), Error = IoError>,
```
Comment (Vurich) [inline libp2p-swarm/src/connection_reuse.rs]: Can you keep the old style here (`where` on its own line)? It makes the changes more obvious and it's what `rustfmt` will change the style to anyway when we finally get that run over the codebase.

File: libp2p-swarm/src/transport.rs (hunk 1 above)
Comment (tomaka) [reply libp2p-swarm/src/transport.rs]: I just made the change

File: libp2p-swarm/src/transport.rs [hunk 6]
```diff
@@ -307,19 +307,19 @@ pub enum EitherListenStream<A, B> {
 
 impl<A, B, Sa, Sb> Stream for EitherListenStream<A, B>
 where
-	A: Stream<Item = (Sa, Multiaddr), Error = IoError>,
-	B: Stream<Item = (Sb, Multiaddr), Error = IoError>,
+	A: Stream<Item = (Result<Sa, IoError>, Multiaddr), Error = IoError>,
```
Comment (Vurich) [inline libp2p-swarm/src/transport.rs]: In general if type parameters get longer than 1 character I tend to give them real names (like in this case I'd call them `AStream` and `BStream`).

File: libp2p-swarm/src/transport.rs [hunk 7]
```diff
@@ -870,23 +867,36 @@ where
 			}
 		};
 
+		// Try to negotiate the protocol.
+		// Note that failing to negotiate a protocol will never produce a future with an error.
+		// Instead the `stream` will produce an `Ok(Err(...))`.
```
Comment (Vurich) [inline libp2p-swarm/src/transport.rs]: I'd say "produce `Ok(Err(...))`" instead of "produce an `Ok(Err(...))`"

**Review by eira-fransham — APPROVED** [review]
All my comments are minor style gripes, I didn't find anything that would block merging.
