### PR TITLE
fix(quic): allow listening on ipv4 and ipv6 separately

### LINKED ISSUE #4165: quic: ability to listen on ipv4 and v6
## Summary

With `libp2p-quic` `v0.8.0-alpha` one can not listen on **both** a v4 and v6 address.

Unconfirmed whether https://github.com/libp2p/rust-libp2p/pull/3454 has the same issue.

## Expected behaviour

Calling `listen_on` with a v4 and v6 address to work.

## Actual behaviour

Apply the following diff:

``` diff
modified   examples/dcutr/src/main.rs
@@ -172,7 +172,10 @@ fn main() -> Result<(), Box<dyn Error>> {
     .build();
 
     swarm
-        .listen_on("/ip4/0.0.0.0/udp/0/quic-v1".parse().unwrap())
+        .listen_on("/ip4/0.0.0.0/udp/4001/quic-v1".parse().unwrap())
+        .unwrap();
+    swarm
+        .listen_on("/ip6/::/udp/4001/quic-v1".parse().unwrap())
         .unwrap();
     swarm
         .listen_on("/ip4/0.0.0.0/tcp/0".parse().unwrap())
```

and then run with:

```
cargo run -- --mode listen --secret-key-seed 0 --relay-address /ip4/127.0.0.1
```

resulting in:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(Custom { kind: Other, error: Transport(Right(Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))) })', examples/dcutr/src/main.rs:179:10
```

<details><summary>Debug Output</summary>
<p>

```
<output>
```
</p>
</details>

## Possible Solution

My suspicion is that the ipv6 `UdpSocket` binds to both v4 and v6 in order to accept IPv4-mapped IPv6 traffic e.g. `::ffff:192.0.2.128`.

In such case we would need to call [`set_only_v6`](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.set_only_v6) on the socket.

See same code on the tcp side:

https://github.com/libp2p/rust-libp2p/blob/2671375cc48d501cffa56ada68012d2b1556a30e/transports/tcp/src/lib.rs#L356-L358

## Version

`libp2p-quic` `v0.8.0-alpha`

## Would you like to work on fixing this bug?

No

### PR DESCRIPTION
**Pull request by jxs**
## Description

Resolves #4165.

## Notes & open questions

Should we also add a test for this?

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: transports/quic/src/transport.rs [hunk 1]
```diff
@@ -188,7 +202,15 @@ impl<P: Provider> Transport for GenTransport<P> {
         let (socket_addr, version, _peer_id) = self.remote_multiaddr_to_socketaddr(addr, false)?;
         let endpoint_config = self.quinn_config.endpoint_config.clone();
         let server_config = self.quinn_config.server_config.clone();
-        let socket = UdpSocket::bind(socket_addr).map_err(Self::Error::from)?;
+        let socket = self
+            .create_socket(&socket_addr)
+            .map_err(Self::Error::from)?;
+
+        socket
+            .bind(&socket_addr.into())
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: We could do this inside the create function, right?

File: transports/quic/src/transport.rs [hunk 2]
```diff
@@ -172,6 +173,19 @@ impl<P: Provider> GenTransport<P> {
...
         }
     }
+
+    fn create_socket(&self, socket_addr: &SocketAddr) -> io::Result<Socket> {
+        let domain = if socket_addr.is_ipv4() {
+            Domain::IPV4
+        } else {
+            Domain::IPV6
+        };
+        let socket = Socket::new(domain, Type::DGRAM, Some(socket2::Protocol::UDP))?;
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: Don't we have to set it to non-blocking as well?

File: transports/quic/Cargo.toml [hunk 3]
```diff
@@ -24,6 +24,7 @@ rand = "0.8.5"
 rustls = { version = "0.21.2", default-features = false }
 thiserror = "1.0.44"
 tokio = { version = "1.29.1", default-features = false, features = ["net", "rt", "time"], optional = true }
+socket2 = { version = "0.5.3", features = ["all"] }
```
Comment (thomaseizinger) [inline transports/quic/Cargo.toml]: Is `all` really necessary?

**Review by thomaseizinger — APPROVED** [review]
Thanks @jxs!

File: transports/quic/Cargo.toml (hunk 3 above)
Comment (jxs) [reply transports/quic/Cargo.toml]: good question, seems to be the [only feature](https://docs.rs/socket2/0.5.3/socket2/#features) but also seems to not be [used](https://github.com/rust-lang/socket2/blob/master/Cargo.toml#L52)? I have removed it.

File: transports/quic/src/transport.rs (hunk 1 above)
Comment (jxs) [reply transports/quic/src/transport.rs]: yeah, makes sense, and save a `map_err` thanks Thomas.

File: transports/quic/src/transport.rs (hunk 2 above)
Comment (jxs) [reply transports/quic/src/transport.rs]: also a good question. We don't do it with TCP, `quinn` forwards the `std::UdpSocket` [to the executors](https://github.com/quinn-rs/quinn/blob/70e14b5c26b45ee1e3d5dd64b2a184e2d6376880/quinn/src/runtime.rs#L20-L21), which in case of  `tokio` uses `mio` which has [this comment](https://github.com/tokio-rs/mio/blob/236fc31abf58bfcb8ed66b9ae2ce570acb911e77/src/net/udp.rs#L129-L130), so it seems optional
[According to the documentation](https://www.gnu.org/software/libc/manual/html_node/Open_002dtime-Flags.html):
> Macro: int O_NONBLOCK
This prevents open from blocking for a “long time” to open the file. This is only meaningful for some kinds of files, usually devices such as serial ports; when it is not meaningful, it is harmless and ignored. Often, opening a port to a modem blocks until the modem reports carrier detection; if O_NONBLOCK is specified, open will return immediately without a carrier.

so i'd say it's redundant, wdyt?

File: transports/quic/Cargo.toml (hunk 3 above)
Comment (thomaseizinger) [reply transports/quic/Cargo.toml]: > good question, seems to be the [only feature](https://docs.rs/socket2/0.5.3/socket2/#features) but also seems to not be [used](https://github.com/rust-lang/socket2/blob/master/Cargo.toml#L52)? I have removed it. 

There might still be feature gates within the code!

File: transports/quic/src/transport.rs [hunk 4]
```diff
@@ -188,7 +204,9 @@ impl<P: Provider> Transport for GenTransport<P> {
         let (socket_addr, version, _peer_id) = self.remote_multiaddr_to_socketaddr(addr, false)?;
         let endpoint_config = self.quinn_config.endpoint_config.clone();
         let server_config = self.quinn_config.server_config.clone();
-        let socket = UdpSocket::bind(socket_addr).map_err(Self::Error::from)?;
+        let socket = self.create_socket(socket_addr).map_err(Self::Error::from)?;
+
+        let socket: UdpSocket = socket.into();
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs]: You could directly return an std socket from the fn, then the use of `socket2` would be encapsulated.

**Review by thomaseizinger — COMMENTED** [review]
Also needs a changelog entry. Is there an easy way to test this? I think attempting to listen on the same port should do it right? We don't actually have to establish connections so it should be a fairly small test :)

File: transports/quic/Cargo.toml (hunk 3 above)
Comment (jxs) [reply transports/quic/Cargo.toml]: Yes I checked, but we are not using it. Basically `all` enables all the features, even the ones that are not available on all platforms, which currently seems to only be [`nonblocking`](https://github.com/rust-lang/socket2/blob/77e3bb9befd4a24b247343040ca766b69968951d/src/socket.rs#L371-L373) which we are not using.

File: transports/quic/src/transport.rs (hunk 4 above)
Comment (jxs) [reply transports/quic/src/transport.rs]: yup, makes sense much more elegant, thanks Thomas. Updated :)

**Review by jxs — COMMENTED** [review]
> Also needs a changelog entry. Is there an easy way to test this? I think attempting to listen on the same port should do it right? We don't actually have to establish connections so it should be a fairly small test :)

Thanks, updated changelog and added a test ptal Thomas.

File: transports/quic/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,9 @@
+## 0.9.1-alpha
+- Allow listening on ipv4 and ipv6 seperately.
```
Comment (thomaseizinger) [inline transports/quic/CHANGELOG.md]:
```suggestion
## 0.9.1-alpha - unreleased

- Allow listening on ipv4 and ipv6 seperately.
```

File: transports/quic/CHANGELOG.md [hunk 6]
```diff
@@ -1,3 +1,10 @@
+## 0.9.1-alpha - unreleased
+
+- Allow listening on ipv4 and ipv6 seperately.
```
Comment (thomaseizinger) [inline transports/quic/CHANGELOG.md]:
```suggestion
- Allow listening on ipv4 and ipv6 separately.
```

File: transports/quic/Cargo.toml
Comment (thomaseizinger) [inline transports/quic/Cargo.toml:1]: You'll need to bump the version in here.

File: transports/quic/Cargo.toml [hunk 7]
```diff
@@ -24,6 +24,7 @@ rand = "0.8.5"
 rustls = { version = "0.21.2", default-features = false }
 thiserror = "1.0.44"
 tokio = { version = "1.29.1", default-features = false, features = ["net", "rt", "time"], optional = true }
+socket2 = { version = "0.5.3" }
```
Comment (thomaseizinger) [inline transports/quic/Cargo.toml]:
```suggestion
socket2 = "0.5.3"
```

File: transports/quic/src/transport.rs [hunk 8]
```diff
@@ -888,4 +906,25 @@ mod test {
             .unwrap();
         assert!(!transport.dialer.contains_key(&SocketFamily::Ipv4));
     }
+
+    #[cfg(feature = "tokio")]
+    #[tokio::test]
+    async fn test_listens_ipv4_ipv6_separately() {
```
Comment (thomaseizinger) [inline transports/quic/src/transport.rs:911]: Can you confirm that this test fails without the fix?

**Review by thomaseizinger — COMMENTED** [review]
A few more things, otherwise LGTM!

Thanks @jxs! :)

File: transports/quic/src/transport.rs [hunk 9]
```diff
@@ -172,6 +173,22 @@ impl<P: Provider> GenTransport<P> {
...
         }
     }
+
+    fn create_socket(&self, socket_addr: SocketAddr) -> io::Result<UdpSocket> {
+        let domain = if socket_addr.is_ipv4() {
+            Domain::IPV4
+        } else {
+            Domain::IPV6
+        };
+        let socket = Socket::new(domain, Type::DGRAM, Some(socket2::Protocol::UDP))?;
```
Comment (mxinden) [inline transports/quic/src/transport.rs]:
```suggestion
        let socket = Socket::new(Domain::for_address(socket_addr), Type::DGRAM, Some(socket2::Protocol::UDP))?;
```

How about using [`for_addr`](https://docs.rs/socket2/latest/socket2/struct.Domain.html#method.for_address) here and in `libp2p-tcp`?

**Review by mxinden — COMMENTED** [review]
Small suggestion. Otherwise looks good to me. Thank you @jxs.

File: transports/quic/Cargo.toml
Comment (jxs) [reply transports/quic/Cargo.toml:1]: thanks, bumped!

File: transports/quic/Cargo.toml (hunk 7 above)
Comment (jxs) [reply transports/quic/Cargo.toml]: thanks :grin:

File: transports/quic/src/transport.rs (hunk 8 above)
Comment (jxs) [reply transports/quic/src/transport.rs:911]: yeah I confirmed before submitting, it fails without the fix.

File: transports/quic/src/transport.rs (hunk 9 above)
Comment (jxs) [reply transports/quic/src/transport.rs]: right, makes total sense. Thanks Max updated :) I can submit the fix for `libp2p-tcp` on another PR.

**Review by mxinden — APPROVED** [review]

**Comment by thomaseizinger** [comment]
@jxs The lockfile doesn't seem to be up-to-date.

**Comment by jxs** [comment]
Thanks for the ping Thomas, updated!

**Comment by jxs** [comment]
can we release 0.9.1-alpha @mxinden? I can then submit a PR to your [`rust-libp2p-server`](https://github.com/mxinden/rust-libp2p-server/) enabling it

**Comment by mxinden** [comment]
> can we release 0.9.1-alpha @mxinden?

Just created https://github.com/libp2p/rust-libp2p/pull/4312.





> I can then submit a PR to your [`rust-libp2p-server`](https://github.com/mxinden/rust-libp2p-server/) enabling it

No need. Will be included in the monorepo soon. See https://github.com/libp2p/rust-libp2p/pull/4311.
