### PR TITLE
fix: ensure `Multiaddr`s are `/p2p` terminated where possible

### LINKED ISSUE #4573: Mismatch with the usage of fully and non-fully qualified multiaddr (/p2p suffix)
## Summary

There seems to be no uniformization with the use of fully-qualified `multiaddr` (ie. with `p2p` suffix). This leads to unfortunate side-effects. 

For example, like it was mentionned in #2280, `multiaddr` are stored fully-qualified in `kad` behaviour, but they are stored not fully-qualified in `identify` behaviour.

### The `identify` case

In `identify`, the cache is constructed with addresses received from the `listen_addrs` fields which do not contains the `/p2p/` part (due to back and forth conversions between `MultiAddr` and `SocketAddr`).

However, removal of such addresses occurrs on `DialError`

https://github.com/libp2p/rust-libp2p/blob/ecdd0ff7677e59af1a1fa63de170e16f75a94f76/protocols/identify/src/behaviour.rs#L389-L397

and on `ConnectionEstablished::failed_addresses` 

https://github.com/libp2p/rust-libp2p/blob/ecdd0ff7677e59af1a1fa63de170e16f75a94f76/protocols/identify/src/behaviour.rs#L218-L222

with fully-qualified multiaddr. This result in addresses never being removed since `/ip4/127.0.0.1/tcp/4001/p2p/Qm...` does not match `/ip4/127.0.0.1/tcp/4001`. 

### The `kad` case

With the current implementation of the kademlia behaviour, events like `ConnectionEstablished` and `DialError` always contain fully-qualified multiaddr. 

But the application can also manually add multiaddresses into the k-bucket (with the `add_address` method) : if we call `add_address` with a fully-qualified multiaddr it will successfully be removed when a `DialError` occurrs, but if we call `add_address` with a non-fully-qualified multiaddr it will never be removed (it might be an expected behaviour for a bootnode for example, we are not sure about it).

Also, non-fully-qualified addresses already present will be duplicated (with `/p2p` suffix) on a `ConnectionEstablished` event as a dialer.

## Expected behaviour

We would expect to have a coherent behaviour  when using multiaddr with or without `/p2p/` suffix.

It would be nice if the documentation specify whether we should provide fully or non-fully qualified addresses (and the possible side effect if there is any). 

## Actual behaviour

Mixed of full and non-full qualified leads to addresses never being removed from the identify cache and the DHT.

### The `identify` case

We have two possible solutions to this problem :
1. ensure that only fully-qualified multiaddr are inserted into the cache
2. keep non-fully-qualified multiaddr in the cache but remove them accordingly 

### The `kad` case

Ensure that we always insert fully-qualified multiaddr when calling `add_address`.

## Version

- libp2p version : 0.52.3

## Would you like to work on fixing this bug?

Yes. We already started to work to address this issue. You can find a proof of concept in the following commit : https://github.com/libp2p/rust-libp2p/commit/d63cd80bce7c38eb5f8e51fa923dc30b2894fb1e

This was made as a starting point for a discussion.

### PR DESCRIPTION
**Pull request by stormshield-frb**
## Description

Fixes #4573.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: swarm/src/lib.rs [hunk 1]
```diff
@@ -1800,7 +1800,7 @@ impl NetworkInfo {
 ///
 /// If the given address is not yet a `p2p` address for the given peer,
 /// the `/p2p/<peer-id>` protocol is appended to the returned address.
-fn p2p_addr(peer: Option<PeerId>, addr: Multiaddr) -> Result<Multiaddr, Multiaddr> {
+pub fn p2p_addr(peer: Option<PeerId>, addr: Multiaddr) -> Result<Multiaddr, Multiaddr> {
```
Comment (thomaseizinger) [inline swarm/src/lib.rs]: Let's not make this public please. Such utility functions are not worth it to be in the public API.

Comment (thomaseizinger) [reply swarm/src/lib.rs]: Plus, on all new usage sites, the error that is produced here can never happen, meaning this function is actually not a good fit for those usecases.

**Review by thomaseizinger — COMMENTED** [review]
Thank you!

All of these changes need changelog entries please.

File: protocols/identify/src/behaviour.rs [hunk 2]
```diff
@@ -472,6 +472,7 @@ impl PeerCache {
             Some(cache) => cache,
         };
 
+        let addresses = addresses.filter_map(|a| libp2p_swarm::p2p_addr(Some(peer), a).ok());
```
Comment (mxinden) [inline protocols/identify/src/behaviour.rs]: I am confused by this change. I don't think all libp2p implementations behave the same. I would expect some to send their addresses with `/p2p` and some without. Why drop the ones without here even though we know the `PeerId`?

Why not, at the `protocol.rs` level, enforce a uniform behavior, e.g. add the `PeerId` if it is not present?

Comment (thomaseizinger) [reply protocols/identify/src/behaviour.rs]: We are not dropping them, we are adding `/p2p` suffix if it isn't there! What is confusing is that we are using the `libp2p-swarm` `p2p_addr` method which is fallible when in reality, this can't actually fail. See my comment above :)

Comment (stormshield-frb) [reply protocols/identify/src/behaviour.rs]: Absolutely. Like @thomaseizinger said, we only drop addresses when the `p2p_addr` returns an error which only happens if there already is `/p2p` suffix in the `multiaddr` but with a different `peer_id`.

I did not look at `protocol.rs`. If it is possible to patch `multiaddr` at a lower level, it would indeed be a great idea. I'm going to look at that. Thanks.

File: swarm/src/lib.rs (hunk 1 above)
Comment (stormshield-frb) [reply swarm/src/lib.rs]: No problem. I did such a thing because a common utility method was necessary in several different crates (`libp2p-identify`, `libp2p-kad` and `libp2p-mdns`) and I did not want to duplicate code. Do you have a better location in mind ? Maybe the best location would be a public method on `multiaddr` itself (but it is in a different repository).

Is it completely sure that it can never have a `/p2p` suffix in these `multiaddr` ? I though it was a good security precaution to be able to handle an already present and different `peer_id`.

On all regards, I think it could be useful to end users to have access to such a method (it is actually the case for us). Indeed, other users could rely on equality of `multiaddr` and experience side effects, the same as we do currently, if they do not handle well the presence or absence of `/p2p` suffix. If we don't want to return a result, we could also just override the present `peer_id` if it differs from the provided one.

Comment (thomaseizinger) [reply swarm/src/lib.rs]: > Maybe the best location would be a public method on `multiaddr` itself (but it is in a different repository).

Yeah I guess it is such a common usecase, it might be worth adding a utility function on `Multiaddr`. Mind proposing a patch at https://github.com/multiformats/rust-multiaddr?

Comment (stormshield-frb) [reply swarm/src/lib.rs]: Of course !! :blush: You can find it here: https://github.com/multiformats/rust-multiaddr/pull/102

Comment (stormshield-frb) [reply swarm/src/lib.rs]: As proposed by @mxinden on https://github.com/multiformats/rust-multiaddr/pull/102, this is the proposal using the `with_p2p` recently added on `Multiaddr`. 

The following part in `Cargo.toml` will of course be replaced when `Multiaddr:0.18.1` will be released : 
```toml
# multiaddr = "0.18.0"
multiaddr = { git = "https://github.com/multiformats/rust-multiaddr", rev = "d0e9ec219645ce8bd8ae7926e4b7316a67c35f84" }
```

File: protocols/identify/src/behaviour.rs (hunk 2 above)
Comment (stormshield-frb) [reply protocols/identify/src/behaviour.rs]: After some tests, I find out that some `Multiaddr` were still not `/p2p` terminated. After searching a bit, I managed to fix the issue following your idea to directly patch at the `protocol.rs` level.

However, I still have to ensure `Mutliaddr` are correctly `/p2p` terminated in the `Behaviour` since every `Multiaddr` is not necessarily constructed at the `protocol.rs` level. That is why I had to add checks in `connection_updated` and `on_address_change`. 

I have to admit that I do not know if it is necessary to handle the `Err` case in `connection_updated` and `on_address_change`. Maybe an `.expect("has never another peer_id")` might be used in these functions but I do not have sufficient perspective to make this decision.

File: swarm/CHANGELOG.md [hunk 3]
```diff
@@ -16,6 +16,8 @@
   See [PR 4715](https://github.com/libp2p/rust-libp2p/pull/4715).
 - Log `PeerId` of `Swarm` even when constructed with new `SwarmBuilder`.
   See [PR 4671](https://github.com/libp2p/rust-libp2p/pull/4671).
+- Remove private `p2p_addr` function and replace it with the newly added `with_p2p` on `Multiaddr`.
```
Comment (stormshield-frb) [inline swarm/CHANGELOG.md]: @thomaseizinger  I did not know if you wanted a changelog entry for this since it was a private function. I still created it but I can of course remove it if you think it is not necessary.

File: protocols/kad/src/behaviour.rs [hunk 4]
```diff
@@ -1210,9 +1217,13 @@ where
     fn connection_updated(
         &mut self,
         peer: PeerId,
-        address: Option<Multiaddr>,
+        mut address: Option<Multiaddr>,
         new_status: NodeStatus,
     ) {
+        if let Some(addr) = address {
+            address = addr.with_p2p(peer).ok();
+        }
```
Comment (mxinden) [inline protocols/kad/src/behaviour.rs]: Wouldn't it make most sense to do the `with_p2p` sanitizing at the borders of the crate only? Given that `connection_updated` is a private method, I would expect a caller to do the sanitization.

Do others share the same intuition?

File: protocols/kad/src/protocol.rs [hunk 5]
```diff
@@ -103,8 +103,11 @@ impl TryFrom<proto::Peer> for KadPeer {
 
         let mut addrs = Vec::with_capacity(peer.addrs.len());
         for addr in peer.addrs.into_iter() {
-            match Multiaddr::try_from(addr) {
-                Ok(a) => addrs.push(a),
+            match Multiaddr::try_from(addr).map(|addr| addr.with_p2p(node_id)) {
+                Ok(Ok(a)) => addrs.push(a),
+                Ok(Err(e)) => {
+                    log::debug!("Unable to parse multiaddr: {e} is not compatible with {node_id}");
```
Comment (mxinden) [inline protocols/kad/src/protocol.rs]:
```suggestion
                Ok(Err(a)) => {
                    log::debug!("Unable to parse multiaddr: {a} is not compatible with {node_id}");
```

Given that it is an address. Not a strong opinion.

File: swarm/CHANGELOG.md (hunk 3 above)
Comment (mxinden) [reply swarm/CHANGELOG.md]: The changelogs are for users only. Thus no need to document a change to a private function.

File: protocols/identify/src/behaviour.rs [hunk 6]
```diff
@@ -471,6 +471,7 @@ impl PeerCache {
             Some(cache) => cache,
         };
 
+        let addresses = addresses.filter_map(|a| a.with_p2p(peer).ok());
```
Comment (mxinden) [inline protocols/identify/src/behaviour.rs:469]: I find the new `with_p2p` very ergonomic.

**Review by mxinden — COMMENTED** [review]
Small comment in regards to sanitization in `libp2p-kad`. Overall this turned out very clean. Thank you!

File: swarm/CHANGELOG.md (hunk 3 above)
Comment (stormshield-frb) [reply swarm/CHANGELOG.md]: Ok thanks. I removed it :wink:

File: protocols/kad/src/behaviour.rs (hunk 4 above)
Comment (stormshield-frb) [reply protocols/kad/src/behaviour.rs]: After your comment I reconsidered why I had done this in `connection_updated` and `on_address_change`. And after re-running my tests, I found out it was no longer necessary since the case is now directly handled in `protocols.rs`. So I removed it :wink:

File: protocols/kad/src/protocol.rs (hunk 5 above)
Comment (stormshield-frb) [reply protocols/kad/src/protocol.rs]: I agree. It's changed now.

File: protocols/identify/src/behaviour.rs (hunk 6 above)
Comment (stormshield-frb) [reply protocols/identify/src/behaviour.rs:469]: Yeah I agree. Our brainstorming with Thomas was definitely worth it :blush:

File: protocols/kad/src/behaviour.rs [hunk 7]
```diff
@@ -593,6 +597,9 @@ where
         peer: &PeerId,
         address: &Multiaddr,
     ) -> Option<kbucket::EntryView<kbucket::Key<PeerId>, Addresses>> {
+        let Ok(address) = &address.to_owned().with_p2p(*peer) else {
+            return None;
```
Comment (thomaseizinger) [inline protocols/kad/src/behaviour.rs]: You should be able to use `.ok()?` here.

**Review by thomaseizinger — COMMENTED** [review]
Looks great!

File: Cargo.toml [hunk 8]
```diff
@@ -114,7 +114,8 @@ libp2p-websocket = { version = "0.43.0", path = "transports/websocket" }
 libp2p-websocket-websys = { version = "0.3.0", path = "transports/websocket-websys" }
 libp2p-webtransport-websys = { version = "0.2.0", path = "transports/webtransport-websys" }
 libp2p-yamux = { version = "0.45.0", path = "muxers/yamux" }
-multiaddr = "0.18.0"
+# multiaddr = "0.18.0"
+multiaddr = { git = "https://github.com/multiformats/rust-multiaddr", rev = "d0e9ec219645ce8bd8ae7926e4b7316a67c35f84" }
```
Comment (mxinden) [inline Cargo.toml]: Release pull request: https://github.com/multiformats/rust-multiaddr/pull/103

File: swarm/src/lib.rs [hunk 9]
```diff
@@ -513,24 +512,30 @@ where
...
-                    match dial {
-                        Ok(fut) => fut
-                            .map(|r| (address, r.map_err(TransportError::Other)))
-                            .boxed(),
-                        Err(err) => futures::future::ready((address, Err(err))).boxed(),
+            .map(|address| {
+                let address_result = match peer_id {
+                    Some(peer_id) => address.with_p2p(peer_id),
+                    None => Ok(address),
+                };
```
Comment (thomaseizinger) [inline swarm/src/lib.rs]: I think we can express this neatly using `Option::map_or`.

**Review by thomaseizinger — COMMENTED** [review]
LGTM, two minor suggestions.

Thanks for upstreaming a nice solution to `multiaddr` :)

File: swarm/src/lib.rs (hunk 9 above)
Comment (stormshield-frb) [reply swarm/src/lib.rs]: It would indeed be cleaner but I don't think it is possible without a `.clone()`.

If I do the following I get `used of moved value`:
```rust
let address_result = peer_id.map_or(Ok(address), |peer_id| address.with_p2p(peer_id));
```

I can make it work with cloning `address` like this:
```rust
let address_result = peer_id.map_or(Ok(address.clone()), |peer_id| address.with_p2p(peer_id));
```

What do you prefer ? Shorter implementation but with cloning or the current one, a little bit longer but without cloning ?

File: protocols/kad/src/behaviour.rs (hunk 7 above)
Comment (stormshield-frb) [reply protocols/kad/src/behaviour.rs]: Indeed. I'm fixing that.

File: swarm/src/lib.rs (hunk 9 above)
Comment (thomaseizinger) [reply swarm/src/lib.rs]: `Multiaddr` has an `Arc` inside so cloning is cheap :)

Comment (stormshield-frb) [reply swarm/src/lib.rs]: Oh that's right. I'm changing this then.

**Comment by thomaseizinger** [comment]
@stormshield-frb Sorry that this is taking so long. We are currently prioritizing getting the `v0.53` release out the door. Once that is done, we will focus on smaller PRs like that can be released as patch-releases.

**Comment by mxinden** [comment]
In the meantime, I don't think there is any need for forcepushing the pull request. Once I released rust-multiaddr, I will merge `master` here.

**Comment by stormshield-frb** [comment]
> In the meantime, I don't think there is any need for forcepushing the pull request. Once I released rust-multiaddr, I will merge `master` here.

Ok sure :blush: I just did it once more because with the release of `0.53` all the `CHANGELOG.md` where in conflict.

File: Cargo.toml (hunk 8 above)
Comment (mxinden) [reply Cargo.toml]: `multiaddr` `v0.18.1` is released. @stormshield-frb may I ask you to do a last update to the pull request to the new release?

Comment (stormshield-frb) [reply Cargo.toml]: Sure. It's done :wink:

**Review by thomaseizinger — APPROVED** [review]
This LGTM, thank you! :)
