### PR TITLE
fix(kad): don't assume `QuerId`s are unique

### LINKED ISSUE #4948: bootstrap triggers a debug_assert
### Summary

We are encountering a strange bug in `protocols/kad/src/handler.rs:queue_new_stream` : the `debug_assert` is reached.

https://github.com/libp2p/rust-libp2p/blob/4d7a535c7fa750ba88622e7d7cbbbbbb6884985c/protocols/kad/src/handler.rs#L582-L585

After doing some heavy diagnostics, we have concluded there does not seem to be a bug with `FuturesMap` (as we thought at first).

Indeed, for some reason (that we do not fully understand, and we do not know if it is normal or not), a `bootstrap` request seems to trigger multiple `FindeNodeReq` on the same `Connection`, with the same `QueryId` and at the same time, resulting in : 
1. multiple `FindeNodeReq` being handled in `on_behaviour_event`
2. which calls `self.pending_messages.push_back`
3. which is itself processed in the `poll` method of `Handler`
4. which calls `self.pending_messages.pop_front`
5. which calls `self.queue_new_stream`
6. which call `self.outbound_substreams.try_push`
7. which returns an error

### Expected behavior

The `debug_assert` should not be reached, no matter the circumstances. 

### Actual behavior

The `debug_assert` is reached.

### Relevant log output

_No response_

### Possible Solution

Our thought is: is it really `Expected to not create more streams than allowed` ? From our perspective, there could be some reasons why we try to create a stream even if there is already one for the corresponding request.

Indeed, is there something preventing the libp2p to not emit `HandlerIn` event on the same `Handler` and with the same `QueryId` while the previous one has not been handled ? It does not seem to be the case when reading the `on_behaviour_event` implementation with all the `self.pending_messages.push_back()`.

Honestly, we are not quite sure where this error is coming from. The peer that was trying to be reached did trigger the timeout of the `TimeoutFuture` so maybe it is related, but we are not sure.

### Version

master branch from yesterday (11/27/2023): dfce3ccecaab40c09b83d67beb914a6a37bc86ca

### Would you like to work on fixing this bug ?

Yes

### PR DESCRIPTION
**Pull request by thomaseizinger**
## Description

We mistakenly assumed that `QueryId`s are unique in that, only a single request will be emitted per `QueryId`. This is wrong. A bootstrap for example will issue multiple requests as part of the same `QueryId`. Thus, we cannot use the `QueryId` as a key for the `FuturesMap`. Instead, we use a `FuturesTupleSet` to associate the `QueryId` with the in-flight request.

Related: #4901.
Resolves: #4948.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Marked as `internal-change` because the refactoring that introduced the use of `FuturesMap` is not yet released and thus, this fix is more of a follow-up rather than a fix that is worth mentioning in the changelog.

**Comment by thomaseizinger** [comment]
cc @stormshield-frb

File: protocols/kad/src/handler.rs [hunk 1]
```diff
@@ -552,32 +553,36 @@ impl Handler {
...
+
+                stream.send(msg).await?;
+                stream.close().await?;
+
+                if !has_answer {
+                    return Ok(None);
+                }
 
-            let msg = stream.next().await.ok_or(io::ErrorKind::UnexpectedEof)??;
+                let msg = stream.next().await.ok_or(io::ErrorKind::UnexpectedEof)??;
```
Comment (stormshield-frb) [inline protocols/kad/src/handler.rs:581]: Is it ok to `stream.close()` before doing a `stream.next()` ? 

Shouldn't we do : 
```rust
stream.send(msg).await?;
if !has_answer {
    stream.close().await?;
    return Ok(None);
}
let msg = stream.next().await.ok_or(io::ErrorKind::UnexpectedEof)??;
stream.close().await?;
```
It's more a question than a suggestion. I don't know the answer :wink:

**Review by stormshield-frb — COMMENTED** [review]
Apart from my little question, LGTM :wink: Thanks @thomaseizinger

File: protocols/kad/src/handler.rs (hunk 1 above)
Comment (thomaseizinger) [reply protocols/kad/src/handler.rs:581]: `close` only closes the writing-side of the channel, we can still read from it after :)

Comment (stormshield-frb) [reply protocols/kad/src/handler.rs:581]: Oh. Ok :+1:  Make sense :joy: Thanks.

**Review by stormshield-frb — APPROVED** [review]

**Comment by thomaseizinger** [comment]
@mxinden This is a fairly important bugfix and we shouldn't release `libp2p-kad` without it.

**Review by mxinden — APPROVED** [review]
Thank you for debugging. Change looks good to me.

Has the bug already been released, if so, this needs a changelog entry. Otherwise not.

**Comment by thomaseizinger** [comment]
> Has the bug already been released, if so, this needs a changelog entry. Otherwise not.

Has not been released yet.

**Comment by thomaseizinger** [comment]
> A bootstrap for example will issue multiple requests as part of the same `QueryId`.

@mxinden Were you aware of this? Was this design intentional?

**Comment by mxinden** [comment]
> > A bootstrap for example will issue multiple requests as part of the same `QueryId`.
> 
> @mxinden Were you aware of this? Was this design intentional?

This was before my time on rust-libp2p. I am assuming that `QueryId` represents an operation like GET PUT and BOOTSTRAP, where an operation can result in many requests. I am fine with alternative designs, though I am not sure the refactoring would be worth the effort.
