### PR TITLE
fix(swarm): keep connections alive while active streams exist

### LINKED ISSUE #4520: swarm: Default to keeping connections alive whilst there are active streams
Currently, whether or not a connection has active streams does not affect its keep-alive. However, for most protocols, that is the default. The only exception that we know of here is the ping protocol.

As a first step, we want to incorporate "counting" of active streams in the keep-alive algorithm of a connection. This code lives here: https://github.com/libp2p/rust-libp2p/blob/c52a2fc3af0d4f348068746edcd8326e6f237d0e/swarm/src/connection.rs#L348-L386

To count the number of active streams on a connection, we embed an `Arc<()>` in each stream. This is possible in a backwards-compatible way because `Stream` is instantiated within this module.

- At the start of the connection, we construct an `Arc<()>` as a stream counter and store it in `Connection`.
- Every time we make a new stream, be in inbound or outbound, we `clone` this `Arc` and store it in the `Stream`
- At any point, we can check how many streams there are by calling [`Arc::strong_count`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.strong_count).

If this count reaches `1`, we know that there are no active streams on this connection. This should be a _pre-condition_ to asking the `ConnectionHandler` via `ConnectionHandler::connection_keep_alive` whether or not the connection is still needed.

Overall, this will allow protocols to not having to do any tracking on their own in regards to whether to keep the connection alive because there are still streams running on it.

As a second step, we need to introduce an "opt-out" functionality for this behaviour:

```rust
impl Stream {
	pub fn no_keep_alive(&mut self);
}
```

Internally, this needs to downgrade the `Arc<()>` to a `Weak<()>` which automatically reduces the `strong_count` and thus "ignores" this stream. The ping protocol needs to call this function on every `Stream` received to not keep the connection alive if the only remaining streams are ping-streams.

Within the same PR, we should remove any book-keeping from protocols around active streams to make sure that this mechanism actually works.

### PR DESCRIPTION
**Pull request by leonzchang**
## Description

Resolves: #4520.
Related: #4306.

## Notes & open questions
Much thanks to @thomaseizinger for the advices!

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: swarm/src/lib.rs [hunk 1]
```diff
@@ -126,7 +126,7 @@ pub use handler::{
 #[cfg(feature = "macros")]
 pub use libp2p_swarm_derive::NetworkBehaviour;
 pub use listen_opts::ListenOpts;
-pub use stream::Stream;
+pub use stream::{Stream, StreamCounter};
```
Comment (thomaseizinger) [inline swarm/src/lib.rs]: Let's keep the public API as small as possible please.

File: swarm/src/connection.rs [hunk 2]
```diff
@@ -347,46 +351,52 @@ where
...
-                (Shutdown::Later(timer, deadline), KeepAlive::Until(t)) => {
-                    if *deadline != t {
-                        *deadline = t;
-                        if let Some(new_duration) = deadline.checked_duration_since(Instant::now())
-                        {
-                            let effective_keep_alive = max(new_duration, *idle_timeout);
-
-                            timer.reset(effective_keep_alive)
+            let active_stream_count = Arc::strong_count(stream_counter);
+            if active_stream_count == 1 {
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]: Would it perhaps be easier to add this condition further down where we check `negotiating_in` etc?

Comment (thomaseizinger) [reply swarm/src/connection.rs]: Plus, it may be about time to extract this into its own function ..

File: swarm/src/stream.rs [hunk 3]
```diff
@@ -1,16 +1,40 @@
...
+    pin::Pin,
+    sync::{Arc, Weak},
+    task::{Context, Poll},
+};
 
 #[derive(Debug)]
-pub struct Stream(Negotiated<SubstreamBox>);
+pub struct Stream {
+    stream: Negotiated<SubstreamBox>,
+    stream_counter: StreamCounter,
```
Comment (thomaseizinger) [inline swarm/src/stream.rs]:
```suggestion
    counter: StreamCounter,
```

File: swarm/src/connection.rs [hunk 4]
```diff
@@ -158,6 +159,7 @@ where
     local_supported_protocols: HashSet<StreamProtocol>,
     remote_supported_protocols: HashSet<StreamProtocol>,
     idle_timeout: Duration,
+    stream_counter: Arc<()>,
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]: To make this a bit easier to understand, can you create a dedicated newtype around `Arc<()>`, named something like `ActiveStreamCounter`?

File: swarm/src/stream.rs [hunk 5]
```diff
@@ -1,16 +1,40 @@
...
+#[derive(Debug)]
+pub enum StreamCounter {
+    Arc(Arc<()>),
+    Weak(Weak<()>),
+}
 
 impl Stream {
-    pub(crate) fn new(stream: Negotiated<SubstreamBox>) -> Self {
-        Self(stream)
+    pub(crate) fn new(stream: Negotiated<SubstreamBox>, stream_counter: StreamCounter) -> Self {
```
Comment (thomaseizinger) [inline swarm/src/stream.rs]: Streams are always initialized with a strong reference right, so we should change this parameter such that any outside module doesn't need to know about `StreamCounter`.

```suggestion
    pub(crate) fn new(stream: Negotiated<SubstreamBox>, counter: Arc<()>) -> Self {
```

Comment (thomaseizinger) [reply swarm/src/stream.rs]: We can then make `StreamCounter` private to this module.

**Review by thomaseizinger — COMMENTED** [review]
Some initial thoughts, thank you for getting this started!

Before we keep on going with the implementation for too long, I'd like us to update the docs on `ConnectionHandler::connection_keep_alive` to reflect what we are changing here. If you give that a start, it will show up in the diff and I can help out with some comments :)

File: swarm/src/lib.rs (hunk 1 above)
Comment (leonzchang) [reply swarm/src/lib.rs]: fixed [8f09bb3](https://github.com/libp2p/rust-libp2p/pull/4595/commits/8f09bb347b9c971b25e2fdfcfab21bc4ef4a41f2)

File: swarm/src/connection.rs (hunk 2 above)
Comment (leonzchang) [reply swarm/src/connection.rs]: fixed [8f09bb3](https://github.com/libp2p/rust-libp2p/pull/4595/commits/8f09bb347b9c971b25e2fdfcfab21bc4ef4a41f2)

File: swarm/src/stream.rs (hunk 3 above)
Comment (leonzchang) [reply swarm/src/stream.rs]: fixed [8f09bb3](https://github.com/libp2p/rust-libp2p/pull/4595/commits/8f09bb347b9c971b25e2fdfcfab21bc4ef4a41f2)

File: swarm/src/connection.rs (hunk 4 above)
Comment (leonzchang) [reply swarm/src/connection.rs]: done [8f09bb3](https://github.com/libp2p/rust-libp2p/pull/4595/commits/8f09bb347b9c971b25e2fdfcfab21bc4ef4a41f2)

File: swarm/src/stream.rs (hunk 5 above)
Comment (leonzchang) [reply swarm/src/stream.rs]: fixed [8f09bb3](https://github.com/libp2p/rust-libp2p/pull/4595/commits/8f09bb347b9c971b25e2fdfcfab21bc4ef4a41f2)

File: swarm/Cargo.toml [hunk 6]
```diff
@@ -24,7 +24,9 @@ rand = "0.8"
 smallvec = "1.11.1"
 void = "1"
 wasm-bindgen-futures = { version = "0.4.37", optional = true }
-getrandom = { version = "0.2.9", features = ["js"], optional = true } # Explicit dependency to be used in `wasm-bindgen` feature
+getrandom = { version = "0.2.9", features = [
```
Comment (thomaseizinger) [inline swarm/Cargo.toml]: No unnecessary reformatting please.

File: protocols/ping/CHANGELOG.md [hunk 7]
```diff
@@ -1,3 +1,7 @@
+## 0.43.2
+- Calling `no_keep_alive` on every Stream received.
+  See [PR 4595](https://github.com/libp2p/rust-libp2p/pull/4595).
```
Comment (thomaseizinger) [inline protocols/ping/CHANGELOG.md]: This is only an internal change so we don't need to document it in the changelog.

```suggestion
## 0.43.2 - unreleased

<!-- Only internal changes so far, please delete this comment with the next user-facing change. -->

```

File: swarm/CHANGELOG.md [hunk 8]
```diff
@@ -1,3 +1,7 @@
+## 0.43.6
+- Keep connections alive whilst there are active streams and implement `no_keep_alive` for `Stream`
```
Comment (thomaseizinger) [inline swarm/CHANGELOG.md]:
```suggestion
## 0.43.6 - unreleased

- Default to keeping connections alive whilst there are active streams and add `Stream::no_keep_alive` to opt-out of this behaviour.
```

File: swarm/src/connection.rs [hunk 9]
```diff
@@ -482,6 +461,52 @@ fn gather_supported_protocols(handler: &impl ConnectionHandler) -> HashSet<Strea
         .collect()
 }
 
+fn handle_should_keep_alive(
+    handler: &impl ConnectionHandler,
+    shutdown: &mut Shutdown,
+    idle_timeout: &mut Duration,
+) {
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]: I think this function would be easier to understand if it would have the following signature:

```suggestion
fn compute_new_shutdown(
    handler: &impl ConnectionHandler,
    current_shutdown: &Shutdown,
    idle_timeout: Duration,
) -> Shutdown {
```

File: swarm/src/handler.rs [hunk 10]
```diff
@@ -125,10 +125,11 @@ pub trait ConnectionHandler: Send + 'static {
...
     ///
-    /// This method is called by the `Swarm` after each invocation of
-    /// [`ConnectionHandler::poll`] to determine if the connection and the associated
-    /// [`ConnectionHandler`]s should be kept alive as far as this handler is concerned
-    /// and if so, for how long.
+    /// `Swarm` checks if there are still active streams on this connection after
+    /// each invocation of [`ConnectionHandler::poll`]. If no, this method will
+    /// be called by the `Swarm` to determine if the connection and the associated
+    /// [`ConnectionHandler`]s should be kept alive as far as this handler is
+    /// concerned and if so, for how long.
```
Comment (thomaseizinger) [inline swarm/src/handler.rs]: Great start! I'd like to see something like:

> By default, connections are considered active and thus kept-alive whilst:
> - There are streams currently being upgraded, see [`InboundUpgrade`] and [`OutboundUpgrade`].
> - There are still active streams, i.e. instances of [`Stream`] where the user **did not** call [`Stream::no_keep_alive`].
> - The `ConnectionHandler` returns `Poll::Ready`.
>
> Only once none of these conditions are true do we invoke this function to determine, whether the connection should be kept alive even further.
> Note that for most protocols, this is not necessary as it represents a completely idle connection with no active and no pending streams.
>
> If you'd like to delay the shutdown of idle connections, consider configuring [`SwarmBuilder::idle_connection_timeout`] in your applications.

Based on this, I think we can delete the remaining text below apart from the `**Note**`.

File: swarm/src/stream.rs [hunk 11]
```diff
@@ -1,16 +1,37 @@
...
 impl Stream {
-    pub(crate) fn new(stream: Negotiated<SubstreamBox>) -> Self {
-        Self(stream)
+    pub(crate) fn new(stream: Negotiated<SubstreamBox>, counter: Arc<()>) -> Self {
+        let counter = StreamCounter::Arc(counter);
+        Self { stream, counter }
+    }
+
+    /// downgrade the Arc<()> to a Weak<()> which automatically
+    /// reduces the strong_count in Connection's stream_counter
```
Comment (thomaseizinger) [inline swarm/src/stream.rs]:
```suggestion
    /// Opt-out this stream from the [`Swarm`]s connection keep alive algorithm.
    ///
    /// By default, any active stream keeps a connection alive.
    /// For most protocols, this is a good default as it ensures that the protocol is completed before a connection is shut down.
    /// Some protocols like libp2p's [ping](https://github.com/libp2p/specs/blob/master/ping/ping.md) for example never complete and are of an auxiliary nature.
    /// These protocols should opt-out of the keep alive algorithm using this method.
```

**Review by thomaseizinger — COMMENTED** [review]
Great progress!

Now, to check that this actually works, we need to go through all implementations of `ConnectionHandler` and remove any code that currently duplicates this kind of stream tracking.

For example here:

https://github.com/libp2p/rust-libp2p/blob/7d1d67cad3847a845ad50d9e56b3b68ca53f5e22/protocols/identify/src/handler.rs#L317-L323

This is now unnecessary and can just return `KeepAlive::No`.

File: swarm/Cargo.toml (hunk 6 above)
Comment (leonzchang) [reply swarm/Cargo.toml]: undo toml formatting  412aa75

File: protocols/ping/CHANGELOG.md (hunk 7 above)
Comment (leonzchang) [reply protocols/ping/CHANGELOG.md]: remove internal change from changelog 412aa75

File: swarm/CHANGELOG.md (hunk 8 above)
Comment (leonzchang) [reply swarm/CHANGELOG.md]: fix document in changelog  412aa75

File: swarm/src/connection.rs (hunk 9 above)
Comment (leonzchang) [reply swarm/src/connection.rs]: yea, it's much clearer, fix in 412aa75

File: swarm/src/handler.rs (hunk 10 above)
Comment (leonzchang) [reply swarm/src/handler.rs]: fix documentation 412aa75

File: swarm/src/stream.rs (hunk 11 above)
Comment (leonzchang) [reply swarm/src/stream.rs]: fix documentation 412aa75

File: protocols/identify/src/handler.rs [hunk 12]
```diff
@@ -315,10 +315,6 @@ impl ConnectionHandler for Handler {
     }
 
     fn connection_keep_alive(&self) -> KeepAlive {
-        if !self.active_streams.is_empty() {
```
Comment (thomaseizinger) [inline protocols/identify/src/handler.rs:318]: Great! Now we just need to do something similar for **all** other protocols, i.e. everything under `protocols/`!

Let me know if you've got any questions :)

**Review by thomaseizinger — COMMENTED** [review]
Great progress!

File: protocols/identify/src/handler.rs (hunk 12 above)
Comment (leonzchang) [reply protocols/identify/src/handler.rs:318]: Kinda confused about this one. We need to go through all implementations of ConnectionHandler `connection_keep_alive` function and remove any duplicate stream tracking code?

Comment (thomaseizinger) [reply protocols/identify/src/handler.rs:318]: > We need to go through all implementations of ConnectionHandler `connection_keep_alive` function and remove any duplicate stream tracking code?

At some point, yes! The end goal of this effort is to make `connection_keep_alive` optional to implement. See https://github.com/libp2p/rust-libp2p/issues/4306.

I think for the most part this should be fairly trivial. If you run into any more complicated ones, feel free to raise a comment. We don't need to strictly remove it within this PR as nothing fails if it is still there. It is just redundant code now because we are doing all the stream-tracking within `Connection`.

We can definitely postpone some of this into follow-up issues but it would be great to get at least all the easy ones like `libp2p-identify` done!

File: swarm/src/connection.rs (hunk 2 above)
Comment (thomaseizinger) [reply swarm/src/connection.rs]: What I meant was to do:

```rust
                if negotiating_in.is_empty()
                    && negotiating_out.is_empty()
                    && requested_substreams.is_empty()
					&& Arc::strong_count(stream_counter) == 1
```

I think it should be fine to always compute the shutdown but only have it take effect once all streams are gone.

Comment (thomaseizinger) [reply swarm/src/connection.rs]: In fact, it is the current behaviour that we always compute the shutdown but only consult it once all negotiated streams are finished.

Comment (leonzchang) [reply swarm/src/connection.rs]: fix 1322ff3

File: protocols/identify/src/handler.rs (hunk 12 above)
Comment (leonzchang) [reply protocols/identify/src/handler.rs:318]: remove stream tracking code c931771

File: protocols/kad/src/handler.rs [hunk 13]
```diff
@@ -491,8 +488,6 @@ impl Handler {
             }
         }
 
-        let keep_alive = KeepAlive::Until(Instant::now() + idle_timeout);
```
Comment (thomaseizinger) [inline protocols/kad/src/handler.rs]: Hmm, this isn't a clean refactoring at the moment because we are now removing a piece of functionality here: The `idle_timeout`. Whilst we do want to remove that (see https://github.com/libp2p/rust-libp2p/issues/3844), I'd like us to deprecate this functionality first to ensure users don't run into any surprises.

I think for this PR, can't transition any of the protocols that still use `KeepAlive::Until` so we'll have to revert this bit here.

File: protocols/perf/src/client/handler.rs [hunk 14]
```diff
@@ -186,18 +183,6 @@ impl ConnectionHandler for Handler {
             }
         }
 
-        if self.outbound.is_empty() {
-            match self.keep_alive {
-                KeepAlive::Yes => {
-                    self.keep_alive = KeepAlive::Until(Instant::now() + Duration::from_secs(10));
```
Comment (thomaseizinger) [inline protocols/perf/src/client/handler.rs]: Same here, we need to remove `KeepAlive::Until` first before we can change this.

File: protocols/relay/src/priv_client/handler.rs [hunk 15]
```diff
@@ -489,10 +489,7 @@ impl ConnectionHandler for Handler {
         }
 
         // Update keep-alive handling.
-        if matches!(self.reservation, Reservation::None)
-            && self.alive_lend_out_substreams.is_empty()
-            && self.circuit_deny_futs.is_empty()
-        {
+        if matches!(self.reservation, Reservation::None) && self.circuit_deny_futs.is_empty() {
```
Comment (thomaseizinger) [inline protocols/relay/src/priv_client/handler.rs]: `circuit_deny_futs` also contains streams so it is implicitly covered. You can remove this bit!

File: protocols/relay/src/behaviour/handler.rs [hunk 16]
```diff
@@ -879,7 +879,6 @@ impl ConnectionHandler for Handler {
         if self.reservation_request_future.is_none()
             && self.circuit_accept_futures.is_empty()
             && self.circuit_deny_futures.is_empty()
-            && self.alive_lend_out_substreams.is_empty()
             && self.circuits.is_empty()
             && self.active_reservation.is_none()
```
Comment (thomaseizinger) [inline protocols/relay/src/behaviour/handler.rs]: Everything but `active_reservation` contains streams so we should be able to remove all other conditions from this `if`.

**Review by thomaseizinger — COMMENTED** [review]
Thanks for making the follow-up changes!

Whilst I think we can overall merge these changes (modulo new comments), it would be much cleaner if we'd get rid of `KeepAlive::Until` first. See https://github.com/libp2p/rust-libp2p/issues/3844. Are you interested in helping out on that front too? :)

File: protocols/identify/CHANGELOG.md [hunk 17]
```diff
@@ -1,3 +1,5 @@
+## 0.43.2 - unreleased
+
 ## 0.43.1 - unreleased
```
Comment (thomaseizinger) [inline protocols/identify/CHANGELOG.md]: `0.43.1` isn't released yet so we don't need to bump the version again! :)

File: protocols/kad/CHANGELOG.md [hunk 18]
```diff
@@ -1,3 +1,5 @@
+## 0.44.7 - unreleased
```
Comment (thomaseizinger) [inline protocols/kad/CHANGELOG.md]: Same here, `0.44.6` isn't released yet so we don't need to add this here.

File: protocols/kad/src/handler.rs (hunk 13 above)
Comment (leonzchang) [reply protocols/kad/src/handler.rs]: reverted b87b155

File: protocols/perf/src/client/handler.rs (hunk 14 above)
Comment (leonzchang) [reply protocols/perf/src/client/handler.rs]: reverted b87b155

File: protocols/relay/src/priv_client/handler.rs (hunk 15 above)
Comment (leonzchang) [reply protocols/relay/src/priv_client/handler.rs]: removed b87b155

File: protocols/relay/src/behaviour/handler.rs (hunk 16 above)
Comment (leonzchang) [reply protocols/relay/src/behaviour/handler.rs]: removed b87b155

File: protocols/identify/CHANGELOG.md (hunk 17 above)
Comment (leonzchang) [reply protocols/identify/CHANGELOG.md]: fixed b87b155

File: protocols/kad/CHANGELOG.md (hunk 18 above)
Comment (leonzchang) [reply protocols/kad/CHANGELOG.md]: fixed b87b155

**Comment by leonzchang** [comment]
> Thanks for making the follow-up changes!
> 
> Whilst I think we can overall merge these changes (modulo new comments), it would be much cleaner if we'd get rid of `KeepAlive::Until` first. See #3844. Are you interested in helping out on that front too? :)

Do you mean remove `KeepAlive::Until` in `/protocols` before this branch merge?
Aye, I can try it out.

File: protocols/kad/src/handler.rs [hunk 19]
```diff
@@ -760,16 +760,6 @@ impl ConnectionHandler for Handler {
             });
         }
 
-        let no_streams = self.outbound_substreams.is_empty() && self.inbound_substreams.is_empty();
-        self.keep_alive = match (no_streams, self.keep_alive) {
-            // No open streams. Preserve the existing idle timeout.
-            (true, k @ KeepAlive::Until(_)) => k,
-            // No open streams. Set idle timeout.
-            (true, _) => KeepAlive::Until(Instant::now() + self.idle_timeout),
```
Comment (thomaseizinger) [inline protocols/kad/src/handler.rs]: Same as for gossipsub, we should deprecate `idle_timeout` first and then remove it with the next breaking release. That will reduce this function down to essentially just checking for existing streams which we no longer need to do with the changes in this PR!

**Comment by thomaseizinger** [comment]
@mxinden Would be great to get your opinion here. We can merge this early by only removing the conditions for stream checks in the protocols where we no longer use `KeepAlive::Until`. Then this could essentially be released as a patch-release.

I am tempted to do that because it just means that we are doing the bookkeeping twice but it doesn't hurt. We can always remove it at a later stage.

File: protocols/kad/src/handler.rs (hunk 19 above)
Comment (leonzchang) [reply protocols/kad/src/handler.rs]: Reverted changes e5a765f, since deprecate PR #4656 already opened

**Comment by leonzchang** [comment]
rebase master

File: protocols/relay/src/behaviour/handler.rs [hunk 20]
```diff
@@ -879,9 +879,7 @@ impl ConnectionHandler for Handler {
         if self.reservation_request_future.is_none()
             && self.circuit_accept_futures.is_empty()
             && self.circuit_deny_futures.is_empty()
-            && self.alive_lend_out_substreams.is_empty()
             && self.circuits.is_empty()
-            && self.active_reservation.is_none()
```
Comment (thomaseizinger) [inline protocols/relay/src/behaviour/handler.rs:889]: This is wrong. In fact, the only condition that should remain here is whether we have an active reservation! :)

Comment (leonzchang) [reply protocols/relay/src/behaviour/handler.rs:889]: fixed 5db7968

**Comment by thomaseizinger** [comment]
Applying `internal-change` to deactivate the changelog lint for all the changes in the protocol crates.

File: protocols/ping/src/handler.rs [hunk 21]
```diff
@@ -261,9 +261,10 @@ impl ConnectionHandler for Handler {
                     log::debug!("Inbound ping error: {:?}", e);
                     self.inbound = None;
                 }
-                Poll::Ready(Ok(stream)) => {
+                Poll::Ready(Ok(mut stream)) => {
                     log::trace!("answered inbound ping from {}", self.peer);
 
+                    stream.no_keep_alive();
```
Comment (thomaseizinger) [inline protocols/ping/src/handler.rs]: We should do the same thing for outbound streams.

**Comment by thomaseizinger** [comment]
Once https://github.com/libp2p/rust-libp2p/pull/4696 and https://github.com/libp2p/rust-libp2p/pull/4659 are merged, you should be able to delete all the `!is_empty` checks in regards to streams from all the protocols and just return `KeepAlive::No`! How beautiful!

File: protocols/ping/src/handler.rs (hunk 21 above)
Comment (leonzchang) [reply protocols/ping/src/handler.rs]: fixed 021da14

**Comment by leonzchang** [comment]
> Once #4696 and #4659 are merged, you should be able to delete all the `!is_empty` checks in regards to streams from all the protocols and just return `KeepAlive::No`! How beautiful!

applied f6531aa

File: protocols/gossipsub/src/handler.rs
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs:1]: I think we can remove the check for the outbound stream here.

File: protocols/kad/src/behaviour/test.rs [hunk 22]
```diff
@@ -73,7 +73,7 @@ fn build_node_with_config(cfg: Config) -> (Multiaddr, TestSwarm) {
         behaviour,
         local_id,
         swarm::Config::with_async_std_executor()
-            .with_idle_connection_timeout(Duration::from_secs(5)),
+            .with_idle_connection_timeout(Duration::from_secs(10)),
```
Comment (thomaseizinger) [inline protocols/kad/src/behaviour/test.rs]: We shouldn't need to increase this. Which tests fail without this?

File: swarm/src/connection.rs [hunk 23]
```diff
@@ -344,18 +352,18 @@ where
                 }
             }
 
-            // Compute new shutdown
-            if let Some(new_shutdown) =
+            if let Some(new_timeout) =
                 compute_new_shutdown(handler.connection_keep_alive(), shutdown, *idle_timeout)
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]: I think you were right about having this one _inside_ the `if` below. We shouldn't ask the handler for its keep-alive unless the connection is actually idle.

**Review by thomaseizinger — COMMENTED** [review]
I think the `dcutr::relayed::Handler` can be simplified too.

**Comment by thomaseizinger** [comment]
`OneshotHandler` should be able to get simpler too!

File: protocols/kad/src/behaviour/test.rs (hunk 22 above)
Comment (leonzchang) [reply protocols/kad/src/behaviour/test.rs]: None of them, I changed this because I found that origin default `connection_idle_timeout` duration was 10 secs in PR #4659. Should we keep origin setting or set it shorter?

File: swarm/src/connection.rs (hunk 23 above)
Comment (leonzchang) [reply swarm/src/connection.rs]: fixed `77b840e`

File: protocols/gossipsub/src/handler.rs
Comment (leonzchang) [reply protocols/gossipsub/src/handler.rs:1]: fixed 77b840e

**Comment by leonzchang** [comment]
> `OneshotHandler` should be able to get simpler too!

fixed 77b840e

File: protocols/kad/src/behaviour/test.rs (hunk 22 above)
Comment (thomaseizinger) [reply protocols/kad/src/behaviour/test.rs]: Can we get away with not setting an idle timeout at all? That would be even better!

Comment (leonzchang) [reply protocols/kad/src/behaviour/test.rs]: I think there are some tests that are based on a default timeout. https://github.com/libp2p/rust-libp2p/pull/4659#issuecomment-1764636057

File: protocols/dcutr/src/handler/relayed.rs [hunk 24]
```diff
@@ -257,10 +257,6 @@ impl ConnectionHandler for Handler {
             return KeepAlive::Yes;
         }
```
Comment (thomaseizinger) [inline protocols/dcutr/src/handler/relayed.rs]: We shouldn't actually need to check for `queued_events` because we don't call `connection_keep_alive` whilst the handler is returned `Poll::Ready` so you can remove the above (either in this PR or a separate one, up to you!)

File: protocols/gossipsub/src/handler.rs [hunk 25]
```diff
@@ -431,15 +431,6 @@ impl ConnectionHandler for Handler {
                     return KeepAlive::Yes;
```
Comment (thomaseizinger) [inline protocols/gossipsub/src/handler.rs]: If you are feeling fancy, we could now refactor this to use a match-arm guard:

```rust
match self {
	Handler::Enabled(h) if h.in_mesh => KeepAlive::Yes,
	_ => KeepAlive::No
}
```

File: protocols/kad/src/behaviour/test.rs (hunk 22 above)
Comment (thomaseizinger) [reply protocols/kad/src/behaviour/test.rs]: Okay thanks!

Can you reduce it down to 5 again then?

File: swarm/src/connection.rs [hunk 26]
```diff
@@ -57,12 +57,16 @@ use std::collections::HashSet;
...
 use std::future::Future;
 use std::sync::atomic::{AtomicUsize, Ordering};
+use std::sync::Arc;
 use std::task::Waker;
 use std::time::Duration;
 use std::{fmt, io, mem, pin::Pin, task::Context, task::Poll};
 
 static NEXT_CONNECTION_ID: AtomicUsize = AtomicUsize::new(1);
 
+///  Counter of the number of active streams on a connection
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]:
```suggestion
/// Counter for the number of active streams on a connection.
```

File: swarm/src/connection.rs [hunk 27]
```diff
@@ -157,6 +161,8 @@ where
     local_supported_protocols: HashSet<StreamProtocol>,
     remote_supported_protocols: HashSet<StreamProtocol>,
     idle_timeout: Duration,
+    /// The counter of active streams
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]: Bit redundant if you ask me :)

```suggestion
```

File: swarm/src/connection.rs [hunk 28]
```diff
@@ -57,12 +57,16 @@ use std::collections::HashSet;
...
 use std::sync::atomic::{AtomicUsize, Ordering};
+use std::sync::Arc;
 use std::task::Waker;
 use std::time::Duration;
 use std::{fmt, io, mem, pin::Pin, task::Context, task::Poll};
 
 static NEXT_CONNECTION_ID: AtomicUsize = AtomicUsize::new(1);
 
+///  Counter of the number of active streams on a connection
+type ActiveStreamCounter = Arc<()>;
```
Comment (thomaseizinger) [inline swarm/src/connection.rs]: I'd have a slight preference for making this a proper new-type actually. I think for people not so familiar with Rust, having `Arc<()>` flying around here is not very intuitive :)

**Review by thomaseizinger — COMMENTED** [review]
Great progress!

I am really looking forward to this landing. It already greatly simplifies the implementation of pretty much all protocols :tada:

**Comment by thomaseizinger** [comment]
Note to myself: Test if we can remove `alive_lend_out_substreams` from `libp2p-relay` now.

File: protocols/kad/src/behaviour/test.rs (hunk 22 above)
Comment (leonzchang) [reply protocols/kad/src/behaviour/test.rs]: changed 3e75728

File: protocols/dcutr/src/handler/relayed.rs (hunk 24 above)
Comment (leonzchang) [reply protocols/dcutr/src/handler/relayed.rs]: removed 3e75728

File: protocols/gossipsub/src/handler.rs (hunk 25 above)
Comment (leonzchang) [reply protocols/gossipsub/src/handler.rs]: fixed 3e75728

File: swarm/src/connection.rs (hunk 26 above)
Comment (leonzchang) [reply swarm/src/connection.rs]: fixed 3e75728

File: swarm/src/connection.rs (hunk 27 above)
Comment (leonzchang) [reply swarm/src/connection.rs]: removed 3e75728

File: swarm/src/stream.rs [hunk 29]
```diff
@@ -1,16 +1,43 @@
...
+
+    /// Opt-out this stream from the [Swarm](crate::Swarm)s connection keep alive algorithm.
+    ///
+    /// By default, any active stream keeps a connection alive. For most protocols,
+    /// this is a good default as it ensures that the protocol is completed before
+    /// a connection is shut down.
+    /// Some protocols like libp2p's [ping](https://github.com/libp2p/specs/blob/master/ping/ping.md)
+    /// for example never complete and are of an auxiliary nature.
+    /// These protocols should opt-out of the keep alive algorithm using this method.
+    pub fn no_keep_alive(&mut self) {
```
Comment (thomaseizinger) [inline swarm/src/stream.rs]:
```suggestion
    pub fn ignore_for_keep_alive(&mut self) {
```

Thinking more about this, I think this is a more descriptive name. What do you think?

File: swarm/src/stream.rs [hunk 30]
```diff
@@ -1,16 +1,43 @@
...
 
 impl Stream {
-    pub(crate) fn new(stream: Negotiated<SubstreamBox>) -> Self {
-        Self(stream)
+    pub(crate) fn new(stream: Negotiated<SubstreamBox>, counter: Arc<()>) -> Self {
+        let counter = StreamCounter::Arc(counter);
+        Self { stream, counter }
+    }
+
+    /// Opt-out this stream from the [Swarm](crate::Swarm)s connection keep alive algorithm.
```
Comment (thomaseizinger) [inline swarm/src/stream.rs]:
```suggestion
    /// Ignore this stream in the [Swarm](crate::Swarm)'s connection-keep-alive algorithm.
```

File: protocols/relay/src/behaviour/handler.rs [hunk 31]
```diff
@@ -615,13 +611,8 @@ impl ConnectionHandler for Handler {
...
 
-    fn connection_keep_alive(&self) -> KeepAlive {
-        match self.idle_at {
-            Some(idle_at) if Instant::now().duration_since(idle_at) > Duration::from_secs(10) => {
-                KeepAlive::No
-            }
-            _ => KeepAlive::Yes,
-        }
+    fn connection_keep_alive(&self) -> bool {
+        !matches!(self.idle_at, Some(idle_at) if Instant::now().duration_since(idle_at) > Duration::from_secs(10))
```
Comment (thomaseizinger) [inline protocols/relay/src/behaviour/handler.rs]: I love a good one-liner but this is a bit much :sweat_smile: 

Can we write this in multiple steps?

Comment (thomaseizinger) [reply protocols/relay/src/behaviour/handler.rs]: If it helps, https://github.com/libp2p/rust-libp2p/pull/4692 should merge soon so you can use `let else` as well.

File: protocols/relay/src/priv_client/handler.rs [hunk 32]
```diff
@@ -319,28 +319,12 @@ impl ConnectionHandler for Handler {
         }
     }
 
-    fn connection_keep_alive(&self) -> KeepAlive {
+    fn connection_keep_alive(&self) -> bool {
         if self.reservation.is_some() {
-            return KeepAlive::Yes;
+            return true;
```
Comment (thomaseizinger) [inline protocols/relay/src/priv_client/handler.rs]: Couldn't you just return `self.reservation.is_some()` directly?

File: swarm/CHANGELOG.md [hunk 33]
```diff
@@ -6,6 +6,8 @@
   See [PR 4225](https://github.com/libp2p/rust-libp2p/pull/4225).
 - Remove deprecated `keep_alive_timeout` in `OneShotHandlerConfig`.
   See [PR 4677](https://github.com/libp2p/rust-libp2p/pull/4677).
+- Add `ConnectionHandler::connection_keep_alive` default implementation that returns `KeepAlive::No`.
+  See [PR 4703](https://github.com/libp2p/rust-libp2p/pull/4703).
```
Comment (thomaseizinger) [inline swarm/CHANGELOG.md]: Needs to mention the rename as well :)

File: swarm/src/handler.rs [hunk 34]
```diff
@@ -179,7 +170,7 @@ pub trait ConnectionHandler: Send + 'static {
     /// Creates a new [`ConnectionHandler`] that selects either this handler or
     /// `other` by delegating methods calls appropriately.
     ///
-    /// > **Note**: The largest `KeepAlive` returned by the two handlers takes precedence,
+    /// > **Note**: The smallest value returned by the two handlers takes precedence,
```
Comment (thomaseizinger) [inline swarm/src/handler.rs]: Does smallest make sense here? It should be a logical OR right?

File: swarm/src/handler.rs [hunk 35]
```diff
@@ -125,25 +124,17 @@ pub trait ConnectionHandler: Send + 'static {
...
-    /// closed and this handler destroyed immediately.
-    ///
-    /// Returning [`KeepAlive::Until`] indicates that the connection may be closed
-    /// and this handler destroyed after the specified `Instant`.
-    ///
-    /// Returning [`KeepAlive::Yes`] indicates that the connection should
-    /// be kept alive until the next call to this method.
+    /// This method is an optional implementation and can be called by the `Swarm` after
+    /// each invocation of [`ConnectionHandler::poll`] to determine if the connection
+    /// and the associated [`ConnectionHandler`]s should be kept alive.
```
Comment (thomaseizinger) [inline swarm/src/handler.rs]: We should bring back the docs we had here earlier that mention the keep alive algorithm based on stream counting.

We should also mention:

- How users can opt out of it (`Stream::no_keep_alive`)
- That this is only called once the `ConnectionHandler` is idle (i.e. returns `Poll::Pending`) AND we don't have active stream upgrades AND we don't have active streams.

In a nutshell, we should just recommend users that they usually don't need to override this unless they want their connection to be kept alive _beyond_ any activity on it.

File: swarm/src/handler/multi.rs [hunk 36]
```diff
@@ -230,12 +229,12 @@ where
...
     }
 
-    fn connection_keep_alive(&self) -> KeepAlive {
+    fn connection_keep_alive(&self) -> bool {
         self.handlers
             .values()
             .map(|h| h.connection_keep_alive())
-            .max()
-            .unwrap_or(KeepAlive::No)
+            .min()
```
Comment (thomaseizinger) [inline swarm/src/handler/multi.rs]: Is this correct? If any of these returns `true`, we should return `true` here.

File: swarm/src/handler/pending.rs [hunk 37]
```diff
@@ -56,8 +56,8 @@ impl ConnectionHandler for PendingConnectionHandler {
         void::unreachable(v)
     }
 
-    fn connection_keep_alive(&self) -> KeepAlive {
-        KeepAlive::No
+    fn connection_keep_alive(&self) -> bool {
+        false
     }
```
Comment (thomaseizinger) [inline swarm/src/handler/pending.rs]: Given the new default implementation, we can remove this everywhere where we statically return `false`.

File: swarm/src/handler/select.rs [hunk 38]
```diff
@@ -208,8 +208,8 @@ where
         }
     }
 
-    fn connection_keep_alive(&self) -> KeepAlive {
-        cmp::max(
+    fn connection_keep_alive(&self) -> bool {
+        cmp::min(
```
Comment (thomaseizinger) [inline swarm/src/handler/select.rs]: I think this should be `max` but overall, it is probably easier to understand if we write it as `|`.

File: swarm/src/keep_alive.rs
Comment (thomaseizinger) [inline swarm/src/keep_alive.rs:1]: This entire module is deprecated so you can remove it as part of this PR :tada:

**Review by thomaseizinger — COMMENTED** [review]
Great progress!

I've left a few more comments. Hope you don't mind :)
Also, if you are interested, we maintainers will meet later today: https://github.com/libp2p/rust-libp2p/discussions/4713. If you want, you can present your work here or also just listen in :)

File: swarm/src/handler/multi.rs (hunk 36 above)
Comment (leonzchang) [reply swarm/src/handler/multi.rs]: I misunderstand `Ord` impl on `KeepAlive` , reverted it back 69a4a8b already

File: swarm/src/handler/select.rs (hunk 38 above)
Comment (leonzchang) [reply swarm/src/handler/select.rs]: I misunderstand `Ord` impl on `KeepAlive` , reverted it back 69a4a8b already

File: swarm/src/stream.rs (hunk 29 above)
Comment (leonzchang) [reply swarm/src/stream.rs]: Agree with this, it would be straightforward.

File: swarm/src/handler/pending.rs (hunk 37 above)
Comment (leonzchang) [reply swarm/src/handler/pending.rs]: removed 3d10eb4

File: swarm/CHANGELOG.md (hunk 33 above)
Comment (leonzchang) [reply swarm/CHANGELOG.md]: updated 3d10eb4

File: swarm/src/stream.rs (hunk 30 above)
Comment (leonzchang) [reply swarm/src/stream.rs]: fixed 3d10eb4

File: protocols/relay/src/behaviour/handler.rs (hunk 31 above)
Comment (leonzchang) [reply protocols/relay/src/behaviour/handler.rs]: fixed 3d10eb4

File: protocols/relay/src/priv_client/handler.rs (hunk 32 above)
Comment (leonzchang) [reply protocols/relay/src/priv_client/handler.rs]: fixed 3d10eb4

File: swarm/src/handler.rs (hunk 35 above)
Comment (leonzchang) [reply swarm/src/handler.rs]: updated 3d10eb4

File: swarm/src/keep_alive.rs
Comment (leonzchang) [reply swarm/src/keep_alive.rs:1]: removed 3d10eb4

**Review by thomaseizinger — APPROVED** [review]
I updated the docs a bit. This is ready from my end, thank you so much for helping out with this! I am super stoked to land this :tada: 

@mxinden Please have a look!

File: swarm/src/connection.rs (hunk 28 above)
Comment (leonzchang) [reply swarm/src/connection.rs]: https://github.com/libp2p/rust-libp2p/pull/4595#discussion_r1367989313 should be already resolved. 
fixed 0c9e3ee

File: protocols/gossipsub/src/behaviour.rs [hunk 39]
```diff
@@ -3265,7 +3265,6 @@ where
     type ConnectionHandler = Handler;
     type ToSwarm = Event;
 
-    #[allow(deprecated)]
```
Comment (mxinden) [inline protocols/gossipsub/src/behaviour.rs:3268]: Is this change related to this pull request?

File: protocols/gossipsub/src/handler.rs [hunk 40]
```diff
@@ -424,26 +423,8 @@ impl ConnectionHandler for Handler {
...
-                }
-
-                #[allow(deprecated)]
-                KeepAlive::No
-            }
-            Handler::Disabled(_) => KeepAlive::No,
-        }
+    fn connection_keep_alive(&self) -> bool {
+        matches!(self, Handler::Enabled(h) if h.in_mesh)
     }
```
Comment (mxinden) [inline protocols/gossipsub/src/handler.rs:428]: Very clean!

File: protocols/ping/src/handler.rs [hunk 41]
```diff
@@ -261,9 +257,10 @@ impl ConnectionHandler for Handler {
                     log::debug!("Inbound ping error: {:?}", e);
                     self.inbound = None;
                 }
-                Poll::Ready(Ok(stream)) => {
+                Poll::Ready(Ok(mut stream)) => {
                     log::trace!("answered inbound ping from {}", self.peer);
 
+                    stream.ignore_for_keep_alive();
```
Comment (mxinden) [inline protocols/ping/src/handler.rs]: Why not call `ignore_for_keep_alive` as soon as the stream is handed to the `ConnectionHandler`, i.e. within `on_connection_event`?

File: protocols/relay/src/behaviour/handler.rs [hunk 42]
```diff
@@ -615,13 +611,12 @@ impl ConnectionHandler for Handler {
...
-                KeepAlive::No
-            }
-            _ => KeepAlive::Yes,
-        }
+    fn connection_keep_alive(&self) -> bool {
+        let Some(idle_at) = self.idle_at else {
+            return true;
+        };
+
+        Instant::now().duration_since(idle_at) <= Duration::from_secs(10)
```
Comment (mxinden) [inline protocols/relay/src/behaviour/handler.rs:619]: let-else :rocket:

File: swarm/CHANGELOG.md [hunk 43]
```diff
@@ -6,6 +6,11 @@
   See [PR 4225](https://github.com/libp2p/rust-libp2p/pull/4225).
 - Remove deprecated `keep_alive_timeout` in `OneShotHandlerConfig`.
   See [PR 4677](https://github.com/libp2p/rust-libp2p/pull/4677).
+- Simplify the connection keep-alive algorithm.
+  Connections are now kept alive by default if there are active `Stream`s on it.
+  As a result, the `ConnectionHandler::connection_keep_alive` method now has a default implementation that returns `false`.
```
Comment (mxinden) [inline swarm/CHANGELOG.md]:
```suggestion
  In case of no active `Stream`s the `ConnectionHandler` is asked whether it wants to keep the connection alive via  `ConnectionHandler::connection_keep_alive` which defaults to `false`.
```

Would be easier for me to understand, more specifically that `connection_keep_alive` is only called in case there are no active streams.

File: swarm/CHANGELOG.md [hunk 44]
```diff
@@ -6,6 +6,11 @@
...
+  See its documentation for more details.
```
Comment (mxinden) [inline swarm/CHANGELOG.md]:
```suggestion
  See documentation on `ConnectionHandler::connection_keep_alive` for more details.
```

File: swarm/src/connection.rs [hunk 45]
```diff
@@ -344,19 +349,19 @@ where
...
-            {
-                *shutdown = new_shutdown;
-            }
-
             // Check if the connection (and handler) should be shut down.
-            // As long as we're still negotiating substreams, shutdown is always postponed.
+            // As long as we're still negotiating substreams or have any active streams shutdown is always postponed.
             if negotiating_in.is_empty()
                 && negotiating_out.is_empty()
                 && requested_substreams.is_empty()
```
Comment (mxinden) [inline swarm/src/connection.rs:353]: Either of these being false, e.g. `negotiating_in` being **not** empty, implies progress, right? Should we add an `else` that sets `shutdown = Shutdown::None`?

Otherwise the idle timer (`Shutdown::Later`) is ticking even though the connection wasn't idle throughout the entire lifetime of the timer.

(This wasn't relevant before, as there wasn't a default implementation on `ConnectionHandler::connection_keep_alive` that defaulted to `false`. In other words, `shutdown` was set to `Shutdown::None` on progress.)

File: swarm/src/handler.rs [hunk 46]
```diff
@@ -123,27 +122,27 @@ pub trait ConnectionHandler: Send + 'static {
...
-    /// > **Note**: The connection is always closed and the handler destroyed
-    /// > when [`ConnectionHandler::poll`] returns an error. Furthermore, the
-    /// > connection may be closed for reasons outside of the control
-    /// > of the handler.
-    fn connection_keep_alive(&self) -> KeepAlive;
+    /// ## Exceptions
+    ///
+    /// - Protocols like [circuit-relay v2](https://github.com/libp2p/specs/blob/master/relay/circuit-v2.md) need to keep a connection alive beyond these circumstances and can thus override this method.
+    /// - Protocols like [ping](https://github.com/libp2p/specs/blob/master/ping/ping.md) **don't** want to keep a connection alive despite an active streams.
+    /// In that case, protocol authors can use [`Stream::ignore_for_keep_alive`](crate::Stream::ignore_for_keep_alive) to opt-out a particular stream from the keep-alive algorithm.
```
Comment (mxinden) [inline swarm/src/handler.rs:142]: Thanks!

**Review by mxinden — COMMENTED** [review]
Lots of simplifications! Well done. Thanks. Also great work on the documentation.

I have a couple of comments. I am sorry in case these have been discussed before.

File: protocols/gossipsub/src/behaviour.rs (hunk 39 above)
Comment (thomaseizinger) [reply protocols/gossipsub/src/behaviour.rs:3268]: Yes because we use `Until` here before. I think it is a left-over.

File: protocols/ping/src/handler.rs (hunk 41 above)
Comment (thomaseizinger) [reply protocols/ping/src/handler.rs]: Yes good call, we should do that as early as possible.

Comment (leonzchang) [reply protocols/ping/src/handler.rs]: changed this call within `on_connection_event ` 92823e1

File: swarm/CHANGELOG.md (hunk 43 above)
Comment (leonzchang) [reply swarm/CHANGELOG.md]: updated 92823e1

File: swarm/CHANGELOG.md (hunk 44 above)
Comment (leonzchang) [reply swarm/CHANGELOG.md]: updated 92823e1

File: swarm/src/connection.rs (hunk 45 above)
Comment (leonzchang) [reply swarm/src/connection.rs:353]: This makes sense to me. We should set `shutdown = Shutdown::None` while it isn't idle.

File: swarm/src/connection.rs (hunk 28 above)
Comment (thomaseizinger) [reply swarm/src/connection.rs]: What I meant was wrapping it in a new struct:

```rust
pub struct ActiveStreamCounter(Arc<()>);

impl ActiveStreamCounter {
	pub fn num_alive_streams(&self) -> usize {
		Arc::strong_count(&self.0)
	}
}
```

We should probably move it into the `stream` module so we can get the `Arc<()>` out of it when we construct a new `Stream`.

Comment (leonzchang) [reply swarm/src/connection.rs]: Oh sorry, adding this 41662a4. I also refactor stream a bit. Since we only care about `Arc::strong_count`, we could drop stream `ActiveStreamCounter` when calling `ignore_for_keep_alive`.

Comment (thomaseizinger) [reply swarm/src/connection.rs]: Nice! Well spotted!

**Review by thomaseizinger — APPROVED** [review]
Great work!

**Review by mxinden — APPROVED** [review]
Well done!

**Comment by mxinden** [comment]
@romanb you might enjoy seeing your proposal from a couple of years ago finally implemented.
