### PR TITLE
chore: fix clippy lints

### LINKED ISSUE #6194: CI is failing for clippy (beta) and check rust-doc intra doc links
### Summary

The CI pipeline is failing now for clippy (beta) and check rust-doc intra doc links steps for PRs that don't touch the modules emitting the errors.

### Expected behavior

The CI pipeline should succeed if no changes have been made to these files.

### Actual behavior

The CI pipeline is failing when no changes have been made to these files.

### Relevant log output

```shell
warning: build failed, waiting for other jobs to finish...
error: unresolved link to `Event::OutboundQueryProgressed{QueryResult::GetClosestPeers}`
Error:    --> protocols/kad/src/behaviour.rs:727:11
    |
727 |     /// [`Event::OutboundQueryProgressed{QueryResult::GetClosestPeers}`].
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the enum `Event` has no variant or associated item named `OutboundQueryProgressed{QueryResult`
    |
    = note: requested on the command line with `-D rustdoc::broken-intra-doc-links`

error: unresolved link to `Event::OutboundQueryProgressed{QueryResult::GetClosestPeers}`
Error:    --> protocols/kad/src/behaviour.rs:740:11
    |
740 |     /// [`Event::OutboundQueryProgressed{QueryResult::GetClosestPeers}`].
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the enum `Event` has no variant or associated item named `OutboundQueryProgressed{QueryResult`

error: unresolved link to `Event::OutboundQueryProgressed{QueryResult::GetRecord}`
Error:    --> protocols/kad/src/behaviour.rs:797:11
    |
797 |     /// [`Event::OutboundQueryProgressed{QueryResult::GetRecord}`].
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the enum `Event` has no variant or associated item named `OutboundQueryProgressed{QueryResult`

error: unresolved link to `Event::OutboundQueryProgressed{QueryResult::PutRecord}`
Error:    --> protocols/kad/src/behaviour.rs:856:11
    |
856 |     /// [`Event::OutboundQueryProgressed{QueryResult::PutRecord}`].
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the enum `Event` has no variant or associated item named `OutboundQueryProgressed{QueryResult`

error: unresolved link to `Event::OutboundQueryProgressed{QueryResult::Bootstrap}`
Error:    --> protocols/kad/src/behaviour.rs:970:24
    |
970 |     /// reported via [`Event::OutboundQueryProgressed{QueryResult::Bootstrap}`] events,
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the enum `Event` has no variant or associated item named `OutboundQueryProgressed{QueryResult`

error: unresolved link to `Event::OutboundQueryProgressed{QueryResult::StartProviding}`
Error:     --> protocols/kad/src/behaviour.rs:1023:24
     |
1023 |     /// reported via [`Event::OutboundQueryProgressed{QueryResult::StartProviding}`].
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the enum `Event` has no variant or associated item named `OutboundQueryProgressed{QueryResult`

error: unresolved link to `Event::OutboundQueryProgressed{QueryResult::GetProviders}`
Error:     --> protocols/kad/src/behaviour.rs:1059:24
     |
1059 |     /// reported via [`Event::OutboundQueryProgressed{QueryResult::GetProviders}`].
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the enum `Event` has no variant or associated item named `OutboundQueryProgressed{QueryResult`

error: could not document `libp2p-kad`
```

### Possible Solution

While I am not sure of the reason causing the CI errors. Something could have changed in the workflow yaml files.

### Version

0.56.1

### Would you like to work on fixing this bug?

No

### PR DESCRIPTION
**Pull request by jxs**
## Description

will address the intra doc links issue on a subsequent PR, the remaining [issue](https://github.com/libp2p/rust-libp2p/actions/runs/19040315461/job/54375441096?pr=6195#step:6:760) seems like a bug, opened https://github.com/rust-lang/rust-clippy/issues/16023.

### CODE REVIEW

File: protocols/dcutr/src/handler/relayed.rs [hunk 1]
```diff
@@ -148,12 +148,11 @@ impl Handler {
 
     fn on_listen_upgrade_error(
         &mut self,
-        ListenUpgradeError { error, .. }: ListenUpgradeError<
+        ListenUpgradeError { .. }: ListenUpgradeError<
             (),
             <Self as ConnectionHandler>::InboundProtocol,
         >,
     ) {
-        libp2p_core::util::unreachable(error.into_inner());
```
Comment (elenaf9) [inline protocols/dcutr/src/handler/relayed.rs:156]: Why is this statement removed?

Comment (jxs) [reply protocols/dcutr/src/handler/relayed.rs:156]: Hi Elena! Glad you chime in, cause it's giving unreachable warning lints, what's the advantage in keeping it? (and the others)

Comment (momoshell) [reply protocols/dcutr/src/handler/relayed.rs:156]: hey guys, because of the rustup update on CI to use the beta channel,  on my [recent PR](https://github.com/libp2p/rust-libp2p/pull/6190/files#diff-ec8e551b52b7a5f7d115f49f3c4e75c8dab2929ccd8f66f060204e34b2b3f69cR156) I had the same issues.

Is it adequate to just use `#[allow(unreachable_code)]` without removing the whole line?

Because ultimately, it's just the variant of `StreamUpgradeError::Apply` which is `Infallible`.

File: protocols/dcutr/src/handler/relayed.rs [hunk 2]
```diff
@@ -148,12 +148,11 @@ impl Handler {
 
     fn on_listen_upgrade_error(
         &mut self,
-        ListenUpgradeError { error, .. }: ListenUpgradeError<
+        ListenUpgradeError { .. }: ListenUpgradeError<
```
Comment (elenaf9) [inline protocols/dcutr/src/handler/relayed.rs]:
```suggestion
        _: ListenUpgradeError<
```

File: swarm/tests/swarm_derive.rs [hunk 3]
```diff
@@ -112,12 +110,8 @@ fn three_fields() {
...
         match _out_event {
             FooEvent::Ping(ping::Event { .. }) => {}
-            FooEvent::Identify(event) => {
-                let _: identify::Event = event;
-            }
-            FooEvent::Kad(event) => {
-                let _: libp2p_kad::Event = event;
-            }
+            FooEvent::Identify(_event) => {}
+            FooEvent::Kad(_event) => {}
```
Comment (elenaf9) [inline swarm/tests/swarm_derive.rs]:
```suggestion
            FooEvent::Identify(_event) => {
                let _: identify::Event = _event;
            }
            FooEvent::Kad(_event) => {
                let _: libp2p_kad::Event = _event;
            }
```

This should also satisfy the lint, but maintains the type check.

File: swarm/tests/swarm_derive.rs [hunk 4]
```diff
@@ -84,9 +84,7 @@ fn two_fields() {
         let _out_event: <Foo as NetworkBehaviour>::ToSwarm = unimplemented!();
         match _out_event {
             FooEvent::Ping(ping::Event { .. }) => {}
-            FooEvent::Identify(event) => {
-                let _: identify::Event = event;
-            }
+            FooEvent::Identify(_event) => {}
```
Comment (elenaf9) [inline swarm/tests/swarm_derive.rs]:
```suggestion
            FooEvent::Identify(_event) => {
                let _: identify::Event = _event;
            }
```
Same here.

File: protocols/dcutr/src/handler/relayed.rs (hunk 1 above)
Comment (elenaf9) [reply protocols/dcutr/src/handler/relayed.rs:156]: Discussed out-of-band. Removing the line is fine, since `libp2p_core::util::unreachable` also just silently discards the error.

**Review by elenaf9 — COMMENTED** [review]
Thanks João!

**Review by elenaf9 — APPROVED** [review]
LGTM!

>  the remaining [issue](https://github.com/libp2p/rust-libp2p/actions/runs/19040315461/job/54375441096?pr=6195#step:6:760) seems like a bug, opened https://github.com/rust-lang/rust-clippy/issues/16023.

Should we still `allow` the lint in the meantime to fix our CI?

**Comment by jxs** [comment]
> LGTM!
> 
> > the remaining [issue](https://github.com/libp2p/rust-libp2p/actions/runs/19040315461/job/54375441096?pr=6195#step:6:760) seems like a bug, opened [rust-lang/rust-clippy#16023](https://github.com/rust-lang/rust-clippy/issues/16023).
> 
> Should we still `allow` the lint in the meantime to fix our CI?

thanks for asking this Elena, yeah I think we should just let `clippy` `beta` fail as it will stop failing eventually vs letting the probability of that `allow` continue there forgotten after
