### PR TITLE
fix(quic): add support for reusing an existing socket for local dialing

### LINKED ISSUE #4259: fix(quic): improve listener socket selection when dialing
Problem

Say the local node listens on `/ip4/0.0.0.0/udp/0/quic-v1`. One would expect a consecutive dial to `/ip4/127.0.0.1/udp/42/quic-v1` to use one of the listen addresses as the source address of the dial.

That is not the case today. Instead `libp2p-quic` will create a new quinn endpoint and thus a new UDP socket for the outgoing dial.

Why?

In TCP we track the specific listen addresses, even if the user calls `listen_on` with an unspecified address (e.g. `0.0.0.0`). If the user calls `listen_on` with a specific IP address i.e. not a wildcard like `0.0.0.0` but e.g. `127.0.0.1` we track (here _register_) the specific address right away.

https://github.com/libp2p/rust-libp2p/blob/f10f1a274abe6e5193de653aa4dd951ae56c775e/transports/tcp/src/lib.rs#L394

In case where the user calls `listen_on` with an unspecified address (e.g. `0.0.0.0`) we depend on `if-watch`, more specifically `poll_if_watch` to provide us with the concrete addresses:

https://github.com/libp2p/rust-libp2p/blob/f10f1a274abe6e5193de653aa4dd951ae56c775e/transports/tcp/src/lib.rs#L666-L682 

Either way, we end up tracking specific listen addresses with port-reuse enabled and can thus choose the right listener in `local_dial_addr`:

https://github.com/libp2p/rust-libp2p/blob/f10f1a274abe6e5193de653aa4dd951ae56c775e/transports/tcp/src/lib.rs#L122-L151

In `libp2p-quic` we only track the initial address that the user provided on the `listen_on` call.

https://github.com/libp2p/rust-libp2p/blob/f10f1a274abe6e5193de653aa4dd951ae56c775e/transports/quic/src/endpoint.rs#L170-L178

This might be a wildcard address. Later on, when dialing a `127.0.0.1` address, the check `listen_addr.ip().is_loopback() == socket_addr.ip().is_loopback()` discards the listener with the unspecified listen address, thus a new dial-only socket is used, even though one of the existing listener sockets is available.

This is e.g. problematic when trying to dial a node on `127.0.0.1` with the expectation that the dial uses one of the listen addresses as a source address.

How does go-libp2p solve this:

go-libp2p asks the OS for the correct interface given a destination address. It uses Google's [routing](https://github.com/google/gopacket/blob/master/routing/) package. See https://github.com/libp2p/go-libp2p/blob/260b9695cafdd8e35ec65b30ef153f0c15549c72/p2p/transport/quicreuse/reuse.go#L209 for concrete usage and implementation.

How to move forward?

I am not sure simply removing the `listen_addr.ip().is_loopback() == socket_addr.ip().is_loopback()` check is the way to go. This check is still helpful. E.g. say we have two listeners, one on localhost, one not on localhost. Ideally we would use the former when dialing.

We could mirror what `libp2p-tcp` does. That is, track the specified listen addresses reported by if-watch. Later, when dialing, choose the listener with the right address.

Ideally I would like to have the operating system choose. It has the most information about all available routes to each interface. In other words ideally we would do what go-libp2p does.

For now, I suggest we go with the `libp2p-tcp` approach. A second iteration would mirror what go-libp2p does.

_Originally posted by @mxinden in https://github.com/libp2p/rust-libp2p/pull/3454#discussion_r1276338263_

Thank you @kpp for surfacing this bug.

Thank you @marten-seemann for the quick help, pointing me to how go-libp2p solves this issue.

### PR DESCRIPTION
**Pull request by arsenron**
## Description
Tracked in #4259. Now if a listener supports loopback interfaces, when a remote address is also a loopback address, we reuse an existing listener. 

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Review by mxinden — COMMENTED** [review]
Neat! Thank you @arsenron for the work.

Would you mind adding a unit test as well? This should be relatively straight forward. Given two nodes A and B:

1. Have A listen on `0.0.0.0:0`.
2. Given the wildcard port (`:0`) store the concrete port chosen by the OS across all interfaces.
3. Have B listen on `127.0.0.1:0`.
4. Have A dial B.
5. Expect the source port of A at B to be the port stored in (2), i.e. to be A's listen port.

**Comment by arsenron** [comment]
> Neat! Thank you @arsenron for the work.
> 
> Would you mind adding a unit test as well? This should be relatively straight forward. Given two nodes A and B:
> 
>     1. Have A listen on `0.0.0.0:0`.
> 
>     2. Given the wildcard port (`:0`) store the concrete port chosen by the OS across all interfaces.
> 
>     3. Have B listen on `127.0.0.1:0`.
> 
>     4. Have A dial B.
> 
>     5. Expect the source port of A at B to be the port stored in (2), i.e. to be A's listen port.

Done.

File: transports/quic/src/transport.rs [hunk 1]
```diff
@@ -524,7 +540,7 @@ impl<P: Provider> Listener<P> {
                     if let Some(listen_addr) =
                         ip_to_listenaddr(&endpoint_addr, inet.addr(), self.version)
                     {
-                        log::debug!("Expired listen address: {}", listen_addr);
+                        log::debug!("Expired listen address: {listen_addr}");
```
Comment (mxinden) [inline transports/quic/src/transport.rs:540]: The `IfEvent::Down` event might be for a localhost address. In such case we would have to change `self.supports_loopback` to `false`.

I wonder whether a single wildcard listen can result in multiple localhost listen addresses. In such case setting `self.supports_loopback` to `false` would be buggy here. E.g. in case the first is down, the second might still be up.

How about tracking a `HashSet<SomeAddressType>` in `Listener`? That `HashSet` can then be iterated for loopback addresses in `eligible_listener`.

File: transports/quic/src/transport.rs [hunk 2]
```diff
@@ -926,4 +942,86 @@ mod test {
...
+        let node_B_multiaddr =
+            socketaddr_to_multiaddr(&listener_addr(&node_B), ProtocolVersion::V1);
+
+        // node A dials node B
+        node_A.dial(node_B_multiaddr).unwrap().await.unwrap();
+
+        // Verify that node B received node A listening port
+        poll_fn(|cx| {
+            let mut pinned = Pin::new(&mut node_B);
+            while let Poll::Ready(e) = pinned.as_mut().poll(cx) {
```
Comment (mxinden) [inline transports/quic/src/transport.rs]: I wonder whether polling only `node_B` here is prone to race conditions. I.e. I would expect one having to poll both in case of any intermittent failure. (Though arguably, e.g. a packet loss is rather rare on localhost.)

Either way, I think you can simplify this test by using the `connect` method:

https://github.com/libp2p/rust-libp2p/blob/da94dcb23b0d65a0e94965e6e8ddb14899053bd8/transports/quic/tests/smoke.rs#L689-L709

What do you think of moving this test to `smoke.rs`?

**Review by mxinden — COMMENTED** [review]
Wow, that was fast. Thank you! Two suggestions.

File: transports/quic/src/transport.rs (hunk 1 above)
Comment (arsenron) [reply transports/quic/src/transport.rs:540]: Agree. A user can just turn off loopback interface while running a libp2p app (but he would be crazy then!). I also tried playing with routing tables and in fact you may have multiple loopback addresses advertised. For example you can establish an additional network address for loopback interface by doing `ifconfig lo0 alias 127.0.0.2 up` on macOS and `if-watch` will return `127.0.0.1` and `127.0.0.2`. 

So, yeah, it makes sense to store loopback addresses as a `HashSet` and handle `IfEvent::Down` events.

File: transports/quic/tests/smoke.rs [hunk 3]
```diff
@@ -414,6 +414,49 @@ async fn write_after_peer_dropped_stream() {
...
+
+    a_transport
+        .listen_on(
+            ListenerId::next(),
+            "/ip4/0.0.0.0/udp/0/quic-v1".parse().unwrap(),
+        )
+        .unwrap();
+
+    // wait until a listener reports a loopback address
+    let a_addr = 'outer: loop {
```
Comment (mxinden) [inline transports/quic/tests/smoke.rs]:
```suggestion
    let a_listen_addr = 'outer: loop {
```

Small nit. Makes it explicit below that we expect the `send_back_addr` (aka. source address) to be the listen address.

File: transports/quic/tests/smoke.rs [hunk 4]
```diff
@@ -414,6 +414,49 @@ async fn write_after_peer_dropped_stream() {
...
+    poll_fn(|cx| {
+        let mut pinned = Pin::new(&mut a_transport);
+        while let Poll::Ready(e) = pinned.as_mut().poll(cx) {}
+        Poll::Ready(())
+    })
+    .await;
+
+    let b_addr = start_listening(&mut b_transport, "/ip4/127.0.0.1/udp/0/quic-v1").await;
+    let (_, send_back_addr, _) = connect(&mut b_transport, &mut a_transport, b_addr).await.0;
+    assert_eq!(send_back_addr, a_addr);
```
Comment (mxinden) [inline transports/quic/tests/smoke.rs]:
```suggestion
    assert_eq!(send_back_addr, a_listen_addr);
```

File: transports/quic/src/transport.rs (hunk 2 above)
Comment (arsenron) [reply transports/quic/src/transport.rs]: Moved the test to `smoke.rs` and simplified it, thanks! But due to listening on `0.0.0.0` it is a bit ugly.

File: transports/quic/tests/smoke.rs [hunk 5]
```diff
@@ -414,6 +414,49 @@ async fn write_after_peer_dropped_stream() {
...
+                    break 'outer listen_addr;
+                }
+            }
+        }
+    };
+    // If we do not poll until the end, `NewAddress` events may be `Ready` and `connect` function
+    // below will panic due to an unexpected event.
+    poll_fn(|cx| {
+        let mut pinned = Pin::new(&mut a_transport);
+        while let Poll::Ready(e) = pinned.as_mut().poll(cx) {}
```
Comment (mxinden) [inline transports/quic/tests/smoke.rs]:
```suggestion
        while let Poll::Ready(_) = pinned.as_mut().poll(cx) {}
```

**Review by mxinden — COMMENTED** [review]
Thank you for adjusting the test.

File: transports/quic/src/transport.rs (hunk 1 above)
Comment (mxinden) [reply transports/quic/src/transport.rs:540]: > For example you can establish an additional network address for loopback interface by doing `ifconfig lo0 alias 127.0.0.2 up` on macOS and `if-watch` will return `127.0.0.1` and `127.0.0.2`.

Today I learned. Thank you for testing this out.

**Comment by arsenron** [comment]
@mxinden Rewrote using a `HashSet` instead of a `bool` to make the logic more reliable

File: transports/quic/tests/smoke.rs [hunk 6]
```diff
@@ -414,6 +414,49 @@ async fn write_after_peer_dropped_stream() {
     stream_b.close().await.expect("Close failed.");
 }
 
+/// - A listens on 0.0.0.0:0
+/// - B listens on 127.0.0.1:0
+/// - A dials B
+/// - Source port of A at B is the A's listen port
+#[cfg(feature = "tokio")]
+#[tokio::test]
+async fn test_local_listener_reuse() {
```
Comment (mxinden) [inline transports/quic/tests/smoke.rs:423]: For the record, tested locally and fails without the patch. :rocket:

**Review by mxinden — APPROVED** [review]
Well done @arsenron! Thank you for the help.

**Comment by mxinden** [comment]
[Tagged](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-quic-v0.9.2-alpha) and [published](https://crates.io/crates/libp2p-quic/0.9.2-alpha).
