### PR TITLE
fix(swarm): gracefully disable oneshot handler on dial upgrade errors

### LINKED ISSUE #3269: swallowed errors, or escalating too quickly
https://github.com/libp2p/rust-libp2p/blob/13a59a38d3385b4c58ef6e0e77694881b46cb7dc/swarm/src/handler/one_shot.rs#L214-L219

@mxinden This is where incoming stream upgrade errors are lost, as mentioned in today’s meeting. #3128 somewhat intentionally did not fix this since the error is returned from `Apply`. Since there is no obvious need for more reaction, I’d propose to log inbound upgrade errors on debug level in the above spot.

In the above code snippet, outbound upgrade errors lead to closing the connection. I’m not sure whether that is the best possible response given that many protocols may be composed and thus the escalation’s scope seems too large.

### PR DESCRIPTION
**Pull request by vnermolaev**
## Description

Resolves https://github.com/libp2p/rust-libp2p/issues/3269.

## Notes

This PR implement changes discussed in #3269 

> > I’d propose to log inbound upgrade errors on debug level in the above spot.
> 
> Sounds good to me.
> 
> > In the above code snippet, outbound upgrade errors lead to closing the connection. I’m not sure whether that is the best possible response given that many protocols may be composed and thus the escalation’s scope seems too large.
> 
> Agreed. Setting its `keep_alive` to `False` should be enough.

## Links to any relevant issues

#3269 

## Change checklist

The changes are trivial. Not sure whether the usual checklist applies.

### CODE REVIEW

File: swarm/src/handler/one_shot.rs [hunk 1]
```diff
@@ -213,7 +213,9 @@ where
             }
             ConnectionEvent::DialUpgradeError(DialUpgradeError { error, .. }) => {
                 if self.pending_error.is_none() {
+                    log::debug!("DialUpgradeError: {error:?}");
                     self.pending_error = Some(error);
```
Comment (thomaseizinger) [inline swarm/src/handler/one_shot.rs]: I think we should remove this, otherwise we will still close the connection later!

File: swarm/src/handler/one_shot.rs [hunk 2]
```diff
@@ -213,7 +213,9 @@ where
             }
             ConnectionEvent::DialUpgradeError(DialUpgradeError { error, .. }) => {
                 if self.pending_error.is_none() {
+                    log::debug!("DialUpgradeError: {error:?}");
```
Comment (thomaseizinger) [inline swarm/src/handler/one_shot.rs]:
```suggestion
                    log::debug!("DialUpgradeError: {error}");
```

Errors can be display formatted but at the moment, that does not necessarily print the entire chain of errors.

@mxinden Should we depend on `anyhow` internally here to print all errors?

**Review by thomaseizinger — COMMENTED** [review]
Thanks!

File: swarm/src/handler/one_shot.rs (hunk 1 above)
Comment (vnermolaev) [reply swarm/src/handler/one_shot.rs]: Pardon me, remove `self.pending_error = Some(error)`?
I am not sure what implications are, so I kept the changes aligned with the approach outlined in the respective issue.

File: swarm/src/handler/one_shot.rs (hunk 2 above)
Comment (vnermolaev) [reply swarm/src/handler/one_shot.rs]: There is a function `print_error_chain` in `swarm/src/lib.rs`. I could use that one. Is this an option?

Comment (thomaseizinger) [reply swarm/src/handler/one_shot.rs]: Happy to use that one yeah as we are within the same crate!

File: swarm/src/handler/one_shot.rs (hunk 1 above)
Comment (thomaseizinger) [reply swarm/src/handler/one_shot.rs]: Anything within `pending_error` will be returned via `ProtocolsHandlerEvent::Close` which effectively closes the connection. In this case, we don't want that but set `keep_alive` to `No` which, if not other handler needs the connection will result in closing it.

File: swarm/src/handler/one_shot.rs [hunk 3]
```diff
@@ -213,7 +213,8 @@ where
             }
             ConnectionEvent::DialUpgradeError(DialUpgradeError { error, .. }) => {
                 if self.pending_error.is_none() {
-                    self.pending_error = Some(error);
+                    log::debug!("DialUpgradeError: {error}");
```
Comment (thomaseizinger) [inline swarm/src/handler/one_shot.rs:216]: I'd like to use `crate::print_error_chain` here and not within the `Display` impl please.

File: swarm/src/handler.rs [hunk 4]
```diff
@@ -467,7 +467,7 @@ where
             ConnectionHandlerUpgrErr::Timer => {
                 write!(f, "Timer error while opening a substream")
             }
-            ConnectionHandlerUpgrErr::Upgrade(err) => write!(f, "{err}"),
+            err @ ConnectionHandlerUpgrErr::Upgrade(_) => crate::print_error_chain(f, err),
```
Comment (thomaseizinger) [inline swarm/src/handler.rs]: I don't think this is what we want, instead, this should probably just print "upgrade error" without printing the inner error. That is what `print_error_chain` then does because the inner error is returned from `source`.

Comment (thomaseizinger) [reply swarm/src/handler.rs]: If you use `print_error_chain` here, we might end up with duplicate printing if somebody uses `print_error_chain` on `ConnectionHandlerUpgrErr`.

**Review by thomaseizinger — CHANGES_REQUESTED** [review]

File: swarm/src/handler/one_shot.rs (hunk 3 above)
Comment (vnermolaev) [reply swarm/src/handler/one_shot.rs:216]: I am afraid it is not that simple. 

- `print_error_chain` requires a `Formatter` and is invoked within implementations of the `Display` trait. So I can't use it directly here
```rust
fn print_error_chain(f: &mut fmt::Formatter<'_>, e: &dyn error::Error) -> fmt::Result {...}
```

- the type of `error` contained in `DialUpgradeError` is `ConnectionHandlerUpgrErr<InnerError>`, where `InnerError` is not bounded to `error::Error`, thus I had to introduce this bound in the `Display` impl for `ConnectionHandlerUpgrErr`.

File: swarm/src/handler.rs (hunk 4 above)
Comment (vnermolaev) [reply swarm/src/handler.rs]: You're right. 
Please see my other comment.
It'd be possible to [mimic](https://github.com/libp2p/rust-libp2p/blob/69af8506d1eb17f5d11b7364693d45b322205180/swarm/src/lib.rs#L1747) `impl fmt::Display for DialError`.

File: swarm/src/handler/one_shot.rs (hunk 3 above)
Comment (thomaseizinger) [reply swarm/src/handler/one_shot.rs:216]: Right, I forgot about that, sorry for the confusion!

I think it is okay to continue using `print_error_chain` here if we consequently don't return the inner error from `source`.

If we do this, I'd like to see a unit test that ensures the `Error` impl is not changed.

Comment (thomaseizinger) [reply swarm/src/handler/one_shot.rs:216]: Alternatively, we can create a local one-off use newtype here that uses `print_error_chain` in its display function. We can then construct this type and immediately use it to print the error.

Comment (vnermolaev) [reply swarm/src/handler/one_shot.rs:216]: I believe it is reasonable to [mimic](https://github.com/libp2p/rust-libp2p/blob/69af8506d1eb17f5d11b7364693d45b322205180/swarm/src/lib.rs#L1747) `impl fmt::Display for DialError`
- `DialEerror` is _structurally_ very similar to `ConnectionHandlerUpgrErr`,
- `DialError` already sets an example of how to use `print_error_chain`.

It feels right that the `Display` knows how to print the error info correctly, thus my proposition would be:

```rust
impl<TUpgrErr> fmt::Display for ConnectionHandlerUpgrErr<TUpgrErr>
where
    TUpgrErr: error::Error + 'static,
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ConnectionHandlerUpgrErr::Timeout => {
                write!(f, "Timeout error while opening a substream")
            }
            ConnectionHandlerUpgrErr::Timer => {
                write!(f, "Timer error while opening a substream")
            }
            ConnectionHandlerUpgrErr::Upgrade(err) => {
                write!(f, "DialUpgradeErr: ")?;
                print_error_chain(f, err)
            }
        }
    }
}
```

Otherwise, let's just use `log::debug!("DialUpgradeError: {error}");`

Comment (thomaseizinger) [reply swarm/src/handler/one_shot.rs:216]: Your proposal sounds good! I think we should also return `None` in `source` then, otherwise we might get double printing.

Comment (vnermolaev) [reply swarm/src/handler/one_shot.rs:216]: Struggling to understand where you'd like to return `None`. The `error::Error` implementation of `ConnectionHandlerUpgrErr` already returns `None` where appropriate
```rust
impl<TUpgrErr> error::Error for ConnectionHandlerUpgrErr<TUpgrErr>
where
    TUpgrErr: error::Error + 'static,
{
    fn source(&self) -> Option<&(dyn error::Error + 'static)> {
        match self {
            ConnectionHandlerUpgrErr::Timeout => None,
            ConnectionHandlerUpgrErr::Timer => None,
            ConnectionHandlerUpgrErr::Upgrade(err) => Some(err),
        }
    }
}
```
Am I missing something?

Comment (thomaseizinger) [reply swarm/src/handler/one_shot.rs:216]: If we print the sources as part of `Display::fmt`, we should return `None` within `source` for the `Upgrade` variant too, otherwise libraries like `anyhow` which walk down the source chain will print all sources again, leading to duplicate error messages for the user.

**Comment by vnermolaev** [comment]
One test is failing but this is due some docker issues.

**Review by thomaseizinger — APPROVED** [review]
Thanks!

**Comment by thomaseizinger** [comment]
> One test is failing but this is due some docker issues.

Yes that is unfortunately a flaky test.

Can you add a small changelog entry to `libp2p-swarm` please?

**Comment by vnermolaev** [comment]
Is it really necessary?
Last time I did a larger refactoring and no changelog has been required because it was not a user-facing feature.
This one does not seem to be user-facing. I can ofc add a change log, but what should I even write? :)

**Comment by thomaseizinger** [comment]
> This one does not seem to be user-facing.

I'd argue that this one is definitely a change in behaviour that is observable.

> I can ofc add a change log, but what should I even write? :)

Feel free to copy the PR title (modulo formatting adjustments)!

**Comment by vnermolaev** [comment]
done

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Thank you!

I've opened https://github.com/libp2p/rust-libp2p/issues/3591 as a spiritual follow-up because we currently have this "problem" in many crates actually.

File: swarm/CHANGELOG.md [hunk 5]
```diff
@@ -90,6 +90,8 @@
 - Deprecate methods `Swarm::with_executor`, `Swarm::with_*_executor`, `Swarm::without_executor`.
   Introduce similar methods in `SwarmBuilder`. See [PR 3588].
 
+- Gracefully disable oneshot handler on dial upgrade errors. See [PR 3577].
```
Comment (mxinden) [inline swarm/CHANGELOG.md:93]: Under the assumption that this is not a breaking change, this pull request should have bumped `libp2p-swarm` to `v0.42.1` and this changelog entry should have been under the `v0.42.1` section.

File: swarm/src/handler/one_shot.rs [hunk 6]
```diff
@@ -213,7 +213,8 @@ where
             }
             ConnectionEvent::DialUpgradeError(DialUpgradeError { error, .. }) => {
                 if self.pending_error.is_none() {
-                    self.pending_error = Some(error);
```
Comment (mxinden) [inline swarm/src/handler/one_shot.rs:216]: As far as I can tell, this was the only occurrence of setting `self.pending_error`. In other words, I don't think `pending_error` is used anywhere after this change. Is that correct?

**Review by mxinden — COMMENTED** [review]
Thanks for the work here. @thomaseizinger or @vnermolaev can either of you address the comments below?

I hope that this is not a breaking change. In other words, I hope that no downstream user depends on the fact that the `OneShotHandler` closes a connection if a remote does not support its protocol.

File: swarm/CHANGELOG.md (hunk 5 above)
Comment (vnermolaev) [reply swarm/CHANGELOG.md:93]: Not sure how to address this because it's been merged.

File: swarm/src/handler/one_shot.rs (hunk 6 above)
Comment (vnermolaev) [reply swarm/src/handler/one_shot.rs:216]: Almost; there is one more place
```rust
if let Some(err) = self.pending_error.take() {
    return Poll::Ready(ConnectionHandlerEvent::Close(err));
}
```      
The resolution of this usage is related to #3591.

File: swarm/CHANGELOG.md (hunk 5 above)
Comment (thomaseizinger) [reply swarm/CHANGELOG.md:93]: We can just fix it in a new PR.

File: swarm/src/handler/one_shot.rs (hunk 6 above)
Comment (thomaseizinger) [reply swarm/src/handler/one_shot.rs:216]: But if it is never set, then this is dead code so we can delete it straight-away!

Sorry for missing that @mxinden.

**Comment by thomaseizinger** [comment]
> I hope that this is not a breaking change. In other words, I hope that no downstream user depends on the fact that the `OneShotHandler` closes a connection if a remote does not support its protocol.

I'd be very surprised if it _breaks_ something. I consider this a bugfix to be honest.
