### PR TITLE
fix(webrtc example): clarify idle connection timeout

### LINKED ISSUE #4950: broken example: browser-webrtc
### Summary

I fired up the latest https://github.com/libp2p/rust-libp2p/tree/master/examples/browser-webrtc to discover there's an error in the browser console

### Expected behavior

The example should ping back and forth between the server and browser, only 1 ping gets across before crashing

### Actual behavior

After the first ping, the browser crashes 

### Relevant log output

```shell
Uncaught Error: closure invoked recursively or after being dropped
    at imports.wbg.__wbindgen_throw (browser_webrtc_example.js:668:15)
    at browser_webrtc_example_bg.wasm:0xbed3a
    at browser_webrtc_example_bg.wasm:0xb6add
    at __wbg_adapter_30 (browser_webrtc_example.js:208:10)
    at RTCDataChannel.real (browser_webrtc_example.js:193:20)
```

### Possible Solution

I suspect one of the `web_sys` closures isn't being handled properly? It likely gets dropped and then called.

### Version

libp2p 0.53.1
libp2p_webrtc 0.6.1-alpha

### Would you like to work on fixing this bug ?

Maybe
```[tasklist]
### Tasks
- [ ] https://github.com/libp2p/rust-libp2p/pull/4952
- [ ] https://github.com/libp2p/rust-libp2p/pull/4966
```

### PR DESCRIPTION
**Pull request by DougAnderson444**
## Description

When I ran the `example/browser-webrtc` example I discovered it would break after a ping or two.
The `Ping` idle timeout needed to be extended, on both the server and the wasm client, which is what this PR fixes.
I also added a small note to the README about ensuring `wasm-pack` is install for the users who are new to the ecosystem.

Fixes: #4950.

## Notes & open questions

The native code can accept `u64::MAX`, but curiously in `wasm` we cannot use `u64::MAX`. The `with_idle_connection_timeout` breaks in the browser on anything bigger than `32_212_254u64`

```rust
.with_swarm_config(|c| {
  c.with_idle_connection_timeout(Duration::from_secs(
   32_212_254u64,
   // 32_212_255u64, // breaks, too large for wasm?
  ))
})
```

The reason why this occurs is left as an open challenge for the community.

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] A changelog entry has been made in the appropriate crates~~

### CODE REVIEW

File: examples/browser-webrtc/src/main.rs [hunk 1]
```diff
@@ -38,7 +38,7 @@ async fn main() -> anyhow::Result<()> {
         .with_behaviour(|_| ping::Behaviour::default())?
         .with_swarm_config(|cfg| {
             cfg.with_idle_connection_timeout(
-                Duration::from_secs(30), // Allows us to observe the pings.
```
Comment (thomaseizinger) [inline examples/browser-webrtc/src/main.rs:41]: Why is 30 not enough to observe some pings?

File: examples/browser-webrtc/src/lib.rs [hunk 2]
```diff
@@ -24,7 +24,9 @@ pub async fn run(libp2p_endpoint: String) -> Result<(), JsError> {
             webrtc_websys::Transport::new(webrtc_websys::Config::new(&key))
         })?
         .with_behaviour(|_| ping::Behaviour::new(ping::Config::new()))?
-        .with_swarm_config(|c| c.with_idle_connection_timeout(Duration::from_secs(5)))
+        // Ping does not KeepAlive, so we set the idle connection timeout to 32_212_254u64,
```
Comment (thomaseizinger) [inline examples/browser-webrtc/src/lib.rs]: Why such a large value? Isn't 30 seconds entirely sufficient to see that the connection works?

**Review by thomaseizinger — COMMENTED** [review]
Two comments. Also linking a related discussion / proposal: https://github.com/libp2p/rust-libp2p/pull/4967.

**Comment by DougAnderson444** [comment]
Yes, 30 seconds is long enough to observe a couple of `Ping`s.

But, I was initially _surprised_ that the pings stopped so soon and _confused_ as to why the pings stopped. The error log (`Uncaught Error: closure invoked recursively or after being dropped`) left me little evidence as to why. I suppose I expected them to ping for an extended period of time, then it just stopped after 3 pings and errored.

I didn't realize _yet_ that `Ping` goes idle right away. I expected the idle to occur only if the connection dropped off (just my assumption), so I was surprised that I needed to extend the idle time to the duration that I wanted to see the pings for longer.

This could be solved by documentation in the example I suppose: 

> `Pings the server for 30 seconds then lets the Ping go idle`

And perhaps a more graceful handling of the error? 

> `info/warn: Ping has gone idle`

I'm open to either/both or additional options but I think it should be clear in the example.

So perhaps this PR should be:

1. Improve the example docs
2. Improve `Ping` goes idle handling (let the connection know?)

Thoughts?

File: examples/browser-webrtc/src/main.rs (hunk 1 above)
Comment (DougAnderson444) [reply examples/browser-webrtc/src/main.rs:41]: I was trying to be consistent with the `Ping` example here:

https://github.com/libp2p/rust-libp2p/blob/c1925e5e612bd609e57d6ac50a7b28cf16a1aa2c/examples/ping/src/main.rs#L42

But see my comment below, I've tweaked the example to be more clear I think

File: examples/browser-webrtc/src/lib.rs (hunk 2 above)
Comment (DougAnderson444) [reply examples/browser-webrtc/src/lib.rs]: Part of this was trying to determine / document why there was a strange idle limit in wasm in case someone tries to do `u64::MAX` like I initially tried to do. For the example though I made some changes which clear it up

**Comment by thomaseizinger** [comment]
The confusion is understandable and a bit unfortunate.

A connection being idle in `rust-libp2p` means that there are no streams (worth having) that need to finish executing. We explicitly exclude all `ping` streams from this because ping is a continuous stream that never finishes so we would never be able to shut down an idle connection.

The problem is really one of the example. Ping is a good dummy protocol to see that the connection works but it does mean we explicitly have to extend the idle timeout.

I am open to making this better but I haven't found a good solution yet. Note that there is a discussion around this here: https://github.com/libp2p/rust-libp2p/issues/4912

File: examples/browser-webrtc/src/lib.rs [hunk 3]
```diff
@@ -46,6 +51,19 @@ pub async fn run(libp2p_endpoint: String) -> Result<(), JsError> {
...
+            SwarmEvent::ConnectionClosed {
+                cause: Some(cause), ..
+            } => {
+                tracing::info!("Swarm event: {:?}", cause);
+
+                if let libp2p::swarm::ConnectionError::KeepAliveTimeout = cause {
+                    body.append_p("All done with pinging! ")?;
+
+                    break;
+                } else {
```
Comment (thomaseizinger) [inline examples/browser-webrtc/src/lib.rs]: This `else` is not needed because you `break` before (which I think is good style!)

Comment (DougAnderson444) [reply examples/browser-webrtc/src/lib.rs]: Ah, good eyes! I'll fix this.

**Comment by DougAnderson444** [comment]
Ok, thanks for your thoughts @thomaseizinger.

I think for the sake of this example, it should be more clear now that I've made the example a bit more verbose for whoever runs it in the future. If they get confused like I initially did, I suppose we'd hear about it and clarify further if needed.

In the end I am also glad it wasn't a bug in WebRTC!

**Review by thomaseizinger — APPROVED** [review]
Great changes! Thank you very much :)

If you are keen, I'd be interested in your opinion on the wider topic of idle timeouts in https://github.com/libp2p/rust-libp2p/pull/4967.
