### PR TITLE
fix(swarm): better error message for failed `DialPeerCondition`s

### LINKED ISSUE #4407: fix(swarm): improve error message on `false` `DialPeerCondition`
With `PeerCondition::Disconnected`, dialing an already connected peer results in the following error message:

```
Dial error: condition Disconnected for dialing peer was false
```

This is not intuitive for newcomers. Something along the lines of the below would be more intuitive:

```
Dial error: condition dial was configured to only happen when disconnected (`PeerCondition::Disconnected`), but node is already connected, thus cancelling new dial.
```

https://github.com/libp2p/rust-libp2p/blob/e36e8ce4456ff059dd54614913b521194d2d478c/swarm/src/lib.rs#L1583-L1585

See e.g. confusion by user https://github.com/libp2p/rust-libp2p/discussions/4395

### PR DESCRIPTION
**Pull request by chirag-bgh**
## Description

Closes #4407.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] A changelog entry has been made in the appropriate crates

### CODE REVIEW

File: swarm/src/lib.rs [hunk 1]
```diff
@@ -1580,8 +1580,8 @@ impl fmt::Display for DialError {
                 f,
                 "Dial error: tried to dial local peer id at {endpoint:?}."
             ),
-            DialError::DialPeerConditionFalse(c) => {
-                write!(f, "Dial error: condition {c:?} for dialing peer was false.")
+            DialError::DialPeerConditionFalse(_) => {
+                write!(f, "Dial error: condition dial was configured to only happen when disconnected (`PeerCondition::Disconnected`), but node is already connected, thus cancelling new dial.")
```
Comment (mxinden) [inline swarm/src/lib.rs]: I think there is more needed, i.e. one needs to differentiate on the `DialPeerConditionFalse` error. `PeerCondition::Disconnected` is one of the reasons it might fail. Take a look at the function throwing the `DialPeerConditionFalse`.

**Review by mxinden — COMMENTED** [review]
Thank you for starting this. There is more needed I am afraid.

File: swarm/src/lib.rs [hunk 2]
```diff
@@ -1580,8 +1580,10 @@ impl fmt::Display for DialError {
                 f,
                 "Dial error: tried to dial local peer id at {endpoint:?}."
             ),
-            DialError::DialPeerConditionFalse(c) => {
-                write!(f, "Dial error: condition {c:?} for dialing peer was false.")
+            DialError::DialPeerConditionFalse(condition) => match condition {
+                PeerCondition::Disconnected => write!(f, "Dial error: condition dial was configured to only happen when disconnected (`PeerCondition::Disconnected`), but node is already connected, thus cancelling new dial."),
+                PeerCondition::NotDialing => write!(f, "Dial error: condition dial was configured to only if there is currently no ongoing dialing attempt (`PeerCondition::NotDialing`), but node is already dialing, thus cancelling new dial."),
```
Comment (mxinden) [inline swarm/src/lib.rs]:
```suggestion
                PeerCondition::Disconnected => write!(f, "Dial error: dial condition was configured to only happen when disconnected (`PeerCondition::Disconnected`), but node is already connected, thus cancelling new dial."),
                PeerCondition::NotDialing => write!(f, "Dial error: dial condition was configured to only happen if there is currently no ongoing dialing attempt (`PeerCondition::NotDialing`), but a dial is in progress, thus cancelling new dial."),
```

File: swarm/src/lib.rs [hunk 3]
```diff
@@ -1580,8 +1580,10 @@ impl fmt::Display for DialError {
...
+                PeerCondition::Always => write!(f, "Dial error: condition dial was configured to always happen (`PeerCondition::Always`)."),
```
Comment (mxinden) [inline swarm/src/lib.rs]:
```suggestion
                PeerCondition::Always => unreachable!(f, "Dial peer condition is by definition true."),
```

**Review by mxinden — COMMENTED** [review]
Smaller nit picks. This looks good overall. Thank you for the work.

File: swarm/src/lib.rs [hunk 4]
```diff
@@ -1580,8 +1580,10 @@ impl fmt::Display for DialError {
                 f,
                 "Dial error: tried to dial local peer id at {endpoint:?}."
             ),
-            DialError::DialPeerConditionFalse(c) => {
-                write!(f, "Dial error: condition {c:?} for dialing peer was false.")
+            DialError::DialPeerConditionFalse(condition) => match condition {
```
Comment (thomaseizinger) [inline swarm/src/lib.rs]: This inner match can be embedded in the outer one:

```suggestion
            DialError::DialPeerConditionFalse(PeerCondition::Disconnected) => {
```

That will reduce indentation of this block :)

**Review by thomaseizinger — COMMENTED** [review]
Thanks!

We will also need a version bump of `libp2p-swarm` and a changelog entry.

File: swarm/CHANGELOG.md [hunk 5]
```diff
@@ -1,3 +1,10 @@
+## 0.43.4
```
Comment (thomaseizinger) [inline swarm/CHANGELOG.md]:
```suggestion
## 0.43.4 0 - unreleased
```

File: swarm/CHANGELOG.md [hunk 6]
```diff
@@ -1,3 +1,10 @@
...
+
+- improve error message on false DialPeerCondition
```
Comment (thomaseizinger) [inline swarm/CHANGELOG.md]:
```suggestion
- Improve error message when `DialPeerCondition` prevents a dial.
```

File: swarm/CHANGELOG.md [hunk 7]
```diff
@@ -1,3 +1,10 @@
...
+  See [PR 4409]
```
Comment (thomaseizinger) [inline swarm/CHANGELOG.md]:
```suggestion
  See [PR 4409].
```

**Review by thomaseizinger — COMMENTED** [review]
Thanks! :)

File: swarm/CHANGELOG.md [hunk 8]
```diff
@@ -1,3 +1,10 @@
+## 0.43.4 0 - unreleased
```
Comment (thomaseizinger) [inline swarm/CHANGELOG.md]:
```suggestion
## 0.43.4 - unreleased
```

**Review by thomaseizinger — DISMISSED** [review]

**Review by thomaseizinger — APPROVED** [review]
