### PR TITLE
fix: allow relay to forward unlimited bytes

### LINKED ISSUE #5170: Relay : 'Hop' spec supports zero limit, but the impl does not
### Description

Hello, I m strugglinhg to establish connections to a relay, where limits are not applied. 
I m not quite sure whether this is a bug or a wrong API usage, so that I post it to the enhancement category.  

According to the spec relay-2.0:

 ```
The limit field in HopMessage, if present, provides information about the limits applied by the relay in relayed connection. When omitted, it indicates that the relay does not apply any limits.

The struct has the following fields:

Limit {
  duration = ...
  data = ...
}
the duration field indicates the maximum duration of a relayed connection in seconds; if 0, there is no limit applied.
the data field indicates the maximum number of bytes allowed to be transmitted in each direction; if 0 there is no limit applied.
```

To establish long-lived connections w/o data limits  my relay app sets default values for these , max_circuit_bytes and max_circuit_duration, before the swarm is initialised.  However setting them to zeros does not negotiate "no limit" condition. E.g. setting the duration to zero causes the relay to open the connection and close it instantly with a timeout error.  
The obvious workaround is to set these values to  high limits ( and it works),  however such cornering is impractical in production cases.

### Motivation

see above

### Current Implementation

see above

### Are you planning to do it yourself in a pull request ?

Yes

### PR DESCRIPTION
**Pull request by drHuangMHT**
## Description

Allow relay to forward unlimited bytes from one peer to another by checking if `max_circuit_bytes` equals to 0 before checking if `bytes_sent` exceeds `max_circuit_bytes`.
This will make current implementation follow the spec.
May close #5170.

## Notes & open questions

Not sure how to write the test.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] A changelog entry has been made in the appropriate crates

### CODE REVIEW

**Comment by drHuangMHT** [comment]
Changelog entry will be added if the fix is accepted, discussion welcome.

File: protocols/relay/src/copy_future.rs [hunk 1]
```diff
@@ -73,7 +73,7 @@ where
         let this = &mut *self;
 
         loop {
-            if this.bytes_sent > this.max_circuit_bytes {
+            if this.max_circuit_bytes != 0 && this.bytes_sent > this.max_circuit_bytes {
```
Comment (jxs) [inline protocols/relay/src/copy_future.rs]: nit:
```suggestion
            if this.max_circuit_bytes > 0 && this.bytes_sent > this.max_circuit_bytes {
```
since `max_circuit_bytes` is an [`u64`](https://github.com/libp2p/rust-libp2p/blob/master/protocols/relay/src/behaviour.rs#L59)

**Review by jxs — APPROVED** [review]
thanks @drHuangMHT! LGTM just one nitpick. Can you also add a `CHANGELOG.md` entry and `Cargo.toml` update please?
cc @dariusc93

File: protocols/relay/src/copy_future.rs (hunk 1 above)
Comment (drHuangMHT) [reply protocols/relay/src/copy_future.rs]: Since `max_circuit_bytes` is an unsigned integer, it can only be either 0 or non-zero positive integer right? In that case negetive integer can be ignored safely. But of course `>0` will make the code more robust. Will do!

**Review by jxs — APPROVED** [review]

File: protocols/relay/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,8 @@
+## unreleased
```
Comment (jxs) [inline protocols/relay/CHANGELOG.md]:
```suggestion
## 0.17.2 - unreleased
```

**Review by jxs — COMMENTED** [review]
ah sorry, it's still missing the `Cargo.toml` version bump

File: protocols/relay/CHANGELOG.md (hunk 2 above)
Comment (drHuangMHT) [reply protocols/relay/CHANGELOG.md]: That's why it's still a draft. One moment.

Comment (jxs) [reply protocols/relay/CHANGELOG.md]: Ah no worries, then feel free to request a review when it's are ready to be reviewed

**Review by jxs — APPROVED** [review]

**Comment by drHuangMHT** [comment]
@jxs Need send-it lable and probably a re-approval to merge this

**Review by jxs — APPROVED** [review]
